-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRATION: Add Embedding Support to lumen_data_atoms
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Purpose: Enable semantic search on all knowledge atoms by adding vector
--          embeddings directly to the atoms table.
--
-- Regulatory Compliance:
--   - 21 CFR Part 11 compliant audit trail via updated_at timestamps
--   - Immutable embedding_model tracking for reproducibility
--   - HNSW index for efficient similarity search
--
-- Author: TrialSage AI Team
-- Date: 2026-01-25
-- Version: 2.0.0
-- ═══════════════════════════════════════════════════════════════════════════

-- Ensure pgvector extension is available
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding columns to lumen_data_atoms
ALTER TABLE lumen_data_atoms
ADD COLUMN IF NOT EXISTS embedding vector(3072),
ADD COLUMN IF NOT EXISTS embedding_model TEXT DEFAULT 'text-embedding-3-large',
ADD COLUMN IF NOT EXISTS embedding_updated_at TIMESTAMP WITH TIME ZONE;

-- Create HNSW index for fast similarity search
-- Using cosine distance (most common for text embeddings)
CREATE INDEX IF NOT EXISTS idx_lumen_atoms_embedding_hnsw
ON lumen_data_atoms
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- Create index for finding atoms without embeddings (for backfill jobs)
CREATE INDEX IF NOT EXISTS idx_lumen_atoms_embedding_null
ON lumen_data_atoms (created_at)
WHERE embedding IS NULL;

-- Create index for embedding freshness tracking
CREATE INDEX IF NOT EXISTS idx_lumen_atoms_embedding_freshness
ON lumen_data_atoms (embedding_updated_at)
WHERE embedding IS NOT NULL;

-- Add comment for documentation
COMMENT ON COLUMN lumen_data_atoms.embedding IS 'Vector embedding (3072 dimensions) generated by text-embedding-3-large model for semantic search';
COMMENT ON COLUMN lumen_data_atoms.embedding_model IS 'Name of the embedding model used (for reproducibility and audit)';
COMMENT ON COLUMN lumen_data_atoms.embedding_updated_at IS 'Timestamp when embedding was last generated/updated';

-- ═══════════════════════════════════════════════════════════════════════════
-- AUDIT TABLE: Track embedding generation jobs
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS embedding_generation_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_type TEXT NOT NULL CHECK (job_type IN ('backfill', 'incremental', 'update')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'failed', 'cancelled')),

    -- Scope
    target_table TEXT NOT NULL DEFAULT 'lumen_data_atoms',
    filter_criteria JSONB,

    -- Progress tracking
    total_records INTEGER DEFAULT 0,
    processed_records INTEGER DEFAULT 0,
    failed_records INTEGER DEFAULT 0,

    -- Timing
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    estimated_completion TIMESTAMP WITH TIME ZONE,

    -- Configuration
    model_name TEXT NOT NULL DEFAULT 'text-embedding-3-large',
    batch_size INTEGER DEFAULT 100,

    -- Error tracking
    last_error TEXT,
    error_details JSONB,

    -- Audit
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for monitoring active jobs
CREATE INDEX IF NOT EXISTS idx_embedding_jobs_status
ON embedding_generation_jobs (status, created_at DESC);

-- ═══════════════════════════════════════════════════════════════════════════
-- FUNCTION: Semantic similarity search on atoms
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION search_atoms_semantic(
    query_embedding vector(3072),
    match_threshold FLOAT DEFAULT 0.7,
    match_count INTEGER DEFAULT 10,
    filter_atom_type TEXT DEFAULT NULL,
    filter_tags TEXT[] DEFAULT NULL
)
RETURNS TABLE (
    id UUID,
    atom_type TEXT,
    title TEXT,
    content TEXT,
    structured_data JSONB,
    tags TEXT[],
    similarity FLOAT
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    RETURN QUERY
    SELECT
        a.id,
        a.atom_type,
        a.title,
        a.content,
        a.structured_data,
        a.tags,
        1 - (a.embedding <=> query_embedding) AS similarity
    FROM lumen_data_atoms a
    WHERE
        a.embedding IS NOT NULL
        AND a.status = 'active'
        AND (filter_atom_type IS NULL OR a.atom_type = filter_atom_type)
        AND (filter_tags IS NULL OR a.tags @> filter_tags)
        AND (1 - (a.embedding <=> query_embedding)) >= match_threshold
    ORDER BY a.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- FUNCTION: Hybrid search (semantic + keyword)
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION search_atoms_hybrid(
    query_text TEXT,
    query_embedding vector(3072),
    semantic_weight FLOAT DEFAULT 0.7,
    keyword_weight FLOAT DEFAULT 0.3,
    match_count INTEGER DEFAULT 10,
    filter_atom_type TEXT DEFAULT NULL
)
RETURNS TABLE (
    id UUID,
    atom_type TEXT,
    title TEXT,
    content TEXT,
    structured_data JSONB,
    tags TEXT[],
    semantic_score FLOAT,
    keyword_score FLOAT,
    combined_score FLOAT
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    RETURN QUERY
    WITH semantic_results AS (
        SELECT
            a.id,
            1 - (a.embedding <=> query_embedding) AS score
        FROM lumen_data_atoms a
        WHERE
            a.embedding IS NOT NULL
            AND a.status = 'active'
            AND (filter_atom_type IS NULL OR a.atom_type = filter_atom_type)
        ORDER BY a.embedding <=> query_embedding
        LIMIT match_count * 3
    ),
    keyword_results AS (
        SELECT
            a.id,
            ts_rank_cd(
                to_tsvector('english', COALESCE(a.title, '') || ' ' || COALESCE(a.content, '')),
                plainto_tsquery('english', query_text)
            ) AS score
        FROM lumen_data_atoms a
        WHERE
            a.status = 'active'
            AND (filter_atom_type IS NULL OR a.atom_type = filter_atom_type)
            AND to_tsvector('english', COALESCE(a.title, '') || ' ' || COALESCE(a.content, ''))
                @@ plainto_tsquery('english', query_text)
        LIMIT match_count * 3
    ),
    combined AS (
        SELECT
            COALESCE(s.id, k.id) AS id,
            COALESCE(s.score, 0) AS sem_score,
            COALESCE(k.score, 0) AS kw_score,
            (COALESCE(s.score, 0) * semantic_weight) +
            (COALESCE(k.score, 0) * keyword_weight) AS combined
        FROM semantic_results s
        FULL OUTER JOIN keyword_results k ON s.id = k.id
    )
    SELECT
        a.id,
        a.atom_type,
        a.title,
        a.content,
        a.structured_data,
        a.tags,
        c.sem_score AS semantic_score,
        c.kw_score AS keyword_score,
        c.combined AS combined_score
    FROM combined c
    JOIN lumen_data_atoms a ON a.id = c.id
    ORDER BY c.combined DESC
    LIMIT match_count;
END;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- TRIGGER: Auto-update updated_at on embedding changes
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION update_embedding_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.embedding IS DISTINCT FROM OLD.embedding THEN
        NEW.embedding_updated_at = NOW();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_embedding_timestamp ON lumen_data_atoms;
CREATE TRIGGER trigger_update_embedding_timestamp
    BEFORE UPDATE ON lumen_data_atoms
    FOR EACH ROW
    EXECUTE FUNCTION update_embedding_timestamp();

-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRATION COMPLETE
-- ═══════════════════════════════════════════════════════════════════════════
