-- =============================================================================
-- eCTD REGULATORY AUDIT CONTEXT
-- System: Lumen Cortex — FDA Shadow Review + eCTD Integrity Layer
-- Compliance: 21 CFR Part 11 (auditability, traceability), ALCOA+ principles
-- Purpose: Evidence Fabric schema — claims, sources, support links, derivation
--          chains, and tamper-evident hash ledger for regulatory defensibility.
--
-- eCTD/CTD Context:
--   - Module(s): Module 2 (summaries), Module 5 (clinical study reports)
--   - Integrity Risk Addressed: Untraced claims, hallucinated outputs,
--     missing source attribution, broken evidence chains.
--
-- Determinism Contract:
--   - Schema changes must not undermine deterministic evidence pointers.
--   - Any change impacting canonical schemas requires spec version bump.
--
-- Notes:
--   - RLS policies enforce program_id isolation via app.current_program_id GUC.
--   - Migration is idempotent (IF NOT EXISTS on schema, tables, indexes).
--   - Hash ledger rows are append-only — no UPDATE/DELETE permitted.
-- =============================================================================

-- ============================================================================
-- Phase 5 — Evidence Fabric: Claims, Sources, Support, Derivations, Hashes
-- Migration: 20260206_phase5_evidence_fabric.sql
--
-- Purpose:
--   1) Create the `evidence` schema for defensible output provenance
--   2) Define atomic claims (the "what was said")
--   3) Define sources (the "where it came from")
--   4) Define support links (many-to-many claim ↔ source with strength)
--   5) Define derivation chains (claim A derived from claim B)
--   6) Define provenance links (execution → claim traceability)
--   7) Define hash ledger (tamper-evident content fingerprints)
--   8) RLS policies scoped to program_id
--   9) Performance indexes
--
-- Anchors to: core.programs(id) — the Domain Spine pivot
-- Bridges to: orchestration.step_runs, orchestration.workflow_runs
-- RLS GUC:    app.current_program_id (consistent with vault/orchestration)
-- PK style:   UUID (consistent with core/identity/vault/orchestration schemas)
--
-- IDEMPOTENT: Safe to run multiple times (Neon-friendly)
-- ============================================================================

-- 0) Schema
CREATE SCHEMA IF NOT EXISTS evidence;

-- ============================================================================
-- 1) evidence.claims — atomic, typed, versioned claim records
-- ============================================================================

CREATE TABLE IF NOT EXISTS evidence.claims (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    program_id      UUID NOT NULL,          -- FK to core.programs(id)
    claim_type      TEXT NOT NULL,           -- 'efficacy', 'safety', 'endpoint', 'regulatory', 'procedural'
    claim_text      TEXT NOT NULL,           -- the natural-language assertion
    structured      JSONB NOT NULL DEFAULT '{}',
        -- typed fields: { entity, field, value, unit, comparator, timeframe }
    section_ref     TEXT,                    -- e.g. 'Module 2.7.3', 'CSR §12.4'
    version         INT NOT NULL DEFAULT 1, -- bump on correction
    supersedes_id   UUID REFERENCES evidence.claims(id),
    status          TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'superseded', 'retracted', 'draft')),
    confidence      NUMERIC(5,4),           -- 0.0000–1.0000, computed by scoring
    created_by      TEXT NOT NULL DEFAULT 'system',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE evidence.claims IS
    'Atomic typed claims extracted or generated by the platform. Every output assertion.';

-- ============================================================================
-- 2) evidence.sources — where evidence originates
-- ============================================================================

CREATE TABLE IF NOT EXISTS evidence.sources (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    program_id      UUID NOT NULL,
    source_type     TEXT NOT NULL,           -- 'csr_section', 'guideline', 'dataset_row', 'model_output', 'literature', 'sap'
    source_ref      TEXT NOT NULL,           -- human-readable ref: 'CSR §12.4', 'ICH E6(R2) §5.18', 'ADSL row 42'
    source_uri      TEXT,                    -- machine-resolvable: blob path, DB row pointer, URL
    content_hash    TEXT,                    -- sha256 of source content at time of capture
    metadata        JSONB NOT NULL DEFAULT '{}',
        -- { document_id, page, paragraph, table_id, nct_id, version }
    captured_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE evidence.sources IS
    'Evidence sources: CSR sections, guidelines, datasets, model outputs. Immutable captures.';

-- ============================================================================
-- 3) evidence.support — many-to-many claim ↔ source with strength
-- ============================================================================

CREATE TABLE IF NOT EXISTS evidence.support (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    claim_id        UUID NOT NULL REFERENCES evidence.claims(id),
    source_id       UUID NOT NULL REFERENCES evidence.sources(id),
    program_id      UUID NOT NULL,
    support_type    TEXT NOT NULL DEFAULT 'supports'
        CHECK (support_type IN ('supports', 'contradicts', 'qualifies', 'neutral')),
    strength        NUMERIC(5,4) NOT NULL DEFAULT 0.5000,
        -- 0 = no support, 1 = definitive
    span_start      INT,                    -- character offset in source content
    span_end        INT,
    annotation      TEXT,                   -- human/model explanation of the link
    created_by      TEXT NOT NULL DEFAULT 'system',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (claim_id, source_id, support_type)
);

COMMENT ON TABLE evidence.support IS
    'Many-to-many links between claims and sources. Includes strength score + span pointers.';

-- ============================================================================
-- 4) evidence.derivations — claim A derived from claim B (reasoning chains)
-- ============================================================================

CREATE TABLE IF NOT EXISTS evidence.derivations (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    program_id      UUID NOT NULL,
    derived_claim_id    UUID NOT NULL REFERENCES evidence.claims(id),
    source_claim_id     UUID NOT NULL REFERENCES evidence.claims(id),
    derivation_type     TEXT NOT NULL DEFAULT 'inference'
        CHECK (derivation_type IN ('inference', 'aggregation', 'correction', 'contradiction', 'synthesis')),
    reasoning       TEXT,                   -- explanation of the derivation step
    model_id        TEXT,                   -- which model/agent produced this
    created_by      TEXT NOT NULL DEFAULT 'system',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (derived_claim_id, source_claim_id, derivation_type),
    CHECK (derived_claim_id != source_claim_id)
);

COMMENT ON TABLE evidence.derivations IS
    'Reasoning lineage: how claim A was derived from claim B. Enables chain-of-thought replay.';

-- ============================================================================
-- 5) evidence.provenance — execution → claim traceability
-- ============================================================================

CREATE TABLE IF NOT EXISTS evidence.provenance (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    program_id          UUID NOT NULL,
    claim_id            UUID REFERENCES evidence.claims(id),
    source_id           UUID REFERENCES evidence.sources(id),
    -- Execution context (nullable — at least one must be set)
    workflow_run_id     UUID,               -- FK to orchestration.workflow_runs(id)
    step_run_id         UUID,               -- FK to orchestration.step_runs(id)
    batch_id            UUID,               -- FK to vault.review_batches(batch_id)
    event_type          TEXT NOT NULL,       -- 'claim_extracted', 'source_captured', 'claim_generated', 'claim_scored'
    actor               TEXT NOT NULL DEFAULT 'system',
    request_id          TEXT,               -- correlates to X-Request-Id header
    metadata            JSONB NOT NULL DEFAULT '{}',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (claim_id IS NOT NULL OR source_id IS NOT NULL)
);

COMMENT ON TABLE evidence.provenance IS
    'Execution provenance: which workflow/step/batch created which claim or source. Forensic bridge.';

-- ============================================================================
-- 6) evidence.hash_ledger — tamper-evident content fingerprints
-- ============================================================================

CREATE TABLE IF NOT EXISTS evidence.hash_ledger (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    program_id      UUID NOT NULL,
    entity_type     TEXT NOT NULL,           -- 'claim', 'source', 'support', 'derivation', 'document'
    entity_id       UUID NOT NULL,
    content_hash    TEXT NOT NULL,           -- sha256 of canonical content
    prev_hash       TEXT,                    -- hash of previous version (chain)
    algorithm       TEXT NOT NULL DEFAULT 'sha256',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE evidence.hash_ledger IS
    'Append-only tamper-evidence ledger. Content hashes for claims, sources, and artifacts.';

-- ============================================================================
-- 7) RLS Policies — program_id isolation
-- ============================================================================

ALTER TABLE evidence.claims       ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence.sources      ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence.support      ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence.derivations  ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence.provenance   ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence.hash_ledger  ENABLE ROW LEVEL SECURITY;

-- Claims
DO $$ BEGIN
CREATE POLICY evidence_claims_program_isolation ON evidence.claims
    USING (
        program_id::TEXT = current_setting('app.current_program_id', TRUE)
        OR current_setting('app.bypass_rls', TRUE) = 'true'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Sources
DO $$ BEGIN
CREATE POLICY evidence_sources_program_isolation ON evidence.sources
    USING (
        program_id::TEXT = current_setting('app.current_program_id', TRUE)
        OR current_setting('app.bypass_rls', TRUE) = 'true'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Support
DO $$ BEGIN
CREATE POLICY evidence_support_program_isolation ON evidence.support
    USING (
        program_id::TEXT = current_setting('app.current_program_id', TRUE)
        OR current_setting('app.bypass_rls', TRUE) = 'true'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Derivations
DO $$ BEGIN
CREATE POLICY evidence_derivations_program_isolation ON evidence.derivations
    USING (
        program_id::TEXT = current_setting('app.current_program_id', TRUE)
        OR current_setting('app.bypass_rls', TRUE) = 'true'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Provenance
DO $$ BEGIN
CREATE POLICY evidence_provenance_program_isolation ON evidence.provenance
    USING (
        program_id::TEXT = current_setting('app.current_program_id', TRUE)
        OR current_setting('app.bypass_rls', TRUE) = 'true'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Hash Ledger
DO $$ BEGIN
CREATE POLICY evidence_hash_ledger_program_isolation ON evidence.hash_ledger
    USING (
        program_id::TEXT = current_setting('app.current_program_id', TRUE)
        OR current_setting('app.bypass_rls', TRUE) = 'true'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================================
-- 8) Indexes — query-path optimized
-- ============================================================================

-- Claims
CREATE INDEX IF NOT EXISTS idx_evidence_claims_program
    ON evidence.claims (program_id);
CREATE INDEX IF NOT EXISTS idx_evidence_claims_type_status
    ON evidence.claims (program_id, claim_type, status);
CREATE INDEX IF NOT EXISTS idx_evidence_claims_section
    ON evidence.claims (program_id, section_ref)
    WHERE section_ref IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_evidence_claims_supersedes
    ON evidence.claims (supersedes_id)
    WHERE supersedes_id IS NOT NULL;

-- Sources
CREATE INDEX IF NOT EXISTS idx_evidence_sources_program
    ON evidence.sources (program_id);
CREATE INDEX IF NOT EXISTS idx_evidence_sources_type
    ON evidence.sources (program_id, source_type);
CREATE INDEX IF NOT EXISTS idx_evidence_sources_content_hash
    ON evidence.sources (content_hash)
    WHERE content_hash IS NOT NULL;

-- Support
CREATE INDEX IF NOT EXISTS idx_evidence_support_claim
    ON evidence.support (claim_id);
CREATE INDEX IF NOT EXISTS idx_evidence_support_source
    ON evidence.support (source_id);
CREATE INDEX IF NOT EXISTS idx_evidence_support_program
    ON evidence.support (program_id);
CREATE INDEX IF NOT EXISTS idx_evidence_support_type
    ON evidence.support (claim_id, support_type);

-- Derivations
CREATE INDEX IF NOT EXISTS idx_evidence_derivations_derived
    ON evidence.derivations (derived_claim_id);
CREATE INDEX IF NOT EXISTS idx_evidence_derivations_source
    ON evidence.derivations (source_claim_id);
CREATE INDEX IF NOT EXISTS idx_evidence_derivations_program
    ON evidence.derivations (program_id);

-- Provenance
CREATE INDEX IF NOT EXISTS idx_evidence_provenance_claim
    ON evidence.provenance (claim_id)
    WHERE claim_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_evidence_provenance_source
    ON evidence.provenance (source_id)
    WHERE source_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_evidence_provenance_program
    ON evidence.provenance (program_id);
CREATE INDEX IF NOT EXISTS idx_evidence_provenance_workflow
    ON evidence.provenance (workflow_run_id)
    WHERE workflow_run_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_evidence_provenance_step
    ON evidence.provenance (step_run_id)
    WHERE step_run_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_evidence_provenance_request
    ON evidence.provenance (request_id)
    WHERE request_id IS NOT NULL;

-- Hash Ledger
CREATE INDEX IF NOT EXISTS idx_evidence_hash_ledger_entity
    ON evidence.hash_ledger (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_evidence_hash_ledger_program
    ON evidence.hash_ledger (program_id);
CREATE INDEX IF NOT EXISTS idx_evidence_hash_ledger_hash
    ON evidence.hash_ledger (content_hash);

-- ============================================================================
-- 9) Views — convenience queries
-- ============================================================================

-- Claim with all supporting sources (denormalized for read)
CREATE OR REPLACE VIEW evidence.v_claim_support AS
SELECT
    c.id AS claim_id,
    c.program_id,
    c.claim_type,
    c.claim_text,
    c.confidence,
    c.status AS claim_status,
    c.section_ref,
    s.id AS support_id,
    s.support_type,
    s.strength,
    src.id AS source_id,
    src.source_type,
    src.source_ref,
    src.content_hash AS source_hash
FROM evidence.claims c
JOIN evidence.support s ON s.claim_id = c.id
JOIN evidence.sources src ON src.id = s.source_id
WHERE c.status = 'active';

COMMENT ON VIEW evidence.v_claim_support IS
    'Denormalized view: active claims with all supporting/contradicting sources.';

-- Derivation chain (one level deep — use recursive CTE in app layer for full chain)
CREATE OR REPLACE VIEW evidence.v_derivation_chain AS
SELECT
    d.id AS derivation_id,
    d.program_id,
    d.derivation_type,
    d.reasoning,
    dc.id AS derived_claim_id,
    dc.claim_text AS derived_text,
    dc.claim_type AS derived_type,
    sc.id AS source_claim_id,
    sc.claim_text AS source_text,
    sc.claim_type AS source_type
FROM evidence.derivations d
JOIN evidence.claims dc ON dc.id = d.derived_claim_id
JOIN evidence.claims sc ON sc.id = d.source_claim_id;

COMMENT ON VIEW evidence.v_derivation_chain IS
    'One-level derivation chain: derived claim ← source claim with reasoning.';

-- Execution provenance (full trace: who/what/when → which evidence)
CREATE OR REPLACE VIEW evidence.v_execution_provenance AS
SELECT
    p.id AS provenance_id,
    p.program_id,
    p.event_type,
    p.actor,
    p.request_id,
    p.created_at,
    p.workflow_run_id,
    p.step_run_id,
    p.batch_id,
    c.id AS claim_id,
    c.claim_text,
    c.claim_type,
    src.id AS source_id,
    src.source_ref,
    src.source_type
FROM evidence.provenance p
LEFT JOIN evidence.claims c ON c.id = p.claim_id
LEFT JOIN evidence.sources src ON src.id = p.source_id;

COMMENT ON VIEW evidence.v_execution_provenance IS
    'Full execution provenance: workflow/step/batch → claim/source with actor + request_id.';

-- ============================================================================
-- 10) Grants — service account access
-- ============================================================================

DO $$ BEGIN
    -- Grant schema usage
    GRANT USAGE ON SCHEMA evidence TO current_user;
    -- Grant table access
    GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA evidence TO current_user;
    -- Hash ledger: append-only (revoke UPDATE/DELETE)
    REVOKE UPDATE, DELETE ON evidence.hash_ledger FROM current_user;
    GRANT SELECT, INSERT ON evidence.hash_ledger TO current_user;
    -- Grant sequence access
    GRANT USAGE ON ALL SEQUENCES IN SCHEMA evidence TO current_user;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Grant adjustments: %', SQLERRM;
END $$;

-- ============================================================================
-- Done — Evidence Fabric schema ready
-- ============================================================================
