-- =============================================================================
-- eCTD REGULATORY AUDIT CONTEXT
-- System: Lumen Cortex — FDA Shadow Review + eCTD Integrity Layer
-- Compliance: 21 CFR Part 11 (auditability, traceability), ALCOA+ principles
-- Purpose: Give the AI provenance ledger a real table, so every AI call's
--          model / parameters / prompt hash / placement is actually recorded.
--
-- eCTD/CTD Context:
--   - Module(s): cross-cutting — any module whose content is AI-assisted
--   - Integrity Risk Addressed: unattributable AI-generated content. Without
--     this table the ledger recorded nothing, so no submission artifact could
--     be traced to the model and parameters that produced it.
--
-- Determinism Contract:
--   - Schema changes must not undermine deterministic evidence pointers.
--   - resolved_model records the snapshot the provider reports, so a row
--     identifies a fixed model rather than a floating alias.
-- =============================================================================
--
-- 20260813_ai_gateway_audit_log.sql
--
-- Own ai.gateway_audit_log in a migration, so the AI provenance ledger EXISTS
-- on a provisioned database.
--
-- ── The defect this closes ───────────────────────────────────────────────────
-- This table had no migration anywhere in the repo. Its only creator was
-- runtime DDL in server/services/ai-gateway/audit.ts (`ensureTable()`), run
-- lazily the first time an AI call tried to persist a record:
--
--     await this.pool.query(`CREATE SCHEMA IF NOT EXISTS ai`);
--     await this.pool.query(`CREATE TABLE IF NOT EXISTS ai.gateway_audit_log (...)`);
--
-- and wrapped in a catch that logged "Table creation failed" and carried on.
-- On a correctly least-privileged deployment that can never succeed: PostgreSQL
-- checks the database-level CREATE privilege BEFORE the `IF NOT EXISTS`
-- short-circuit, so the first statement raises `permission denied for database`
-- for the non-superuser runtime role even though the `ai` schema already exists
-- (059_gcc_vector_embeddings.sql creates it). The exception was swallowed,
-- `tableInitialized` stayed false, and every subsequent INSERT failed the same
-- way into the same catch.
--
-- This is not a hypothetical. scripts/ci/tables-live-schema-baseline.json —
-- which is generated by diffing the tables the server QUERIES against a real
-- PostgreSQL built by a full install-fresh + deploy-migrate run — lists
-- `ai.gateway_audit_log` as absent, attributed to audit.ts.
--
-- So: the ledger that is supposed to record which model, at which temperature,
-- from which prompt, in which region, produced every AI output on a regulated
-- platform recorded nothing at all, and the gateway logged each call as
-- audited. A control that reports success while writing nothing is worse than
-- no control, because only the first one gets relied on in an inspection.
--
-- ── resolved_model, and why it is separate from model ────────────────────────
-- `model` is what the gateway ASKED for — `modelConfig.model` straight out of
-- the DEFAULT_MODELS registry. Most of those entries are floating aliases
-- (gpt-4o, claude-opus-4-8, claude-sonnet-4-6, moonshot-v1-128k, ...), and an
-- alias points at a different snapshot over time. Recording only the alias
-- means a ledger row cannot answer "which model produced this output" — the one
-- question the row exists to answer.
--
-- Both providers return the resolved identifier in the response body
-- (`completion.model` on the OpenAI-compatible surface, `model` on Anthropic
-- messages). `resolved_model` records it verbatim. Keeping both columns rather
-- than overwriting `model` preserves the routing decision (which alias the
-- policy chose) alongside the fact (which snapshot answered); collapsing them
-- would lose the first, and existing dashboards group by `model`.
--
-- It is nullable: a provider that omits the field, and the cached/deterministic
-- paths, legitimately have nothing to record. NULL here means "the provider did
-- not tell us", which is a true statement — unlike copying the alias across,
-- which would manufacture a resolution that never happened.
--
-- ── Why this table is NOT immutable ──────────────────────────────────────────
-- Its sibling audit.tamper_proof_log carries a BEFORE UPDATE OR DELETE trigger
-- and append-only grants, because it is the 21 CFR Part 11 tamper-evident
-- store. This one deliberately does not. It holds user_id and organization_id
-- and is therefore in scope for erasure and retention work; a hard DELETE block
-- would put the two obligations in direct conflict and the trigger would have
-- to be dropped to satisfy the second. The Part 11 tamper-evidence claim rests
-- on audit.tamper_proof_log, not here, and claiming immutability that the
-- retention path must later break would be a claim this schema cannot keep.
--
-- Idempotent throughout (IF NOT EXISTS / ADD COLUMN IF NOT EXISTS); safe to
-- re-run on every deploy, and safe against a deployment where the old runtime
-- DDL already managed to create the table.

BEGIN;

CREATE SCHEMA IF NOT EXISTS ai;

CREATE TABLE IF NOT EXISTS ai.gateway_audit_log (
  id                 SERIAL PRIMARY KEY,
  request_id         UUID NOT NULL,
  timestamp          TIMESTAMPTZ DEFAULT NOW(),

  -- Routing outcome.
  provider           VARCHAR(20) NOT NULL,
  model              VARCHAR(64) NOT NULL,   -- alias/registry entry requested
  resolved_model     VARCHAR(128),           -- snapshot the provider reports
  task_type          VARCHAR(32) NOT NULL,
  strategy           VARCHAR(32) NOT NULL,

  -- Attribution.
  organization_id    VARCHAR(64),
  user_id            VARCHAR(64),
  project_id         VARCHAR(64),
  caller_module      VARCHAR(128),

  -- Usage / cost.
  input_tokens       INTEGER DEFAULT 0,
  output_tokens      INTEGER DEFAULT 0,
  total_tokens       INTEGER DEFAULT 0,
  estimated_cost_usd NUMERIC(10,6) DEFAULT 0,
  latency_ms         INTEGER DEFAULT 0,

  -- Outcome.
  success            BOOLEAN DEFAULT true,
  error              TEXT,
  cached             BOOLEAN DEFAULT false,
  deterministic      BOOLEAN DEFAULT false,
  metadata           JSONB,

  -- Reproducibility: the parameters + prompt that produced the output.
  -- temperature is the EFFECTIVE value — NULL for reasoning-only models that
  -- reject sampling entirely, rather than the defaulted value we would have
  -- sent. seed is NULL unless a caller supplied one; no seed was transmitted.
  temperature        NUMERIC(4,2),
  seed               BIGINT,
  prompt_hash        VARCHAR(64),
  prompt_version     VARCHAR(64),
  tried_models       JSONB,

  -- Placement evidence: where regulated data was actually processed.
  substrate          VARCHAR(20),
  region             VARCHAR(16),
  retention_policy   VARCHAR(20)
);

-- Bring a table created by the old runtime DDL up to the current shape. Every
-- column below post-dates some deployed version of ensureTable().
ALTER TABLE ai.gateway_audit_log
  ADD COLUMN IF NOT EXISTS resolved_model   VARCHAR(128),
  ADD COLUMN IF NOT EXISTS temperature      NUMERIC(4,2),
  ADD COLUMN IF NOT EXISTS seed             BIGINT,
  ADD COLUMN IF NOT EXISTS prompt_hash      VARCHAR(64),
  ADD COLUMN IF NOT EXISTS prompt_version   VARCHAR(64),
  ADD COLUMN IF NOT EXISTS tried_models     JSONB,
  ADD COLUMN IF NOT EXISTS substrate        VARCHAR(20),
  ADD COLUMN IF NOT EXISTS region           VARCHAR(16),
  ADD COLUMN IF NOT EXISTS retention_policy VARCHAR(20);

CREATE INDEX IF NOT EXISTS idx_gateway_audit_org         ON ai.gateway_audit_log(organization_id);
CREATE INDEX IF NOT EXISTS idx_gateway_audit_timestamp   ON ai.gateway_audit_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_gateway_audit_provider    ON ai.gateway_audit_log(provider);
CREATE INDEX IF NOT EXISTS idx_gateway_audit_request     ON ai.gateway_audit_log(request_id);
CREATE INDEX IF NOT EXISTS idx_gateway_audit_prompt_hash ON ai.gateway_audit_log(prompt_hash);

-- Grant the runtime role now, rather than relying on provision-app-role.mjs
-- having run after this migration. That script grants ON ALL TABLES IN SCHEMA
-- plus ALTER DEFAULT PRIVILEGES, so it covers this table on its next run
-- either way; granting here means the ledger is writable the moment it exists,
-- regardless of step ordering. `ai` carries no entry in
-- SCHEMA_PRIVILEGE_OVERRIDES, so its runtime privileges are the full-DML
-- default — matched here deliberately (see "Why this table is NOT immutable").
DO $$
DECLARE
  app_role text := current_setting('app.service_role', TRUE);
BEGIN
  IF app_role IS NULL OR app_role = '' THEN app_role := 'app_service'; END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = app_role) THEN
    EXECUTE format('GRANT USAGE ON SCHEMA ai TO %I', app_role);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ai.gateway_audit_log TO %I', app_role);
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE ai.gateway_audit_log_id_seq TO %I', app_role);
    RAISE NOTICE '[ai-gateway] grants applied to %', app_role;
  END IF;
END
$$;

COMMIT;
