-- Submission-chat rewrite proposal store.
--
-- Persists rewrite proposals generated by submission-chat so that:
--   - confirm_apply ("apply that") resolves to a server-side proposal id
--     instead of trusting the client to re-send the proposal payload.
--   - the proposal -> apply chain is durable + auditable.
--   - replay attacks fail (proposal_id is bound to content_hash + status).
--   - stale proposals are bounded by expires_at (default 24h).
--
-- Tenant isolation is enforced at the service layer (organization_id +
-- artifact_pk + project_id are checked before any apply).

BEGIN;

CREATE TABLE IF NOT EXISTS ana_submission_chat_proposals (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id             TEXT NOT NULL,
  artifact_id           TEXT NOT NULL,        -- external artifact_xxx id
  artifact_pk           INTEGER NOT NULL,     -- concept2cure_artifacts.id (numeric)
  organization_id       INTEGER NOT NULL,
  project_id            INTEGER NOT NULL,
  section_code          TEXT,
  target_agency         TEXT,                 -- canonical: EMA, FDA, PMDA, ...
  rationale             TEXT,
  proposed_content      TEXT NOT NULL,
  content_hash          TEXT NOT NULL,        -- sha256(proposed_content)
  claim_verification    JSONB,                -- per-paragraph verifier rollup
  claim_status_counts   JSONB,                -- { supported, weak, unsupported }

  -- pending = active, can be applied
  -- applied = was applied; applied_audit_id + applied_version_id link to the audit chain
  -- superseded = a newer proposal for the same artifact replaced this one
  -- expired = past expires_at without being applied
  status                TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','applied','superseded','expired')),
  applied_audit_id      TEXT,
  applied_version_id    INTEGER,
  applied_at            TIMESTAMPTZ,

  created_by            INTEGER,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at            TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '24 hours')
);

-- Hot path: confirm_apply looks up the latest pending proposal for a
-- (thread_id, artifact_id) pair.
CREATE INDEX IF NOT EXISTS idx_ana_sc_proposals_thread_artifact
  ON ana_submission_chat_proposals(thread_id, artifact_id, status);

-- Tenant scope.
CREATE INDEX IF NOT EXISTS idx_ana_sc_proposals_org
  ON ana_submission_chat_proposals(organization_id);

-- Janitor: find pending proposals past their TTL.
CREATE INDEX IF NOT EXISTS idx_ana_sc_proposals_status_expires
  ON ana_submission_chat_proposals(status, expires_at)
  WHERE status = 'pending';

-- Supersede sweep: when a new proposal lands for an artifact, the service
-- marks any other pending proposals for the same artifact as superseded.
CREATE INDEX IF NOT EXISTS idx_ana_sc_proposals_artifact_status
  ON ana_submission_chat_proposals(artifact_id, status)
  WHERE status = 'pending';

COMMIT;
