"""Generate premium seed DOCX template files with {{ variable }} placeholders.

Phase 6.6 — Premium Template Packs: IND full application, 510(k) full dossier,
and Clinical Evaluation Report (CER) designed for eCTD 4.0.

Run once to create the actual .docx files in demo_templates/.
These are committed to the repo so the seed script can load them.

Usage:
    python -m shadow_service.generate_seed_templates

Template Catalog (19 templates):
  IND Full Application (10):
    1.  eCTD Cover Letter
    2.  Form FDA 1571 Narrative Summary
    3.  Investigator Brochure Change Summary
    4.  CMC Drug Substance Overview (3.2.S)
    5.  CMC Drug Product Overview (3.2.P)
    6.  Clinical Overview: Benefit/Risk Summary (2.5)
    7.  Nonclinical Overview (2.4)
    8.  Quality Overall Summary (2.3)
    9.  Clinical Study Report Synopsis
    10. Protocol Synopsis

  510(k) Full Dossier (5):
    11. 510(k) Cover Letter + Administrative Info
    12. Substantial Equivalence / Predicate Comparison
    13. Device Description + Performance Testing
    14. 510(k) Summary
    15. Biocompatibility Evaluation Summary

  CER for eCTD 4.0 (4):
    16. Clinical Evaluation Plan (CEP)
    17. Clinical Evaluation Report — Literature Analysis
    18. CER Benefit-Risk Determination + PMCF Plan
    19. State of the Art Report
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import TYPE_CHECKING

from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

if TYPE_CHECKING:
    from docx.document import Document as DocumentClass


TEMPLATES_DIR = Path(__file__).parent / "demo_templates"


# =============================================================================
# Helpers
# =============================================================================

def _add_heading(doc: DocumentClass, text: str, level: int = 0) -> None:
    doc.add_heading(text, level=level)


def _add_para(doc: DocumentClass, text: str, bold: bool = False) -> None:
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = bold


def _add_table_row(table, cells: list[str]) -> None:
    row = table.add_row()
    for i, val in enumerate(cells):
        row.cells[i].text = val


def _make_table(doc: DocumentClass, headers: list[str], rows: list[list[str]]) -> None:
    """Add a table with headers + data rows."""
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    for i, h in enumerate(headers):
        table.rows[0].cells[i].text = h
    for row_data in rows:
        _add_table_row(table, row_data)


def _add_signature_block(doc: DocumentClass, prefix: str = "") -> None:
    """Standard regulatory signature block."""
    _add_para(doc, "")
    _add_para(doc, "Respectfully submitted,")
    _add_para(doc, f"{{{{ {prefix}signatory_name }}}}")
    _add_para(doc, f"{{{{ {prefix}signatory_title }}}}")
    _add_para(doc, f"{{{{ {prefix}sponsor_name }}}}")
    _add_para(doc, f"Date: {{{{ {prefix}signature_date }}}}")


def _add_doc_control_footer(doc: DocumentClass, doc_id_var: str = "document_id") -> None:
    """Controlled document footer with provenance."""
    _add_para(doc, "")
    _add_para(doc, "─" * 60)
    _add_para(doc, f"Document ID: {{{{ {doc_id_var} }}}}")
    _add_para(doc, "Classification: {{ classification }}")
    _add_para(doc, "Generated by: ClinicalSage DOCX Factory")
    _add_para(doc, "This document is electronically generated. No wet signature required when submitted via eCTD gateway.")


# =============================================================================
# IND FULL APPLICATION (10 templates)
# =============================================================================

# ---------------------------------------------------------------------------
# 1. eCTD Cover Letter (upgraded)
# ---------------------------------------------------------------------------
def make_ectd_cover_letter() -> None:
    doc = Document()
    _add_heading(doc, "eCTD Cover Letter", level=0)

    _add_para(doc, "Date: {{ submission_date }}")
    _add_para(doc, "")
    _add_para(doc, "{{ regulatory_authority }}")
    _add_para(doc, "{{ authority_address }}")
    _add_para(doc, "")
    _add_para(doc, "Re: {{ submission_type }} for {{ product_name }} ({{ generic_name }})")
    _add_para(doc, "Application Number: {{ application_number }}")
    _add_para(doc, "Sequence Number: {{ sequence_number }}")
    _add_para(doc, "")
    _add_para(doc, "Dear {{ reviewer_name }},")
    _add_para(doc, "")
    _add_para(
        doc,
        "{{ sponsor_name }} hereby submits this {{ submission_type }} for "
        "{{ product_name }} ({{ generic_name }}), {{ dosage_form }}, for the "
        "proposed indication of {{ indication }}."
    )
    _add_para(doc, "")

    # Modules included table
    _add_para(doc, "Modules Included in This Submission", bold=True)
    _make_table(doc, ["Module", "Content", "Status"], [
        ["1", "Administrative Information", "{{ module_1_status }}"],
        ["2.2", "Introduction", "{{ module_2_2_status }}"],
        ["2.3", "Quality Overall Summary", "{{ module_2_3_status }}"],
        ["2.4", "Nonclinical Overview", "{{ module_2_4_status }}"],
        ["2.5", "Clinical Overview", "{{ module_2_5_status }}"],
        ["2.7", "Clinical Summary", "{{ module_2_7_status }}"],
        ["3", "Quality (CMC)", "{{ module_3_status }}"],
        ["4", "Nonclinical Study Reports", "{{ module_4_status }}"],
        ["5", "Clinical Study Reports", "{{ module_5_status }}"],
    ])
    _add_para(doc, "")

    _add_para(doc, "Key changes in this sequence include: {{ key_changes }}")
    _add_para(doc, "")

    _add_para(doc, "Contact Information", bold=True)
    _make_table(doc, ["Role", "Name", "Email", "Phone"], [
        ["Regulatory Contact", "{{ contact_name }}", "{{ contact_email }}", "{{ contact_phone }}"],
        ["Medical Monitor", "{{ medical_monitor_name }}", "{{ medical_monitor_email }}", "{{ medical_monitor_phone }}"],
    ])

    _add_signature_block(doc)
    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "ectd_cover_letter.docx"))


# ---------------------------------------------------------------------------
# 2. Form FDA 1571 Narrative Summary (upgraded)
# ---------------------------------------------------------------------------
def make_fda_1571_narrative() -> None:
    doc = Document()
    _add_heading(doc, "IND Application — Form FDA 1571 Narrative Summary", level=0)

    _add_para(doc, "1. Sponsor Information", bold=True)
    _make_table(doc, ["Field", "Value"], [
        ["Sponsor Name", "{{ sponsor_name }}"],
        ["Sponsor Address", "{{ sponsor_address }}"],
        ["IND Number", "{{ ind_number }}"],
        ["Date of Submission", "{{ submission_date }}"],
        ["Product Name", "{{ product_name }} ({{ generic_name }})"],
        ["Phase of Investigation", "{{ phase }}"],
        ["Therapeutic Area", "{{ therapeutic_area }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "2. Investigational Plan Summary", bold=True)
    _add_para(
        doc,
        "{{ product_name }} ({{ generic_name }}) is a {{ drug_class }} being "
        "developed for the treatment of {{ indication }}. This {{ phase }} "
        "study is designed as {{ study_design }}."
    )
    _add_para(doc, "")
    _add_para(doc, "Study Endpoints", bold=True)
    _make_table(doc, ["Endpoint Type", "Measure", "Timepoint"], [
        ["Primary", "{{ primary_endpoint }}", "{{ primary_timepoint }}"],
        ["Secondary", "{{ secondary_endpoint_1 }}", "{{ secondary_timepoint_1 }}"],
        ["Secondary", "{{ secondary_endpoint_2 }}", "{{ secondary_timepoint_2 }}"],
        ["Exploratory", "{{ exploratory_endpoint }}", "{{ exploratory_timepoint }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "3. Chemistry, Manufacturing, and Controls Summary", bold=True)
    _make_table(doc, ["Parameter", "Detail"], [
        ["Manufacturer", "{{ manufacturer }}"],
        ["Manufacturing Site", "{{ manufacturing_site }}"],
        ["Dosage Form", "{{ dosage_form }}"],
        ["Dosage Strength", "{{ dosage_strength }}"],
        ["Route of Administration", "{{ route_of_admin }}"],
        ["Storage Conditions", "{{ storage_conditions }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "4. Pharmacology / Toxicology Summary", bold=True)
    _add_para(doc, "{{ nonclinical_summary }}")
    _add_para(doc, "")
    _add_para(doc, "Key Nonclinical Studies", bold=True)
    _make_table(doc, ["Study Type", "Species", "Duration", "Finding"], [
        ["Single-dose tox", "{{ tox_species_1 }}", "{{ tox_duration_1 }}", "{{ tox_finding_1 }}"],
        ["Repeat-dose tox", "{{ tox_species_2 }}", "{{ tox_duration_2 }}", "{{ tox_finding_2 }}"],
        ["Genotoxicity", "{{ gentox_system }}", "—", "{{ gentox_finding }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "5. Previous Human Experience", bold=True)
    _add_para(doc, "{{ previous_human_experience }}")

    _add_para(doc, "")
    _add_para(doc, "6. Investigator Information", bold=True)
    _make_table(doc, ["Role", "Name", "Site", "Qualifications"], [
        ["Principal Investigator", "{{ principal_investigator }}", "{{ clinical_site }}", "{{ pi_qualifications }}"],
        ["Sub-Investigator", "{{ sub_investigator }}", "{{ clinical_site }}", "{{ si_qualifications }}"],
    ])

    _add_signature_block(doc)
    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "fda_1571_narrative.docx"))


# ---------------------------------------------------------------------------
# 3. Investigator Brochure Change Summary (upgraded)
# ---------------------------------------------------------------------------
def make_ib_change_summary() -> None:
    doc = Document()
    _add_heading(doc, "Investigator's Brochure — Change Summary", level=0)

    _add_para(doc, "Product: {{ product_name }} ({{ generic_name }})")
    _add_para(doc, "IB Edition: {{ ib_edition }}")
    _add_para(doc, "Effective Date: {{ effective_date }}")
    _add_para(doc, "Sponsor: {{ sponsor_name }}")
    _add_para(doc, "")

    _add_para(doc, "1. Revision History", bold=True)
    _make_table(doc, ["Edition", "Date", "Author", "Description of Change"], [
        ["{{ previous_edition }}", "{{ previous_edition_date }}", "{{ previous_author }}", "{{ previous_change_desc }}"],
        ["{{ ib_edition }}", "{{ effective_date }}", "{{ current_author }}", "{{ current_change_desc }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "2. Summary of Changes", bold=True)
    _add_para(
        doc,
        "This edition of the Investigator's Brochure for {{ product_name }} "
        "incorporates the following changes from edition {{ previous_edition }}:"
    )
    _add_para(doc, "")

    _add_para(doc, "2.1 Section-by-Section Changes", bold=True)
    _make_table(doc, ["IB Section", "Change Type", "Description"], [
        ["{{ changed_section_1 }}", "{{ change_type_1 }}", "{{ change_desc_1 }}"],
        ["{{ changed_section_2 }}", "{{ change_type_2 }}", "{{ change_desc_2 }}"],
        ["{{ changed_section_3 }}", "{{ change_type_3 }}", "{{ change_desc_3 }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "3. New Safety Data", bold=True)
    _add_para(doc, "{{ new_safety_data }}")
    _add_para(doc, "")
    _add_para(doc, "Adverse Event Summary (cumulative)", bold=True)
    _make_table(doc, ["Event", "Incidence", "Severity", "Relatedness"], [
        ["{{ ae_event_1 }}", "{{ ae_incidence_1 }}", "{{ ae_severity_1 }}", "{{ ae_relatedness_1 }}"],
        ["{{ ae_event_2 }}", "{{ ae_incidence_2 }}", "{{ ae_severity_2 }}", "{{ ae_relatedness_2 }}"],
        ["{{ ae_event_3 }}", "{{ ae_incidence_3 }}", "{{ ae_severity_3 }}", "{{ ae_relatedness_3 }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "4. Updated Efficacy Information", bold=True)
    _add_para(doc, "{{ updated_efficacy }}")

    _add_para(doc, "")
    _add_para(doc, "5. Revised Dosing Information", bold=True)
    _add_para(doc, "{{ revised_dosing }}")

    _add_para(doc, "")
    _add_para(doc, "6. Impact Assessment", bold=True)
    _add_para(
        doc,
        "The changes described above {{ impact_assessment }}. "
        "The overall benefit-risk profile remains {{ benefit_risk_status }}."
    )

    _add_para(doc, "")
    _add_para(doc, "Prepared by: {{ prepared_by }}")
    _add_para(doc, "Reviewed by: {{ reviewed_by }}")
    _add_para(doc, "Medical Review: {{ medical_reviewer }}")
    _add_para(doc, "Date: {{ review_date }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "ib_change_summary.docx"))


# ---------------------------------------------------------------------------
# 4. CMC Drug Substance Overview (3.2.S) (upgraded)
# ---------------------------------------------------------------------------
def make_cmc_drug_substance() -> None:
    doc = Document()
    _add_heading(doc, "Module 3.2.S — Drug Substance", level=0)
    _add_para(doc, "{{ product_name }} ({{ generic_name }})")
    _add_para(doc, "Sponsor: {{ sponsor_name }}")
    _add_para(doc, "")

    _add_para(doc, "S.1 General Information", bold=True)
    _make_table(doc, ["Property", "Value"], [
        ["INN / Generic Name", "{{ generic_name }}"],
        ["Chemical Name (IUPAC)", "{{ chemical_name }}"],
        ["Molecular Formula", "{{ molecular_formula }}"],
        ["Molecular Weight", "{{ molecular_weight }}"],
        ["Structural Class", "{{ structural_class }}"],
        ["CAS Registry Number", "{{ cas_number }}"],
        ["Appearance", "{{ appearance }}"],
        ["Solubility", "{{ solubility }}"],
        ["pKa", "{{ pka }}"],
        ["Polymorphism", "{{ polymorphism }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "S.2 Manufacture", bold=True)
    _make_table(doc, ["Parameter", "Detail"], [
        ["Manufacturer", "{{ manufacturer }}"],
        ["Manufacturing Site", "{{ manufacturing_site }}"],
        ["GMP Certification", "{{ gmp_certification }}"],
        ["Batch Size", "{{ batch_size }}"],
        ["Synthetic Steps", "{{ synthetic_steps }}"],
    ])
    _add_para(doc, "Process Description: {{ process_description }}")

    _add_para(doc, "")
    _add_para(doc, "S.3 Characterization", bold=True)
    _add_para(doc, "S.3.1 Elucidation of Structure: {{ structure_elucidation }}")
    _add_para(doc, "S.3.2 Impurity Profile:", bold=True)
    _make_table(doc, ["Impurity", "Origin", "Specification", "Method"], [
        ["{{ impurity_1_name }}", "{{ impurity_1_origin }}", "{{ impurity_1_spec }}", "{{ impurity_1_method }}"],
        ["{{ impurity_2_name }}", "{{ impurity_2_origin }}", "{{ impurity_2_spec }}", "{{ impurity_2_method }}"],
        ["{{ impurity_3_name }}", "{{ impurity_3_origin }}", "{{ impurity_3_spec }}", "{{ impurity_3_method }}"],
        ["Total Impurities", "—", "{{ total_impurities_spec }}", "—"],
    ])

    _add_para(doc, "")
    _add_para(doc, "S.4 Control of Drug Substance", bold=True)
    _add_para(doc, "S.4.1 Specification:", bold=True)
    _make_table(doc, ["Test", "Method", "Acceptance Criteria", "Typical Result"], [
        ["Appearance", "Visual", "{{ appearance_spec }}", "{{ appearance_result }}"],
        ["Identity (IR)", "{{ identity_method }}", "Matches reference", "{{ identity_result }}"],
        ["Assay", "{{ assay_method }}", "{{ assay_spec }}", "{{ assay_result }}"],
        ["Related Substances", "{{ rs_method }}", "{{ rs_spec }}", "{{ rs_result }}"],
        ["Residual Solvents", "GC-HS", "{{ residual_solvent_spec }}", "{{ residual_solvent_result }}"],
        ["Water Content", "Karl Fischer", "{{ water_spec }}", "{{ water_result }}"],
        ["Particle Size", "{{ psd_method }}", "{{ psd_spec }}", "{{ psd_result }}"],
    ])

    _add_para(doc, "S.4.2 Analytical Procedures: {{ analytical_procedures }}")
    _add_para(doc, "S.4.3 Validation: {{ validation_summary }}")
    _add_para(doc, "S.4.4 Batch Analysis:", bold=True)
    _make_table(doc, ["Batch", "Scale", "Assay (%)", "Total Impurities (%)", "Date"], [
        ["{{ batch_1_id }}", "{{ batch_1_scale }}", "{{ batch_1_assay }}", "{{ batch_1_impurities }}", "{{ batch_1_date }}"],
        ["{{ batch_2_id }}", "{{ batch_2_scale }}", "{{ batch_2_assay }}", "{{ batch_2_impurities }}", "{{ batch_2_date }}"],
        ["{{ batch_3_id }}", "{{ batch_3_scale }}", "{{ batch_3_assay }}", "{{ batch_3_impurities }}", "{{ batch_3_date }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "S.5 Reference Standards: {{ reference_standards }}")
    _add_para(doc, "S.6 Container Closure: {{ container_closure }}")

    _add_para(doc, "")
    _add_para(doc, "S.7 Stability", bold=True)
    _add_para(doc, "S.7.1 Stability Summary:", bold=True)
    _make_table(doc, ["Condition", "Duration", "Result", "Conclusion"], [
        ["25°C/60% RH (Long-term)", "{{ lt_duration }}", "{{ lt_result }}", "{{ lt_conclusion }}"],
        ["30°C/65% RH (Intermediate)", "{{ im_duration }}", "{{ im_result }}", "{{ im_conclusion }}"],
        ["40°C/75% RH (Accelerated)", "{{ ac_duration }}", "{{ ac_result }}", "{{ ac_conclusion }}"],
    ])
    _add_para(doc, "Proposed Retest Period: {{ retest_period }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "cmc_drug_substance.docx"))


# ---------------------------------------------------------------------------
# 5. CMC Drug Product Overview (3.2.P) — NEW
# ---------------------------------------------------------------------------
def make_cmc_drug_product() -> None:
    doc = Document()
    _add_heading(doc, "Module 3.2.P — Drug Product", level=0)
    _add_para(doc, "{{ product_name }} ({{ generic_name }}), {{ dosage_form }}")
    _add_para(doc, "Sponsor: {{ sponsor_name }}")
    _add_para(doc, "")

    _add_para(doc, "P.1 Description and Composition", bold=True)
    _make_table(doc, ["Component", "Function", "Grade", "Quantity per Unit"], [
        ["{{ generic_name }}", "Active ingredient", "{{ ds_grade }}", "{{ ds_quantity }}"],
        ["{{ excipient_1 }}", "{{ excipient_1_function }}", "{{ excipient_1_grade }}", "{{ excipient_1_qty }}"],
        ["{{ excipient_2 }}", "{{ excipient_2_function }}", "{{ excipient_2_grade }}", "{{ excipient_2_qty }}"],
        ["{{ excipient_3 }}", "{{ excipient_3_function }}", "{{ excipient_3_grade }}", "{{ excipient_3_qty }}"],
        ["{{ excipient_4 }}", "{{ excipient_4_function }}", "{{ excipient_4_grade }}", "{{ excipient_4_qty }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "P.2 Pharmaceutical Development", bold=True)
    _add_para(doc, "P.2.1 Components of the Drug Product: {{ dp_components_rationale }}")
    _add_para(doc, "P.2.2 Drug Product Formulation Development: {{ formulation_development }}")
    _add_para(doc, "P.2.3 Manufacturing Process Development: {{ process_development }}")
    _add_para(doc, "P.2.4 Container Closure System: {{ dp_container_closure }}")

    _add_para(doc, "")
    _add_para(doc, "P.3 Manufacture", bold=True)
    _make_table(doc, ["Parameter", "Detail"], [
        ["Manufacturer", "{{ dp_manufacturer }}"],
        ["Site Address", "{{ dp_manufacturing_site }}"],
        ["Batch Size", "{{ dp_batch_size }}"],
        ["Process Type", "{{ dp_process_type }}"],
    ])
    _add_para(doc, "Manufacturing Process Flow: {{ dp_process_flow }}")
    _add_para(doc, "Critical Process Parameters: {{ dp_cpp }}")
    _add_para(doc, "In-Process Controls: {{ dp_ipc }}")

    _add_para(doc, "")
    _add_para(doc, "P.4 Control of Excipients", bold=True)
    _add_para(doc, "{{ excipient_control_summary }}")

    _add_para(doc, "")
    _add_para(doc, "P.5 Control of Drug Product", bold=True)
    _add_para(doc, "P.5.1 Specification:", bold=True)
    _make_table(doc, ["Test", "Method", "Acceptance Criteria"], [
        ["Appearance", "Visual", "{{ dp_appearance_spec }}"],
        ["Identification", "{{ dp_id_method }}", "{{ dp_id_spec }}"],
        ["Assay", "{{ dp_assay_method }}", "{{ dp_assay_spec }}"],
        ["Content Uniformity", "{{ dp_cu_method }}", "{{ dp_cu_spec }}"],
        ["Dissolution", "{{ dp_diss_method }}", "{{ dp_diss_spec }}"],
        ["Related Substances", "{{ dp_rs_method }}", "{{ dp_rs_spec }}"],
        ["Microbial Limits", "USP <61>/<62>", "{{ dp_micro_spec }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "P.6 Reference Standards: {{ dp_reference_standards }}")

    _add_para(doc, "")
    _add_para(doc, "P.7 Container Closure: {{ dp_final_container }}")

    _add_para(doc, "")
    _add_para(doc, "P.8 Stability", bold=True)
    _make_table(doc, ["Condition", "Duration", "Result", "Conclusion"], [
        ["25°C/60% RH", "{{ dp_lt_duration }}", "{{ dp_lt_result }}", "{{ dp_lt_conclusion }}"],
        ["30°C/65% RH", "{{ dp_im_duration }}", "{{ dp_im_result }}", "{{ dp_im_conclusion }}"],
        ["40°C/75% RH", "{{ dp_ac_duration }}", "{{ dp_ac_result }}", "{{ dp_ac_conclusion }}"],
    ])
    _add_para(doc, "Proposed Shelf Life: {{ dp_shelf_life }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "cmc_drug_product.docx"))


# ---------------------------------------------------------------------------
# 6. Clinical Overview: Benefit/Risk Summary (2.5) (upgraded)
# ---------------------------------------------------------------------------
def make_clinical_benefit_risk() -> None:
    doc = Document()
    _add_heading(doc, "Module 2.5 — Clinical Overview", level=0)
    _add_para(doc, "{{ product_name }} ({{ generic_name }}) for {{ indication }}")
    _add_para(doc, "Sponsor: {{ sponsor_name }}")
    _add_para(doc, "Date: {{ report_date }}")
    _add_para(doc, "")

    _add_para(doc, "1. Product Overview", bold=True)
    _make_table(doc, ["Attribute", "Detail"], [
        ["Product Name", "{{ product_name }}"],
        ["Generic Name", "{{ generic_name }}"],
        ["Drug Class", "{{ drug_class }}"],
        ["Mechanism of Action", "{{ mechanism_of_action }}"],
        ["Proposed Indication", "{{ indication }}"],
        ["Proposed Dosage", "{{ proposed_dosage }}"],
        ["Route", "{{ route_of_admin }}"],
        ["Target Population", "{{ target_population }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "2. Overview of Clinical Pharmacology", bold=True)
    _add_para(doc, "{{ clinical_pharmacology_summary }}")

    _add_para(doc, "")
    _add_para(doc, "3. Overview of Efficacy", bold=True)
    _add_para(doc, "3.1 Pivotal Studies", bold=True)
    _make_table(doc, ["Study", "Design", "N", "Primary Endpoint", "Result", "p-value"], [
        ["{{ pivotal_study_1 }}", "{{ pivotal_design_1 }}", "{{ pivotal_n_1 }}", "{{ pivotal_endpoint_1 }}", "{{ pivotal_result_1 }}", "{{ pivotal_pvalue_1 }}"],
        ["{{ pivotal_study_2 }}", "{{ pivotal_design_2 }}", "{{ pivotal_n_2 }}", "{{ pivotal_endpoint_2 }}", "{{ pivotal_result_2 }}", "{{ pivotal_pvalue_2 }}"],
    ])
    _add_para(doc, "3.2 Secondary and Exploratory Results: {{ secondary_endpoints }}")
    _add_para(doc, "3.3 Patient-Reported Outcomes: {{ patient_reported_outcomes }}")

    _add_para(doc, "")
    _add_para(doc, "4. Overview of Safety", bold=True)
    _add_para(doc, "4.1 Adverse Event Summary", bold=True)
    _make_table(doc, ["Event", "Drug N (%)", "Placebo N (%)", "Risk Difference"], [
        ["{{ ae_1_name }}", "{{ ae_1_drug }}", "{{ ae_1_placebo }}", "{{ ae_1_rd }}"],
        ["{{ ae_2_name }}", "{{ ae_2_drug }}", "{{ ae_2_placebo }}", "{{ ae_2_rd }}"],
        ["{{ ae_3_name }}", "{{ ae_3_drug }}", "{{ ae_3_placebo }}", "{{ ae_3_rd }}"],
        ["{{ ae_4_name }}", "{{ ae_4_drug }}", "{{ ae_4_placebo }}", "{{ ae_4_rd }}"],
    ])
    _add_para(doc, "4.2 Serious Adverse Events: {{ serious_adverse_events }}")
    _add_para(doc, "4.3 Deaths: {{ deaths_summary }}")
    _add_para(doc, "4.4 Laboratory Findings: {{ lab_findings }}")

    _add_para(doc, "")
    _add_para(doc, "5. Benefit-Risk Assessment", bold=True)
    _make_table(doc, ["Dimension", "Assessment"], [
        ["Severity of condition", "{{ severity_of_condition }}"],
        ["Unmet medical need", "{{ unmet_medical_need }}"],
        ["Efficacy evidence strength", "{{ efficacy_strength }}"],
        ["Safety profile", "{{ safety_profile }}"],
        ["Risk mitigation", "{{ risk_mitigation }}"],
    ])
    _add_para(doc, "")
    _add_para(doc, "Benefit-Risk Conclusion: {{ benefit_risk_conclusion }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "clinical_benefit_risk.docx"))


# ---------------------------------------------------------------------------
# 7. Nonclinical Overview (2.4) — NEW
# ---------------------------------------------------------------------------
def make_nonclinical_overview() -> None:
    doc = Document()
    _add_heading(doc, "Module 2.4 — Nonclinical Overview", level=0)
    _add_para(doc, "{{ product_name }} ({{ generic_name }})")
    _add_para(doc, "Sponsor: {{ sponsor_name }}")
    _add_para(doc, "Date: {{ report_date }}")
    _add_para(doc, "")

    _add_para(doc, "1. Overview of Nonclinical Testing Strategy", bold=True)
    _add_para(doc, "{{ nonclinical_strategy }}")

    _add_para(doc, "")
    _add_para(doc, "2. Pharmacology", bold=True)
    _add_para(doc, "2.1 Primary Pharmacodynamics: {{ primary_pd }}")
    _add_para(doc, "2.2 Secondary Pharmacodynamics: {{ secondary_pd }}")
    _add_para(doc, "2.3 Safety Pharmacology:", bold=True)
    _make_table(doc, ["System", "Study", "Species", "Dose", "Finding"], [
        ["CNS", "{{ cns_study }}", "{{ cns_species }}", "{{ cns_dose }}", "{{ cns_finding }}"],
        ["Cardiovascular", "{{ cv_study }}", "{{ cv_species }}", "{{ cv_dose }}", "{{ cv_finding }}"],
        ["Respiratory", "{{ resp_study }}", "{{ resp_species }}", "{{ resp_dose }}", "{{ resp_finding }}"],
    ])
    _add_para(doc, "2.4 Pharmacodynamic Drug Interactions: {{ pd_interactions }}")

    _add_para(doc, "")
    _add_para(doc, "3. Pharmacokinetics", bold=True)
    _make_table(doc, ["Parameter", "Rat", "Dog", "Monkey"], [
        ["Oral Bioavailability (%)", "{{ pk_f_rat }}", "{{ pk_f_dog }}", "{{ pk_f_monkey }}"],
        ["Cmax (ng/mL)", "{{ pk_cmax_rat }}", "{{ pk_cmax_dog }}", "{{ pk_cmax_monkey }}"],
        ["AUC (ng·h/mL)", "{{ pk_auc_rat }}", "{{ pk_auc_dog }}", "{{ pk_auc_monkey }}"],
        ["t½ (h)", "{{ pk_thalf_rat }}", "{{ pk_thalf_dog }}", "{{ pk_thalf_monkey }}"],
        ["Protein Binding (%)", "{{ pk_ppb_rat }}", "{{ pk_ppb_dog }}", "{{ pk_ppb_monkey }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "4. Toxicology", bold=True)
    _add_para(doc, "4.1 Single-Dose Toxicity:", bold=True)
    _make_table(doc, ["Species", "Route", "LD50/MTD", "Key Finding"], [
        ["{{ sd_species_1 }}", "{{ sd_route_1 }}", "{{ sd_ld50_1 }}", "{{ sd_finding_1 }}"],
        ["{{ sd_species_2 }}", "{{ sd_route_2 }}", "{{ sd_ld50_2 }}", "{{ sd_finding_2 }}"],
    ])
    _add_para(doc, "4.2 Repeat-Dose Toxicity:", bold=True)
    _make_table(doc, ["Species", "Route", "Duration", "NOAEL", "Key Finding"], [
        ["{{ rd_species_1 }}", "{{ rd_route_1 }}", "{{ rd_duration_1 }}", "{{ rd_noael_1 }}", "{{ rd_finding_1 }}"],
        ["{{ rd_species_2 }}", "{{ rd_route_2 }}", "{{ rd_duration_2 }}", "{{ rd_noael_2 }}", "{{ rd_finding_2 }}"],
    ])
    _add_para(doc, "4.3 Genotoxicity: {{ genotoxicity_summary }}")
    _add_para(doc, "4.4 Carcinogenicity: {{ carcinogenicity_summary }}")
    _add_para(doc, "4.5 Reproductive/Developmental Toxicity: {{ repro_tox_summary }}")

    _add_para(doc, "")
    _add_para(doc, "5. Integrated Overview and Conclusions", bold=True)
    _add_para(doc, "{{ nonclinical_conclusions }}")
    _add_para(doc, "NOAEL-based Human Equivalent Dose: {{ hed_calculation }}")
    _add_para(doc, "Proposed Starting Dose Rationale: {{ starting_dose_rationale }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "nonclinical_overview.docx"))


# ---------------------------------------------------------------------------
# 8. Quality Overall Summary (2.3) — NEW
# ---------------------------------------------------------------------------
def make_quality_overall_summary() -> None:
    doc = Document()
    _add_heading(doc, "Module 2.3 — Quality Overall Summary", level=0)
    _add_para(doc, "{{ product_name }} ({{ generic_name }}), {{ dosage_form }}")
    _add_para(doc, "Sponsor: {{ sponsor_name }}")
    _add_para(doc, "")

    _add_para(doc, "S. Drug Substance — {{ generic_name }}", bold=True)
    _make_table(doc, ["Section", "Summary"], [
        ["S.1 General Information", "{{ qos_s1_summary }}"],
        ["S.2 Manufacture", "{{ qos_s2_summary }}"],
        ["S.3 Characterization", "{{ qos_s3_summary }}"],
        ["S.4 Control", "{{ qos_s4_summary }}"],
        ["S.5 Reference Standards", "{{ qos_s5_summary }}"],
        ["S.6 Container Closure", "{{ qos_s6_summary }}"],
        ["S.7 Stability", "{{ qos_s7_summary }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "P. Drug Product — {{ product_name }} {{ dosage_form }}", bold=True)
    _make_table(doc, ["Section", "Summary"], [
        ["P.1 Description and Composition", "{{ qos_p1_summary }}"],
        ["P.2 Pharmaceutical Development", "{{ qos_p2_summary }}"],
        ["P.3 Manufacture", "{{ qos_p3_summary }}"],
        ["P.4 Control of Excipients", "{{ qos_p4_summary }}"],
        ["P.5 Control of Drug Product", "{{ qos_p5_summary }}"],
        ["P.6 Reference Standards", "{{ qos_p6_summary }}"],
        ["P.7 Container Closure", "{{ qos_p7_summary }}"],
        ["P.8 Stability", "{{ qos_p8_summary }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "Regional Information", bold=True)
    _add_para(doc, "{{ regional_info }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "quality_overall_summary.docx"))


# ---------------------------------------------------------------------------
# 9. Clinical Study Report Synopsis — NEW
# ---------------------------------------------------------------------------
def make_csr_synopsis() -> None:
    doc = Document()
    _add_heading(doc, "Clinical Study Report — Synopsis", level=0)
    _add_para(doc, "ICH E3 Guideline Format")
    _add_para(doc, "")

    _make_table(doc, ["Field", "Detail"], [
        ["Protocol Number", "{{ protocol_number }}"],
        ["Study Title", "{{ study_title }}"],
        ["Sponsor", "{{ sponsor_name }}"],
        ["IND/Application Number", "{{ application_number }}"],
        ["Phase", "{{ phase }}"],
        ["Study Dates", "{{ first_patient_in }} to {{ last_patient_out }}"],
        ["Report Date", "{{ report_date }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "Objectives", bold=True)
    _add_para(doc, "Primary: {{ primary_objective }}")
    _add_para(doc, "Secondary: {{ secondary_objective }}")

    _add_para(doc, "")
    _add_para(doc, "Methodology", bold=True)
    _make_table(doc, ["Parameter", "Detail"], [
        ["Design", "{{ study_design }}"],
        ["Duration", "{{ study_duration }}"],
        ["Population", "{{ study_population }}"],
        ["Sample Size", "{{ planned_n }} planned / {{ actual_n }} enrolled"],
        ["Dosage & Route", "{{ dosage_regimen }}"],
        ["Comparator", "{{ comparator }}"],
        ["Randomization", "{{ randomization }}"],
        ["Blinding", "{{ blinding }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "Efficacy Results", bold=True)
    _make_table(doc, ["Endpoint", "Drug Arm", "Comparator", "Difference", "p-value"], [
        ["{{ eff_endpoint_1 }}", "{{ eff_drug_1 }}", "{{ eff_comp_1 }}", "{{ eff_diff_1 }}", "{{ eff_p_1 }}"],
        ["{{ eff_endpoint_2 }}", "{{ eff_drug_2 }}", "{{ eff_comp_2 }}", "{{ eff_diff_2 }}", "{{ eff_p_2 }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "Safety Results", bold=True)
    _make_table(doc, ["Category", "Drug N (%)", "Comparator N (%)"], [
        ["Any AE", "{{ any_ae_drug }}", "{{ any_ae_comp }}"],
        ["Drug-related AE", "{{ related_ae_drug }}", "{{ related_ae_comp }}"],
        ["Serious AE", "{{ sae_drug }}", "{{ sae_comp }}"],
        ["Discontinuation due to AE", "{{ disc_ae_drug }}", "{{ disc_ae_comp }}"],
        ["Deaths", "{{ deaths_drug }}", "{{ deaths_comp }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "Conclusions", bold=True)
    _add_para(doc, "{{ study_conclusions }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "csr_synopsis.docx"))


# ---------------------------------------------------------------------------
# 10. Protocol Synopsis — NEW
# ---------------------------------------------------------------------------
def make_protocol_synopsis() -> None:
    doc = Document()
    _add_heading(doc, "Clinical Protocol — Synopsis", level=0)
    _add_para(doc, "")

    _make_table(doc, ["Field", "Detail"], [
        ["Protocol Number", "{{ protocol_number }}"],
        ["Protocol Title", "{{ protocol_title }}"],
        ["Sponsor", "{{ sponsor_name }}"],
        ["IND Number", "{{ ind_number }}"],
        ["Phase", "{{ phase }}"],
        ["Indication", "{{ indication }}"],
        ["Version / Date", "{{ protocol_version }} / {{ protocol_date }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "Objectives and Endpoints", bold=True)
    _make_table(doc, ["Type", "Objective", "Endpoint", "Timepoint"], [
        ["Primary", "{{ primary_objective }}", "{{ primary_endpoint }}", "{{ primary_timepoint }}"],
        ["Secondary", "{{ secondary_objective_1 }}", "{{ secondary_endpoint_1 }}", "{{ secondary_timepoint_1 }}"],
        ["Secondary", "{{ secondary_objective_2 }}", "{{ secondary_endpoint_2 }}", "{{ secondary_timepoint_2 }}"],
        ["Exploratory", "{{ exploratory_objective }}", "{{ exploratory_endpoint }}", "{{ exploratory_timepoint }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "Study Design", bold=True)
    _add_para(doc, "{{ study_design_description }}")

    _add_para(doc, "")
    _add_para(doc, "Study Population", bold=True)
    _add_para(doc, "Target Enrollment: {{ target_enrollment }}")
    _add_para(doc, "Key Inclusion Criteria:", bold=True)
    _add_para(doc, "{{ inclusion_criteria }}")
    _add_para(doc, "Key Exclusion Criteria:", bold=True)
    _add_para(doc, "{{ exclusion_criteria }}")

    _add_para(doc, "")
    _add_para(doc, "Investigational Product", bold=True)
    _make_table(doc, ["Parameter", "Detail"], [
        ["Drug Name", "{{ product_name }} ({{ generic_name }})"],
        ["Dosage / Route", "{{ dosage_regimen }}"],
        ["Treatment Duration", "{{ treatment_duration }}"],
        ["Comparator", "{{ comparator }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "Statistical Considerations", bold=True)
    _add_para(doc, "Sample Size: {{ sample_size_justification }}")
    _add_para(doc, "Primary Analysis: {{ primary_analysis_method }}")
    _add_para(doc, "Interim Analysis: {{ interim_analysis }}")

    _add_para(doc, "")
    _add_para(doc, "Schedule of Assessments", bold=True)
    _make_table(doc, ["Visit", "Day", "Procedures"], [
        ["Screening", "{{ screening_window }}", "{{ screening_procedures }}"],
        ["Baseline", "Day 1", "{{ baseline_procedures }}"],
        ["{{ visit_1_name }}", "{{ visit_1_day }}", "{{ visit_1_procedures }}"],
        ["{{ visit_2_name }}", "{{ visit_2_day }}", "{{ visit_2_procedures }}"],
        ["End of Treatment", "{{ eot_day }}", "{{ eot_procedures }}"],
        ["Follow-up", "{{ followup_day }}", "{{ followup_procedures }}"],
    ])

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "protocol_synopsis.docx"))


# =============================================================================
# 510(k) FULL DOSSIER (5 templates)
# =============================================================================

# ---------------------------------------------------------------------------
# 11. 510(k) Cover Letter + Admin (upgraded)
# ---------------------------------------------------------------------------
def make_510k_cover_letter() -> None:
    doc = Document()
    _add_heading(doc, "510(k) Premarket Notification", level=0)
    _add_para(doc, "Date: {{ submission_date }}")
    _add_para(doc, "")
    _add_para(doc, "U.S. Food and Drug Administration")
    _add_para(doc, "Center for Devices and Radiological Health")
    _add_para(doc, "Document Control Center — WO66-G609")
    _add_para(doc, "10903 New Hampshire Avenue")
    _add_para(doc, "Silver Spring, MD 20993-0002")
    _add_para(doc, "")
    _add_para(doc, "Re: 510(k) Premarket Notification for {{ device_name }}")
    _add_para(doc, "")
    _add_para(doc, "Dear Sir/Madam,")
    _add_para(doc, "")
    _add_para(
        doc,
        "{{ submitter_name }} hereby submits this 510(k) Premarket Notification "
        "for {{ device_name }}, classified under 21 CFR {{ regulation_number }}, "
        "product code {{ product_code }}."
    )
    _add_para(doc, "")

    _add_para(doc, "Administrative Information", bold=True)
    _make_table(doc, ["Field", "Value"], [
        ["Submitter / Applicant", "{{ submitter_name }}"],
        ["Address", "{{ submitter_address }}"],
        ["Contact Person", "{{ contact_name }}"],
        ["Contact Email", "{{ contact_email }}"],
        ["Contact Phone", "{{ contact_phone }}"],
        ["Establishment Registration #", "{{ establishment_number }}"],
        ["Device Trade Name", "{{ device_trade_name }}"],
        ["Common Name", "{{ device_common_name }}"],
        ["Classification", "Class {{ device_class }}"],
        ["Product Code", "{{ product_code }}"],
        ["Regulation Number", "21 CFR {{ regulation_number }}"],
        ["Predicate Device", "{{ predicate_device }}"],
        ["Predicate 510(k) Number", "{{ predicate_510k }}"],
    ])
    _add_para(doc, "")

    _add_para(doc, "Truthful and Accurate Statement", bold=True)
    _add_para(
        doc,
        "I certify that, in my capacity as {{ signatory_title }} of {{ submitter_name }}, "
        "I believe the information contained in this premarket notification is truthful "
        "and accurate and that no material fact has been omitted."
    )

    _add_signature_block(doc, prefix="")
    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "510k_cover_letter.docx"))


# ---------------------------------------------------------------------------
# 12. Substantial Equivalence / Predicate Comparison — NEW
# ---------------------------------------------------------------------------
def make_510k_se_comparison() -> None:
    doc = Document()
    _add_heading(doc, "Substantial Equivalence Comparison", level=0)
    _add_para(doc, "Subject Device: {{ device_name }}")
    _add_para(doc, "Predicate Device: {{ predicate_device }} ({{ predicate_510k }})")
    _add_para(doc, "")

    _add_para(doc, "1. Intended Use Comparison", bold=True)
    _make_table(doc, ["Attribute", "Subject Device", "Predicate Device", "Comparison"], [
        ["Intended Use", "{{ subject_intended_use }}", "{{ predicate_intended_use }}", "{{ intended_use_comparison }}"],
        ["Indications for Use", "{{ subject_indications }}", "{{ predicate_indications }}", "{{ indications_comparison }}"],
        ["Target Population", "{{ subject_population }}", "{{ predicate_population }}", "{{ population_comparison }}"],
        ["Use Environment", "{{ subject_environment }}", "{{ predicate_environment }}", "{{ environment_comparison }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "2. Technological Characteristics Comparison", bold=True)
    _make_table(doc, ["Feature", "Subject Device", "Predicate Device", "Difference?"], [
        ["Materials", "{{ subject_materials }}", "{{ predicate_materials }}", "{{ materials_diff }}"],
        ["Design / Architecture", "{{ subject_design }}", "{{ predicate_design }}", "{{ design_diff }}"],
        ["Energy Source", "{{ subject_energy }}", "{{ predicate_energy }}", "{{ energy_diff }}"],
        ["Software / Firmware", "{{ subject_software }}", "{{ predicate_software }}", "{{ software_diff }}"],
        ["Sterilization", "{{ subject_sterilization }}", "{{ predicate_sterilization }}", "{{ sterilization_diff }}"],
        ["Dimensions", "{{ subject_dimensions }}", "{{ predicate_dimensions }}", "{{ dimensions_diff }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "3. Performance Comparison", bold=True)
    _make_table(doc, ["Test", "Subject Result", "Predicate Result", "Acceptance Criteria", "Pass?"], [
        ["{{ perf_test_1 }}", "{{ perf_subj_1 }}", "{{ perf_pred_1 }}", "{{ perf_criteria_1 }}", "{{ perf_pass_1 }}"],
        ["{{ perf_test_2 }}", "{{ perf_subj_2 }}", "{{ perf_pred_2 }}", "{{ perf_criteria_2 }}", "{{ perf_pass_2 }}"],
        ["{{ perf_test_3 }}", "{{ perf_subj_3 }}", "{{ perf_pred_3 }}", "{{ perf_criteria_3 }}", "{{ perf_pass_3 }}"],
        ["{{ perf_test_4 }}", "{{ perf_subj_4 }}", "{{ perf_pred_4 }}", "{{ perf_criteria_4 }}", "{{ perf_pass_4 }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "4. Substantial Equivalence Determination", bold=True)
    _add_para(doc, "{{ se_determination }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "510k_se_comparison.docx"))


# ---------------------------------------------------------------------------
# 13. Device Description + Performance Testing — NEW
# ---------------------------------------------------------------------------
def make_510k_device_description() -> None:
    doc = Document()
    _add_heading(doc, "Device Description and Performance Testing", level=0)
    _add_para(doc, "Device: {{ device_name }} ({{ device_trade_name }})")
    _add_para(doc, "")

    _add_para(doc, "1. Device Description", bold=True)
    _add_para(doc, "{{ device_description }}")
    _add_para(doc, "")
    _add_para(doc, "1.1 Principles of Operation: {{ principles_of_operation }}")
    _add_para(doc, "1.2 Components:", bold=True)
    _make_table(doc, ["Component", "Material", "Function", "Specifications"], [
        ["{{ component_1 }}", "{{ comp_material_1 }}", "{{ comp_function_1 }}", "{{ comp_spec_1 }}"],
        ["{{ component_2 }}", "{{ comp_material_2 }}", "{{ comp_function_2 }}", "{{ comp_spec_2 }}"],
        ["{{ component_3 }}", "{{ comp_material_3 }}", "{{ comp_function_3 }}", "{{ comp_spec_3 }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "2. Performance Testing — Bench", bold=True)
    _make_table(doc, ["Test", "Standard", "Method", "Result", "Criteria", "Pass/Fail"], [
        ["{{ bench_test_1 }}", "{{ bench_std_1 }}", "{{ bench_method_1 }}", "{{ bench_result_1 }}", "{{ bench_criteria_1 }}", "{{ bench_pass_1 }}"],
        ["{{ bench_test_2 }}", "{{ bench_std_2 }}", "{{ bench_method_2 }}", "{{ bench_result_2 }}", "{{ bench_criteria_2 }}", "{{ bench_pass_2 }}"],
        ["{{ bench_test_3 }}", "{{ bench_std_3 }}", "{{ bench_method_3 }}", "{{ bench_result_3 }}", "{{ bench_criteria_3 }}", "{{ bench_pass_3 }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "3. Electrical Safety and EMC", bold=True)
    _make_table(doc, ["Test", "Standard", "Result"], [
        ["Electrical Safety", "{{ elec_safety_std }}", "{{ elec_safety_result }}"],
        ["EMC — Emissions", "{{ emc_emission_std }}", "{{ emc_emission_result }}"],
        ["EMC — Immunity", "{{ emc_immunity_std }}", "{{ emc_immunity_result }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "4. Software Documentation (if applicable)", bold=True)
    _make_table(doc, ["Parameter", "Detail"], [
        ["Software Level of Concern", "{{ sw_level_of_concern }}"],
        ["Software Version", "{{ sw_version }}"],
        ["IEC 62304 Classification", "{{ sw_safety_class }}"],
        ["Cybersecurity Considerations", "{{ cybersecurity }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "5. Labeling", bold=True)
    _add_para(doc, "{{ labeling_summary }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "510k_device_description.docx"))


# ---------------------------------------------------------------------------
# 14. 510(k) Summary — NEW
# ---------------------------------------------------------------------------
def make_510k_summary() -> None:
    doc = Document()
    _add_heading(doc, "510(k) Summary (21 CFR 807.92)", level=0)
    _add_para(doc, "")

    _make_table(doc, ["Field", "Detail"], [
        ["Submitter", "{{ submitter_name }}"],
        ["Address", "{{ submitter_address }}"],
        ["Contact", "{{ contact_name }} ({{ contact_email }})"],
        ["Date Prepared", "{{ summary_date }}"],
        ["Device Trade Name", "{{ device_trade_name }}"],
        ["Common Name", "{{ device_common_name }}"],
        ["Classification", "Class {{ device_class }}"],
        ["Product Code", "{{ product_code }}"],
        ["Predicate Device", "{{ predicate_device }} ({{ predicate_510k }})"],
    ])

    _add_para(doc, "")
    _add_para(doc, "Intended Use", bold=True)
    _add_para(doc, "{{ intended_use }}")

    _add_para(doc, "")
    _add_para(doc, "Device Description", bold=True)
    _add_para(doc, "{{ device_description_summary }}")

    _add_para(doc, "")
    _add_para(doc, "Substantial Equivalence Summary", bold=True)
    _add_para(doc, "{{ se_summary }}")

    _add_para(doc, "")
    _add_para(doc, "Performance Data Summary", bold=True)
    _make_table(doc, ["Test Category", "# Tests", "Pass Rate", "Key Findings"], [
        ["Bench Testing", "{{ bench_count }}", "{{ bench_pass_rate }}", "{{ bench_findings }}"],
        ["Biocompatibility", "{{ biocompat_count }}", "{{ biocompat_pass_rate }}", "{{ biocompat_findings }}"],
        ["Electrical Safety", "{{ elec_count }}", "{{ elec_pass_rate }}", "{{ elec_findings }}"],
        ["Software Verification", "{{ sw_count }}", "{{ sw_pass_rate }}", "{{ sw_findings }}"],
        ["Clinical (if applicable)", "{{ clin_count }}", "{{ clin_pass_rate }}", "{{ clin_findings }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "Conclusions", bold=True)
    _add_para(doc, "{{ summary_conclusions }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "510k_summary.docx"))


# ---------------------------------------------------------------------------
# 15. Biocompatibility Evaluation Summary — NEW
# ---------------------------------------------------------------------------
def make_510k_biocompatibility() -> None:
    doc = Document()
    _add_heading(doc, "Biocompatibility Evaluation Summary", level=0)
    _add_para(doc, "Device: {{ device_name }}")
    _add_para(doc, "Per ISO 10993-1:2018 and FDA Guidance")
    _add_para(doc, "")

    _add_para(doc, "1. Device Categorization", bold=True)
    _make_table(doc, ["Parameter", "Classification"], [
        ["Nature of Body Contact", "{{ body_contact_type }}"],
        ["Contact Duration", "{{ contact_duration }}"],
        ["Device Category (ISO 10993-1)", "{{ iso_category }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "2. Material Characterization", bold=True)
    _make_table(doc, ["Material", "Supplier", "Grade", "Contact Surface"], [
        ["{{ mat_1_name }}", "{{ mat_1_supplier }}", "{{ mat_1_grade }}", "{{ mat_1_contact }}"],
        ["{{ mat_2_name }}", "{{ mat_2_supplier }}", "{{ mat_2_grade }}", "{{ mat_2_contact }}"],
        ["{{ mat_3_name }}", "{{ mat_3_supplier }}", "{{ mat_3_grade }}", "{{ mat_3_contact }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "3. Biological Evaluation Matrix", bold=True)
    _make_table(doc, ["Endpoint", "Required?", "Test Performed?", "Standard", "Result"], [
        ["Cytotoxicity", "{{ cyto_req }}", "{{ cyto_done }}", "ISO 10993-5", "{{ cyto_result }}"],
        ["Sensitization", "{{ sens_req }}", "{{ sens_done }}", "ISO 10993-10", "{{ sens_result }}"],
        ["Irritation", "{{ irr_req }}", "{{ irr_done }}", "ISO 10993-10", "{{ irr_result }}"],
        ["Systemic Toxicity", "{{ syst_req }}", "{{ syst_done }}", "ISO 10993-11", "{{ syst_result }}"],
        ["Genotoxicity", "{{ geno_req }}", "{{ geno_done }}", "ISO 10993-3", "{{ geno_result }}"],
        ["Implantation", "{{ impl_req }}", "{{ impl_done }}", "ISO 10993-6", "{{ impl_result }}"],
        ["Hemocompatibility", "{{ hemo_req }}", "{{ hemo_done }}", "ISO 10993-4", "{{ hemo_result }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "4. Conclusions", bold=True)
    _add_para(doc, "{{ biocompat_conclusions }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "510k_biocompatibility.docx"))


# =============================================================================
# CER FOR eCTD 4.0 (4 templates)
# =============================================================================

# ---------------------------------------------------------------------------
# 16. Clinical Evaluation Plan (CEP) — NEW
# ---------------------------------------------------------------------------
def make_cer_evaluation_plan() -> None:
    doc = Document()
    _add_heading(doc, "Clinical Evaluation Plan (CEP)", level=0)
    _add_para(doc, "Per MEDDEV 2.7/1 Rev 4 and EU MDR 2017/745 Article 61")
    _add_para(doc, "eCTD 4.0 Module: {{ ectd_module }}")
    _add_para(doc, "")

    _make_table(doc, ["Field", "Detail"], [
        ["Device Name", "{{ device_name }}"],
        ["Manufacturer", "{{ manufacturer }}"],
        ["Classification", "{{ device_classification }}"],
        ["UDI-DI", "{{ udi_di }}"],
        ["Intended Purpose", "{{ intended_purpose }}"],
        ["CEP Version", "{{ cep_version }}"],
        ["CEP Date", "{{ cep_date }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "1. Scope and Objectives", bold=True)
    _add_para(doc, "{{ cep_scope }}")

    _add_para(doc, "")
    _add_para(doc, "2. Device Description and Equivalence", bold=True)
    _add_para(doc, "2.1 Device Description: {{ device_description }}")
    _add_para(doc, "2.2 Equivalent Device Justification:", bold=True)
    _make_table(doc, ["Criterion", "Subject Device", "Equivalent Device", "Equivalence?"], [
        ["Clinical", "{{ subj_clinical }}", "{{ equiv_clinical }}", "{{ clinical_equiv }}"],
        ["Technical", "{{ subj_technical }}", "{{ equiv_technical }}", "{{ technical_equiv }}"],
        ["Biological", "{{ subj_biological }}", "{{ equiv_biological }}", "{{ biological_equiv }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "3. Literature Search Strategy", bold=True)
    _make_table(doc, ["Parameter", "Detail"], [
        ["Databases", "{{ search_databases }}"],
        ["Search Terms", "{{ search_terms }}"],
        ["Date Range", "{{ search_date_range }}"],
        ["Inclusion Criteria", "{{ search_inclusion }}"],
        ["Exclusion Criteria", "{{ search_exclusion }}"],
        ["Appraisal Method", "{{ appraisal_method }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "4. Clinical Investigation Plan", bold=True)
    _add_para(doc, "{{ clinical_investigation_plan }}")

    _add_para(doc, "")
    _add_para(doc, "5. Post-Market Surveillance Integration", bold=True)
    _add_para(doc, "{{ pms_integration }}")

    _add_para(doc, "")
    _add_para(doc, "6. CEP Update Schedule", bold=True)
    _add_para(doc, "{{ cep_update_schedule }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "cer_evaluation_plan.docx"))


# ---------------------------------------------------------------------------
# 17. CER — Literature Analysis — NEW
# ---------------------------------------------------------------------------
def make_cer_literature_analysis() -> None:
    doc = Document()
    _add_heading(doc, "Clinical Evaluation Report — Literature Analysis", level=0)
    _add_para(doc, "Per MEDDEV 2.7/1 Rev 4 and EU MDR 2017/745")
    _add_para(doc, "eCTD 4.0 Module: {{ ectd_module }}")
    _add_para(doc, "")

    _make_table(doc, ["Field", "Detail"], [
        ["Device Name", "{{ device_name }}"],
        ["Manufacturer", "{{ manufacturer }}"],
        ["CER Version", "{{ cer_version }}"],
        ["CER Date", "{{ cer_date }}"],
        ["Evaluator", "{{ evaluator_name }}, {{ evaluator_qualifications }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "1. Literature Search Results", bold=True)
    _make_table(doc, ["Database", "Hits", "After Dedup", "After Screen", "Included"], [
        ["PubMed/MEDLINE", "{{ pubmed_hits }}", "{{ pubmed_dedup }}", "{{ pubmed_screen }}", "{{ pubmed_included }}"],
        ["Embase", "{{ embase_hits }}", "{{ embase_dedup }}", "{{ embase_screen }}", "{{ embase_included }}"],
        ["Cochrane", "{{ cochrane_hits }}", "{{ cochrane_dedup }}", "{{ cochrane_screen }}", "{{ cochrane_included }}"],
        ["Total", "{{ total_hits }}", "{{ total_dedup }}", "{{ total_screen }}", "{{ total_included }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "2. Appraisal of Clinical Data", bold=True)
    _add_para(doc, "2.1 Pivotal Studies:", bold=True)
    _make_table(doc, ["Reference", "Type", "N", "Follow-up", "Primary Outcome", "Quality Score"], [
        ["{{ lit_ref_1 }}", "{{ lit_type_1 }}", "{{ lit_n_1 }}", "{{ lit_fu_1 }}", "{{ lit_outcome_1 }}", "{{ lit_quality_1 }}"],
        ["{{ lit_ref_2 }}", "{{ lit_type_2 }}", "{{ lit_n_2 }}", "{{ lit_fu_2 }}", "{{ lit_outcome_2 }}", "{{ lit_quality_2 }}"],
        ["{{ lit_ref_3 }}", "{{ lit_type_3 }}", "{{ lit_n_3 }}", "{{ lit_fu_3 }}", "{{ lit_outcome_3 }}", "{{ lit_quality_3 }}"],
    ])

    _add_para(doc, "2.2 Summary of Favorable Data: {{ favorable_data_summary }}")
    _add_para(doc, "2.3 Summary of Unfavorable Data: {{ unfavorable_data_summary }}")

    _add_para(doc, "")
    _add_para(doc, "3. Clinical Performance Analysis", bold=True)
    _add_para(doc, "{{ clinical_performance }}")

    _add_para(doc, "")
    _add_para(doc, "4. Clinical Safety Analysis", bold=True)
    _make_table(doc, ["Event / Risk", "Incidence", "Severity", "Source"], [
        ["{{ risk_1 }}", "{{ risk_1_incidence }}", "{{ risk_1_severity }}", "{{ risk_1_source }}"],
        ["{{ risk_2 }}", "{{ risk_2_incidence }}", "{{ risk_2_severity }}", "{{ risk_2_source }}"],
        ["{{ risk_3 }}", "{{ risk_3_incidence }}", "{{ risk_3_severity }}", "{{ risk_3_source }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "5. Gap Analysis", bold=True)
    _add_para(doc, "{{ gap_analysis }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "cer_literature_analysis.docx"))


# ---------------------------------------------------------------------------
# 18. CER Benefit-Risk Determination + PMCF Plan — NEW
# ---------------------------------------------------------------------------
def make_cer_benefit_risk_pmcf() -> None:
    doc = Document()
    _add_heading(doc, "CER — Benefit-Risk Determination & PMCF Plan", level=0)
    _add_para(doc, "Per EU MDR 2017/745 Articles 61, 85; MEDDEV 2.12/2 Rev 2")
    _add_para(doc, "eCTD 4.0 Module: {{ ectd_module }}")
    _add_para(doc, "")

    _make_table(doc, ["Field", "Detail"], [
        ["Device Name", "{{ device_name }}"],
        ["Manufacturer", "{{ manufacturer }}"],
        ["Risk Class", "{{ risk_class }}"],
    ])

    # Part A: Benefit-Risk
    _add_para(doc, "")
    _add_heading(doc, "Part A — Benefit-Risk Determination", level=1)

    _add_para(doc, "1. Clinical Benefits", bold=True)
    _make_table(doc, ["Benefit", "Evidence", "Magnitude", "Certainty"], [
        ["{{ benefit_1 }}", "{{ benefit_1_evidence }}", "{{ benefit_1_magnitude }}", "{{ benefit_1_certainty }}"],
        ["{{ benefit_2 }}", "{{ benefit_2_evidence }}", "{{ benefit_2_magnitude }}", "{{ benefit_2_certainty }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "2. Clinical Risks", bold=True)
    _make_table(doc, ["Risk", "Probability", "Severity", "Detectability", "Mitigation"], [
        ["{{ cer_risk_1 }}", "{{ cer_risk_1_prob }}", "{{ cer_risk_1_sev }}", "{{ cer_risk_1_detect }}", "{{ cer_risk_1_mitigation }}"],
        ["{{ cer_risk_2 }}", "{{ cer_risk_2_prob }}", "{{ cer_risk_2_sev }}", "{{ cer_risk_2_detect }}", "{{ cer_risk_2_mitigation }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "3. Benefit-Risk Conclusion", bold=True)
    _add_para(doc, "{{ cer_benefit_risk_conclusion }}")

    # Part B: PMCF
    _add_para(doc, "")
    _add_heading(doc, "Part B — Post-Market Clinical Follow-up (PMCF) Plan", level=1)

    _add_para(doc, "1. PMCF Objectives", bold=True)
    _add_para(doc, "{{ pmcf_objectives }}")

    _add_para(doc, "")
    _add_para(doc, "2. PMCF Activities", bold=True)
    _make_table(doc, ["Activity", "Method", "Sample Size", "Timeline", "Responsible"], [
        ["{{ pmcf_activity_1 }}", "{{ pmcf_method_1 }}", "{{ pmcf_n_1 }}", "{{ pmcf_timeline_1 }}", "{{ pmcf_responsible_1 }}"],
        ["{{ pmcf_activity_2 }}", "{{ pmcf_method_2 }}", "{{ pmcf_n_2 }}", "{{ pmcf_timeline_2 }}", "{{ pmcf_responsible_2 }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "3. PMCF Evaluation Criteria", bold=True)
    _add_para(doc, "{{ pmcf_evaluation_criteria }}")

    _add_para(doc, "")
    _add_para(doc, "4. PMCF Report Schedule", bold=True)
    _add_para(doc, "{{ pmcf_report_schedule }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "cer_benefit_risk_pmcf.docx"))


# ---------------------------------------------------------------------------
# 19. State of the Art Report — NEW
# ---------------------------------------------------------------------------
def make_cer_state_of_art() -> None:
    doc = Document()
    _add_heading(doc, "State of the Art Report", level=0)
    _add_para(doc, "Per MEDDEV 2.7/1 Rev 4, Section 8")
    _add_para(doc, "eCTD 4.0 Module: {{ ectd_module }}")
    _add_para(doc, "")

    _make_table(doc, ["Field", "Detail"], [
        ["Device Name", "{{ device_name }}"],
        ["Manufacturer", "{{ manufacturer }}"],
        ["Therapeutic Area", "{{ therapeutic_area }}"],
        ["Report Date", "{{ report_date }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "1. Medical Condition / Disease Background", bold=True)
    _add_para(doc, "{{ disease_background }}")
    _add_para(doc, "Epidemiology: {{ epidemiology }}")
    _add_para(doc, "Current Diagnostic Pathway: {{ diagnostic_pathway }}")

    _add_para(doc, "")
    _add_para(doc, "2. Current Treatment / Management Options", bold=True)
    _make_table(doc, ["Treatment", "Type", "Efficacy", "Limitations"], [
        ["{{ treatment_1 }}", "{{ treatment_1_type }}", "{{ treatment_1_efficacy }}", "{{ treatment_1_limitations }}"],
        ["{{ treatment_2 }}", "{{ treatment_2_type }}", "{{ treatment_2_efficacy }}", "{{ treatment_2_limitations }}"],
        ["{{ treatment_3 }}", "{{ treatment_3_type }}", "{{ treatment_3_efficacy }}", "{{ treatment_3_limitations }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "3. Available Alternatives (Medical Devices)", bold=True)
    _make_table(doc, ["Device / Technology", "Manufacturer", "Regulatory Status", "Key Outcomes"], [
        ["{{ alt_device_1 }}", "{{ alt_mfg_1 }}", "{{ alt_status_1 }}", "{{ alt_outcomes_1 }}"],
        ["{{ alt_device_2 }}", "{{ alt_mfg_2 }}", "{{ alt_status_2 }}", "{{ alt_outcomes_2 }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "4. Applicable Standards and Guidance", bold=True)
    _make_table(doc, ["Standard", "Title", "Applicability"], [
        ["{{ std_1_number }}", "{{ std_1_title }}", "{{ std_1_applicability }}"],
        ["{{ std_2_number }}", "{{ std_2_title }}", "{{ std_2_applicability }}"],
        ["{{ std_3_number }}", "{{ std_3_title }}", "{{ std_3_applicability }}"],
    ])

    _add_para(doc, "")
    _add_para(doc, "5. Unmet Clinical Needs", bold=True)
    _add_para(doc, "{{ unmet_clinical_needs }}")

    _add_para(doc, "")
    _add_para(doc, "6. Conclusions on State of the Art", bold=True)
    _add_para(doc, "{{ sota_conclusions }}")

    _add_doc_control_footer(doc)
    doc.save(str(TEMPLATES_DIR / "cer_state_of_art.docx"))


# =============================================================================
# Main
# =============================================================================
def main() -> None:
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)

    generators = [
        # IND Full Application (10)
        ("eCTD Cover Letter", make_ectd_cover_letter),
        ("FDA 1571 Narrative", make_fda_1571_narrative),
        ("IB Change Summary", make_ib_change_summary),
        ("CMC Drug Substance (3.2.S)", make_cmc_drug_substance),
        ("CMC Drug Product (3.2.P)", make_cmc_drug_product),
        ("Clinical Overview (2.5)", make_clinical_benefit_risk),
        ("Nonclinical Overview (2.4)", make_nonclinical_overview),
        ("Quality Overall Summary (2.3)", make_quality_overall_summary),
        ("CSR Synopsis", make_csr_synopsis),
        ("Protocol Synopsis", make_protocol_synopsis),
        # 510(k) Full Dossier (5)
        ("510(k) Cover Letter", make_510k_cover_letter),
        ("510(k) SE Comparison", make_510k_se_comparison),
        ("510(k) Device Description", make_510k_device_description),
        ("510(k) Summary", make_510k_summary),
        ("510(k) Biocompatibility", make_510k_biocompatibility),
        # CER for eCTD 4.0 (4)
        ("CER — Clinical Evaluation Plan", make_cer_evaluation_plan),
        ("CER — Literature Analysis", make_cer_literature_analysis),
        ("CER — Benefit-Risk + PMCF", make_cer_benefit_risk_pmcf),
        ("CER — State of the Art", make_cer_state_of_art),
    ]

    for name, gen in generators:
        gen()
        print(f"  ✓ Generated: {name}")

    print(f"\n{len(generators)} templates written to {TEMPLATES_DIR}")


if __name__ == "__main__":
    main()
