# Reviewed entries for every tool the prefix pass generated. family, verb, object, source[, preview]
# E = a deterministic computation over the inputs given (engine claim; the gate verifies no model is reachable).
# K = curated regulatory knowledge (advisors, requirement and guidance lookups, plan templates).
E, K = 'engine', 'knowledge'
G = {
 # statistics, modelling and design calculations
 'adjust_multiplicity': ('engines', 'apply', 'a multiplicity adjustment', E),
 'analyze_external_control_borrow': ('engines', 'analyze', 'external-control borrowing', E),
 'analyze_missing_data_impact': ('engines', 'analyze', 'the impact of missing data', E),
 'analyze_rmst': ('engines', 'compute', 'the restricted mean survival time', E),
 'analyze_safety_signal': ('engines', 'compute', 'the disproportionality ratios', E),
 'analyze_win_ratio': ('engines', 'compute', 'the win ratio', E),
 'compute_assurance': ('engines', 'compute', 'the assurance', E),
 'compute_diagnostic_accuracy': ('engines', 'compute', 'the diagnostic accuracy', E),
 'compute_sample_size': ('engines', 'compute', 'the sample size', E),
 'estimate_sample_size': ('engines', 'compute', 'the sample size', E),
 'compare_statistical_scenarios': ('engines', 'compare', 'two study-design scenarios', E),
 'assess_statistical_defensibility': ('engines', 'assess', 'the statistical defensibility', E),
 'design_group_sequential': ('engines', 'compute', 'the group-sequential boundaries', E),
 'design_mmrm': ('engines', 'compute', 'the MMRM sample size', E),
 'design_dose_finding': ('engines', 'compute', 'the dose-finding boundaries', E),
 'design_bayesian_device': ('engines', 'compute', 'the Bayesian device study size', E),
 'design_mrmc_reader_study': ('engines', 'compute', 'the reader-study power', E),
 'size_diagnostic_study': ('engines', 'compute', 'the diagnostic study size', E),
 'forecast_enrollment': ('engines', 'forecast', 'enrollment', E),
 'project_events': ('engines', 'forecast', 'event accrual', E),
 'model_budget_impact': ('engines', 'compute', 'the budget impact', E),
 'model_budget_impact_mix': ('engines', 'compute', 'the budget impact', E),
 'model_cost_effectiveness': ('engines', 'compute', 'the cost-effectiveness', E),
 'model_cost_effectiveness_nmb': ('engines', 'compute', 'the cost-effectiveness', E),
 'model_markov_cohort': ('engines', 'simulate', 'a Markov cohort', E),
 'run_monte_carlo_simulation': ('engines', 'simulate', 'the outcome distributions', E),
 'run_probabilistic_sensitivity': ('engines', 'run', 'a probabilistic sensitivity analysis', E),
 'determine_assay_cutoff': ('engines', 'determine', 'the assay cutoff', E),
 'determine_meaningful_change': ('engines', 'determine', 'the meaningful-change threshold', E),
 'detect_safety_signal': ('engines', 'check', 'for a safety signal', E),
 'screen_signal_panel': ('engines', 'screen', 'for safety signals', E),
 'assess_output_confidence': ('engines', 'assess', 'how confident the answer can be', E),
 'assess_benefit_risk': ('engines', 'compute', 'the benefit-risk score', E),
 'assess_benefit_risk_balance': ('engines', 'assess', 'the benefit-risk balance', E),
 'assess_biomarker_clinical_validation': ('engines', 'compute', 'the biomarker validation figures', E),
 'assess_lot_consistency': ('engines', 'design', 'the lot-consistency study', E),
 'define_estimand': ('engines', 'build', 'the estimand', E),
 # CMC and quality computations
 'assess_accelerated_stability': ('engines', 'compute', 'the shelf life from accelerated data', E),
 'assess_shelf_life_stability': ('engines', 'compute', 'the shelf life', E),
 'estimate_shelf_life': ('engines', 'estimate', 'the shelf life', E),
 'assess_batch_poolability': ('engines', 'check', 'whether batches can be pooled', E),
 'assess_dissolution_similarity': ('engines', 'compute', 'the dissolution similarity', E),
 'assess_analytical_method_validation': ('engines', 'assess', 'the method-validation data', E),
 'compute_analytical_performance': ('engines', 'compute', 'the analytical performance', E),
 'assess_ivd_analytical_extensions': ('engines', 'compute', 'the IVD analytical performance', E),
 'calculate_ttc': ('engines', 'compute', 'the TTC limit', E),
 'assess_analytical_similarity': ('engines', 'assess', 'the analytical similarity', E),
 'assess_comparability': ('engines', 'assess', 'the comparability', E),
 'assess_immunogenicity': ('engines', 'compute', 'the immunogenicity incidence', E),
 'assess_bla_filing_risk': ('engines', 'assess', 'the BLA filing risk', E),
 'screen_compound_liabilities': ('engines', 'screen', 'the compound for liabilities', E),
 # clinical pharmacology and nonclinical computations
 'compute_fih_dose': ('engines', 'compute', 'the first-in-human dose', E),
 'calculate_safety_margin': ('engines', 'compute', 'the safety margin', E),
 'assess_concentration_qtc': ('engines', 'assess', 'the concentration-QTc relationship', E),
 'assess_ddi_risk': ('engines', 'assess', 'the drug-interaction risk', E),
 'characterize_pk': ('engines', 'analyze', 'the pharmacokinetics', E),
 'assess_dose_exposure_response': ('engines', 'assess', 'the exposure-response', E),
 'select_exposure_response_dose': ('engines', 'select', 'a dose from exposure-response', E),
 'classify_tox_findings': ('engines', 'classify', 'the toxicology findings', E),
 'assess_nonclinical_program': ('engines', 'check', 'the nonclinical program for gaps', E),
 'assess_nonclinical_safety': ('engines', 'assemble', 'the nonclinical safety assessment', E),
 'classify_bcs': ('engines', 'classify', 'the BCS class', E),
 'classify_cyp_phenotype': ('engines', 'classify', 'the CYP phenotype', E),
 'assess_protein_binding': ('engines', 'assess', 'the protein binding', E),
 'load_nonclinical_program': ('project', 'read', 'the nonclinical studies for the program', 'project'),
 # classifiers and scores from structured facts
 'classify_pediatric_age': ('engines', 'classify', 'the pediatric age band', E),
 'classify_medical_device': ('engines', 'classify', 'the medical device', E),
 'classify_device': ('engines', 'classify', 'the device', E),
 'classify_samd': ('engines', 'classify', 'the software as a medical device', E),
 'classify_impurity': ('engines', 'classify', 'the impurity', E),
 'classify_mutagenic_impurity': ('engines', 'classify', 'the mutagenic impurity', E),
 'classify_post_approval_change': ('engines', 'classify', 'the post-approval change', E),
 'classify_post_submission_change': ('engines', 'classify', 'the post-approval change', E),
 'classify_expedited_reporting': ('engines', 'classify', 'the safety case for reporting', E),
 'classify_protocol_deviation': ('engines', 'classify', 'the protocol deviation', E),
 'classify_gmp_deviation': ('engines', 'classify', 'the GMP deviation', E),
 'classify_combination_product': ('engines', 'classify', 'the combination product', E),
 'classify_biomarker': ('engines', 'classify', 'the biomarker', E),
 'classify_atmp': ('engines', 'classify', 'the advanced therapy', E),
 'classify_ddi_risk': ('engines', 'classify', 'the drug-interaction risk', E),
 'classify_immunogenicity_clinical_impact': ('engines', 'classify', 'the immunogenicity impact', E),
 'assess_pv_causality': ('engines', 'assess', 'the case causality', E),
 'assess_mdr_reportability': ('engines', 'check', 'whether the event is reportable', E),
 'assess_signal_priority': ('engines', 'score', 'the signal priority', E),
 'assess_substantial_equivalence': ('engines', 'assess', 'the substantial equivalence', E),
 'score_predicate_adequacy': ('engines', 'score', 'the candidate predicates', E),
 'score_rwe_data_source': ('engines', 'score', 'the real-world data source', E),
 'determine_primary_mode_of_action': ('engines', 'determine', 'the primary mode of action', E),
 # validators and text checks
 'validate_adam_dataset': ('engines', 'validate', 'the ADaM dataset', E),
 'validate_sdtm_dataset': ('engines', 'validate', 'the SDTM dataset', E),
 'validate_cdisc_dataset': ('engines', 'validate', 'the CDISC dataset', E),
 'check_dataset_conformance': ('engines', 'check', 'the dataset spec', E),
 'run_cdisc_pipeline': ('engines', 'check', 'the dataset against CDISC', E),
 'validate_spl': ('engines', 'validate', 'the SPL', E),
 'validate_spl_structure': ('engines', 'validate', 'the SPL XML', E),
 'validate_udi': ('engines', 'validate', 'the UDI', E),
 'generate_define_xml': ('engines', 'generate', 'the define.xml', E),
 'check_guidance_freshness': ('engines', 'check', 'that the cited guidance is current', E),
 'detect_evidence_contradictions': ('engines', 'check', 'the evidence for contradictions', E),
 'detect_evidence_gaps': ('engines', 'check', 'the evidence for gaps', E),
 'format_references': ('engines', 'format', 'the references', E),
 'lint_references': ('engines', 'check', 'the reference list', E),
 'import_ris_references': ('engines', 'convert', 'RIS references', E),
 # regulatory knowledge: advisors
 'advise_coa_selection': ('regulatory knowledge', 'look_up', 'guidance on COA selection', K),
 'advise_ctd_structure': ('regulatory knowledge', 'look_up', 'guidance on CTD structure', K),
 'advise_data_integrity': ('regulatory knowledge', 'look_up', 'guidance on data integrity', K),
 'advise_device_readiness': ('regulatory knowledge', 'assess', 'eSTAR readiness', K),
 'advise_estimand': ('regulatory knowledge', 'look_up', 'guidance on estimands', K),
 'advise_eu_technical_file_readiness': ('regulatory knowledge', 'assess', 'EU technical-file readiness', K),
 'advise_gcp': ('regulatory knowledge', 'look_up', 'guidance on GCP', K),
 'advise_global_market_strategy': ('regulatory knowledge', 'assess', 'market-entry options', K),
 'advise_global_submission_plan': ('regulatory knowledge', 'plan', 'the multi-market device submission', K),
 'advise_labeling_structure': ('regulatory knowledge', 'look_up', 'guidance on labeling structure', K),
 'advise_medical_information': ('regulatory knowledge', 'look_up', 'guidance on medical information', K),
 'advise_midd': ('regulatory knowledge', 'look_up', 'guidance on model-informed development', K),
 'advise_pharmacovigilance': ('regulatory knowledge', 'look_up', 'guidance on pharmacovigilance', K),
 'advise_pma_readiness': ('regulatory knowledge', 'assess', 'PMA readiness', K),
 'advise_regulatory_pathway': ('regulatory knowledge', 'look_up', 'guidance on the regulatory pathway', K),
 'advise_reporting_guideline': ('regulatory knowledge', 'look_up', 'the reporting guideline', K),
 'advise_risk_management': ('regulatory knowledge', 'look_up', 'guidance on risk management', K),
 'advise_rwe_design': ('regulatory knowledge', 'look_up', 'guidance on real-world evidence design', K),
 'advise_special_designation': ('regulatory knowledge', 'look_up', 'guidance on special designations', K),
 'advise_study_design': ('regulatory knowledge', 'look_up', 'guidance on study design', K),
 # regulatory knowledge: assessments against frameworks
 'assess_abuse_liability': ('regulatory knowledge', 'assess', 'the abuse potential', K),
 'assess_ai_ml_device': ('regulatory knowledge', 'assess', 'the AI/ML device function', K),
 'assess_analytical_similarity_biosimilar': ('regulatory knowledge', 'assess', 'biosimilar analytical similarity', K),
 'assess_api_gmp': ('regulatory knowledge', 'look_up', 'API GMP expectations', K),
 'assess_atmp_comparability': ('regulatory knowledge', 'assess', 'ATMP comparability', K),
 'assess_biomarker_analytical_validation': ('regulatory knowledge', 'assess', 'the biomarker assay validation', K),
 'assess_biosimilar_cmc': ('regulatory knowledge', 'assess', 'the biosimilar CMC strategy', K),
 'assess_biowaiver': ('regulatory knowledge', 'check', 'biowaiver eligibility', K),
 'assess_boxed_warning': ('regulatory knowledge', 'assess', 'the need for a boxed warning', K),
 'assess_br_uncertainty': ('regulatory knowledge', 'assess', 'the benefit-risk uncertainty', K),
 'assess_carcinogenicity_need': ('regulatory knowledge', 'assess', 'the need for carcinogenicity studies', K),
 'assess_cardiovascular_safety_pharmacology': ('regulatory knowledge', 'assess', 'the cardiovascular safety package', K),
 'assess_cart_requirements': ('regulatory knowledge', 'look_up', 'CAR-T requirements', K),
 'assess_cell_therapy_manufacturing': ('regulatory knowledge', 'look_up', 'cell-therapy manufacturing requirements', K),
 'assess_cns_safety_pharmacology': ('regulatory knowledge', 'assess', 'the CNS safety package', K),
 'assess_coa_fit_for_purpose': ('regulatory knowledge', 'assess', 'whether the COA fits its use', K),
 'assess_coa_validation': ('regulatory knowledge', 'assess', 'the COA validation', K),
 'assess_combination_product': ('regulatory knowledge', 'assess', 'the combination product', K),
 'assess_comparability_protocol': ('regulatory knowledge', 'look_up', 'the comparability requirements', K),
 'assess_computer_system_validation': ('regulatory knowledge', 'assess', 'the computer system validation', K),
 'assess_correlate_of_protection': ('regulatory knowledge', 'assess', 'the correlate of protection', K),
 'assess_data_integrity': ('regulatory knowledge', 'assess', 'the data integrity', K),
 'assess_device_constituent_controls': ('regulatory knowledge', 'look_up', 'the device-constituent design controls', K),
 'assess_device_cybersecurity': ('regulatory knowledge', 'assess', 'the device cybersecurity', K),
 'assess_device_evidence_structure': ('regulatory knowledge', 'check', 'the device evidence document', K),
 'assess_essential_principles': ('regulatory knowledge', 'build', 'the essential-principles matrix', K),
 'assess_established_conditions': ('regulatory knowledge', 'assess', 'the established conditions', K),
 'assess_expedited_program': ('regulatory knowledge', 'assess', 'expedited-program eligibility', K),
 'assess_food_effect': ('regulatory knowledge', 'assess', 'the food-effect risk', K),
 'assess_gcp_compliance': ('regulatory knowledge', 'assess', 'GCP conformance', K),
 'assess_gene_therapy_requirements': ('regulatory knowledge', 'look_up', 'gene-therapy requirements', K),
 'assess_gmlp': ('regulatory knowledge', 'assess', 'GMLP conformity', K),
 'assess_immunogenicity_comparability': ('regulatory knowledge', 'assess', 'immunogenicity comparability', K),
 'assess_immunogenicity_risk': ('regulatory knowledge', 'assess', 'the immunogenicity risk', K),
 'assess_indication_extrapolation': ('regulatory knowledge', 'assess', 'indication extrapolation', K),
 'assess_inspection_readiness': ('regulatory knowledge', 'assess', 'inspection readiness', K),
 'assess_interchangeability': ('regulatory knowledge', 'assess', 'interchangeability', K),
 'assess_intercurrent_event_strategy': ('regulatory knowledge', 'assess', 'the intercurrent-event strategies', K),
 'assess_iso17511_traceability': ('regulatory knowledge', 'assess', 'the traceability chain', K),
 'assess_metabolite_safety': ('regulatory knowledge', 'assess', 'the metabolite safety', K),
 'assess_nitrosamine_risk': ('regulatory knowledge', 'assess', 'the nitrosamine risk', K),
 'assess_orphan_designation': ('regulatory knowledge', 'assess', 'orphan-designation eligibility', K),
 'assess_otc_labeling': ('regulatory knowledge', 'look_up', 'the OTC labeling requirements', K),
 'assess_pathway_eligibility': ('regulatory knowledge', 'check', 'designation eligibility', K),
 'assess_pediatric_extrapolation': ('regulatory knowledge', 'assess', 'pediatric extrapolation', K),
 'assess_pediatric_requirements': ('regulatory knowledge', 'look_up', 'the pediatric requirements', K),
 'assess_plr_structure': ('regulatory knowledge', 'look_up', 'the PLR labeling structure', K),
 'assess_postapproval_comparability': ('regulatory knowledge', 'assess', 'post-approval comparability', K),
 'assess_pregnancy_lactation_labeling': ('regulatory knowledge', 'look_up', 'the pregnancy and lactation labeling', K),
 'assess_process_validation': ('regulatory knowledge', 'look_up', 'process-validation guidance', K),
 'assess_project_optimus_alignment': ('regulatory knowledge', 'assess', 'Project Optimus alignment', K),
 'assess_qms': ('regulatory knowledge', 'check', 'the QMS against ISO 13485', K),
 'assess_qtc_risk': ('regulatory knowledge', 'assess', 'the QTc risk', K),
 'assess_rare_disease_endpoint': ('regulatory knowledge', 'assess', 'rare-disease endpoints', K),
 'assess_respiratory_safety_pharmacology': ('regulatory knowledge', 'assess', 'the respiratory safety package', K),
 'assess_rolling_submission': ('regulatory knowledge', 'assess', 'rolling-submission eligibility', K),
 'assess_rwe_bias_risk': ('regulatory knowledge', 'assess', 'the RWE bias risk', K),
 'assess_rwe_regulatory_acceptability': ('regulatory knowledge', 'assess', 'the RWE acceptability', K),
 'assess_scientific_validity': ('regulatory knowledge', 'assess', 'the scientific validity', K),
 'assess_small_population_design': ('regulatory knowledge', 'assess', 'small-population designs', K),
 'assess_structural_alerts': ('regulatory knowledge', 'assess', 'the structural alerts', K),
 'assess_vaccine_platform': ('regulatory knowledge', 'assess', 'the vaccine platform', K),
 'evaluate_pbpk_model': ('regulatory knowledge', 'assess', 'the PBPK model', K),
 # regulatory knowledge: builds, designs, plans and selections from curated frameworks
 'build_device_blueprint': ('regulatory knowledge', 'build', 'the device submission blueprint', K),
 'build_effects_table': ('regulatory knowledge', 'build', 'the effects table', K),
 'build_global_device_strategy': ('regulatory knowledge', 'build', 'the global device strategy', K),
 'build_postmarket_report': ('regulatory knowledge', 'draft', 'a post-market report', K),
 'compare_global_pathways': ('regulatory knowledge', 'compare', 'pathways across markets', K),
 'control_mutagenic_impurity': ('regulatory knowledge', 'design', 'the mutagenic-impurity control', K),
 'cross_region_gap_analysis': ('regulatory knowledge', 'compare', 'what another region needs', K),
 'design_ada_assay_strategy': ('regulatory knowledge', 'design', 'the ADA assay strategy', K),
 'design_adaptive_design': ('regulatory knowledge', 'design', 'the adaptive design', K),
 'design_adme_program': ('regulatory knowledge', 'design', 'the ADME program', K),
 'design_backfill_strategy': ('regulatory knowledge', 'design', 'the backfill strategy', K),
 'design_be_study': ('regulatory knowledge', 'design', 'the bioequivalence study', K),
 'design_bioanalytical_method': ('regulatory knowledge', 'design', 'the bioanalytical method', K),
 'design_biosimilar_clinical': ('regulatory knowledge', 'design', 'the biosimilar clinical program', K),
 'design_capa': ('regulatory knowledge', 'design', 'a CAPA plan', K),
 'design_cdx_codevelopment': ('regulatory knowledge', 'design', 'the CDx co-development', K),
 'design_core_battery': ('regulatory knowledge', 'design', 'the safety pharmacology battery', K),
 'design_device_clinical_evidence': ('regulatory knowledge', 'design', 'the device clinical evidence', K),
 'design_external_control': ('regulatory knowledge', 'design', 'the external control', K),
 'design_followup_safety_study': ('regulatory knowledge', 'design', 'the follow-up safety studies', K),
 'design_genotox_battery': ('regulatory knowledge', 'design', 'the genotoxicity battery', K),
 'design_human_factors_study': ('regulatory knowledge', 'design', 'the human factors study', K),
 'design_informed_consent': ('regulatory knowledge', 'design', 'the informed-consent framework', K),
 'design_mass_balance_study': ('regulatory knowledge', 'design', 'the mass-balance study', K),
 'design_monitoring_plan': ('regulatory knowledge', 'design', 'the monitoring plan', K),
 'design_nab_assay': ('regulatory knowledge', 'design', 'the NAb assay', K),
 'design_natural_history_study': ('regulatory knowledge', 'design', 'the natural-history study', K),
 'design_organ_impairment_study': ('regulatory knowledge', 'design', 'the organ-impairment study', K),
 'design_pacmp': ('regulatory knowledge', 'design', 'the change management protocol', K),
 'design_pccp': ('regulatory knowledge', 'design', 'the change control plan', K),
 'design_pediatric_investigation': ('regulatory knowledge', 'design', 'the pediatric plan', K),
 'design_popk_study': ('regulatory knowledge', 'design', 'the population PK analysis', K),
 'design_propensity_analysis': ('regulatory knowledge', 'design', 'the propensity analysis', K),
 'design_purge_study': ('regulatory knowledge', 'design', 'the purge assessment', K),
 'design_pv_system': ('regulatory knowledge', 'design', 'the pharmacovigilance system', K),
 'design_randomized_dose_comparison': ('regulatory knowledge', 'design', 'the randomized dose comparison', K),
 'design_reaction_phenotyping': ('regulatory knowledge', 'design', 'the reaction-phenotyping study', K),
 'design_rems': ('regulatory knowledge', 'design', 'the REMS', K),
 'design_repeat_dose_study': ('regulatory knowledge', 'design', 'the repeat-dose study', K),
 'design_repro_tox_study': ('regulatory knowledge', 'design', 'the reproductive toxicology studies', K),
 'design_samd_clinical_validation': ('regulatory knowledge', 'design', 'the SaMD clinical validation', K),
 'design_stability_study': ('regulatory knowledge', 'design', 'the stability study', K),
 'design_sterile_controls': ('regulatory knowledge', 'design', 'the contamination control strategy', K),
 'design_target_trial': ('regulatory knowledge', 'design', 'the target trial emulation', K),
 'design_toxicokinetics': ('regulatory knowledge', 'design', 'the toxicokinetics', K),
 'design_vaccine_clinical_program': ('regulatory knowledge', 'design', 'the vaccine clinical program', K),
 'design_vaccine_cmc': ('regulatory knowledge', 'design', 'the vaccine CMC plan', K),
 'design_value_tree': ('regulatory knowledge', 'design', 'the benefit-risk value tree', K),
 'generate_declaration_of_conformity': ('regulatory knowledge', 'generate', 'the Declaration of Conformity', K),
 'generate_dsur_structure': ('regulatory knowledge', 'generate', 'the DSUR structure', K),
 'generate_psur_structure': ('regulatory knowledge', 'generate', 'the PSUR structure', K),
 'generate_spl': ('regulatory knowledge', 'generate', 'the SPL document', K),
 'generate_spl_xml': ('regulatory knowledge', 'generate', 'an SPL skeleton', K),
 'plan_aggregate_safety_report': ('regulatory knowledge', 'plan', 'the aggregate safety reports', K),
 'plan_annual_report': ('regulatory knowledge', 'plan', 'the annual report', K),
 'plan_bayesian_borrowing': ('regulatory knowledge', 'plan', 'Bayesian borrowing', K),
 'plan_biomarker_qualification': ('regulatory knowledge', 'plan', 'the biomarker qualification', K),
 'plan_biosimilar_ip_strategy': ('regulatory knowledge', 'plan', 'the biosimilar IP strategy', K),
 'plan_br_communication': ('regulatory knowledge', 'plan', 'the benefit-risk communication', K),
 'plan_coa_development': ('regulatory knowledge', 'plan', 'the COA development', K),
 'plan_combination_cgmp': ('regulatory knowledge', 'plan', 'the combination-product cGMP', K),
 'plan_device_submission': ('regulatory knowledge', 'plan', 'the device submission', K),
 'plan_enrichment_strategy': ('regulatory knowledge', 'plan', 'the enrichment strategy', K),
 'plan_essential_documents': ('regulatory knowledge', 'plan', 'the essential documents', K),
 'plan_fda_meeting': ('regulatory knowledge', 'plan', 'the FDA meeting', K),
 'plan_immunogenicity_sampling': ('regulatory knowledge', 'plan', 'the immunogenicity sampling', K),
 'plan_lifecycle_management': ('regulatory knowledge', 'plan', 'the lifecycle management', K),
 'plan_multiplicity_control': ('regulatory knowledge', 'plan', 'the multiplicity control', K),
 'plan_orphan_drug_designation': ('regulatory knowledge', 'plan', 'the orphan-drug designation request', K),
 'plan_rare_disease_program': ('regulatory knowledge', 'plan', 'the rare-disease program', K),
 'plan_vaccine_special_populations': ('regulatory knowledge', 'plan', 'the vaccine special populations', K),
 'position_coa_endpoint': ('regulatory knowledge', 'select', "the COA endpoint's position", K),
 'select_505_pathway': ('regulatory knowledge', 'select', 'the 505 pathway', K),
 'select_atmp_pathway': ('regulatory knowledge', 'select', 'the advanced-therapy pathway', K),
 'select_coa_type': ('regulatory knowledge', 'select', 'the COA type', K),
 'select_combination_submission_pathway': ('regulatory knowledge', 'select', 'the combination-product pathway', K),
 'select_device_pathway': ('regulatory knowledge', 'select', 'the device pathway', K),
 'select_dose': ('regulatory knowledge', 'select', 'the dose framework', K),
 'select_dose_finding_design': ('regulatory knowledge', 'select', 'the dose-finding design', K),
 'select_missing_data_strategy': ('regulatory knowledge', 'select', 'the missing-data strategy', K),
 'select_pediatric_dose': ('regulatory knowledge', 'select', 'the pediatric dose method', K),
 'select_pediatric_formulation': ('regulatory knowledge', 'select', 'the pediatric formulation', K),
 'select_rp2d': ('regulatory knowledge', 'select', 'the phase 2 dose', K),
 'select_rwe_design': ('regulatory knowledge', 'select', 'the RWE design', K),
 'select_tox_species': ('regulatory knowledge', 'select', 'the toxicology species', K),
 'set_specifications': ('regulatory knowledge', 'look_up', 'the specification tests', K),
 'structure_benefit_risk_framework': ('regulatory knowledge', 'build', 'the benefit-risk framework', K),
 'structure_smpc': ('regulatory knowledge', 'build', 'the SmPC structure', K),
 'analyze_exposure_response': ('regulatory knowledge', 'plan', 'the exposure-response analysis', K),
 # regulatory knowledge: registries (global RI)
 'global_ri_advanced_therapy': ('regulatory knowledge', 'classify', 'the advanced therapy for a region', K),
 'global_ri_bcs_biowaiver': ('regulatory knowledge', 'look_up', 'BCS biowaiver eligibility', K),
 'global_ri_bioequivalence_criteria': ('regulatory knowledge', 'look_up', 'the bioequivalence criteria', K),
 'global_ri_cmc_specifications': ('regulatory knowledge', 'look_up', 'the specification tests', K),
 'global_ri_companion_diagnostic': ('regulatory knowledge', 'look_up', 'the companion-diagnostic framework', K),
 'global_ri_controlled_substance': ('regulatory knowledge', 'look_up', 'the controlled-substance schedule', K),
 'global_ri_device_classification': ('regulatory knowledge', 'look_up', 'the device market pathway', K),
 'global_ri_dossier_classifier': ('regulatory knowledge', 'classify', 'the dossier type', K),
 'global_ri_establishment_registration': ('regulatory knowledge', 'look_up', 'the registration obligations', K),
 'global_ri_evidence_standard': ('regulatory knowledge', 'look_up', 'the evidence standard', K),
 'global_ri_exclusivity': ('regulatory knowledge', 'compute', 'regulatory exclusivity', K),
 'global_ri_expanded_access': ('regulatory knowledge', 'look_up', 'expanded-access options', K),
 'global_ri_expedited_programs': ('regulatory knowledge', 'look_up', 'expedited programs', K),
 'global_ri_fee_estimate': ('regulatory knowledge', 'estimate', 'agency fees', K),
 'global_ri_import_export': ('regulatory knowledge', 'look_up', 'import and export licensing', K),
 'global_ri_lifecycle_schedule': ('regulatory knowledge', 'build', 'the lifecycle calendar', K),
 'global_ri_pediatric_plan': ('regulatory knowledge', 'look_up', 'the pediatric plan requirements', K),
 'global_ri_post_approval_change': ('regulatory knowledge', 'classify', 'the post-approval change', K),
 'global_ri_process_validation': ('regulatory knowledge', 'look_up', 'the process-validation framework', K),
 'global_ri_promotional_compliance': ('regulatory knowledge', 'look_up', 'the promotion rules', K),
 'global_ri_regulatory_pathway': ('regulatory knowledge', 'look_up', 'the regulatory pathway', K),
 'global_ri_reliance_pathways': ('regulatory knowledge', 'look_up', 'reliance pathways', K),
 'global_ri_safety_reporting': ('regulatory knowledge', 'classify', 'the safety case for reporting', K),
 'global_ri_special_designations': ('regulatory knowledge', 'look_up', 'designation eligibility', K),
 'global_ri_stability_conditions': ('regulatory knowledge', 'look_up', 'the stability conditions', K),
 'global_ri_strategy_brief': ('regulatory knowledge', 'build', 'the global strategy brief', K),
 # regulatory knowledge: guidance and requirement lookups (were in the prefix pass)
 'explain_cmc_topic': ('regulatory knowledge', 'explain', 'a CMC topic', K, ['query']),
 'fetch_ich_guideline_updates': ('regulatory knowledge', 'look_up', 'ICH guideline updates', K),
 'find_cmc_guidance': ('regulatory knowledge', 'look_up', 'the CMC guidance', K, ['query']),
 'get_biocompatibility_endpoints': ('regulatory knowledge', 'look_up', 'the biocompatibility endpoints', K),
 'get_cmc_requirements': ('regulatory knowledge', 'look_up', 'the CMC requirements', K),
 'get_device_labeling': ('regulatory knowledge', 'look_up', 'the device labeling requirements', K),
 'get_document_section_requirements': ('regulatory knowledge', 'look_up', 'what the document must contain', K, ['section']),
 'get_electrical_standards': ('regulatory knowledge', 'look_up', 'the electrical-safety standards', K),
 'get_regulatory_timeline': ('regulatory knowledge', 'look_up', 'the review timeline', K),
 'get_sterilization_requirements': ('regulatory knowledge', 'look_up', 'the sterilization requirements', K),
 'guidance_for_anda': ('regulatory knowledge', 'look_up', 'guidance for a generic application', K),
 'ivd_knowledge_lookup': ('regulatory knowledge', 'look_up', 'IVD knowledge', K, ['query', 'topic']),
 'list_fda_technical_rules': ('regulatory knowledge', 'look_up', "FDA's technical submission rules", K),
 'lookup_fda_guidance': ('regulatory knowledge', 'look_up', 'FDA guidance', K, ['topic']),
 'lookup_ich_guideline': ('regulatory knowledge', 'look_up', 'ICH guidelines', K, ['section', 'topic']),
 'lookup_regulatory_pathway': ('regulatory knowledge', 'look_up', 'expedited pathways', K, ['query']),
 'plan_submission_from_database_lock': ('regulatory knowledge', 'look_up', 'the steps from database lock to filing', K),
 'run_compliance_checklist': ('regulatory knowledge', 'look_up', 'the compliance checklist', K),
 'search_ivd_knowledge': ('regulatory knowledge', 'search', 'the IVD knowledge base', K, ['query']),
 'value_dossier_guidance': ('regulatory knowledge', 'look_up', 'value-dossier guidance', K),
 'check_regulatory_currency': ('regulatory knowledge', 'check', 'that the rule is still current', K, ['topic']),
}
