apiVersion: v1
kind: Secret
metadata:
  name: { { include "common.names.fullname" . } }
  labels: { { - include "common.labels.standard" . | nindent 4 } }
type: Opaque
data:
  openai-api-key: { { .Values.secrets.openaiApiKey | b64enc | quote } }
  pinecone-api-key: { { .Values.secrets.pineconeApiKey | b64enc | quote } }
  api-key: { { .Values.secrets.apiKey | b64enc | quote } }
