                           List of relations
 Schema |                  Name                  | Type  |    Owner     
--------+----------------------------------------+-------+--------------
 public | activity_feed                          | table | neondb_owner
 public | activity_reactions                     | table | neondb_owner
 public | agency_communications                  | table | neondb_owner
 public | agency_correspondence                  | table | neondb_owner
 public | agency_validation_results              | table | neondb_owner
 public | ai_audit_log                           | table | neondb_owner
 public | ai_dead_letter_queue                   | table | neondb_owner
 public | ai_token_budget                        | table | neondb_owner
 public | analytical_methods                     | table | neondb_owner
 public | audit_events                           | table | neondb_owner
 public | audit_logs                             | table | neondb_owner
 public | audit_trail                            | table | neondb_owner
 public | auth_password_resets                   | table | neondb_owner
 public | auth_refresh_tokens                    | table | neondb_owner
 public | auth_users                             | table | neondb_owner
 public | available_modules                      | table | neondb_owner
 public | batch_genealogy                        | table | neondb_owner
 public | batches                                | table | neondb_owner
 public | biomarker_endpoints                    | table | neondb_owner
 public | cdisc_adam_specs                       | table | neondb_owner
 public | cdisc_cdash_fields                     | table | neondb_owner
 public | cdisc_cdash_forms                      | table | neondb_owner
 public | cdisc_cdash_sdtm_mappings              | table | neondb_owner
 public | cdisc_compliance_agency_prefs          | table | neondb_owner
 public | cdisc_compliance_results               | table | neondb_owner
 public | cdisc_compliance_rules                 | table | neondb_owner
 public | cdisc_compliance_versions              | table | neondb_owner
 public | cdisc_csr_sap                          | table | neondb_owner
 public | cdisc_csr_templates                    | table | neondb_owner
 public | cdisc_csr_tfl                          | table | neondb_owner
 public | cdisc_device_de                        | table | neondb_owner
 public | cdisc_device_dx                        | table | neondb_owner
 public | cdisc_device_relationships             | table | neondb_owner
 public | cdisc_docs_acrf                        | table | neondb_owner
 public | cdisc_docs_define_artifacts            | table | neondb_owner
 public | cdisc_docs_repository                  | table | neondb_owner
 public | cdisc_ectd_datasets                    | table | neondb_owner
 public | cdisc_ectd_define_xml                  | table | neondb_owner
 public | cdisc_ectd_reviewers_guide             | table | neondb_owner
 public | cdisc_ectd_sdsp                        | table | neondb_owner
 public | cdisc_ind_integration                  | table | neondb_owner
 public | cdisc_ind_ise                          | table | neondb_owner
 public | cdisc_ind_iss                          | table | neondb_owner
 public | cdisc_ind_send                         | table | neondb_owner
 public | cdisc_pq_domains                       | table | neondb_owner
 public | cdisc_pq_manufacturing                 | table | neondb_owner
 public | cdisc_pq_stability                     | table | neondb_owner
 public | cdisc_prm_endpoints                    | table | neondb_owner
 public | cdisc_prm_epochs                       | table | neondb_owner
 public | cdisc_prm_studies                      | table | neondb_owner
 public | cdisc_prm_study_arms                   | table | neondb_owner
 public | cdisc_prm_visits                       | table | neondb_owner
 public | cdisc_task_deliverables                | table | neondb_owner
 public | cdisc_task_milestones                  | table | neondb_owner
 public | cdisc_task_validation_queue            | table | neondb_owner
 public | cdisc_task_workflows                   | table | neondb_owner
 public | cer_approvals                          | table | neondb_owner
 public | cer_clinical_evidence                  | table | neondb_owner
 public | cer_compliance_checks                  | table | neondb_owner
 public | cer_documents                          | table | neondb_owner
 public | cer_essential_requirements             | table | neondb_owner
 public | cer_exports                            | table | neondb_owner
 public | cer_faers_data                         | table | neondb_owner
 public | cer_literature                         | table | neondb_owner
 public | cer_projects                           | table | neondb_owner
 public | cer_reports                            | table | neondb_owner
 public | cer_sections                           | table | neondb_owner
 public | cer_templates                          | table | neondb_owner
 public | cer_version_history                    | table | neondb_owner
 public | cer_workflows                          | table | neondb_owner
 public | cerv2_510k_sections                    | table | neondb_owner
 public | cerv2_audit_events                     | table | neondb_owner
 public | cerv2_claims                           | table | neondb_owner
 public | cerv2_document_sessions                | table | neondb_owner
 public | cerv2_evidence                         | table | neondb_owner
 public | cerv2_evidence_links                   | table | neondb_owner
 public | cerv2_outcomes                         | table | neondb_owner
 public | cerv2_section_versions                 | table | neondb_owner
 public | cerv2_standards                        | table | neondb_owner
 public | change_requests                        | table | neondb_owner
 public | client_access                          | table | neondb_owner
 public | client_security_settings               | table | neondb_owner
 public | client_user_permissions                | table | neondb_owner
 public | client_workspace_settings              | table | neondb_owner
 public | client_workspaces                      | table | neondb_owner
 public | clinical_feedback                      | table | neondb_owner
 public | clinical_outcomes                      | table | neondb_owner
 public | cmc_change_control                     | table | neondb_owner
 public | coauthor_annotations                   | table | neondb_owner
 public | coauthor_document_versions             | table | neondb_owner
 public | coauthor_documents                     | table | neondb_owner
 public | coauthor_import_history                | table | neondb_owner
 public | coauthor_sections                      | table | neondb_owner
 public | coauthor_status_history                | table | neondb_owner
 public | coauthor_validation_history            | table | neondb_owner
 public | coauthor_validation_rules              | table | neondb_owner
 public | comparability_studies                  | table | neondb_owner
 public | compliance_calendar                    | table | neondb_owner
 public | compliance_tracking                    | table | neondb_owner
 public | component_cross_references             | table | neondb_owner
 public | component_sequence_references          | table | neondb_owner
 public | component_versions                     | table | neondb_owner
 public | components                             | table | neondb_owner
 public | context_groups                         | table | neondb_owner
 public | context_members                        | table | neondb_owner
 public | cro_clients                            | table | neondb_owner
 public | cro_milestones                         | table | neondb_owner
 public | cro_regulatory_submissions             | table | neondb_owner
 public | cro_studies                            | table | neondb_owner
 public | cro_team_assignments                   | table | neondb_owner
 public | cross_module_task_links                | table | neondb_owner
 public | cross_species_pkpd                     | table | neondb_owner
 public | csr_reports                            | table | neondb_owner
 public | ctq_factors                            | table | neondb_owner
 public | data_lineage_tracking                  | table | neondb_owner
 public | deviations                             | table | neondb_owner
 public | device_audit_trail                     | table | neondb_owner
 public | device_components                      | table | neondb_owner
 public | device_data_categories                 | table | neondb_owner
 public | device_data_center                     | table | neondb_owner
 public | device_profiles                        | table | neondb_owner
 public | device_submission_documents            | table | neondb_owner
 public | device_submission_workflows            | table | neondb_owner
 public | device_submissions                     | table | neondb_owner
 public | device_test_standards                  | table | neondb_owner
 public | diagnostic_analytes                    | table | neondb_owner
 public | diagnostic_performance_metrics         | table | neondb_owner
 public | diagnostic_profiles                    | table | neondb_owner
 public | diagnostic_specimens                   | table | neondb_owner
 public | dlt_events                             | table | neondb_owner
 public | document_audit_log                     | table | neondb_owner
 public | document_audit_trail                   | table | neondb_owner
 public | document_comments                      | table | neondb_owner
 public | document_components                    | table | neondb_owner
 public | document_folders                       | table | neondb_owner
 public | document_locks                         | table | neondb_owner
 public | document_sections                      | table | neondb_owner
 public | document_sessions                      | table | neondb_owner
 public | document_templates                     | table | neondb_owner
 public | document_vectors                       | table | neondb_owner
 public | document_versions                      | table | neondb_owner
 public | documents                              | table | neondb_owner
 public | doe_analysis_results                   | table | neondb_owner
 public | doe_experiments                        | table | neondb_owner
 public | doe_factors                            | table | neondb_owner
 public | doe_responses                          | table | neondb_owner
 public | doe_studies                            | table | neondb_owner
 public | dose_cohorts                           | table | neondb_owner
 public | dose_escalation_studies                | table | neondb_owner
 public | dose_levels                            | table | neondb_owner
 public | drug_products                          | table | neondb_owner
 public | drug_substances                        | table | neondb_owner
 public | ectd_change_control                    | table | neondb_owner
 public | ectd_compilations                      | table | neondb_owner
 public | ectd_cross_references                  | table | neondb_owner
 public | ectd_granules                          | table | neondb_owner
 public | ectd_modules                           | table | neondb_owner
 public | ectd_templates                         | table | neondb_owner
 public | electronic_signatures                  | table | neondb_owner
 public | facts                                  | table | neondb_owner
 public | fda_510k_data_mappings                 | table | neondb_owner
 public | fda_510k_documents                     | table | neondb_owner
 public | fda_510k_projects                      | table | neondb_owner
 public | fda_510k_stage_progress                | table | neondb_owner
 public | fda_510k_submission_packages           | table | neondb_owner
 public | fda_510k_submissions                   | table | neondb_owner
 public | fda_510k_templates                     | table | neondb_owner
 public | fda_integration_logs                   | table | neondb_owner
 public | foresight_predictions                  | table | neondb_owner
 public | gate_approvals                         | table | neondb_owner
 public | ind_applications                       | table | neondb_owner
 public | ind_documents                          | table | neondb_owner
 public | ind_narrative_sections                 | table | neondb_owner
 public | ind_narratives                         | table | neondb_owner
 public | ind_package_plan_documents             | table | neondb_owner
 public | ind_package_plan_modalities            | table | neondb_owner
 public | ind_package_plan_regions               | table | neondb_owner
 public | ind_package_plan_requirements          | table | neondb_owner
 public | ind_package_plan_timelines             | table | neondb_owner
 public | ind_package_plans                      | table | neondb_owner
 public | ind_projects                           | table | neondb_owner
 public | ind_submissions                        | table | neondb_owner
 public | ind_template_usage_logs                | table | neondb_owner
 public | ind_templates                          | table | neondb_owner
 public | integration_tokens                     | table | neondb_owner
 public | leaf_citations                         | table | neondb_owner
 public | leaf_patches                           | table | neondb_owner
 public | leaves                                 | table | neondb_owner
 public | license_entitlements                   | table | neondb_owner
 public | link_edges                             | table | neondb_owner
 public | lumen_audit_events                     | table | neondb_owner
 public | lumen_cache_entries                    | table | neondb_owner
 public | lumen_data_atoms                       | table | neondb_owner
 public | lumen_filing_documents                 | table | neondb_owner
 public | lumen_observation_terms                | table | neondb_owner
 public | lumen_risk_records                     | table | neondb_owner
 public | lumen_usage_events                     | table | neondb_owner
 public | materials                              | table | neondb_owner
 public | medical_devices                        | table | neondb_owner
 public | module_subscriptions                   | table | neondb_owner
 public | multi_agency_validation_sessions       | table | neondb_owner
 public | notification_preferences               | table | neondb_owner
 public | notifications                          | table | neondb_owner
 public | obligation_updates                     | table | neondb_owner
 public | organization_licenses                  | table | neondb_owner
 public | organization_users                     | table | neondb_owner
 public | organizations                          | table | neondb_owner
 public | patches                                | table | neondb_owner
 public | permissions                            | table | neondb_owner
 public | pkpd_compartments                      | table | neondb_owner
 public | pma_submissions                        | table | neondb_owner
 public | post_approval_commitments              | table | neondb_owner
 public | process_validation                     | table | neondb_owner
 public | project_activities                     | table | neondb_owner
 public | project_documents                      | table | neondb_owner
 public | project_milestones                     | table | neondb_owner
 public | project_modules                        | table | neondb_owner
 public | project_risks                          | table | neondb_owner
 public | project_tasks                          | table | neondb_owner
 public | project_templates                      | table | neondb_owner
 public | project_workflow_stages                | table | neondb_owner
 public | projects                               | table | neondb_owner
 public | qc_testing                             | table | neondb_owner
 public | qmp_audit_trail                        | table | neondb_owner
 public | qmp_section_gating                     | table | neondb_owner
 public | qmp_traceability_matrix                | table | neondb_owner
 public | quality_management_plans               | table | neondb_owner
 public | rag_chunks                             | table | neondb_owner
 public | rag_documents                          | table | neondb_owner
 public | rag_ingestion_jobs                     | table | neondb_owner
 public | rag_knowledge_graph                    | table | neondb_owner
 public | rag_queries                            | table | neondb_owner
 public | rag_sources                            | table | neondb_owner
 public | recent_documents                       | table | neondb_owner
 public | reg_attachments                        | table | neondb_owner
 public | reg_messages                           | table | neondb_owner
 public | reg_obligation_events                  | table | neondb_owner
 public | reg_obligation_templates               | table | neondb_owner
 public | reg_obligations                        | table | neondb_owner
 public | reg_questions                          | table | neondb_owner
 public | reg_responses                          | table | neondb_owner
 public | regulatory_agencies                    | table | neondb_owner
 public | regulatory_atoms                       | table | neondb_owner
 public | regulatory_audit_logs                  | table | neondb_owner
 public | regulatory_calendar                    | table | neondb_owner
 public | regulatory_change_control              | table | neondb_owner
 public | regulatory_documents                   | table | neondb_owner
 public | regulatory_intelligence                | table | neondb_owner
 public | regulatory_obligations                 | table | neondb_owner
 public | regulatory_submissions                 | table | neondb_owner
 public | regulatory_tasks                       | table | neondb_owner
 public | replacement_rules                      | table | neondb_owner
 public | roles                                  | table | neondb_owner
 public | section_graph_nodes                    | table | neondb_owner
 public | section_leaves                         | table | neondb_owner
 public | section_links                          | table | neondb_owner
 public | section_patches                        | table | neondb_owner
 public | section_propagations                   | table | neondb_owner
 public | sections                               | table | neondb_owner
 public | sharepoint_audit_log                   | table | neondb_owner
 public | sharepoint_comments                    | table | neondb_owner
 public | sharepoint_file_versions               | table | neondb_owner
 public | sharepoint_files                       | table | neondb_owner
 public | sharepoint_integration                 | table | neondb_owner
 public | sharepoint_locks                       | table | neondb_owner
 public | sharepoint_shares                      | table | neondb_owner
 public | simple_document_versions               | table | neondb_owner
 public | simple_documents                       | table | neondb_owner
 public | source_data_point_bindings             | table | neondb_owner
 public | source_data_points                     | table | neondb_owner
 public | source_documents                       | table | neondb_owner
 public | species_comparisons                    | table | neondb_owner
 public | stability_studies                      | table | neondb_owner
 public | staff_assignments                      | table | neondb_owner
 public | stage_gates                            | table | neondb_owner
 public | structured_observation_terms           | table | neondb_owner
 public | supply_chain_batches                   | table | neondb_owner
 public | supply_chain_coas                      | table | neondb_owner
 public | supply_chain_materials                 | table | neondb_owner
 public | supply_chain_organizations             | table | neondb_owner
 public | supply_chain_shipments                 | table | neondb_owner
 public | supply_chain_suppliers                 | table | neondb_owner
 public | supply_chain_temperature_readings      | table | neondb_owner
 public | sync_status                            | table | neondb_owner
 public | task_automation                        | table | neondb_owner
 public | task_dependencies                      | table | neondb_owner
 public | task_templates                         | table | neondb_owner
 public | template_usage                         | table | neondb_owner
 public | tenant_style_preferences               | table | neondb_owner
 public | translational_patterns                 | table | neondb_owner
 public | unified_tasks                          | table | neondb_owner
 public | user_following                         | table | neondb_owner
 public | user_identities                        | table | neondb_owner
 public | user_presence                          | table | neondb_owner
 public | user_roles                             | table | neondb_owner
 public | users                                  | table | neondb_owner
 public | validation_findings                    | table | neondb_owner
 public | validation_harmonization_opportunities | table | neondb_owner
 public | validation_issues                      | table | neondb_owner
 public | workbench_sessions                     | table | neondb_owner
 public | workflow_progress                      | table | neondb_owner
(301 rows)

