{pkgs}: {
  deps = [
    pkgs.nodePackages.prettier
    pkgs.python3
    pkgs.zip
    pkgs.tesseract
    pkgs.pinentry-all
    pkgs.gnupg
    pkgs.openssh
    pkgs.bc
    pkgs.poppler
    pkgs.unzip
    pkgs.jq
    pkgs.tk
    pkgs.tcl
    pkgs.qhull
    pkgs.gtk3
    pkgs.gobject-introspection
    pkgs.ghostscript
    pkgs.ffmpeg-full
    pkgs.cairo
    pkgs.xsimd
    pkgs.pkg-config
    pkgs.wget
    pkgs.libxcrypt
    pkgs.glibcLocales
    pkgs.swig
    pkgs.openjpeg
    pkgs.mupdf
    pkgs.libjpeg_turbo
    pkgs.jbig2dec
    pkgs.harfbuzz
    pkgs.gumbo
    pkgs.freetype
    pkgs.postgresql
  ];
}
