/**
 * @fileoverview IND eCTD Section Map — Complete Module 1-5 Definition
 * @module services/regulatory/ind-ectd-sections
 * @version 1.0.0
 *
 * @description
 * Canonical TypeScript definition of every IND CTD section per 21 CFR 312.23(a)
 * and ICH M4/M2 eCTD specification. Each section is mapped to:
 *   - eCTD module code (m1.x, m2.x, etc.)
 *   - IND Pyramid task ID (for workflow bridge)
 *   - Document type and authoring template
 *   - Required/optional status
 *   - Responsible role
 *   - AI drafting capability flag
 *
 * Reference documents:
 *   - 21 CFR 312.23(a) — Content and format of an IND
 *   - ICH M4 — The Common Technical Document
 *   - FDA eCTD v4.0 Specification
 *   - ICH M8 — eCTD v4.0 Implementation Guide
 *
 * @compliance FDA 21 CFR Part 11, ICH M4, ICH M8
 */

// ═══════════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════════

/** eCTD top-level module identifier */
export type CTDModule = 'M1' | 'M2' | 'M3' | 'M4' | 'M5';

/** Section lifecycle for authoring workflow */
export type SectionStatus =
  | 'not_started'
  | 'data_gathering'
  | 'drafting'
  | 'internal_review'
  | 'revision'
  | 'qa_review'
  | 'approved'
  | 'signed'
  | 'locked';

/** Document format for the section */
export type DocumentFormat = 'pdf' | 'xml' | 'docx' | 'json' | 'xpt';

/** Authoring mode */
export type AuthoringMode = 'ai_draft' | 'manual' | 'template_fill' | 'data_import' | 'form';

/** A single eCTD section definition */
export interface INDSection {
  /** eCTD module code (e.g., "m1.2", "m2.3.S.1") */
  code: string;
  /** Human-readable section title */
  title: string;
  /** Parent eCTD code (null for top-level modules) */
  parentCode: string | null;
  /** CTD Module (M1-M5) */
  module: CTDModule;
  /** Depth in hierarchy (0=module, 1=section, 2=subsection, 3=leaf) */
  depth: number;
  /** Linked IND Pyramid task ID (for workflow engine bridge) */
  pyramidTaskId: string | null;
  /** Required for initial IND filing */
  required: boolean;
  /** Required for IND amendments */
  requiredForAmendment: boolean;
  /** Document format */
  format: DocumentFormat;
  /** How this section is authored */
  authoringMode: AuthoringMode;
  /** Whether Lumen Cortex can AI-draft this section */
  aiDraftable: boolean;
  /** Responsible role */
  role: string;
  /** Regulatory reference (CFR citation) */
  regulatoryRef: string;
  /** Brief description of content requirements */
  description: string;
  /** Child sections (recursive tree) */
  children?: INDSection[];
  /** eCTD 4.0 Context of Use code (ICH M8) */
  contextOfUse?: string;
  /** Estimated authoring hours */
  estimatedHours: number;
}

/** Complete IND eCTD package definition */
export interface INDPackageDefinition {
  submissionType: 'IND';
  ectdVersion: '4.0';
  agency: 'FDA';
  totalSections: number;
  requiredSections: number;
  estimatedTotalHours: number;
  modules: INDSection[];
}

// ═══════════════════════════════════════════════════════════════════════════════
// MODULE 1 — REGIONAL ADMINISTRATIVE INFORMATION (FDA-SPECIFIC)
// 21 CFR 312.23(a)(1)
// ═══════════════════════════════════════════════════════════════════════════════

const MODULE_1: INDSection = {
  code: 'm1',
  title: 'Module 1: Regional Administrative Information',
  parentCode: null,
  module: 'M1',
  depth: 0,
  pyramidTaskId: null,
  required: true,
  requiredForAmendment: true,
  format: 'pdf',
  authoringMode: 'manual',
  aiDraftable: false,
  role: 'ra_lead',
  regulatoryRef: '21 CFR 312.23(a)(1)',
  description: 'FDA-specific administrative forms, cover letter, and regulatory correspondence.',
  estimatedHours: 0,
  contextOfUse: 'm1',
  children: [
    {
      code: 'm1.1',
      title: 'FDA Forms',
      parentCode: 'm1',
      module: 'M1',
      depth: 1,
      pyramidTaskId: 'phase3.form_1571',
      required: true,
      requiredForAmendment: true,
      format: 'pdf',
      authoringMode: 'form',
      aiDraftable: false,
      role: 'ra_associate',
      regulatoryRef: '21 CFR 312.23(a)(1)(i)',
      description:
        'FDA Form 1571 (IND Application), Form 1572 (Investigator Statement), Form 3674 (Certification of Compliance).',
      estimatedHours: 4,
      contextOfUse: 'm1-1',
      children: [
        {
          code: 'm1.1.1',
          title: 'Form FDA 1571',
          parentCode: 'm1.1',
          module: 'M1',
          depth: 2,
          pyramidTaskId: 'phase3.form_1571',
          required: true,
          requiredForAmendment: true,
          format: 'pdf',
          authoringMode: 'form',
          aiDraftable: false,
          role: 'ra_associate',
          regulatoryRef: '21 CFR 312.23(a)(1)',
          description:
            'Investigational New Drug Application form — identifies sponsor, drug, IND number.',
          estimatedHours: 2,
          contextOfUse: 'm1-1-1',
        },
        {
          code: 'm1.1.2',
          title: 'Form FDA 1572',
          parentCode: 'm1.1',
          module: 'M1',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'form',
          aiDraftable: false,
          role: 'ra_associate',
          regulatoryRef: '21 CFR 312.53(c)',
          description: 'Statement of Investigator — each clinical investigator must sign.',
          estimatedHours: 1,
          contextOfUse: 'm1-1-2',
        },
        {
          code: 'm1.1.3',
          title: 'Form FDA 3674',
          parentCode: 'm1.1',
          module: 'M1',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'form',
          aiDraftable: false,
          role: 'ra_associate',
          regulatoryRef: '42 USC 282(j)(5)(B)',
          description: 'Certification of Compliance with ClinicalTrials.gov requirements.',
          estimatedHours: 0.5,
          contextOfUse: 'm1-1-3',
        },
        {
          code: 'm1.1.4',
          title: 'Form FDA 3455',
          parentCode: 'm1.1',
          module: 'M1',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'form',
          aiDraftable: false,
          role: 'ra_associate',
          regulatoryRef: '21 CFR 54',
          description:
            'Disclosure of Financial Interests and Arrangements of Clinical Investigators.',
          estimatedHours: 1,
          contextOfUse: 'm1-1-4',
        },
      ],
    },
    {
      code: 'm1.2',
      title: 'Cover Letter',
      parentCode: 'm1',
      module: 'M1',
      depth: 1,
      pyramidTaskId: 'phase3.cover_letter',
      required: true,
      requiredForAmendment: true,
      format: 'pdf',
      authoringMode: 'ai_draft',
      aiDraftable: true,
      role: 'ra_lead',
      regulatoryRef: '21 CFR 312.23(a)(1)',
      description:
        'Cover letter introducing the IND, summarizing contents, and highlighting key points for the FDA reviewer.',
      estimatedHours: 3,
      contextOfUse: 'm1-2',
    },
    {
      code: 'm1.3',
      title: 'Administrative Information',
      parentCode: 'm1',
      module: 'M1',
      depth: 1,
      pyramidTaskId: null,
      required: true,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'manual',
      aiDraftable: false,
      role: 'ra_associate',
      regulatoryRef: '21 CFR 312.23(a)(1)',
      description: 'Contact information, agent designation, transfer statements.',
      estimatedHours: 2,
      contextOfUse: 'm1-3',
      children: [
        {
          code: 'm1.3.1',
          title: 'Contact/Agent Information',
          parentCode: 'm1.3',
          module: 'M1',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'form',
          aiDraftable: false,
          role: 'ra_associate',
          regulatoryRef: '21 CFR 312.23(a)(1)',
          description: 'Sponsor contact and authorized US agent.',
          estimatedHours: 0.5,
          contextOfUse: 'm1-3-1',
        },
        {
          code: 'm1.3.2',
          title: 'Field Copy Certification',
          parentCode: 'm1.3',
          module: 'M1',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'form',
          aiDraftable: false,
          role: 'ra_associate',
          regulatoryRef: '21 CFR 312.23(a)(1)',
          description: 'Certification for field copy of IND.',
          estimatedHours: 0.5,
          contextOfUse: 'm1-3-2',
        },
        {
          code: 'm1.3.3',
          title: 'Debarment Certification',
          parentCode: 'm1.3',
          module: 'M1',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'form',
          aiDraftable: false,
          role: 'ra_associate',
          regulatoryRef: '21 USC 335a',
          description: 'Certification that no debarred persons are involved.',
          estimatedHours: 0.5,
          contextOfUse: 'm1-3-3',
        },
      ],
    },
    {
      code: 'm1.4',
      title: 'References',
      parentCode: 'm1',
      module: 'M1',
      depth: 1,
      pyramidTaskId: null,
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'manual',
      aiDraftable: false,
      role: 'ra_associate',
      regulatoryRef: '21 CFR 312.23(b)',
      description:
        'Letters of authorization, right of reference, cross-references to other INDs/NDAs.',
      estimatedHours: 2,
      contextOfUse: 'm1-4',
      children: [
        {
          code: 'm1.4.1',
          title: 'Letter of Authorization',
          parentCode: 'm1.4',
          module: 'M1',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'manual',
          aiDraftable: false,
          role: 'ra_associate',
          regulatoryRef: '21 CFR 312.23(b)',
          description: 'Authorization to reference another IND or DMF.',
          estimatedHours: 1,
          contextOfUse: 'm1-4-1',
        },
        {
          code: 'm1.4.2',
          title: 'Statement of Right of Reference',
          parentCode: 'm1.4',
          module: 'M1',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'manual',
          aiDraftable: false,
          role: 'ra_associate',
          regulatoryRef: '21 CFR 312.23(b)',
          description: 'Statement granting right of reference to supporting data.',
          estimatedHours: 1,
          contextOfUse: 'm1-4-2',
        },
      ],
    },
    {
      code: 'm1.5',
      title: 'Table of Contents',
      parentCode: 'm1',
      module: 'M1',
      depth: 1,
      pyramidTaskId: 'phase3.toc',
      required: true,
      requiredForAmendment: true,
      format: 'pdf',
      authoringMode: 'template_fill',
      aiDraftable: true,
      role: 'regulatory_ops',
      regulatoryRef: '21 CFR 312.23(a)(1)',
      description: 'Complete table of contents with hyperlinked bookmarks for the eCTD submission.',
      estimatedHours: 2,
      contextOfUse: 'm1-5',
    },
    {
      code: 'm1.6',
      title: 'Introductory Statement and General Investigational Plan',
      parentCode: 'm1',
      module: 'M1',
      depth: 1,
      pyramidTaskId: 'phase3.intro_statement',
      required: true,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'ai_draft',
      aiDraftable: true,
      role: 'medical_writer',
      regulatoryRef: '21 CFR 312.23(a)(3)',
      description:
        'Brief introductory statement plus general investigational plan for the ensuing year.',
      estimatedHours: 8,
      contextOfUse: 'm1-6',
      children: [
        {
          code: 'm1.6.1',
          title: 'Introductory Statement',
          parentCode: 'm1.6',
          module: 'M1',
          depth: 2,
          pyramidTaskId: 'phase3.intro_statement',
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'medical_writer',
          regulatoryRef: '21 CFR 312.23(a)(3)(i)',
          description:
            'Name of drug, active ingredients, pharmacological class, structural formula, dosage form/route, broad objectives.',
          estimatedHours: 4,
          contextOfUse: 'm1-6-1',
        },
        {
          code: 'm1.6.2',
          title: 'General Investigational Plan',
          parentCode: 'm1.6',
          module: 'M1',
          depth: 2,
          pyramidTaskId: 'phase3.general_plan',
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'medical_writer',
          regulatoryRef: '21 CFR 312.23(a)(3)(iv)',
          description:
            'Rationale, indication, approach, planned studies for ensuing year, anticipated risks.',
          estimatedHours: 4,
          contextOfUse: 'm1-6-2',
        },
      ],
    },
    {
      code: 'm1.7',
      title: "Investigator's Brochure",
      parentCode: 'm1',
      module: 'M1',
      depth: 1,
      pyramidTaskId: 'phase4.ib_finalize',
      required: true,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'ai_draft',
      aiDraftable: true,
      role: 'medical_writer',
      regulatoryRef: '21 CFR 312.23(a)(5)',
      description:
        "Investigator's Brochure containing nonclinical and clinical data available to investigators.",
      estimatedHours: 20,
      contextOfUse: 'm1-7',
    },
    {
      code: 'm1.8',
      title: 'Previous Human Experience',
      parentCode: 'm1',
      module: 'M1',
      depth: 1,
      pyramidTaskId: null,
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'ai_draft',
      aiDraftable: true,
      role: 'medical_writer',
      regulatoryRef: '21 CFR 312.23(a)(4)',
      description:
        'Summary of previous human experience with the drug (if marketed elsewhere or investigated in other countries).',
      estimatedHours: 6,
      contextOfUse: 'm1-8',
    },
    {
      code: 'm1.9',
      title: 'Environmental Assessment or Claim of Categorical Exclusion',
      parentCode: 'm1',
      module: 'M1',
      depth: 1,
      pyramidTaskId: 'phase3.env_assessment',
      required: true,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'template_fill',
      aiDraftable: true,
      role: 'ra_associate',
      regulatoryRef: '21 CFR 25.31',
      description:
        'Environmental assessment per NEPA or claim of categorical exclusion under 21 CFR 25.31(e).',
      estimatedHours: 2,
      contextOfUse: 'm1-9',
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// MODULE 2 — COMMON TECHNICAL DOCUMENT SUMMARIES
// ICH M4, 21 CFR 312.23(a)(8-11)
// ═══════════════════════════════════════════════════════════════════════════════

const MODULE_2: INDSection = {
  code: 'm2',
  title: 'Module 2: CTD Summaries',
  parentCode: null,
  module: 'M2',
  depth: 0,
  pyramidTaskId: null,
  required: true,
  requiredForAmendment: false,
  format: 'pdf',
  authoringMode: 'manual',
  aiDraftable: false,
  role: 'medical_writer',
  regulatoryRef: 'ICH M4',
  description:
    'Common Technical Document overviews and summaries covering Quality, Nonclinical, and Clinical.',
  estimatedHours: 0,
  contextOfUse: 'm2',
  children: [
    {
      code: 'm2.2',
      title: 'Introduction to the CTD',
      parentCode: 'm2',
      module: 'M2',
      depth: 1,
      pyramidTaskId: null,
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'ai_draft',
      aiDraftable: true,
      role: 'medical_writer',
      regulatoryRef: 'ICH M4',
      description: 'Brief overview of the drug and development program.',
      estimatedHours: 2,
      contextOfUse: 'm2-2',
    },
    {
      code: 'm2.3',
      title: 'Quality Overall Summary',
      parentCode: 'm2',
      module: 'M2',
      depth: 1,
      pyramidTaskId: 'phase6.cmc_review',
      required: true,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'ai_draft',
      aiDraftable: true,
      role: 'cmc_lead',
      regulatoryRef: 'ICH M4Q(R1)',
      description: 'Summary of Module 3 CMC data: drug substance, drug product, appendices.',
      estimatedHours: 16,
      contextOfUse: 'm2-3',
      children: [
        {
          code: 'm2.3.S',
          title: 'Drug Substance',
          parentCode: 'm2.3',
          module: 'M2',
          depth: 2,
          pyramidTaskId: 'phase6.drug_substance',
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'cmc_lead',
          regulatoryRef: 'ICH M4Q S',
          description: 'Summary of drug substance information.',
          estimatedHours: 0,
          contextOfUse: 'm2-3-s',
          children: [
            {
              code: 'm2.3.S.1',
              title: 'General Information',
              parentCode: 'm2.3.S',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'ai_draft',
              aiDraftable: true,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q S.1',
              description: 'Nomenclature, structure, general properties.',
              estimatedHours: 2,
              contextOfUse: 'm2-3-s-1',
            },
            {
              code: 'm2.3.S.2',
              title: 'Manufacture',
              parentCode: 'm2.3.S',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'ai_draft',
              aiDraftable: true,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q S.2',
              description: 'Manufacturer, description of manufacturing process and controls.',
              estimatedHours: 3,
              contextOfUse: 'm2-3-s-2',
            },
            {
              code: 'm2.3.S.3',
              title: 'Characterization',
              parentCode: 'm2.3.S',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'ai_draft',
              aiDraftable: true,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q S.3',
              description: 'Elucidation of structure and impurities.',
              estimatedHours: 2,
              contextOfUse: 'm2-3-s-3',
            },
            {
              code: 'm2.3.S.4',
              title: 'Control of Drug Substance',
              parentCode: 'm2.3.S',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'ai_draft',
              aiDraftable: true,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q S.4',
              description: 'Specification, analytical procedures, batch analyses.',
              estimatedHours: 3,
              contextOfUse: 'm2-3-s-4',
            },
            {
              code: 'm2.3.S.5',
              title: 'Reference Standards',
              parentCode: 'm2.3.S',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'manual',
              aiDraftable: false,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q S.5',
              description: 'Reference standards or materials.',
              estimatedHours: 1,
              contextOfUse: 'm2-3-s-5',
            },
            {
              code: 'm2.3.S.6',
              title: 'Container Closure System',
              parentCode: 'm2.3.S',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'manual',
              aiDraftable: false,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q S.6',
              description: 'Description of container closure system.',
              estimatedHours: 1,
              contextOfUse: 'm2-3-s-6',
            },
            {
              code: 'm2.3.S.7',
              title: 'Stability',
              parentCode: 'm2.3.S',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'data_import',
              aiDraftable: true,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q S.7',
              description: 'Stability summary, protocols, results.',
              estimatedHours: 3,
              contextOfUse: 'm2-3-s-7',
            },
          ],
        },
        {
          code: 'm2.3.P',
          title: 'Drug Product',
          parentCode: 'm2.3',
          module: 'M2',
          depth: 2,
          pyramidTaskId: 'phase6.drug_product',
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'cmc_lead',
          regulatoryRef: 'ICH M4Q P',
          description: 'Summary of drug product information.',
          estimatedHours: 0,
          contextOfUse: 'm2-3-p',
          children: [
            {
              code: 'm2.3.P.1',
              title: 'Description and Composition',
              parentCode: 'm2.3.P',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'ai_draft',
              aiDraftable: true,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q P.1',
              description: 'Description of dosage form, composition, type of container.',
              estimatedHours: 2,
              contextOfUse: 'm2-3-p-1',
            },
            {
              code: 'm2.3.P.2',
              title: 'Pharmaceutical Development',
              parentCode: 'm2.3.P',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'ai_draft',
              aiDraftable: true,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q P.2',
              description: 'Development studies, formulation rationale.',
              estimatedHours: 4,
              contextOfUse: 'm2-3-p-2',
            },
            {
              code: 'm2.3.P.3',
              title: 'Manufacture',
              parentCode: 'm2.3.P',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'ai_draft',
              aiDraftable: true,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q P.3',
              description: 'Manufacturers, batch formula, manufacturing process.',
              estimatedHours: 3,
              contextOfUse: 'm2-3-p-3',
            },
            {
              code: 'm2.3.P.4',
              title: 'Control of Excipients',
              parentCode: 'm2.3.P',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'manual',
              aiDraftable: false,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q P.4',
              description: 'Excipient specifications and analytical procedures.',
              estimatedHours: 2,
              contextOfUse: 'm2-3-p-4',
            },
            {
              code: 'm2.3.P.5',
              title: 'Control of Drug Product',
              parentCode: 'm2.3.P',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'ai_draft',
              aiDraftable: true,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q P.5',
              description: 'Specifications, analytical procedures, batch analyses.',
              estimatedHours: 3,
              contextOfUse: 'm2-3-p-5',
            },
            {
              code: 'm2.3.P.6',
              title: 'Reference Standards',
              parentCode: 'm2.3.P',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: false,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'manual',
              aiDraftable: false,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q P.6',
              description: 'Reference standards for drug product testing.',
              estimatedHours: 1,
              contextOfUse: 'm2-3-p-6',
            },
            {
              code: 'm2.3.P.7',
              title: 'Container Closure System',
              parentCode: 'm2.3.P',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'manual',
              aiDraftable: false,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q P.7',
              description: 'Container closure system description and suitability.',
              estimatedHours: 1,
              contextOfUse: 'm2-3-p-7',
            },
            {
              code: 'm2.3.P.8',
              title: 'Stability',
              parentCode: 'm2.3.P',
              module: 'M2',
              depth: 3,
              pyramidTaskId: null,
              required: true,
              requiredForAmendment: false,
              format: 'pdf',
              authoringMode: 'data_import',
              aiDraftable: true,
              role: 'cmc_lead',
              regulatoryRef: 'ICH M4Q P.8',
              description: 'Drug product stability summary, protocols, results.',
              estimatedHours: 3,
              contextOfUse: 'm2-3-p-8',
            },
          ],
        },
        {
          code: 'm2.3.A',
          title: 'Appendices',
          parentCode: 'm2.3',
          module: 'M2',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'manual',
          aiDraftable: false,
          role: 'cmc_lead',
          regulatoryRef: 'ICH M4Q A',
          description: 'Facilities, adventitious agents, novel excipients.',
          estimatedHours: 4,
          contextOfUse: 'm2-3-a',
        },
      ],
    },
    {
      code: 'm2.4',
      title: 'Nonclinical Overview',
      parentCode: 'm2',
      module: 'M2',
      depth: 1,
      pyramidTaskId: 'phase4.nonclinical_summary',
      required: true,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'ai_draft',
      aiDraftable: true,
      role: 'toxicologist',
      regulatoryRef: 'ICH M4S(R2)',
      description: 'Integrated overview of nonclinical evaluation strategy and findings.',
      estimatedHours: 10,
      contextOfUse: 'm2-4',
    },
    {
      code: 'm2.5',
      title: 'Clinical Overview',
      parentCode: 'm2',
      module: 'M2',
      depth: 1,
      pyramidTaskId: 'phase4.clinical_summary',
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'ai_draft',
      aiDraftable: true,
      role: 'clinical_lead',
      regulatoryRef: 'ICH M4E(R2)',
      description:
        'Critical assessment of clinical data (typically for NDA; optional for initial IND).',
      estimatedHours: 8,
      contextOfUse: 'm2-5',
    },
    {
      code: 'm2.6',
      title: 'Nonclinical Written and Tabulated Summaries',
      parentCode: 'm2',
      module: 'M2',
      depth: 1,
      pyramidTaskId: 'phase7.integrated_summary',
      required: true,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'ai_draft',
      aiDraftable: true,
      role: 'toxicologist',
      regulatoryRef: 'ICH M4S(R2)',
      description:
        'Written summaries of pharmacology, PK, and toxicology plus tabulated summaries.',
      estimatedHours: 16,
      contextOfUse: 'm2-6',
      children: [
        {
          code: 'm2.6.1',
          title: 'Introduction',
          parentCode: 'm2.6',
          module: 'M2',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'toxicologist',
          regulatoryRef: 'ICH M4S',
          description: 'Overview of nonclinical testing strategy.',
          estimatedHours: 2,
          contextOfUse: 'm2-6-1',
        },
        {
          code: 'm2.6.2',
          title: 'Pharmacology Written Summary',
          parentCode: 'm2.6',
          module: 'M2',
          depth: 2,
          pyramidTaskId: 'phase7.pharm_summary',
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'toxicologist',
          regulatoryRef: 'ICH M4S',
          description: 'Primary and secondary pharmacodynamics, safety pharmacology.',
          estimatedHours: 4,
          contextOfUse: 'm2-6-2',
        },
        {
          code: 'm2.6.3',
          title: 'Pharmacology Tabulated Summary',
          parentCode: 'm2.6',
          module: 'M2',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH M4S',
          description: 'Tabulated pharmacology study results.',
          estimatedHours: 2,
          contextOfUse: 'm2-6-3',
        },
        {
          code: 'm2.6.4',
          title: 'Pharmacokinetics Written Summary',
          parentCode: 'm2.6',
          module: 'M2',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'clinical_pharmacology',
          regulatoryRef: 'ICH M4S',
          description: 'Absorption, distribution, metabolism, excretion summary.',
          estimatedHours: 4,
          contextOfUse: 'm2-6-4',
        },
        {
          code: 'm2.6.5',
          title: 'Pharmacokinetics Tabulated Summary',
          parentCode: 'm2.6',
          module: 'M2',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH M4S',
          description: 'Tabulated PK study results.',
          estimatedHours: 2,
          contextOfUse: 'm2-6-5',
        },
        {
          code: 'm2.6.6',
          title: 'Toxicology Written Summary',
          parentCode: 'm2.6',
          module: 'M2',
          depth: 2,
          pyramidTaskId: 'phase7.tox_summary',
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'toxicologist',
          regulatoryRef: 'ICH M4S',
          description:
            'Single/repeat dose, genotoxicity, carcinogenicity, reproductive toxicity summaries.',
          estimatedHours: 6,
          contextOfUse: 'm2-6-6',
        },
        {
          code: 'm2.6.7',
          title: 'Toxicology Tabulated Summary',
          parentCode: 'm2.6',
          module: 'M2',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH M4S',
          description: 'Tabulated toxicology study results.',
          estimatedHours: 2,
          contextOfUse: 'm2-6-7',
        },
      ],
    },
    {
      code: 'm2.7',
      title: 'Clinical Summary',
      parentCode: 'm2',
      module: 'M2',
      depth: 1,
      pyramidTaskId: 'phase4.clinical_summary',
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'ai_draft',
      aiDraftable: true,
      role: 'clinical_lead',
      regulatoryRef: 'ICH M4E(R2)',
      description:
        'Clinical summary including biopharmaceutics, clinical pharmacology, efficacy, safety (typically NDA; limited for initial IND).',
      estimatedHours: 12,
      contextOfUse: 'm2-7',
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// MODULE 3 — QUALITY (CMC)
// ICH M4Q(R1), 21 CFR 312.23(a)(7)
// ═══════════════════════════════════════════════════════════════════════════════

const MODULE_3: INDSection = {
  code: 'm3',
  title: 'Module 3: Quality',
  parentCode: null,
  module: 'M3',
  depth: 0,
  pyramidTaskId: null,
  required: true,
  requiredForAmendment: true,
  format: 'pdf',
  authoringMode: 'manual',
  aiDraftable: false,
  role: 'cmc_lead',
  regulatoryRef: '21 CFR 312.23(a)(7)',
  description:
    'Chemistry, manufacturing, and controls (CMC) data for drug substance and drug product.',
  estimatedHours: 0,
  contextOfUse: 'm3',
  children: [
    {
      code: 'm3.2.S',
      title: 'Drug Substance',
      parentCode: 'm3',
      module: 'M3',
      depth: 1,
      pyramidTaskId: 'phase6.drug_substance',
      required: true,
      requiredForAmendment: true,
      format: 'pdf',
      authoringMode: 'ai_draft',
      aiDraftable: true,
      role: 'cmc_lead',
      regulatoryRef: 'ICH M4Q S',
      description: 'Full drug substance CMC data.',
      estimatedHours: 0,
      contextOfUse: 'm3-2-s',
      children: [
        {
          code: 'm3.2.S.1',
          title: 'General Information',
          parentCode: 'm3.2.S',
          module: 'M3',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'cmc_lead',
          regulatoryRef: 'ICH Q6A/Q6B',
          description: 'Nomenclature, structure, general properties of the drug substance.',
          estimatedHours: 3,
          contextOfUse: 'm3-2-s-1',
        },
        {
          code: 'm3.2.S.2',
          title: 'Manufacture',
          parentCode: 'm3.2.S',
          module: 'M3',
          depth: 2,
          pyramidTaskId: 'phase6.manufacturing',
          required: true,
          requiredForAmendment: true,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'cmc_lead',
          regulatoryRef: 'ICH Q7',
          description:
            'Manufacturer info, description of process. Process flow diagram, controls, equipment.',
          estimatedHours: 8,
          contextOfUse: 'm3-2-s-2',
        },
        {
          code: 'm3.2.S.3',
          title: 'Characterization',
          parentCode: 'm3.2.S',
          module: 'M3',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'cmc_lead',
          regulatoryRef: 'ICH Q6A/Q6B',
          description: 'Structural elucidation, impurity characterization.',
          estimatedHours: 4,
          contextOfUse: 'm3-2-s-3',
        },
        {
          code: 'm3.2.S.4',
          title: 'Control of Drug Substance',
          parentCode: 'm3.2.S',
          module: 'M3',
          depth: 2,
          pyramidTaskId: 'phase6.control_strategy',
          required: true,
          requiredForAmendment: true,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'cmc_lead',
          regulatoryRef: 'ICH Q6A',
          description:
            'Specifications, analytical procedures, validation, batch analyses, justification.',
          estimatedHours: 6,
          contextOfUse: 'm3-2-s-4',
        },
        {
          code: 'm3.2.S.5',
          title: 'Reference Standards',
          parentCode: 'm3.2.S',
          module: 'M3',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'manual',
          aiDraftable: false,
          role: 'cmc_lead',
          regulatoryRef: 'ICH M4Q',
          description: 'Reference standards or materials used for testing.',
          estimatedHours: 1,
          contextOfUse: 'm3-2-s-5',
        },
        {
          code: 'm3.2.S.6',
          title: 'Container Closure System',
          parentCode: 'm3.2.S',
          module: 'M3',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'manual',
          aiDraftable: false,
          role: 'cmc_lead',
          regulatoryRef: 'ICH M4Q',
          description: 'Container closure system for drug substance storage.',
          estimatedHours: 1,
          contextOfUse: 'm3-2-s-6',
        },
        {
          code: 'm3.2.S.7',
          title: 'Stability',
          parentCode: 'm3.2.S',
          module: 'M3',
          depth: 2,
          pyramidTaskId: 'phase6.stability',
          required: true,
          requiredForAmendment: true,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: true,
          role: 'cmc_lead',
          regulatoryRef: 'ICH Q1A/Q1B',
          description: 'Stability summary, post-approval stability protocol, stability data.',
          estimatedHours: 6,
          contextOfUse: 'm3-2-s-7',
        },
      ],
    },
    {
      code: 'm3.2.P',
      title: 'Drug Product',
      parentCode: 'm3',
      module: 'M3',
      depth: 1,
      pyramidTaskId: 'phase6.drug_product',
      required: true,
      requiredForAmendment: true,
      format: 'pdf',
      authoringMode: 'ai_draft',
      aiDraftable: true,
      role: 'cmc_lead',
      regulatoryRef: 'ICH M4Q P',
      description: 'Full drug product CMC data.',
      estimatedHours: 0,
      contextOfUse: 'm3-2-p',
      children: [
        {
          code: 'm3.2.P.1',
          title: 'Description and Composition',
          parentCode: 'm3.2.P',
          module: 'M3',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'cmc_lead',
          regulatoryRef: 'ICH M4Q P.1',
          description:
            'Dosage form description, composition including overages, formulation development.',
          estimatedHours: 3,
          contextOfUse: 'm3-2-p-1',
        },
        {
          code: 'm3.2.P.2',
          title: 'Pharmaceutical Development',
          parentCode: 'm3.2.P',
          module: 'M3',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'cmc_lead',
          regulatoryRef: 'ICH Q8',
          description:
            'Formulation development, manufacturing process development, container closure selection.',
          estimatedHours: 6,
          contextOfUse: 'm3-2-p-2',
        },
        {
          code: 'm3.2.P.3',
          title: 'Manufacture',
          parentCode: 'm3.2.P',
          module: 'M3',
          depth: 2,
          pyramidTaskId: 'phase6.manufacturing',
          required: true,
          requiredForAmendment: true,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'cmc_lead',
          regulatoryRef: 'ICH Q7',
          description:
            'Manufacturers, batch formula, manufacturing process flow, in-process controls.',
          estimatedHours: 6,
          contextOfUse: 'm3-2-p-3',
        },
        {
          code: 'm3.2.P.4',
          title: 'Control of Excipients',
          parentCode: 'm3.2.P',
          module: 'M3',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'manual',
          aiDraftable: false,
          role: 'cmc_lead',
          regulatoryRef: 'ICH M4Q P.4',
          description:
            'Excipient specifications, analytical procedures, human/animal origin excipients.',
          estimatedHours: 3,
          contextOfUse: 'm3-2-p-4',
        },
        {
          code: 'm3.2.P.5',
          title: 'Control of Drug Product',
          parentCode: 'm3.2.P',
          module: 'M3',
          depth: 2,
          pyramidTaskId: 'phase6.control_strategy',
          required: true,
          requiredForAmendment: true,
          format: 'pdf',
          authoringMode: 'ai_draft',
          aiDraftable: true,
          role: 'cmc_lead',
          regulatoryRef: 'ICH Q6A',
          description: 'Specifications, analytical procedures, validation, batch analyses.',
          estimatedHours: 5,
          contextOfUse: 'm3-2-p-5',
        },
        {
          code: 'm3.2.P.6',
          title: 'Reference Standards',
          parentCode: 'm3.2.P',
          module: 'M3',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'manual',
          aiDraftable: false,
          role: 'cmc_lead',
          regulatoryRef: 'ICH M4Q P.6',
          description: 'Reference standards for drug product testing.',
          estimatedHours: 1,
          contextOfUse: 'm3-2-p-6',
        },
        {
          code: 'm3.2.P.7',
          title: 'Container Closure System',
          parentCode: 'm3.2.P',
          module: 'M3',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'manual',
          aiDraftable: false,
          role: 'cmc_lead',
          regulatoryRef: 'ICH M4Q P.7',
          description: 'Description and suitability of primary packaging for drug product.',
          estimatedHours: 2,
          contextOfUse: 'm3-2-p-7',
        },
        {
          code: 'm3.2.P.8',
          title: 'Stability',
          parentCode: 'm3.2.P',
          module: 'M3',
          depth: 2,
          pyramidTaskId: 'phase6.stability',
          required: true,
          requiredForAmendment: true,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: true,
          role: 'cmc_lead',
          regulatoryRef: 'ICH Q1A/Q5C',
          description: 'Drug product stability summary, protocols, accelerated and long-term data.',
          estimatedHours: 6,
          contextOfUse: 'm3-2-p-8',
        },
      ],
    },
    {
      code: 'm3.2.A',
      title: 'Appendices',
      parentCode: 'm3',
      module: 'M3',
      depth: 1,
      pyramidTaskId: null,
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'manual',
      aiDraftable: false,
      role: 'cmc_lead',
      regulatoryRef: 'ICH M4Q',
      description: 'Facilities and equipment, adventitious agents, novel excipients.',
      estimatedHours: 4,
      contextOfUse: 'm3-2-a',
    },
    {
      code: 'm3.2.R',
      title: 'Regional Information',
      parentCode: 'm3',
      module: 'M3',
      depth: 1,
      pyramidTaskId: null,
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'manual',
      aiDraftable: false,
      role: 'ra_associate',
      regulatoryRef: 'FDA Guidance',
      description: 'FDA-specific regional CMC information.',
      estimatedHours: 2,
      contextOfUse: 'm3-2-r',
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// MODULE 4 — NONCLINICAL STUDY REPORTS
// ICH M4S(R2), 21 CFR 312.23(a)(8)
// ═══════════════════════════════════════════════════════════════════════════════

const MODULE_4: INDSection = {
  code: 'm4',
  title: 'Module 4: Nonclinical Study Reports',
  parentCode: null,
  module: 'M4',
  depth: 0,
  pyramidTaskId: null,
  required: true,
  requiredForAmendment: false,
  format: 'pdf',
  authoringMode: 'manual',
  aiDraftable: false,
  role: 'toxicologist',
  regulatoryRef: '21 CFR 312.23(a)(8)',
  description: 'Full nonclinical study reports: pharmacology, pharmacokinetics, toxicology.',
  estimatedHours: 0,
  contextOfUse: 'm4',
  children: [
    {
      code: 'm4.2.1',
      title: 'Pharmacology',
      parentCode: 'm4',
      module: 'M4',
      depth: 1,
      pyramidTaskId: 'phase7.pharm_summary',
      required: true,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'data_import',
      aiDraftable: true,
      role: 'toxicologist',
      regulatoryRef: 'ICH S7A/S7B',
      description: 'Primary/secondary pharmacodynamics and safety pharmacology study reports.',
      estimatedHours: 8,
      contextOfUse: 'm4-2-1',
      children: [
        {
          code: 'm4.2.1.1',
          title: 'Primary Pharmacodynamics',
          parentCode: 'm4.2.1',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH S7A',
          description: 'Studies on mode of action/effects related to desired therapeutic target.',
          estimatedHours: 3,
          contextOfUse: 'm4-2-1-1',
        },
        {
          code: 'm4.2.1.2',
          title: 'Secondary Pharmacodynamics',
          parentCode: 'm4.2.1',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH S7A',
          description: 'Studies on effects unrelated to desired therapeutic target.',
          estimatedHours: 2,
          contextOfUse: 'm4-2-1-2',
        },
        {
          code: 'm4.2.1.3',
          title: 'Safety Pharmacology',
          parentCode: 'm4.2.1',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH S7A/S7B',
          description: 'Core battery: cardiovascular, CNS, respiratory safety studies.',
          estimatedHours: 3,
          contextOfUse: 'm4-2-1-3',
        },
        {
          code: 'm4.2.1.4',
          title: 'Pharmacodynamic Drug Interactions',
          parentCode: 'm4.2.1',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH M3(R2)',
          description: 'Nonclinical pharmacodynamic drug interaction studies.',
          estimatedHours: 2,
          contextOfUse: 'm4-2-1-4',
        },
      ],
    },
    {
      code: 'm4.2.2',
      title: 'Pharmacokinetics',
      parentCode: 'm4',
      module: 'M4',
      depth: 1,
      pyramidTaskId: 'phase4.pk_pd',
      required: true,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'data_import',
      aiDraftable: true,
      role: 'clinical_pharmacology',
      regulatoryRef: 'ICH S3A/S3B',
      description: 'ADME study reports, analytical methods, and PK drug interactions.',
      estimatedHours: 10,
      contextOfUse: 'm4-2-2',
      children: [
        {
          code: 'm4.2.2.1',
          title: 'Analytical Methods and Validation',
          parentCode: 'm4.2.2',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'clinical_pharmacology',
          regulatoryRef: 'ICH M3(R2)',
          description: 'Bioanalytical method validation for nonclinical PK studies.',
          estimatedHours: 2,
          contextOfUse: 'm4-2-2-1',
        },
        {
          code: 'm4.2.2.2',
          title: 'Absorption',
          parentCode: 'm4.2.2',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'clinical_pharmacology',
          regulatoryRef: 'ICH S3A',
          description: 'Absorption studies in animal species.',
          estimatedHours: 2,
          contextOfUse: 'm4-2-2-2',
        },
        {
          code: 'm4.2.2.3',
          title: 'Distribution',
          parentCode: 'm4.2.2',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'clinical_pharmacology',
          regulatoryRef: 'ICH S3B',
          description: 'Tissue distribution, plasma protein binding, whole-body autoradiography.',
          estimatedHours: 2,
          contextOfUse: 'm4-2-2-3',
        },
        {
          code: 'm4.2.2.4',
          title: 'Metabolism',
          parentCode: 'm4.2.2',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'clinical_pharmacology',
          regulatoryRef: 'ICH M3(R2)',
          description: 'In vitro and in vivo metabolism, metabolite identification.',
          estimatedHours: 2,
          contextOfUse: 'm4-2-2-4',
        },
        {
          code: 'm4.2.2.5',
          title: 'Excretion',
          parentCode: 'm4.2.2',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'clinical_pharmacology',
          regulatoryRef: 'ICH S3A',
          description: 'Urinary, fecal, biliary excretion studies.',
          estimatedHours: 1,
          contextOfUse: 'm4-2-2-5',
        },
        {
          code: 'm4.2.2.6',
          title: 'Pharmacokinetic Drug Interactions',
          parentCode: 'm4.2.2',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'clinical_pharmacology',
          regulatoryRef: 'ICH M3(R2)',
          description: 'In vitro CYP inhibition/induction and transporter studies.',
          estimatedHours: 2,
          contextOfUse: 'm4-2-2-6',
        },
      ],
    },
    {
      code: 'm4.2.3',
      title: 'Toxicology',
      parentCode: 'm4',
      module: 'M4',
      depth: 1,
      pyramidTaskId: 'phase7.tox_summary',
      required: true,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'data_import',
      aiDraftable: true,
      role: 'toxicologist',
      regulatoryRef: 'ICH M3(R2)/S2(R1)/S5(R3)',
      description:
        'Complete toxicology study reports: acute, repeat-dose, genotoxicity, reproductive, special.',
      estimatedHours: 20,
      contextOfUse: 'm4-2-3',
      children: [
        {
          code: 'm4.2.3.1',
          title: 'Single-Dose Toxicity',
          parentCode: 'm4.2.3',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH M3(R2)',
          description: 'Acute toxicity studies in rodent and non-rodent species.',
          estimatedHours: 2,
          contextOfUse: 'm4-2-3-1',
        },
        {
          code: 'm4.2.3.2',
          title: 'Repeat-Dose Toxicity',
          parentCode: 'm4.2.3',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH M3(R2)',
          description:
            'Sub-acute and chronic repeat-dose toxicity studies (28-day, 90-day minimum for Phase I).',
          estimatedHours: 6,
          contextOfUse: 'm4-2-3-2',
        },
        {
          code: 'm4.2.3.3',
          title: 'Genotoxicity',
          parentCode: 'm4.2.3',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: true,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH S2(R1)',
          description:
            'Standard battery: Ames test, in vitro chromosomal aberration, in vivo micronucleus.',
          estimatedHours: 3,
          contextOfUse: 'm4-2-3-3',
        },
        {
          code: 'm4.2.3.4',
          title: 'Carcinogenicity',
          parentCode: 'm4.2.3',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH S1A/S1B',
          description: 'Carcinogenicity studies (typically not required for initial IND).',
          estimatedHours: 2,
          contextOfUse: 'm4-2-3-4',
        },
        {
          code: 'm4.2.3.5',
          title: 'Reproductive and Developmental Toxicity',
          parentCode: 'm4.2.3',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH S5(R3)',
          description: 'Fertility, embryo-fetal development, pre/postnatal development studies.',
          estimatedHours: 4,
          contextOfUse: 'm4-2-3-5',
        },
        {
          code: 'm4.2.3.6',
          title: 'Local Tolerance',
          parentCode: 'm4.2.3',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH M3(R2)',
          description: 'Local tolerance studies (for non-oral or injection routes).',
          estimatedHours: 1,
          contextOfUse: 'm4-2-3-6',
        },
        {
          code: 'm4.2.3.7',
          title: 'Other Toxicity Studies',
          parentCode: 'm4.2.3',
          module: 'M4',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: false,
          role: 'toxicologist',
          regulatoryRef: 'ICH M3(R2)',
          description:
            'Immunotoxicity, juvenile toxicity, phototoxicity, dependence studies as applicable.',
          estimatedHours: 2,
          contextOfUse: 'm4-2-3-7',
        },
      ],
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// MODULE 5 — CLINICAL STUDY REPORTS
// ICH E3, 21 CFR 312.23(a)(6)
// ═══════════════════════════════════════════════════════════════════════════════

const MODULE_5: INDSection = {
  code: 'm5',
  title: 'Module 5: Clinical Study Reports',
  parentCode: null,
  module: 'M5',
  depth: 0,
  pyramidTaskId: null,
  required: true,
  requiredForAmendment: false,
  format: 'pdf',
  authoringMode: 'manual',
  aiDraftable: false,
  role: 'clinical_lead',
  regulatoryRef: '21 CFR 312.23(a)(6)',
  description:
    'Clinical protocols and study reports. For initial IND: the Phase 1 protocol plus any available clinical data.',
  estimatedHours: 0,
  contextOfUse: 'm5',
  children: [
    {
      code: 'm5.3.1',
      title: 'Reports of Biopharmaceutic Studies',
      parentCode: 'm5',
      module: 'M5',
      depth: 1,
      pyramidTaskId: null,
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'data_import',
      aiDraftable: false,
      role: 'clinical_pharmacology',
      regulatoryRef: 'ICH E3',
      description: 'Bioavailability, bioequivalence, in vitro-in vivo correlation studies.',
      estimatedHours: 4,
      contextOfUse: 'm5-3-1',
    },
    {
      code: 'm5.3.2',
      title: 'Reports of Studies Pertinent to Pharmacokinetics Using Human Biomaterials',
      parentCode: 'm5',
      module: 'M5',
      depth: 1,
      pyramidTaskId: null,
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'data_import',
      aiDraftable: false,
      role: 'clinical_pharmacology',
      regulatoryRef: 'ICH E3',
      description:
        'Plasma protein binding, hepatic metabolism, metabolite profiling in human tissues.',
      estimatedHours: 4,
      contextOfUse: 'm5-3-2',
    },
    {
      code: 'm5.3.3',
      title: 'Reports of Human PK Studies',
      parentCode: 'm5',
      module: 'M5',
      depth: 1,
      pyramidTaskId: 'phase4.pk_pd',
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'data_import',
      aiDraftable: false,
      role: 'clinical_pharmacology',
      regulatoryRef: 'ICH E3',
      description:
        'Healthy volunteer PK, food effect, drug interaction, renal/hepatic impairment PK studies.',
      estimatedHours: 8,
      contextOfUse: 'm5-3-3',
    },
    {
      code: 'm5.3.4',
      title: 'Reports of Human Pharmacodynamic Studies',
      parentCode: 'm5',
      module: 'M5',
      depth: 1,
      pyramidTaskId: null,
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'data_import',
      aiDraftable: false,
      role: 'clinical_pharmacology',
      regulatoryRef: 'ICH E3',
      description: 'Mechanism of action studies in humans, PK/PD modeling.',
      estimatedHours: 4,
      contextOfUse: 'm5-3-4',
    },
    {
      code: 'm5.3.5',
      title: 'Reports of Efficacy and Safety Studies',
      parentCode: 'm5',
      module: 'M5',
      depth: 1,
      pyramidTaskId: 'phase5.protocol_finalize',
      required: true,
      requiredForAmendment: true,
      format: 'pdf',
      authoringMode: 'ai_draft',
      aiDraftable: true,
      role: 'clinical_lead',
      regulatoryRef: '21 CFR 312.23(a)(6)(iii)(a)',
      description:
        'For initial IND: the Phase 1 clinical protocol. For amendments: study reports as they become available.',
      estimatedHours: 20,
      contextOfUse: 'm5-3-5',
      children: [
        {
          code: 'm5.3.5.1',
          title: 'Clinical Study Reports of Controlled Studies',
          parentCode: 'm5.3.5',
          module: 'M5',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: true,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: true,
          role: 'clinical_lead',
          regulatoryRef: 'ICH E3',
          description: 'Full clinical study reports per ICH E3 format.',
          estimatedHours: 0,
          contextOfUse: 'm5-3-5-1',
        },
        {
          code: 'm5.3.5.2',
          title: 'Clinical Study Reports of Uncontrolled Studies',
          parentCode: 'm5.3.5',
          module: 'M5',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: true,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: true,
          role: 'clinical_lead',
          regulatoryRef: 'ICH E3',
          description: 'Open-label, single-arm, or observational study reports.',
          estimatedHours: 0,
          contextOfUse: 'm5-3-5-2',
        },
        {
          code: 'm5.3.5.3',
          title: 'Reports of Analyses of Data from More than One Study',
          parentCode: 'm5.3.5',
          module: 'M5',
          depth: 2,
          pyramidTaskId: null,
          required: false,
          requiredForAmendment: false,
          format: 'pdf',
          authoringMode: 'data_import',
          aiDraftable: true,
          role: 'biostatistician',
          regulatoryRef: 'ICH E3',
          description: 'Integrated summaries, pooled analyses, meta-analyses.',
          estimatedHours: 0,
          contextOfUse: 'm5-3-5-3',
        },
      ],
    },
    {
      code: 'm5.3.6',
      title: 'Reports of Post-Marketing Experience',
      parentCode: 'm5',
      module: 'M5',
      depth: 1,
      pyramidTaskId: null,
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'data_import',
      aiDraftable: false,
      role: 'clinical_lead',
      regulatoryRef: 'ICH E3',
      description:
        'Post-marketing experience from other countries (if drug is marketed elsewhere).',
      estimatedHours: 4,
      contextOfUse: 'm5-3-6',
    },
    {
      code: 'm5.3.7',
      title: 'Case Report Forms and Individual Patient Listings',
      parentCode: 'm5',
      module: 'M5',
      depth: 1,
      pyramidTaskId: null,
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'data_import',
      aiDraftable: false,
      role: 'clinical_lead',
      regulatoryRef: '21 CFR 312.23(a)(6)(iii)(d)',
      description: 'Blank CRFs and individual patient data listings for clinical studies.',
      estimatedHours: 4,
      contextOfUse: 'm5-3-7',
    },
    {
      code: 'm5.4',
      title: 'Literature References',
      parentCode: 'm5',
      module: 'M5',
      depth: 1,
      pyramidTaskId: null,
      required: false,
      requiredForAmendment: false,
      format: 'pdf',
      authoringMode: 'manual',
      aiDraftable: false,
      role: 'medical_writer',
      regulatoryRef: 'ICH M4',
      description: 'Published literature used to support the clinical section.',
      estimatedHours: 4,
      contextOfUse: 'm5-4',
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// PACKAGE BUILDER + UTILITIES
// ═══════════════════════════════════════════════════════════════════════════════

/** Flatten a section tree into a flat list */
function flattenSections(section: INDSection): INDSection[] {
  const result: INDSection[] = [section];
  if (section.children) {
    for (const child of section.children) {
      result.push(...flattenSections(child));
    }
  }
  return result;
}

/** Count total and required sections */
function countSections(modules: INDSection[]): { total: number; required: number } {
  let total = 0;
  let required = 0;
  for (const mod of modules) {
    const flat = flattenSections(mod);
    for (const s of flat) {
      // Only count leaf or meaningful non-container sections
      if (s.estimatedHours > 0 || !s.children || s.children.length === 0) {
        total++;
        if (s.required) required++;
      }
    }
  }
  return { total, required };
}

/** Sum estimated hours across all sections */
function totalHours(modules: INDSection[]): number {
  let hours = 0;
  for (const mod of modules) {
    for (const s of flattenSections(mod)) {
      hours += s.estimatedHours;
    }
  }
  return hours;
}

/**
 * Build the complete IND eCTD Package Definition.
 * This is the single source of truth for every section in an IND filing.
 */
export function buildINDPackageDefinition(): INDPackageDefinition {
  const modules = [MODULE_1, MODULE_2, MODULE_3, MODULE_4, MODULE_5];
  const counts = countSections(modules);
  return {
    submissionType: 'IND',
    ectdVersion: '4.0',
    agency: 'FDA',
    totalSections: counts.total,
    requiredSections: counts.required,
    estimatedTotalHours: totalHours(modules),
    modules,
  };
}

/**
 * Get a flat list of all IND sections (for search, filtering, status tracking).
 */
export function getAllINDSections(): INDSection[] {
  const pkg = buildINDPackageDefinition();
  return pkg.modules.flatMap(flattenSections);
}

/**
 * Get all sections that Lumen Cortex can AI-draft.
 */
export function getAIDraftableSections(): INDSection[] {
  return getAllINDSections().filter(s => s.aiDraftable);
}

/**
 * Get sections required for initial IND filing.
 */
export function getRequiredSections(): INDSection[] {
  return getAllINDSections().filter(s => s.required);
}

/**
 * Lookup a section by its eCTD code.
 */
export function getSectionByCode(code: string): INDSection | undefined {
  return getAllINDSections().find(s => s.code === code);
}

/**
 * Get sections mapped to a specific pyramid task.
 */
export function getSectionsForPyramidTask(taskId: string): INDSection[] {
  return getAllINDSections().filter(s => s.pyramidTaskId === taskId);
}

/**
 * Bridge: Given an IND pyramid task, return the eCTD sections it produces.
 * This is the key connector between the workflow engine and the eCTD structure.
 */
export function pyramidToECTDMap(): Map<string, INDSection[]> {
  const map = new Map<string, INDSection[]>();
  for (const section of getAllINDSections()) {
    if (section.pyramidTaskId) {
      const existing = map.get(section.pyramidTaskId) || [];
      existing.push(section);
      map.set(section.pyramidTaskId, existing);
    }
  }
  return map;
}

/**
 * Get the module-level progress summary for an IND submission.
 * Takes a map of section code → status and returns per-module stats.
 */
export function getModuleProgress(statusMap: Map<string, SectionStatus>): Array<{
  module: CTDModule;
  title: string;
  total: number;
  completed: number;
  inProgress: number;
  percentage: number;
}> {
  const pkg = buildINDPackageDefinition();
  return pkg.modules.map(mod => {
    const sections = flattenSections(mod).filter(
      s => s.estimatedHours > 0 || !s.children || s.children.length === 0
    );
    let completed = 0;
    let inProgress = 0;
    for (const s of sections) {
      const status = statusMap.get(s.code);
      if (status === 'approved' || status === 'signed' || status === 'locked') completed++;
      else if (status && status !== 'not_started') inProgress++;
    }
    return {
      module: mod.module,
      title: mod.title,
      total: sections.length,
      completed,
      inProgress,
      percentage: sections.length > 0 ? Math.round((completed / sections.length) * 100) : 0,
    };
  });
}
