/**
 * eCTD qualification harness.
 *
 * Proves the publishing engine against real validators, per the qualification
 * contract: for each supported region + version —
 *   1. generate a golden package (deterministic fixtures);
 *   2. run the accepted validators — xmllint (well-formedness always; DTD/XSD
 *      when the licensed DTD/RPS schema is vendored), the FDA-criteria subset,
 *      the configured external eValidator (LORENZ) when present, and the RPS
 *      model validator for v4.0;
 *   3. preserve the report, recording the EXACT spec version qualified against;
 *   4. exercise a lifecycle sequence (original → amendment) with
 *      replace / delete / append (v3.2.2) or revise (v4.0);
 *   5. reopen the produced ZIP and re-verify EVERY checksum + per-document
 *      integrity.
 *
 * Deterministic and reproducible. Writes one JSON report per run.
 *
 * @module server/services/ectd/qualification/qualify
 */

import { promises as fs } from 'fs';
import * as os from 'os';
import * as path from 'path';
import { createHash } from 'crypto';
import JSZip from 'jszip';
import { packageEctdSubmission } from '../../submission-gateways/regional-packager';
// Region is declared in the gateway's types module; regional-packager only
// imports it (TS2459 if re-imported from there).
import type { Region } from '../../submission-gateways/types';
import { packageRpsSubmission, validateRpsMessage } from '../ectd4';
import {
  checkWellFormed,
  validateAgainstDtd,
  validateAgainstXsd,
  isXmllintAvailable,
} from '../xml-validator';
import { validateFdaCriteria, fdaCriteriaFallbackEnabled } from '../external-validator/fda-criteria-adapter';
import { resolveExternalValidator, runExternalValidation } from '../external-validator';
import type { EctdRegion } from '../external-validator/types';
import { verifyChecksumManifest } from '../checksum-manifest';
import { resolveDtdDir, listVendoredDtds } from '../dtd-bundler';
import { resolveSchemaDir, RPS_MESSAGE_XSD } from '../schema-bundler';
import {
  writeGoldenLeaves,
  v3GoldenInput,
  v4GoldenMessage,
} from './golden-fixtures';

/** Exact spec versions each qualification run is measured against. */
export const SPEC_VERSIONS = {
  'v3.2.2': {
    ichBackbone: 'ICH eCTD v3.2.2',
    fdaRegionalDtd: 'FDA US Regional DTD v3.3 (eCTD Backbone Files Specification for Module 1)',
    validationCriteria: 'FDA Specifications for eCTD Validation Criteria v4.5 (2025-10-01)',
    fileFormats: 'FDA Specifications for File Format Types v9.3 (2025-08-20)',
    transmission: 'FDA Transmitting eCTD Submissions v2.0 (2026-07)',
  },
  'v4.0': {
    message: 'ICH eCTD v4.0 / HL7 RPS message (PORP_IN000001UV)',
    fdaRegionalIg: 'FDA eCTD v4.0 Regional IG OID 2.16.840.1.113883.3.989.5.1.2.2.1.18.8',
    controlledVocab: 'FDA eCTD v4.0 Controlled Vocabulary Package v1.1 (2026-06)',
    validationCriteria: 'FDA Specifications for eCTD v4.0 Validation Criteria v1.5',
  },
} as const;

export type EctdVersion = keyof typeof SPEC_VERSIONS;

export interface ValidatorRunReport {
  name: string;
  ran: boolean;
  passed: boolean;
  errorCount: number;
  warningCount: number;
  /** First few messages, for the report (full findings are large). */
  sample: string[];
}

export interface ChecksumVerification {
  manifest: string;
  filesChecked: number;
  mismatches: Array<{ relPath: string; expected: string; actual: string }>;
  missing: string[];
  ok: boolean;
}

export interface QualificationReport {
  id: string;
  version: EctdVersion;
  region: Region;
  specVersions: Record<string, string>;
  package: { path: string; sha256: string; sizeBytes: number };
  validators: ValidatorRunReport[];
  checksum: ChecksumVerification;
  lifecycle: {
    priorSequence: string;
    nextSequence: string;
    /** Operations OBSERVED in the emitted amendment backbone (replace/delete/
     *  append or revise) — read from the generated bytes, not hardcoded. */
    operations: string[];
    /** Of those, the superseding operations that carried a modified-file pointer
     *  at the leaf they supersede (a replace/delete must reference its target). */
    operationsWithModifiedFile: string[];
    nextPackagePassed: boolean;
    checksum: ChecksumVerification;
  };
  passed: boolean;
  ranAt: string;
  notes: string[];
}

/** Reopen a ZIP and re-verify every entry against its util/index-md5.txt line. */
async function verifyZipChecksums(zipPath: string): Promise<ChecksumVerification> {
  const buf = await fs.readFile(zipPath);
  const zip = await JSZip.loadAsync(buf);
  const manifestFile = zip.file('util/index-md5.txt') ?? zip.file('index-md5.txt');
  const result: ChecksumVerification = {
    manifest: manifestFile ? manifestFile.name : '(none)',
    filesChecked: 0,
    mismatches: [],
    missing: [],
    ok: false,
  };
  if (!manifestFile) return result;

  const manifest = await manifestFile.async('string');
  for (const line of manifest.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const sep = trimmed.indexOf('  ');
    if (sep < 0) continue;
    const expected = trimmed.slice(0, sep).trim();
    const relPath = trimmed.slice(sep + 2).trim();
    const entry = zip.file(relPath);
    if (!entry) {
      result.missing.push(relPath);
      continue;
    }
    const actual = createHash('md5').update(await entry.async('nodebuffer')).digest('hex');
    result.filesChecked += 1;
    if (actual !== expected) result.mismatches.push({ relPath, expected, actual });
  }
  result.ok = result.mismatches.length === 0 && result.missing.length === 0;
  return result;
}

function tally(name: string, ran: boolean, findings: Array<{ severity: string; message: string }>): ValidatorRunReport {
  const errors = findings.filter((f) => f.severity === 'error');
  const warnings = findings.filter((f) => f.severity === 'warning');
  return {
    name,
    ran,
    passed: ran && errors.length === 0,
    errorCount: errors.length,
    warningCount: warnings.length,
    sample: findings.slice(0, 5).map((f) => `[${f.severity}] ${f.message}`),
  };
}

/**
 * What a backbone's own DOCTYPE declares, as a discriminated result.
 *
 * The system id is relative to the backbone (index.xml → `util/dtd/…`;
 * m1/us/us-regional.xml → `../../util/dtd/…`), so it is resolved from the
 * backbone's own directory, exactly as xmllint resolves it.
 *
 * EVERY non-`declared` outcome is a DEFECT, not an absence: an eCTD backbone
 * must reference the grammar it is written to, and that reference must resolve
 * to a file the package itself ships. Collapsing them to `null` (as the first
 * cut of the per-backbone activation did) makes a packager regression — a
 * dropped DOCTYPE line — indistinguishable from a clean run.
 */
type BackboneDoctype =
  | { kind: 'declared'; absPath: string; fileName: string; systemId: string }
  /** The file was read but carries no `<!DOCTYPE …>` at all. */
  | { kind: 'no-doctype' }
  /** A DOCTYPE is present but declares no parseable `SYSTEM "…"` identifier. */
  | { kind: 'no-system-id' }
  /** The system id is an absolute URI (http:, file:, …): the grammar is fetched
   *  from outside the package, so the package is not self-contained. */
  | { kind: 'external-uri'; systemId: string }
  /** The system id resolves outside the package directory. */
  | { kind: 'outside-package'; systemId: string }
  /** The backbone itself could not be read. */
  | { kind: 'unreadable'; reason: string };

async function referencedDtd(packageDir: string, relPath: string): Promise<BackboneDoctype> {
  let xml: string;
  try {
    xml = await fs.readFile(path.join(packageDir, relPath), 'utf8');
  } catch (err) {
    return { kind: 'unreadable', reason: err instanceof Error ? err.message : String(err) };
  }
  if (!/<!DOCTYPE\s/i.test(xml)) return { kind: 'no-doctype' };
  // Stop the scan at `[` so an internal subset cannot be mistaken for a system
  // id, and accept either quote style (the packager emits double quotes; a
  // single-quoted DOCTYPE is still a valid declaration and must not read as
  // "no DTD declared").
  const m = /<!DOCTYPE[^>[]*\sSYSTEM\s+(?:"([^"]+)"|'([^']+)')/i.exec(xml);
  const systemId = m?.[1] ?? m?.[2];
  if (!systemId) return { kind: 'no-system-id' };
  if (/^[a-z][a-z0-9+.-]*:/i.test(systemId)) return { kind: 'external-uri', systemId };
  const absPath = path.resolve(path.dirname(path.join(packageDir, relPath)), systemId);
  // Containment: a system id that climbs out of the package would validate
  // against a DTD the shipped ZIP does not carry — certifying a package that is
  // not self-contained, on a build machine that happens to have the file.
  const rel = path.relative(path.resolve(packageDir), absPath);
  if (rel === '' || rel.startsWith('..') || path.isAbsolute(rel)) {
    return { kind: 'outside-package', systemId };
  }
  return { kind: 'declared', absPath, fileName: path.basename(systemId), systemId };
}

/** The error message for each non-`declared` DOCTYPE outcome. One sentence of
 *  fact, then what it means for the package. */
function doctypeDefect(relPath: string, d: Exclude<BackboneDoctype, { kind: 'declared' }>): string {
  switch (d.kind) {
    case 'no-doctype':
      return `${relPath} declares no DOCTYPE. An eCTD backbone must reference the DTD it is written to (<!DOCTYPE … SYSTEM "util/dtd/…">); DTD validity cannot be attempted without it.`;
    case 'no-system-id':
      return `${relPath} has a DOCTYPE with no parseable SYSTEM identifier, so no DTD can be resolved for it.`;
    case 'external-uri':
      return `${relPath} declares an EXTERNAL DTD (SYSTEM "${d.systemId}"): the package does not ship the grammar it references and is not self-contained.`;
    case 'outside-package':
      return `${relPath} declares SYSTEM "${d.systemId}", which resolves outside the package directory — the shipped package does not contain that DTD.`;
    case 'unreadable':
      return `${relPath} could not be read (${d.reason}), so its DOCTYPE could not be examined.`;
  }
}

export interface BackboneValidation {
  reports: ValidatorRunReport[];
  /** Set when DTD validity could NOT be attempted because the DTD this
   *  backbone's DOCTYPE names is not in the package. Reported, never silent. */
  dtdSkipped: { relPath: string; dtd: string } | null;
}

/**
 * Run xmllint well-formedness on a backbone, plus DTD validity when — and only
 * when — the DTD that backbone's OWN DOCTYPE names is present in the package.
 *
 * Activation used to be "does util/dtd/ hold any *.dtd at all?". That is
 * all-or-nothing across regions, and vendoring is not: the acquisition runbook
 * works agency by agency, so the ICH + FDA pair lands before EMA/PMDA/HC. Under
 * the old test a partial drop switched DTD validation ON for every region, and
 * xmllint --valid then reported "Validation failed: no DTD found !" against
 * each backbone whose DTD was legitimately not vendored yet — rendering an
 * un-acquired artifact as a validation FAILURE and failing the whole
 * qualification. Deciding per backbone lets each region light up exactly when
 * its own DTD arrives, and says so when it has not.
 *
 * Three outcomes, three different rows — never silence:
 *   • DOCTYPE resolves to a DTD IN the package  → `xmllint DTD (…)` runs;
 *   • DOCTYPE resolves to a DTD NOT vendored yet → `dtdSkipped`, stated in the
 *     run notes (an un-acquired artifact, not a failure);
 *   • no usable DOCTYPE at all (absent, unparseable, external, or escaping the
 *     package) → a FAILING `backbone DOCTYPE (…)` row. That case is a packager
 *     regression and must fail the qualification, exactly as it did under the
 *     old all-or-nothing activation.
 *
 * Exported for the negative tests: the DOCTYPE is written by the packager, so a
 * backbone without one cannot be produced through `qualifyV3`'s inputs.
 */
export async function validateBackboneFile(packageDir: string, relPath: string): Promise<BackboneValidation> {
  const filePath = path.join(packageDir, relPath);
  const reports: ValidatorRunReport[] = [];
  const wf = await checkWellFormed(filePath, true);
  reports.push(tally(`xmllint well-formed (${relPath})`, wf.ran, wf.errors.map((m) => ({ severity: wf.valid ? 'info' : 'error', message: m }))));

  // The DOCTYPE row is ALWAYS emitted, pass or fail. A backbone that declares no
  // usable DTD is a defect and must be reported as one — never an early return
  // that leaves the report byte-identical to a clean run (which is what a
  // dropped DOCTYPE line used to look like once activation became per-backbone).
  const referenced = await referencedDtd(packageDir, relPath);
  if (referenced.kind !== 'declared') {
    reports.push(tally(`backbone DOCTYPE (${relPath})`, true, [
      { severity: 'error', message: doctypeDefect(relPath, referenced) },
    ]));
    return { reports, dtdSkipped: null };
  }
  reports.push(tally(`backbone DOCTYPE (${relPath})`, true, []));

  const dtdPresent = await fs.access(referenced.absPath).then(() => true).catch(() => false);
  if (!dtdPresent) return { reports, dtdSkipped: { relPath, dtd: referenced.fileName } };

  const dtd = await validateAgainstDtd(filePath);
  reports.push(tally(`xmllint DTD (${relPath})`, dtd.ran, dtd.valid ? [] : dtd.errors.map((m) => ({ severity: 'error', message: m }))));
  return { reports, dtdSkipped: null };
}

/**
 * Read the leaf `operation` attributes (and modified-file presence) ACTUALLY
 * emitted into a package's backbones. The qualification report states what the
 * packager produced rather than a hardcoded claim — so "test replace/delete/
 * append" is proven from the generated bytes, not asserted.
 *
 * NB: the exact cross-sequence modified-file PATH convention (grouped
 * `../../../../{app}/{seq}/…` vs sibling `../…`) is confirmed by the external
 * eValidator; here we verify the operation attributes are emitted and that a
 * superseding operation carries a modified-file pointer at all.
 */
async function readEmittedLeafOps(
  packageDir: string,
  backboneRelPaths: string[],
): Promise<Array<{ operation: string; hasModifiedFile: boolean; href: string | null }>> {
  const leaves: Array<{ operation: string; hasModifiedFile: boolean; href: string | null }> = [];
  for (const rel of backboneRelPaths) {
    let xml: string;
    try {
      xml = await fs.readFile(path.join(packageDir, rel), 'utf8');
    } catch {
      continue; // backbone absent (e.g. a region without that file) — skip
    }
    for (const tag of xml.match(/<leaf\b[^>]*>/g) ?? []) {
      const op = /\boperation="([^"]*)"/.exec(tag)?.[1];
      if (!op) continue;
      const mf = /\bmodified-file="([^"]*)"/.exec(tag)?.[1] ?? '';
      const href = /\bxlink:href="([^"]*)"/.exec(tag)?.[1] ?? null;
      leaves.push({ operation: op, hasModifiedFile: mf.length > 0, href });
    }
  }
  return leaves;
}

/**
 * The note that states exactly which backbone was NOT DTD-validated and which
 * DTD it is waiting on. A skipped check must never read as a passed one, and
 * "no DTDs at all" and "some regions' DTDs not acquired yet" are different
 * facts about the run — so they read differently.
 */
async function dtdSkipNote(skips: Array<{ relPath: string; dtd: string }>): Promise<string> {
  const vendored = await listVendoredDtds();
  const lead = vendored.length === 0
    ? 'No DTDs vendored (assets/ectd-dtd/*.dtd); '
    : `Partial DTD acquisition (${vendored.length} vendored); `;
  return (
    lead +
    `DTD *validity* is skipped for ${skips.map((sk) => `${sk.relPath} (needs ${sk.dtd})`).join(', ')} — ` +
    'that DTD is not in the package. Those backbones remain well-formed-validated. ' +
    'Drop the licensed DTD(s) into assets/ectd-dtd/ (or $ECTD_DTD_DIR) to enable it.'
  );
}

/** Qualify one region for eCTD v3.2.2. */
export async function qualifyV3(region: Region, workDir: string): Promise<QualificationReport> {
  const notes: string[] = [];
  const app = region === 'fda' ? '123456' : 'GOLDEN-APP';
  const leavesDir = path.join(workDir, `v3-${region}-leaves`);
  const paths = await writeGoldenLeaves(leavesDir);
  const outDir = path.join(workDir, `v3-${region}-out`);

  // 1. Original sequence (0000).
  const bundle = await packageEctdSubmission(v3GoldenInput({ region, sequence: '0000', applicationId: app, outputDir: outDir, paths }));
  const pkgDir = path.join(outDir, `${app}-0000-${region}`);

  // 2. Validators.
  const validators: ValidatorRunReport[] = [];
  const indexBackbone = await validateBackboneFile(pkgDir, 'index.xml');
  validators.push(...indexBackbone.reports);
  // Regional Module-1 subfolder + backbone filename per region (fda→us/eu/jp/ca).
  const m1Sub: Partial<Record<Region, string>> = { fda: 'us', ema: 'eu', pmda: 'jp', ca: 'ca' };
  const sub = m1Sub[region] ?? region;
  const regionalRel = `m1/${sub}/${sub}-regional.xml`;
  const regionalBackbone = await validateBackboneFile(pkgDir, regionalRel);
  validators.push(...regionalBackbone.reports);
  /** Backbones whose DTD validity could NOT be attempted because the DTD their
   *  own DOCTYPE names is not in the package. Stated in the notes below — a
   *  skipped check must never read as a passed one. */
  const dtdSkips = [indexBackbone.dtdSkipped, regionalBackbone.dtdSkipped]
    .filter((sk): sk is NonNullable<typeof sk> => sk !== null)
    // Prefixed with the sequence, because the lifecycle amendment below
    // validates a backbone of the SAME relPath in its OWN package directory and
    // its skip is folded into this same note. Unlabelled, three entries would
    // read as one file listed twice.
    .map((sk) => ({ ...sk, relPath: `0000/${sk.relPath}` }));
  if (fdaCriteriaFallbackEnabled() && (region === 'fda' || region === 'ema' || region === 'pmda')) {
    const rep = await validateFdaCriteria({ packageDir: pkgDir, region });
    validators.push(tally(`fda-criteria-subset`, rep.ran, rep.findings));
  }
  const external = await resolveExternalValidator();
  if (external.name !== 'noop' && (region === 'fda' || region === 'ema' || region === 'pmda')) {
    // Fail-closed: a configured-but-failing engine yields an un-run report, never a throw.
    const rep = await runExternalValidation({ packageDir: pkgDir, region: region as EctdRegion });
    validators.push(tally(external.name, rep.ran, rep.findings));
    notes.push(`External validator "${external.name}" ${rep.ran ? 'ran' : 'was configured but did not complete'}.`);
  } else {
    notes.push('No external eValidator configured; xmllint + FDA-criteria subset are the accepted validators for this run.');
  }

  // 2b. Vendored-artifact integrity: verify the drop-point checksum manifest so
  //     a tampered, stale or unrecorded file is refused. The drop-point holds
  //     BOTH the DTDs and the agency stylesheets, and checksums.txt records all
  //     seven (see its header) — so verifying '.dtd' alone left the *.xsl
  //     unexamined while this row still reported "passed", even though every
  //     index.xml renders through util/style/ectd-2-0.xsl and the FDA backbone
  //     through us-regional.xsl. When nothing is vendored this is a
  //     trivially-ok no-op (nothing to verify).
  //     THREE FAULT CLASSES, NOT TWO. `verifyChecksumManifest` reports
  //     `mismatched` (tampered/stale), `unlistedFiles` (present, unrecorded) and
  //     `missingFiles` (recorded, gone from disk) — and its own `ok` counts all
  //     three. This row mapped the first two, so a drop point whose
  //     checksums.txt still records a DTD after the file was deleted returned
  //     `ok: false` from the verifier and `dtd-checksum-manifest: passed` in the
  //     report a filer reads. That is the worst of the three to drop: a DTD
  //     named in the manifest and absent from disk is exactly the
  //     not-self-contained package the ECTD_REQUIRE_DTD gate exists to stop.
  const dtdManifest = await verifyChecksumManifest(resolveDtdDir(), 'checksums.txt', ['.dtd', '.xsl']);
  validators.push(tally('dtd-checksum-manifest', true, [
    ...dtdManifest.mismatched.map((m) => ({ severity: 'error', message: `Vendored ${m.fileName} hash mismatch (tampered/stale).` })),
    ...dtdManifest.unlistedFiles.map((f) => ({ severity: 'error', message: `Vendored file ${f} is not recorded in checksums.txt.` })),
    ...dtdManifest.missingFiles.map((f) => ({ severity: 'error', message: `checksums.txt records ${f} but no such file is in the drop point.` })),
  ]));
  // The note itself is pushed AFTER the lifecycle package below, so the
  // amendment's own skip can be in it — see there.

  // 2c. STF cross-linking + intra-package cross-reference resolution evidence
  //     (surfaced by the packager on the bundle).
  if (bundle.stf) {
    validators.push(tally('stf-cross-linking', true,
      bundle.stf.untagged > 0 ? [{ severity: 'warning', message: `${bundle.stf.untagged} study leaf/leaves untagged` }] : []));
    notes.push(`STF: ${bundle.stf.studies} study tagging file(s) generated + cross-linked (${bundle.stf.leaves} tagged leaves).`);
  }
  if (bundle.crossReferenceStatus) {
    validators.push(tally('cross-references', true,
      bundle.crossReferenceStatus.broken.map((b) => ({ severity: 'error', message: `${b.source}→${b.target}: ${b.reason}` }))));
    notes.push(`Cross-references: ${bundle.crossReferenceStatus.resolved} resolved, ${bundle.crossReferenceStatus.broken.length} broken.`);
  }

  // 3. Reopen + verify checksums.
  const checksum = await verifyZipChecksums(bundle.path);

  // 4. Lifecycle: amendment 0001 with replace/delete/append.
  const lcBundle = await packageEctdSubmission(v3GoldenInput({ region, sequence: '0001', applicationId: app, outputDir: outDir, paths, lifecycle: true, priorSequence: '0000' }));
  const lcDir = path.join(outDir, `${app}-0001-${region}`);
  const lcRegional = await validateBackboneFile(lcDir, regionalRel);
  const lcChecksum = await verifyZipChecksums(lcBundle.path);
  const lcPassed = lcRegional.reports.every((v) => v.passed) && lcChecksum.ok;
  /* THE AMENDMENT'S SKIP IS ITS OWN FACT. `lcRegional.dtdSkipped` was computed
     here and discarded, and a skip emits NO row — so `lcPassed`, which is
     `reports.every(v => v.passed)`, stayed true and the report carried
     `lifecycle.nextPackagePassed: true` with nothing said about the amendment's
     backbone never having been DTD-validated. That is the silence `dtdSkipNote`
     exists to prevent: a skipped check must never read as a passed one.

     It is NOT a duplicate of the 0000 skip above. Each package bundles its own
     DTDs and this reads `lcDir`, not `pkgDir`, so a lifecycle packager that
     stops copying them into 0001 produces exactly this divergence — and
     produced a clean report. */
  if (lcRegional.dtdSkipped) {
    dtdSkips.push({ ...lcRegional.dtdSkipped, relPath: `0001/${lcRegional.dtdSkipped.relPath}` });
  }
  if (dtdSkips.length) notes.push(await dtdSkipNote(dtdSkips));

  // Read the operation attributes ACTUALLY emitted into the amendment's
  // backbones (index.xml for m2–5, the regional backbone for m1), so the report
  // proves what the packager produced instead of restating a fixed list.
  const lcLeafOps = await readEmittedLeafOps(lcDir, ['index.xml', regionalRel]);
  const observedOps = Array.from(new Set(lcLeafOps.map((l) => l.operation))).sort();
  // The amendment operations are everything except the baseline 'new'.
  const lifecycleOps = observedOps.filter((o) => o !== 'new');
  const opsWithModifiedFile = Array.from(
    new Set(lcLeafOps.filter((l) => l.hasModifiedFile).map((l) => l.operation)),
  ).sort();
  notes.push(
    `Lifecycle backbone operations emitted: ${observedOps.join(', ') || '(none)'}; ` +
      `superseding operations carrying a modified-file pointer: ${opsWithModifiedFile.join(', ') || '(none)'}.`,
  );

  const passed = validators.every((v) => v.passed) && checksum.ok;
  return {
    id: `v3.2.2-${region}`,
    version: 'v3.2.2',
    region,
    specVersions: SPEC_VERSIONS['v3.2.2'],
    package: { path: bundle.path, sha256: bundle.sha256, sizeBytes: bundle.sizeBytes },
    validators,
    checksum,
    lifecycle: {
      priorSequence: '0000',
      nextSequence: '0001',
      operations: lifecycleOps,
      operationsWithModifiedFile: opsWithModifiedFile,
      nextPackagePassed: lcPassed,
      checksum: lcChecksum,
    },
    passed: passed && lcPassed,
    ranAt: '(stamped by caller)',
    notes,
  };
}

/** Qualify FDA for eCTD v4.0 (HL7 RPS). */
export async function qualifyV4(workDir: string): Promise<QualificationReport> {
  const notes: string[] = [];
  const app = '123456';
  const outDir = path.join(workDir, 'v4-fda-out');

  // 1. Original submission unit (0000).
  const golden = v4GoldenMessage({ applicationId: app, sequence: '0000' });
  const pkg = await packageRpsSubmission({ message: golden.message, sources: golden.sources, outputDir: outDir, emitUnzipped: true, creationTime: '20260730120000' });
  const pkgDir = path.join(outDir, `${app}-0000-fda-v4`);

  // 2. Validators: RPS model + xmllint well-formed on the message.
  const validators: ValidatorRunReport[] = [];
  validators.push(tally('rps-model-validator', true, pkg.validation.findings));
  const msgPath = path.join(pkgDir, 'submissionUnit.xml');
  if (await isXmllintAvailable()) {
    const wf = await checkWellFormed(msgPath, true);
    validators.push(tally('xmllint well-formed (submissionUnit.xml)', wf.ran, wf.valid ? [] : wf.errors.map((m) => ({ severity: 'error', message: m }))));
  }
  // RPS XSD validation: validate against the schema bundled into util/schema/
  // (from assets/ectd-schema/) when the licensed ICH RPS schema is vendored.
  const bundledSchema = path.join(pkgDir, 'util', 'schema', RPS_MESSAGE_XSD);
  const hasRpsSchema = await fs.access(bundledSchema).then(() => true).catch(() => false);
  if (hasRpsSchema) {
    const xsd = await validateAgainstXsd(msgPath, bundledSchema, true);
    validators.push(tally('xmllint XSD (submissionUnit.xml)', xsd.ran, xsd.valid ? [] : xsd.errors.map((m) => ({ severity: 'error', message: m }))));
  } else {
    notes.push('RPS XSD validation skipped — vendor the ICH RPS message schema into assets/ectd-schema/ (rps-message.xsd) to enable it.');
  }
  // Vendored-schema integrity (drop-point manifest). All THREE of the verifier's
  // fault classes, for the same reason as `dtd-checksum-manifest` above: an XSD
  // recorded in checksums.txt and absent from the drop point is a schema
  // submissionUnit.xml cannot be validated against, and mapping only the first
  // two reported it as a passed integrity check.
  const schemaManifest = await verifyChecksumManifest(resolveSchemaDir(), 'checksums.txt', ['.xsd']);
  validators.push(tally('schema-checksum-manifest', true, [
    ...schemaManifest.mismatched.map((m) => ({ severity: 'error', message: `Schema ${m.fileName} hash mismatch.` })),
    ...schemaManifest.unlistedFiles.map((f) => ({ severity: 'error', message: `Vendored schema ${f} is not recorded in checksums.txt.` })),
    ...schemaManifest.missingFiles.map((f) => ({ severity: 'error', message: `checksums.txt records schema ${f} but no such file is in the drop point.` })),
  ]));

  // External agency-grade validator (LORENZ) — runs for v4.0 too when configured.
  const external = await resolveExternalValidator();
  if (external.name !== 'noop') {
    const rep = await runExternalValidation({ packageDir: pkgDir, region: 'fda' });
    validators.push(tally(external.name, rep.ran, rep.findings));
    notes.push(`External validator "${external.name}" ${rep.ran ? 'ran' : 'was configured but did not complete'}.`);
  }

  // 3. Reopen + verify: package checksums AND in-message SHA-256 integrity.
  const checksum = await verifyZipChecksums(pkg.path);
  const integrityMismatches = await verifyRpsIntegrity(pkg.path);
  if (integrityMismatches.length) {
    notes.push(`In-message document integrity mismatches: ${integrityMismatches.join(', ')}`);
  }

  // 4. Lifecycle: amendment 0001 (revise) referencing 0000 CoUs.
  const golden1 = v4GoldenMessage({ applicationId: app, sequence: '0001', lifecycle: true, priorSequence: '0000' });
  const lcValidation = validateRpsMessage(golden1.message, '0001');
  const lcPkg = await packageRpsSubmission({ message: golden1.message, sources: golden1.sources, outputDir: outDir, emitUnzipped: true, creationTime: '20260730120000' });
  const lcChecksum = await verifyZipChecksums(lcPkg.path);
  const lcPassed = lcValidation.valid && lcChecksum.ok;

  // Operations are read from the emitted RPS message's contexts of use, not
  // hardcoded. v4.0 has no modified-file: a revised document points at its
  // predecessor via relatedContextOfUse, so that linkage is the v4 analogue
  // recorded in operationsWithModifiedFile.
  const v4Cous = golden1.message.contextsOfUse ?? [];
  const v4Ops = Array.from(
    new Set(v4Cous.map((c) => c.operation).filter((o): o is NonNullable<typeof o> => o != null)),
  ).sort();
  const v4Linked = Array.from(
    new Set(
      v4Cous
        .filter((c) => c.relatedContextOfUseId)
        .map((c) => c.operation)
        .filter((o): o is NonNullable<typeof o> => o != null),
    ),
  ).sort();
  notes.push(
    `v4.0 lifecycle CoU operations emitted: ${v4Ops.join(', ') || '(none)'}; ` +
      `operations linked to a predecessor via relatedContextOfUse: ${v4Linked.join(', ') || '(none)'}.`,
  );

  const passed = validators.every((v) => v.passed) && checksum.ok && integrityMismatches.length === 0;
  return {
    id: 'v4.0-fda',
    version: 'v4.0',
    region: 'fda',
    specVersions: SPEC_VERSIONS['v4.0'],
    package: { path: pkg.path, sha256: pkg.sha256, sizeBytes: pkg.sizeBytes },
    validators,
    checksum,
    lifecycle: {
      priorSequence: '0000',
      nextSequence: '0001',
      operations: v4Ops.filter((o) => o !== 'create'),
      operationsWithModifiedFile: v4Linked,
      nextPackagePassed: lcPassed,
      checksum: lcChecksum,
    },
    passed: passed && lcPassed,
    ranAt: '(stamped by caller)',
    notes,
  };
}

/** Verify each RPS document's in-message SHA-256 integrityCheck matches the
 *  bytes shipped in the ZIP. Returns the hrefs that mismatch. */
async function verifyRpsIntegrity(zipPath: string): Promise<string[]> {
  const buf = await fs.readFile(zipPath);
  const zip = await JSZip.loadAsync(buf);
  const msg = await (zip.file('submissionUnit.xml')?.async('string') ?? Promise.resolve(''));
  const mismatches: string[] = [];
  // Pair each <text ... integrityCheck="HASH"> with the following <reference value="HREF"/>.
  const docRe = /integrityCheck="([0-9a-f]+)"[\s\S]*?<reference value="([^"]+)"/g;
  let m: RegExpExecArray | null;
  while ((m = docRe.exec(msg)) !== null) {
    const [, hash, href] = m;
    const entry = zip.file(href);
    if (!entry) { mismatches.push(`${href} (missing)`); continue; }
    const actual = createHash('sha256').update(await entry.async('nodebuffer')).digest('hex');
    if (actual !== hash) mismatches.push(`${href} (hash)`);
  }
  return mismatches;
}

export interface RunQualificationOptions {
  /** Regions to qualify for v3.2.2 (default: fda, ema, pmda, ca). */
  v3Regions?: Region[];
  /** Include the v4.0 FDA qualification (default: true). */
  includeV4?: boolean;
  /** Directory to write JSON reports into (default: <cwd>/qualification-reports). */
  reportDir?: string;
  /** ISO timestamp to stamp reports with (caller supplies for determinism). */
  ranAt?: string;
  /** Working dir for generated packages (default: a fresh temp dir). */
  workDir?: string;
}

export interface QualificationSummary {
  ranAt: string;
  reportDir: string;
  reports: QualificationReport[];
  passed: boolean;
}

/** Run the full qualification suite and preserve the reports. */
export async function runQualification(opts: RunQualificationOptions = {}): Promise<QualificationSummary> {
  const ranAt = opts.ranAt ?? new Date().toISOString();
  const reportDir = opts.reportDir ?? path.resolve(process.cwd(), 'qualification-reports');
  const workDir = opts.workDir ?? (await fs.mkdtemp(path.join(os.tmpdir(), 'ectd-qual-')));
  const v3Regions = opts.v3Regions ?? (['fda', 'ema', 'pmda', 'ca'] as Region[]);

  const reports: QualificationReport[] = [];
  for (const region of v3Regions) {
    const r = await qualifyV3(region, workDir);
    r.ranAt = ranAt;
    reports.push(r);
  }
  if (opts.includeV4 !== false) {
    const r = await qualifyV4(workDir);
    r.ranAt = ranAt;
    reports.push(r);
  }

  await fs.mkdir(reportDir, { recursive: true });
  for (const r of reports) {
    await fs.writeFile(path.join(reportDir, `${r.id}.json`), JSON.stringify(r, null, 2));
  }
  const summary: QualificationSummary = {
    ranAt,
    reportDir,
    reports,
    passed: reports.every((r) => r.passed),
  };
  await fs.writeFile(path.join(reportDir, 'summary.json'), JSON.stringify(summary, null, 2));
  return summary;
}
