import crypto from 'node:crypto';
import { getPool } from '../../db';

interface WritebackInput {
  organizationId: number;
  projectId: number;
  userId: number;
  title: string;
  content: string;
  ctdSection?: string;
  sourceJobId: string;
  surfaceKey: string;
}

export async function registerArtifactWithGovernance(input: WritebackInput): Promise<{
  artifactId: string;
  version: number;
  artifactTitle: string;
  artifactStatus: string;
  placementState: 'placed' | 'unplaced';
  provenanceEventId: string;
  auditId: string;
}> {
  const pool = getPool();
  const client = await pool.connect();
  const now = new Date();
  const externalArtifactId = `artifact_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`;
  const contentHash = crypto.createHash('sha256').update(input.content).digest('hex');

  try {
    await client.query('BEGIN');

    const artifactInsert = await client.query(
      `INSERT INTO concept2cure_artifacts (
        artifact_id, project_id, organization_id, type, category, title, content,
        content_hash, version, ctd_section, status, created_by_id, metadata, created_at, updated_at
      ) VALUES ($1,$2,$3,'regulatory_document','document',$4,$5,$6,1,$7,'draft',$8,$9,$10,$10)
      RETURNING id, artifact_id, version`,
      [
        externalArtifactId,
        input.projectId,
        input.organizationId,
        input.title,
        input.content,
        contentHash,
        input.ctdSection ?? null,
        input.userId,
        JSON.stringify({ computeJobId: input.sourceJobId, surfaceKey: input.surfaceKey }),
        now,
      ]
    );

    const artifactPk = artifactInsert.rows[0].id;

    const versionInsert = await client.query(
      `INSERT INTO concept2cure_artifact_versions (
        artifact_id, organization_id, version, content, content_hash, change_description, created_by_id, created_at, updated_at
      ) VALUES ($1,$2,1,$3,$4,$5,$6,$7,$7)
      RETURNING id`,
      [
        artifactPk,
        input.organizationId,
        input.content,
        contentHash,
        `Initial artifact generated by compute job ${input.sourceJobId}`,
        input.userId,
        now,
      ]
    );

    const provenanceEventId = `prov_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`;
    await client.query(
      `INSERT INTO concept2cure_provenance_events (
        event_id, artifact_id, artifact_version_id, organization_id, event_type, event_action,
        actor_id, actor_name, actor_email, details, source_description, backend_route, backend_service, ip_address, created_at, updated_at
      ) VALUES ($1,$2,$3,$4,'generation','artifact_compute_writeback',$5,'Artifact Compute Plane',NULL,$6,$7,$8,'artifact-compute','127.0.0.1',$9,$9)`,
      [
        provenanceEventId,
        artifactPk,
        versionInsert.rows[0].id,
        input.organizationId,
        input.userId,
        JSON.stringify({ computeJobId: input.sourceJobId, generatedAt: now.toISOString() }),
        `Compute surface ${input.surfaceKey}`,
        '/api/concept2cure/compute/jobs/:jobId/finalize',
        now,
      ]
    );

    const auditId = `audit_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`;
    await client.query(
      `INSERT INTO regulatory_audit_logs (
        audit_id, organization_id, entity_type, entity_id, action, action_category,
        previous_value, new_value, user_id, user_name, user_role, ip_address,
        is_gxp_relevant, timestamp, metadata, created_at, updated_at
      ) VALUES ($1,$2,'artifact',$3,'CREATE','data-change',NULL,$4,$5,'artifact-compute','system','127.0.0.1',TRUE,$6,$7,$6,$6)`,
      [
        auditId,
        input.organizationId,
        externalArtifactId,
        JSON.stringify({ title: input.title, sourceJobId: input.sourceJobId }),
        input.userId,
        now,
        JSON.stringify({ source: 'artifact_compute_plane', surfaceKey: input.surfaceKey }),
      ]
    );

    await client.query('COMMIT');

    return {
      artifactId: artifactInsert.rows[0].artifact_id,
      version: artifactInsert.rows[0].version,
      artifactTitle: input.title,
      artifactStatus: 'draft',
      placementState: input.ctdSection ? 'placed' : 'unplaced',
      provenanceEventId,
      auditId,
    };
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}
