/**
 * The environment a sandboxed worker is allowed to see.
 *
 * ── What this closes ──────────────────────────────────────────────────────────
 * Both artifact-compute spawn sites passed `{ ...process.env }` to the Python
 * runtimes. `python-script-runtime.py` exists to `exec()` AnA-authored code —
 * that is its documented purpose, not a defect — so every secret in the server
 * environment was one `os.environ` away from code an LLM wrote.
 *
 * That matters more than it would in an ordinary scripting sandbox, because the
 * code is not authored by the operator. It is generated by a model that reads
 * customer documents, so anything that can steer the model can steer the script.
 * The path from a sentence buried in an uploaded PDF to `DATABASE_URL`,
 * `AUDIT_HMAC_SECRET`, `AUDIT_ATTESTATION_KEY` or a payment key was one hop.
 *
 * ── Why not rely on the network guard ─────────────────────────────────────────
 * `_install_network_guard()` reassigns `socket.socket`, `socket.create_connection`
 * and `socket.create_server`. That stops the accidental cases it is documented to
 * stop — a library reaching for the internet — and stops nothing deliberate:
 * `subprocess`, `os.system`, or `importlib.reload(socket)` all walk past it. The
 * runtime's own docstring is honest about this ("defence-in-depth, not the only
 * boundary") and names the container as the real boundary. `runner.ts` says that
 * process *should* run in a locked-down container — a statement of intent, with
 * no code behind it in this repository.
 *
 * So the containment that exists today is: whatever the host provides, plus this.
 * Given that, not handing the script the credentials in the first place is the
 * cheapest real reduction available — it removes the prize rather than guarding
 * the exit.
 *
 * ── Why an allowlist and not a denylist ───────────────────────────────────────
 * A denylist of secret-looking names has to be right about every variable that
 * will ever exist, including ones added after this file is forgotten. An
 * allowlist has to be right about what `python3` needs to start, which is a
 * short and stable list, and its failure mode is a worker that will not run
 * rather than a credential that quietly leaks.
 */

/**
 * Variables a Python interpreter needs to start and behave predictably.
 * Deliberately short. Anything absent from `process.env` is simply not passed.
 */
const PASSTHROUGH = [
  'PATH', // finding python3 at all
  'HOME', // some stdlib paths consult it
  'LANG',
  'LC_ALL',
  'LC_CTYPE', // text encoding; without these Python may pick ASCII
  'TZ',
  'TMPDIR',
  'TEMP',
  'TMP',
  'PYTHONPATH',
  'PYTHONHOME',
  'PYTHONIOENCODING',
  'SYSTEMROOT', // Windows: python fails to initialise without it
  'COMSPEC',
] as const;

/**
 * Build the environment for a sandboxed worker process.
 *
 * @param extra values the runtime contract requires (workdir, policy flags).
 *              These are applied last and may override a passthrough name.
 */
export function sandboxEnv(extra: Record<string, string> = {}): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = {};
  for (const key of PASSTHROUGH) {
    const value = process.env[key];
    if (value !== undefined) env[key] = value;
  }
  return { ...env, ...extra };
}

/**
 * The passthrough list, exported so a test can assert the policy directly
 * rather than re-deriving it and agreeing with itself.
 */
export const SANDBOX_PASSTHROUGH: readonly string[] = PASSTHROUGH;
