import type { ReportTypeDefinition } from './taxonomy';

/**
 * Global-markets expansion of the Insights report taxonomy.
 *
 * New, regulatorily-accurate report-type definitions covering all global
 * markets. NO typeId here overlaps the existing REPORT_TYPE_SEED. Each entry
 * uses the real pathway / dossier / document names a paying RA professional
 * works with (e.g. Day-120/Day-180 LoQ, JNDA/Shonin, NDS/SNDS, ILAP, ARTG).
 */
export const GLOBAL_REPORT_TYPE_SEED: ReportTypeDefinition[] = [
  // USA FDA — drug / biologic pathways (IND, NDA/BLA, CRL, Type A/B/C, De Novo).
  {
    typeId: 'usa_fda.ind_safety_readiness',
    label: 'FDA IND Safety & Readiness Pack (21 CFR 312)',
    family: 'usa_fda_ind',
    allowedScopes: ['project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'pv_lead', 'qa'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['submission_readiness', 'nonclinical_studies', 'safety_signals', 'module_completeness'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'fda-ind-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'USA_FDA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, forbidFinalIfMissingCritical: true, requireConfidence: true },
  },
  {
    typeId: 'usa_fda.nda_bla_filing_readiness',
    label: 'FDA NDA / BLA Filing Readiness Assessment (eCTD)',
    family: 'usa_fda_nda_bla',
    allowedScopes: ['program', 'project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'executive', 'qa'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['submission_readiness', 'module_completeness', 'section_status', 'question_risk'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'fda-nda-bla-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'USA_FDA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, forbidFinalIfMissingCritical: true, requireConfidence: true },
  },
  {
    typeId: 'usa_fda.crl_response_intelligence',
    label: 'FDA Complete Response Letter (CRL) Response Pack',
    family: 'usa_fda_response',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'qa', 'executive'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['correspondence_issues', 'root_cause_analysis', 'response_actions', 'risk_register'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'fda-crl-response-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'USA_FDA' },
    truthfulnessRules: { allowPartial: false, requireBlockers: true, requireExplicitGaps: true, forbidFinalIfMissingCritical: true },
  },
  {
    typeId: 'usa_fda.type_bcd_meeting_brief',
    label: 'FDA Type A/B/C Meeting Briefing Package',
    family: 'usa_fda_meetings',
    allowedScopes: ['project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'executive'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['ha_interactions', 'submission_readiness', 'question_risk', 'evidence_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'project_sections'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'fda-meeting-briefing-package',
    governanceRequirements: { part11: true, auditTrail: true, region: 'USA_FDA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },
  {
    typeId: 'usa_fda.de_novo_classification_pack',
    label: 'FDA De Novo Classification Request Pack (21 CFR 860)',
    family: 'usa_fda_de_novo',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['ra_lead', 'qa', 'medical_writer'],
    allowedClientSegments: ['device'],
    dataDependencies: ['submission_readiness', 'clinical_evidence', 'device_safety_summary', 'predicate_mapping'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'fda-de-novo-classification-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'USA_FDA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireExplicitGaps: true, requireConfidence: true },
  },

  // EU EMA — centralised procedure (LoQ Day-120/180, variations, PSUR/PBRER, SA).
  {
    typeId: 'ema.maa_loq_response_pack',
    label: 'EMA MAA List of Questions (Day-120 / Day-180) Response Pack',
    family: 'ema_response',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'qa'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['correspondence_issues', 'response_actions', 'question_risk', 'evidence_links'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'ema-loq-response-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'EU_EMA' },
    truthfulnessRules: { allowPartial: false, requireBlockers: true, requireExplicitGaps: true, forbidFinalIfMissingCritical: true },
  },
  {
    typeId: 'ema.variation_readiness',
    label: 'EMA Variation Readiness Pack (Type IA / IB / II)',
    family: 'ema_variation',
    allowedScopes: ['project', 'submission'],
    allowedPersonas: ['ra_lead', 'ra_ops', 'qa'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['submission_readiness', 'module_completeness', 'lifecycle_obligations'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'ema-variation-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'EU_EMA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },
  {
    typeId: 'ema.psur_pbrer_pack',
    label: 'EMA PSUR / PBRER Pack (ICH E2C(R2))',
    family: 'ema_post_market',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['pv_lead', 'ra_lead', 'medical_writer'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['safety_signals', 'benefit_risk', 'risk_management_plan', 'evidence_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'ema-psur-pbrer-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'EU_EMA' },
    truthfulnessRules: { allowPartial: true, requireExplicitGaps: true, requireConfidence: true },
  },
  {
    typeId: 'ema.scientific_advice_brief',
    label: 'EMA Scientific Advice / Protocol Assistance Briefing Package',
    family: 'ema_meetings',
    allowedScopes: ['project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'executive'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['ha_interactions', 'submission_readiness', 'question_risk', 'evidence_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'project_sections'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'ema-scientific-advice-brief',
    governanceRequirements: { part11: true, auditTrail: true, region: 'EU_EMA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },

  // EU devices — MDR (EU 2017/745) / IVDR (EU 2017/746) technical documentation.
  {
    typeId: 'eu_mdr.technical_documentation_readiness',
    label: 'EU MDR Technical Documentation Readiness (Annex II / III)',
    family: 'eu_mdr_techdoc',
    allowedScopes: ['project', 'submission'],
    allowedPersonas: ['ra_lead', 'qa', 'medical_writer'],
    allowedClientSegments: ['device'],
    dataDependencies: ['submission_readiness', 'module_completeness', 'clinical_evidence', 'device_safety_summary'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'eu-mdr-techdoc-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'EU_MDR' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireExplicitGaps: true, requireConfidence: true },
  },
  {
    typeId: 'eu_mdr.cer_per_completeness',
    label: 'EU MDR Clinical Evaluation Report (CER) Completeness Pack (MEDDEV 2.7/1 Rev.4)',
    family: 'eu_mdr_clinical',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'qa'],
    allowedClientSegments: ['device'],
    dataDependencies: ['clinical_evidence', 'evidence_links', 'benefit_risk', 'section_status'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['project_sections', 'governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'eu-mdr-cer-completeness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'EU_MDR' },
    truthfulnessRules: { allowPartial: true, requireExplicitGaps: true, requireConfidence: true },
  },
  {
    typeId: 'eu_ivdr.performance_evaluation_readiness',
    label: 'EU IVDR Performance Evaluation Report (PER) Readiness (Annex XIII)',
    family: 'eu_ivdr_performance',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'qa'],
    allowedClientSegments: ['ivd', 'device'],
    dataDependencies: ['clinical_evidence', 'evidence_links', 'device_safety_summary', 'section_status'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['project_sections', 'governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'eu-ivdr-per-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'EU_IVDR' },
    truthfulnessRules: { allowPartial: true, requireExplicitGaps: true, requireConfidence: true },
  },

  // Japan PMDA — JNDA/Shonin approval, consultation (taimen), re-examination.
  {
    typeId: 'japan_pmda.jnda_shonin_readiness',
    label: 'PMDA J-NDA / Shonin Approval Readiness Pack',
    family: 'japan_pmda_jnda',
    allowedScopes: ['program', 'project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'executive'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['submission_readiness', 'module_completeness', 'question_risk', 'section_status'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'pmda-jnda-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'JP_PMDA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },
  {
    typeId: 'japan_pmda.consultation_brief',
    label: 'PMDA Consultation (Taimen Advice) Briefing Package',
    family: 'japan_pmda_meetings',
    allowedScopes: ['project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'executive'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['ha_interactions', 'submission_readiness', 'question_risk', 'evidence_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'project_sections'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'pmda-consultation-brief',
    governanceRequirements: { part11: true, auditTrail: true, region: 'JP_PMDA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },
  {
    typeId: 'japan_pmda.reexamination_pack',
    label: 'PMDA Re-examination (Saishinsa) Pack',
    family: 'japan_pmda_post_market',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['ra_lead', 'pv_lead', 'qa'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['safety_signals', 'benefit_risk', 'lifecycle_obligations', 'evidence_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'pmda-reexamination-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'JP_PMDA' },
    truthfulnessRules: { allowPartial: true, requireExplicitGaps: true, requireConfidence: true },
  },

  // Health Canada — NDS/SNDS (drugs), Medical Device Licence (MDL).
  {
    typeId: 'canada_hc.nds_snds_readiness',
    label: 'Health Canada NDS / SNDS Filing Readiness Pack',
    family: 'canada_hc_nds',
    allowedScopes: ['program', 'project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'qa'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['submission_readiness', 'module_completeness', 'question_risk', 'section_status'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'hc-nds-snds-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'CA_HC' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },
  {
    typeId: 'canada_hc.device_licence_readiness',
    label: 'Health Canada Medical Device Licence (MDL) Readiness Pack',
    family: 'canada_hc_device',
    allowedScopes: ['project', 'submission'],
    allowedPersonas: ['ra_lead', 'qa', 'medical_writer'],
    allowedClientSegments: ['device'],
    dataDependencies: ['submission_readiness', 'clinical_evidence', 'device_safety_summary', 'module_completeness'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'hc-device-licence-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'CA_HC' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireExplicitGaps: true, requireConfidence: true },
  },

  // UK MHRA — national MAA, Innovative Licensing and Access Pathway (ILAP).
  {
    typeId: 'uk_mhra.maa_readiness',
    label: 'MHRA Marketing Authorisation Application Readiness Pack',
    family: 'uk_mhra_maa',
    allowedScopes: ['program', 'project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'executive'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['submission_readiness', 'module_completeness', 'question_risk', 'section_status'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'mhra-maa-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'UK_MHRA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },
  {
    typeId: 'uk_mhra.ilap_pathway_brief',
    label: 'MHRA ILAP Target Development Profile Briefing Package',
    family: 'uk_mhra_pathway',
    allowedScopes: ['project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'executive'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['ha_interactions', 'submission_readiness', 'question_risk', 'evidence_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'project_sections'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'mhra-ilap-pathway-brief',
    governanceRequirements: { part11: true, auditTrail: true, region: 'UK_MHRA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },

  // Australia TGA — prescription medicine registration (ARTG), device inclusion.
  {
    typeId: 'australia_tga.prescription_medicine_readiness',
    label: 'TGA Prescription Medicine Registration Readiness Pack (ARTG)',
    family: 'australia_tga_medicine',
    allowedScopes: ['program', 'project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'qa'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['submission_readiness', 'module_completeness', 'question_risk', 'section_status'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'tga-prescription-medicine-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'AU_TGA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },
  {
    typeId: 'australia_tga.artg_device_inclusion_readiness',
    label: 'TGA Medical Device ARTG Inclusion Readiness Pack',
    family: 'australia_tga_device',
    allowedScopes: ['project', 'submission'],
    allowedPersonas: ['ra_lead', 'qa', 'medical_writer'],
    allowedClientSegments: ['device'],
    dataDependencies: ['submission_readiness', 'clinical_evidence', 'device_safety_summary', 'module_completeness'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'tga-artg-device-inclusion-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'AU_TGA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireExplicitGaps: true, requireConfidence: true },
  },

  // South Korea MFDS — drug item registration (KDF / IND-NDA).
  {
    typeId: 'korea_mfds.drug_registration_readiness',
    label: 'MFDS Drug Item Registration Readiness Pack',
    family: 'korea_mfds_registration',
    allowedScopes: ['program', 'project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'qa'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['submission_readiness', 'module_completeness', 'question_risk', 'formatting_compliance'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'mfds-drug-registration-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'KR_MFDS' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },

  // Switzerland Swissmedic — national MAA (Zulassung).
  {
    typeId: 'switzerland_swissmedic.maa_readiness',
    label: 'Swissmedic Marketing Authorisation (Zulassung) Readiness Pack',
    family: 'switzerland_swissmedic_maa',
    allowedScopes: ['program', 'project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'qa'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['submission_readiness', 'module_completeness', 'question_risk', 'section_status'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'swissmedic-maa-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'CH_SWISSMEDIC' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },

  // Brazil ANVISA — registration dossier (Registro) under RDC 200/2017.
  {
    typeId: 'brazil_anvisa.registration_dossier_readiness',
    label: 'ANVISA Registration Dossier (Registro) Readiness Pack',
    family: 'brazil_anvisa_registration',
    allowedScopes: ['program', 'project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'qa'],
    allowedClientSegments: ['pharma', 'biotech', 'device'],
    dataDependencies: ['submission_readiness', 'module_completeness', 'question_risk', 'formatting_compliance'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'anvisa-registration-dossier-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'BR_ANVISA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },

  // Cross-region / portfolio — multi-market comparison, ICH harmonization, labeling.
  {
    typeId: 'global.cross_region_submission_comparison',
    label: 'Cross-Region Submission Comparison Matrix',
    family: 'global_portfolio',
    allowedScopes: ['account', 'program', 'project'],
    allowedPersonas: ['ra_lead', 'reg_strategy', 'executive'],
    allowedClientSegments: ['pharma', 'device', 'biotech'],
    dataDependencies: ['submission_readiness', 'module_completeness', 'rim_registrations', 'question_risk'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'global-cross-region-comparison-matrix',
    governanceRequirements: { part11: true, auditTrail: true },
    truthfulnessRules: { allowPartial: true, requireExplicitGaps: true, requireConfidence: true },
  },
  {
    typeId: 'global.harmonization_gap_matrix',
    label: 'ICH Harmonization Gap Matrix (Cross-Market Alignment)',
    family: 'global_portfolio',
    allowedScopes: ['account', 'program', 'project'],
    allowedPersonas: ['ra_lead', 'reg_strategy', 'qa', 'executive'],
    allowedClientSegments: ['pharma', 'device', 'biotech'],
    dataDependencies: ['module_completeness', 'formatting_compliance', 'rim_registrations', 'evidence_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'global-harmonization-gap-matrix',
    governanceRequirements: { part11: true, auditTrail: true },
    truthfulnessRules: { allowPartial: true, requireExplicitGaps: true, requireConfidence: true },
  },
  {
    typeId: 'global.label_currency_matrix',
    label: 'Label Currency Matrix (USPI / SmPC / PIL / J-Label per Market)',
    family: 'global_labeling',
    allowedScopes: ['account', 'program', 'project'],
    allowedPersonas: ['labeling_lead', 'ra_ops', 'ra_lead', 'executive'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['rim_labels', 'rim_registrations', 'rim_products', 'lifecycle_obligations'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'global-label-currency-matrix',
    governanceRequirements: { part11: true, auditTrail: true },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, forbidFinalIfMissingCritical: true },
  },

  // Pharmacovigilance (global) — DSUR (ICH E2F), signal management (GVP Module IX).
  {
    typeId: 'pv.dsur_readiness',
    label: 'DSUR Readiness Pack (ICH E2F)',
    family: 'pv_periodic',
    allowedScopes: ['program', 'project', 'submission'],
    allowedPersonas: ['pv_lead', 'ra_lead', 'medical_writer'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['safety_signals', 'benefit_risk', 'nonclinical_studies', 'evidence_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'pv-dsur-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireExplicitGaps: true, requireConfidence: true },
  },
  {
    typeId: 'pv.signal_management_report',
    label: 'Signal Management Report (GVP Module IX)',
    family: 'pv_signal',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['pv_lead', 'ra_lead', 'qa'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['safety_signals', 'benefit_risk', 'risk_management_plan', 'evidence_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'pv-signal-management-report',
    governanceRequirements: { part11: true, auditTrail: true },
    truthfulnessRules: { allowPartial: true, requireExplicitGaps: true, requireConfidence: true },
  },
];
