import type { ReportScope } from '@shared/schema/report-os';

export interface ReportTypeDefinition {
  typeId: string;
  label: string;
  family: string;
  allowedScopes: ReportScope[];
  allowedPersonas: string[];
  allowedClientSegments: string[];
  dataDependencies: string[];
  artifactDependencies: string[];
  workflowDependencies: string[];
  anaModules: string[];
  exportTemplate: string;
  governanceRequirements: Record<string, unknown>;
  truthfulnessRules: Record<string, unknown>;
}

export const REPORT_TYPE_SEED: ReportTypeDefinition[] = [
  {
    typeId: 'readiness.executive_digest',
    label: 'Executive Readiness Digest',
    family: 'readiness',
    allowedScopes: ['program', 'project', 'submission'],
    allowedPersonas: ['executive', 'ra_lead', 'pm'],
    allowedClientSegments: ['pharma', 'device', 'biotech'],
    dataDependencies: ['submission_readiness', 'section_status', 'artifact_lifecycle'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['project_sections', 'submission_ops'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'executive-board-pack',
    governanceRequirements: { part11: true, auditTrail: true },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, forbidFinalIfMissingCritical: true },
  },
  {
    typeId: 'provenance.evidence_trace_report',
    label: 'Evidence & Provenance Trace Report',
    family: 'evidence_provenance',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'qa'],
    allowedClientSegments: ['pharma', 'device', 'biotech'],
    dataDependencies: ['provenance_map', 'cross_refs', 'evidence_links'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['editor_verify_panels'],
    anaModules: ['ana-ri'],
    exportTemplate: 'evidence-provenance-pack',
    governanceRequirements: { part11: true, provenanceCompleteness: true },
    truthfulnessRules: { allowPartial: true, requireConfidence: true },
  },
  {
    typeId: 'compliance.audit_assurance_pack',
    label: 'Compliance & Audit Assurance Pack',
    family: 'compliance_audit',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['qa', 'ra_lead', 'auditor'],
    allowedClientSegments: ['pharma', 'device', 'biotech'],
    dataDependencies: ['audit_events', 'signature_chain', 'compliance_scan'],
    artifactDependencies: ['immutable_report_records', 'report_seal_events'],
    workflowDependencies: ['signature_workflow', 'governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'qa-audit-pack',
    governanceRequirements: { part11: true, signatureChain: true },
    truthfulnessRules: { allowPartial: true, requireExplicitGaps: true },
  },
  {
    typeId: 'usa_fda.pma_submission_readiness',
    label: 'FDA PMA Submission Readiness Pack',
    family: 'usa_fda_pma',
    allowedScopes: ['project', 'submission'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'executive'],
    allowedClientSegments: ['device', 'biotech'],
    dataDependencies: ['submission_readiness', 'clinical_evidence', 'device_safety_summary'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'fda-pma-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'USA_FDA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },
  {
    typeId: 'usa_fda.estar_510k_equivalence_matrix',
    label: 'FDA eSTAR / 510(k) Equivalence Matrix',
    family: 'usa_fda_510k',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['ra_lead', 'qa'],
    allowedClientSegments: ['device'],
    dataDependencies: ['predicate_mapping', 'substantial_equivalence', 'testing_coverage'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'project_sections'],
    anaModules: ['ana-ri'],
    exportTemplate: 'fda-510k-equivalence-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'USA_FDA' },
    truthfulnessRules: { allowPartial: true, requireExplicitGaps: true, requireConfidence: true },
  },
  {
    typeId: 'usa_fda.deficiency_response_intelligence',
    label: 'FDA Deficiency Response Intelligence Report',
    family: 'usa_fda_response',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['ra_lead', 'qa', 'medical_writer'],
    allowedClientSegments: ['pharma', 'device', 'biotech'],
    dataDependencies: ['correspondence_issues', 'response_actions', 'risk_register'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'fda-deficiency-response-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'USA_FDA' },
    truthfulnessRules: { allowPartial: false, requireBlockers: true, requireExplicitGaps: true },
  },
  {
    typeId: 'ema.maa_readiness_assessment',
    label: 'EMA MAA Readiness Assessment',
    family: 'ema_maa',
    allowedScopes: ['program', 'project', 'submission'],
    allowedPersonas: ['ra_lead', 'executive', 'medical_writer'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['submission_readiness', 'module_completeness', 'question_risk'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'project_sections'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'ema-maa-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'EU_EMA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },
  {
    typeId: 'ema.rmp_psur_signal_alignment',
    label: 'EMA RMP / PSUR Signal Alignment Report',
    family: 'ema_post_market',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['ra_lead', 'qa'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['safety_signals', 'benefit_risk', 'risk_management_plan'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'ema-rmp-psur-alignment-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'EU_EMA' },
    truthfulnessRules: { allowPartial: true, requireExplicitGaps: true, requireConfidence: true },
  },
  {
    typeId: 'china_nmpa.ctd_module_gap_analysis',
    label: 'NMPA CTD Module Gap Analysis',
    family: 'china_nmpa_ctd',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['ra_lead', 'medical_writer', 'qa'],
    allowedClientSegments: ['pharma', 'biotech', 'device'],
    dataDependencies: ['module_completeness', 'formatting_compliance', 'evidence_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['project_sections', 'submission_ops'],
    anaModules: ['ana-ri'],
    exportTemplate: 'nmpa-ctd-gap-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'CN_NMPA' },
    truthfulnessRules: { allowPartial: true, requireExplicitGaps: true, requireConfidence: true },
  },
  {
    typeId: 'china_nmpa.registration_dossier_readiness',
    label: 'NMPA Registration Dossier Readiness Pack',
    family: 'china_nmpa_registration',
    allowedScopes: ['program', 'project', 'submission'],
    allowedPersonas: ['ra_lead', 'executive'],
    allowedClientSegments: ['pharma', 'biotech', 'device'],
    dataDependencies: ['submission_readiness', 'artifact_lifecycle', 'question_risk'],
    artifactDependencies: ['concept2cure_artifacts', 'immutable_report_records'],
    workflowDependencies: ['submission_ops', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'nmpa-registration-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'CN_NMPA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },
  {
    typeId: 'china_nmpa.deficiency_letter_root_cause_pack',
    label: 'NMPA Deficiency Letter Root-Cause Pack',
    family: 'china_nmpa_response',
    allowedScopes: ['project', 'submission', 'document'],
    allowedPersonas: ['ra_lead', 'qa', 'medical_writer'],
    allowedClientSegments: ['pharma', 'biotech', 'device'],
    dataDependencies: ['correspondence_issues', 'root_cause_analysis', 'response_actions'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['submission_ops', 'governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'nmpa-deficiency-root-cause-pack',
    governanceRequirements: { part11: true, auditTrail: true, region: 'CN_NMPA' },
    truthfulnessRules: { allowPartial: false, requireBlockers: true, requireExplicitGaps: true },
  },
  {
    // Clinical investigator financial-disclosure register (21 CFR 54; C2C-01).
    typeId: 'fcoi.disclosure_register',
    label: 'Financial Disclosure Register (21 CFR 54)',
    family: 'fcoi_compliance',
    allowedScopes: ['submission', 'project'],
    allowedPersonas: ['ra_lead', 'qa', 'submission_coordinator'],
    allowedClientSegments: ['pharma', 'biotech', 'device'],
    dataDependencies: ['financial_disclosures', 'disclosure_interests', 'provenance_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['signature_workflow', 'governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'fcoi-disclosure-register',
    governanceRequirements: { part11: true, auditTrail: true, region: 'USA_FDA' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, forbidFinalIfMissingCritical: true },
  },
  {
    // HA interaction history + commitment register (PMR/PMC/REMS; C2C-03).
    typeId: 'ha.commitment_register',
    label: 'HA Interaction & Commitment Register',
    family: 'ha_commitment',
    allowedScopes: ['submission', 'project', 'program'],
    allowedPersonas: ['ra_lead', 'reg_strategy', 'executive'],
    allowedClientSegments: ['pharma', 'biotech', 'device'],
    dataDependencies: ['ha_interactions', 'regulatory_commitments', 'commitment_milestones', 'provenance_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['governance_boundary'],
    anaModules: ['ana-ri', 'foresight_risk_synthesis'],
    exportTemplate: 'ha-commitment-register',
    governanceRequirements: { part11: true, auditTrail: true },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },
  {
    // IACUC animal-use protocol register + census (PHS Policy/AWA/OLAW; C2C-05).
    typeId: 'iacuc.protocol_register',
    label: 'IACUC Protocol & Animal Census Register',
    family: 'iacuc_governance',
    allowedScopes: ['project', 'submission', 'program'],
    allowedPersonas: ['iacuc_coordinator', 'ra_lead', 'qa'],
    allowedClientSegments: ['academic', 'biotech', 'pharma'],
    dataDependencies: ['iacuc_protocols', 'iacuc_animal_cohorts', 'iacuc_reviews', 'iacuc_amendments', 'provenance_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'iacuc-protocol-register',
    governanceRequirements: { part11: true, auditTrail: true, region: 'USA_OLAW' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, forbidFinalIfMissingCritical: true },
  },
  {
    // IRB submission + ethics determination register (Common Rule/21 CFR 56; C2C-06).
    typeId: 'irb.submission_register',
    label: 'IRB Submission & Determination Register',
    family: 'irb_ethics',
    allowedScopes: ['study', 'submission', 'project'],
    allowedPersonas: ['clinical_ops', 'ra_lead', 'qa'],
    allowedClientSegments: ['biotech', 'pharma', 'academic'],
    dataDependencies: ['irb_submissions', 'irb_sites', 'irb_reviews', 'irb_amendments', 'irb_reportable_events', 'provenance_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'irb-submission-register',
    governanceRequirements: { part11: true, auditTrail: true, region: 'USA_OHRP' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, forbidFinalIfMissingCritical: true },
  },
  {
    // IBC biosafety registration + containment register (NIH Guidelines; C2C-07).
    typeId: 'ibc.registration_register',
    label: 'IBC Biosafety Registration & Containment Register',
    family: 'ibc_biosafety',
    allowedScopes: ['project', 'submission', 'program'],
    allowedPersonas: ['biosafety_officer', 'ra_lead', 'qa'],
    allowedClientSegments: ['biotech', 'academic', 'pharma'],
    dataDependencies: ['ibc_registrations', 'ibc_biological_agents', 'ibc_reviews', 'provenance_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'ibc-registration-register',
    governanceRequirements: { part11: true, auditTrail: true, region: 'USA_NIH' },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, forbidFinalIfMissingCritical: true },
  },
  {
    // Nonclinical study + SEND readiness register (ICH M4/S; SENDIG; C2C-04).
    typeId: 'nonclinical.study_send_register',
    label: 'Nonclinical Study & SEND Readiness Register',
    family: 'nonclinical_module4',
    allowedScopes: ['submission', 'program', 'project'],
    allowedPersonas: ['nonclinical_lead', 'ra_lead', 'qa'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['nonclinical_studies', 'send_datasets', 'provenance_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'nonclinical-study-send-register',
    governanceRequirements: { part11: true, auditTrail: true },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, forbidFinalIfMissingCritical: true },
  },
  {
    // Sponsored-programs grant portfolio: pre/post-award, milestones, invoicing (C2C-14).
    typeId: 'grants.portfolio_register',
    label: 'Grant Portfolio & Funder-Milestone Register',
    family: 'sponsored_programs',
    allowedScopes: ['program', 'project', 'account'],
    allowedPersonas: ['research_admin', 'pi', 'finance', 'executive'],
    allowedClientSegments: ['academic', 'biotech'],
    dataDependencies: ['grant_opportunities', 'grant_proposals', 'grant_awards', 'grant_milestones', 'grant_invoices', 'provenance_links'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'grant-portfolio-register',
    governanceRequirements: { part11: true, auditTrail: true },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true },
  },
  {
    // RIM-lite product registration grid + labeling (21 CFR 201 / 2001/83/EC; C2C-12).
    typeId: 'rim.registration_grid',
    label: 'Product Registration Grid & Labeling Register',
    family: 'rim_registration',
    allowedScopes: ['program', 'project', 'account'],
    allowedPersonas: ['ra_ops', 'labeling_lead', 'executive'],
    allowedClientSegments: ['pharma', 'biotech'],
    dataDependencies: ['rim_products', 'rim_registrations', 'rim_labels'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'rim-registration-grid',
    governanceRequirements: { part11: true, auditTrail: true },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, forbidFinalIfMissingCritical: true },
  },
  {
    // Inspection readiness + 483 response tracker (FDA BIMO/PAI; C2C-13).
    typeId: 'inspection.readiness_pack',
    label: 'Inspection Readiness & 483 Response Pack',
    family: 'inspection_readiness',
    allowedScopes: ['program', 'project', 'submission'],
    allowedPersonas: ['qa', 'ra_lead', 'executive'],
    allowedClientSegments: ['pharma', 'biotech', 'device', 'ivd'],
    dataDependencies: ['inspections', 'inspection_findings', 'finding_responses', 'readiness_assessments'],
    artifactDependencies: ['concept2cure_artifacts'],
    workflowDependencies: ['governance_boundary'],
    anaModules: ['ana-ri'],
    exportTemplate: 'inspection-readiness-pack',
    governanceRequirements: { part11: true, auditTrail: true },
    truthfulnessRules: { allowPartial: true, requireBlockers: true, forbidFinalIfMissingCritical: true },
  },
];
