import React from 'react';

/**
 * AI Generated Badge Component
 *
 * A badge that indicates content was generated by AI.
 */
const AiGeneratedBadge = () => {
  return (
    <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-hotpink-100 text-hotpink-800">
      <svg className="mr-1.5 h-2 w-2 text-hotpink-400" fill="currentColor" viewBox="0 0 8 8">
        <circle cx="4" cy="4" r="3" />
      </svg>
      AI Generated
    </span>
  );
};

export default AiGeneratedBadge;
