/**
 * ui-v2 surface additions — the surfaces the Concept2Cure.RI design kit
 * (design_handoff_c2c_v2_ui_replacement) adds on top of the canonical set in
 * ui-surface-registry.ts. (The count is deliberately not written down here: it
 * said "48 on top of 33" long after both halves had grown past those numbers,
 * and a stale count in a header is a small lie that costs a reader a grep.)
 * Split out of ui-surface-registry.ts (kept both files under the
 * repo-health 1,500-line gate); the main file spreads UI_V2_SURFACES into
 * UI_SURFACES so every consumer and selector is unchanged.
 *
 * Ids are the kit registry.jsx ids verbatim — deep links depend on them.
 * Routes were repo-verified against all 15 server/bootstrap mount files in
 * the kit GA_READINESS_AUDIT (2026-07-05). Where the kit named a contract
 * that isn't a real @shared/*.ts file yet, sharedContract is null and the ref
 * is preserved in notes (GAP RULE — surfaced, not faked). See
 * docs/design/UI_V2_REGISTRY_RECONCILIATION_2026-07-06.md.
 */
import type { ComplianceRail, UiSurface } from './ui-surface-registry';

// Shorthand for the two near-universal rails (mirrors the main file).
const A11Y: ComplianceRail = 'accessibility-enforcement';
const TONE: ComplianceRail = 'microcopy-tone';
const PART11: ComplianceRail = 'regulatory-compliance-ux';

export const UI_V2_SURFACES: UiSurface[] = [
  // ─── ui-v2 additions: global ─────────────────────────────────────────────
  {
    id: 'ana-command',
    label: 'AnA Command',
    navTier: 'global',
    layoutMode: 'ana-command',
    group: 'explore',
    icon: 'sparkles',
    uiKit: null,
    apiPrefixes: ['/api/orchestration/continuity', '/api/orchestration/recommendations', '/api/orchestration/templates', '/api/orchestration/execute', '/api/orchestration/pre-submission-gate', '/api/orchestration/projects/:id/readiness'],
    anaToolFamilies: ['generate_recommendations', 'execute_workflow', 'assess_readiness'],
    sharedContract: '@shared/types/orchestration',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'AnA on top of everything across the portfolio: continuity briefing (what changed / newly ready / needs attention / trajectory), ranked dispatchable recommendations, runnable multi-step workflow templates (submission_readiness_review · draft_validate_route · project_blocker_scan), and the unified pre-submission go/no-go gate (readiness + CMC + CRL + RTF + ICH), audited to Part 11.',
  },
  {
    id: 'cro-portfolio',
    label: 'Sponsor portfolio',
    navTier: 'global',
    layoutMode: 'cro-portfolio',
    group: 'workspace',
    icon: 'network',
    uiKit: 'home',
    apiPrefixes: ['/api/cro/clients', '/api/cro/studies', '/api/cro/submissions'],
    anaToolFamilies: ['plan_submission'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'CRO multi-sponsor rollup. croClients → croStudies → croRegulatorySubmissions, every query org-scoped. Drill into a sponsor; each submission flows through its matching pathway onto the shared Submission Center lifecycle.',
  },
  {
    id: 'etmf',
    label: 'Inspection readiness',
    navTier: 'global',
    layoutMode: 'etmf',
    group: 'workspace',
    icon: 'network',
    uiKit: 'home',
    apiPrefixes: ['/api/etmf'],
    anaToolFamilies: ['generate_inspection_package'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'eTMF inspection-readiness (CRO deliverable). Completeness is assessed against the DIA TMF Reference Model — 11 zones, ICH E6(R2) §8 essential documents — and gaps are filed from the same screen. AnA generates the inspection-readiness package itself rather than showing a dashboard about it. The package ZIP is not built yet: Download produces the in-browser readiness report instead, and says so.',
    engineering: 'assessTmfCompleteness via GET /api/etmf/trials/:trialId/completeness; file gaps via POST .../artifacts. The inspection-package ZIP and artifacts/bulk endpoints are unbuilt; Download degrades live-first.',
  },
  {
    id: 'filings-catalog',
    label: 'Filings catalog',
    navTier: 'global',
    layoutMode: 'filings-catalog',
    group: 'workspace',
    icon: 'clipboardList',
    uiKit: 'home',
    apiPrefixes: ['/api/regulatory/registry'],
    anaToolFamilies: ['get_csr_template', 'plan_submission'],
    sharedContract: '@shared/regulatory/global-document-registry',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'The canonical index of every regulatory filing type, across pharma/biotech, device, IVD and cross-cutting. Each routes into its execution workflow (IND/NDA/BLA/MAA/510k/PMA/De Novo/CER). The count is computed from the registry and shown on the page.',
  },
  {
    // Routable but unregistered until now. `/concept2cure/client-portal` is
    // where auth/redirectUtils.ts sends a `client_user` / `client_admin` after
    // login (CLIENT_FALLBACK), and `surfaceIdFromLocation` carries the segment
    // through unaliased — so `getSurface('client-portal')` returned undefined
    // and V2App's fallback ctxSurface labelled the whole screen "Home". Every
    // external client landed on a breadcrumb reading
    // "Concept2Cure.RI › Biotech & Pharma › Home".
    id: 'client-portal',
    label: 'Client portal (external view)',
    navTier: 'global',
    layoutMode: 'client-portal',
    group: 'workspace',
    icon: 'building',
    uiKit: 'home',
    apiPrefixes: ['/api/client-portal'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes:
      'The read-only workspace a CRO/sponsor shares with its external client. Fixture-free: every value comes from GET /api/client-portal/overview (mounted in register-tenant-routes.ts, tested in server/routes/__tests__/client-portal.test.ts), which resolves the caller\'s client workspace server-side from the verified JWT and returns only that workspace\'s programs, shared deliverables and updates. Renders without the internal AnA rail — a client sees their partner\'s shared view, not the internal assistant.',
  },

  // ─── ui-v2 additions: project ─────────────────────────────────────────────
  {
    id: 'program-journey',
    label: 'Program journey',
    navTier: 'project',
    layoutMode: 'program-journey',
    group: 'workspace',
    icon: 'workflow',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/biopharma/programs', '/api/rim', '/api/regulatory-correspondence', '/api/ectd'],
    anaToolFamilies: ['plan_submission', 'assess_filing_readiness'],
    sharedContract: '@shared/types/submission-api',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The end-to-end biotech/pharma spine — concept to submission to lifecycle. 9 lifecycle stages, each with its agency gate, deliverables and the deep-linked capabilities that serve it, plus program intelligence: CTD readiness, review clock, predicted HAQs, contradictions and blockers.',
  },
  {
    id: 'dispatch-readiness',
    label: 'Dispatch readiness',
    navTier: 'project',
    layoutMode: 'dispatch-readiness',
    group: 'submission',
    icon: 'send',
    uiKit: 'mdx',
    apiPrefixes: ['/api/submissions/sequences'],
    anaToolFamilies: ['assess_dispatch_readiness', 'run_validation'],
    sharedContract: '@shared/types/submission-ui',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The deterministic last gate before transmit. Composes structural validation, unacknowledged Shadow Review criticals and the external eValidator; every input is computed server-side, so the client cannot talk the verdict down. Flags the cleared-but-never-reviewed blind spot.',
    engineering: 'dispatch-gate.ts. Bound to GET /api/submissions/sequences/:seqId/dispatch-readiness.',
  },
  {
    id: 'shadow-review',
    label: 'Shadow review',
    navTier: 'project',
    layoutMode: 'shadow-review',
    group: 'submission',
    icon: 'eye',
    uiKit: 'mdx',
    apiPrefixes: ['/api/submissions/sequences'],
    anaToolFamilies: ['run_shadow_review', 'assess_filing_readiness'],
    sharedContract: '@shared/types/submission-ui',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'AnA simulates the reviewer who will read your submission (5 real lenses: FDA filing / EMA D120 / PMDA / MDR NB / IVDR NB) and scores the two gates that kill a filing — RTF (administrative) and CRL (substantive). Findings are model_assisted; the risk aggregation is the verbatim deterministic aggregateRisk (a single critical saturates).',
    engineering: 'Bound to POST /api/submissions/sequences/:seqId/shadow-review.',
  },
  {
    id: 'decision-lineage',
    label: 'Decision lineage',
    navTier: 'project',
    layoutMode: 'decision-lineage',
    group: 'workspace',
    icon: 'gitBranch',
    uiKit: 'mdx',
    apiPrefixes: ['/api/decision-lineage', '/api/provenance'],
    anaToolFamilies: ['get_document', 'run_validation'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The immutable, Part-11 hash-chained decision trail behind every governed artifact (who decided what, when, on what evidence, signed how). Answer-first defensibility read, then the readable chain of governed decisions (5 node types), then chain-integrity verify + compliance frameworks + eCTD-compatible export.',
    engineering: 'Bound to GET /api/decision-lineage/:entityType/:entityId + verify-chain. Contract ref (not yet a @shared file): @shared/types/decision-lineage.',
  },
  {
    id: 'ivd-completeness',
    label: 'IVD completeness',
    navTier: 'project',
    layoutMode: 'ivd-completeness',
    group: 'workspace',
    icon: 'microscope',
    uiKit: 'mdx',
    apiPrefixes: ['/api/validate-completeness', '/api/c2c/projects'],
    anaToolFamilies: ['assess_filing_readiness', 'draft_section'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'IVDR technical-file completeness (validate-completeness IVDR branch) — GSPR Annex I, Performance Evaluation Report Annex XIII, analytical + clinical performance, scientific validity, PMPF/PMS. IVD-only; derives from the diagnostics IVDR spine. Answer-first CE-marking readiness, not the borrowed device checklist.',
    engineering: 'Contract ref (not yet a @shared file): @shared/regulatory/ivdr.',
  },
  {
    id: 'batch-draft',
    label: 'Parallel drafting',
    navTier: 'project',
    layoutMode: 'batch-draft',
    group: 'authoring',
    icon: 'sparkles',
    uiKit: 'authoring',
    apiPrefixes: ['/api/c2c/documents'],
    anaToolFamilies: ['batch_draft_sections', 'draft_section'],
    sharedContract: '@shared/types/document-contract',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'AnA drafts several dossier sections in parallel (batch_draft_sections) — one Accept card per section, each promoting through the same governed PATCH (saveSection · draftSource=ana). Fans out concurrent streamDraft SSE calls over the live per-section route.',
  },
  {
    id: 'authoring-engine',
    label: 'AnA Authoring Engine',
    navTier: 'project',
    layoutMode: 'authoring-engine',
    group: 'authoring',
    icon: 'sparkles',
    uiKit: 'authoring',
    apiPrefixes: ['/api/document-authoring', '/api/authoring', '/api/coauthor', '/api/templates', '/api/c2c/templates', '/api/task-management'],
    anaToolFamilies: ['draft_section', 'get_csr_template', 'get_nonclinical_template', 'draft_clinical_overview_m2_5'],
    sharedContract: '@shared/types/document-contract',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE, 'motion-discipline'],
    notes: 'End-to-end document suite for the whole CTD pyramid, raw data to final draft. An AI system per document type (no hallucinations, every required element), multi-modal (text/tables/figures/graphs), template-learning, and GxP automations whose non-AI validation logic runs as intended 100% of the time.',
  },
  {
    id: 'inconsistency',
    label: 'Inconsistency Intelligence',
    navTier: 'project',
    layoutMode: 'inconsistency',
    group: 'authoring',
    icon: 'gitCompare',
    uiKit: 'authoring',
    apiPrefixes: ['/api/governed-intelligence', '/api/coauthor', '/api/document-authoring', '/api/task-management'],
    anaToolFamilies: ['assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Change a governed value once and propagate it across every document that cites it. Draft sections update inline; approved and locked sections are flagged for re-approval with a task, on the audit trail.',
    engineering: 'Matches Artos Inconsistency Intelligence / Weave content-update. Contract ref (not yet a @shared file): server/routes/assumption-decision-contradiction.ts.',
  },
  {
    id: 'source-tracer',
    label: 'Source Tracer',
    navTier: 'project',
    layoutMode: 'source-tracer',
    group: 'authoring',
    icon: 'search',
    uiKit: 'authoring',
    apiPrefixes: ['/api/documents/:id/sources', '/api/documents/:id/sources/analyze', '/api/citations/verify'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Sentence-level provenance: every sentence carries a typed source (trial data, literature, regulatory guidance or internal data) with a confidence score, and untraced claims are surfaced. Literature citations are checked against PubMed and CrossRef — an unconfirmed citation is flagged, never assumed. Still sample-backed, and labelled as such until it is wired to live data.',
    engineering: 'POST /sources/analyze (claimsFound); verification via /api/citations/verify (verified|not_found|unverifiable|error). Contract ref (not yet a @shared file): server/routes/sourceLinks.ts + server/routes/citations.ts.',
  },
  {
    id: 'dossier',
    label: 'Dossier',
    navTier: 'project',
    layoutMode: 'dossier',
    group: 'workspace',
    icon: 'folder',
    uiKit: 'mdx',
    apiPrefixes: ['/api/ectd', '/api/documents', '/api/corpus'],
    anaToolFamilies: ['draft_section', 'get_document'],
    sharedContract: '@shared/types/document-contract',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Document-first workspace (Artos/Weave model): eCTD folder tree · submission documents in process with status/version · the live document · Data Room of source files.',
  },
  {
    id: 'conversation-thread',
    label: 'Conversation',
    navTier: 'project',
    layoutMode: 'conversation-thread',
    group: 'workspace',
    icon: 'messageSquare',
    uiKit: 'mdx',
    apiPrefixes: ['/api/conversation-os', '/api/chat', '/api/authoring-actions'],
    anaToolFamilies: [],
    sharedContract: '@shared/schema',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Conversation-os thread: user+AnA messages, artifact proposals (propose→accept→apply), governed mutations, inline document/task/file references that route out. Contract detail: concept2cureConversations/Messages',
  },
  {
    id: 'evidence-search',
    label: 'Evidence search (RAG)',
    navTier: 'project',
    layoutMode: 'vault-workspace',
    group: 'evidence',
    icon: 'search',
    uiKit: null,
    apiPrefixes: ['/api/evidence', '/api/corpus'],
    anaToolFamilies: ['get_evidence_chain'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Ask a question across the corpus — 3-layer memory → gateway → cited answer traced back to source chunks.',
  },
  {
    id: 'haq-manager',
    label: 'Health authority questions',
    navTier: 'project',
    layoutMode: 'haq',
    group: 'submission',
    icon: 'messageSquare',
    uiKit: 'mdx',
    apiPrefixes: ['/api/haq-manager', '/api/regulatory-correspondence', '/api/precedent-engine'],
    anaToolFamilies: ['draft_haq_response', 'search_precedent_responses'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Post-submission review phase: agency IR / Day-120 LoQ / CRL decomposed, source-traced responses with precedent intelligence, governed e-sign into the response package.',
    engineering: 'Contract ref (not yet a @shared file): @shared/types/haq.',
  },
  {
    id: 'nda-cockpit',
    label: 'NDA / BLA filing',
    navTier: 'project',
    layoutMode: 'nda-cockpit',
    group: 'submission',
    icon: 'beaker',
    uiKit: 'mdx',
    apiPrefixes: ['/api/ectd', '/api/biopharma', '/api/submission', '/api/shadow'],
    anaToolFamilies: ['assess_filing_readiness', 'run_shadow_review'],
    sharedContract: '@shared/types/submission-api',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'NDA/BLA filing cockpit: CTD M1–5 readiness, Module 1 admin set (356h), PDUFA review clock, Refuse-to-File risk (shadow review).',
  },
  {
    id: 'maa-cockpit',
    // BP-W1-5: was 'MAA / non-US Module 1'. Module 1 is regional by definition —
    // "non-US Module 1" is not one thing — and the surface itself is already a
    // per-agency checklist, so the name now says so.
    label: 'MAA Module 1 (Regional)',
    navTier: 'project',
    layoutMode: 'maa-cockpit',
    group: 'submission',
    icon: 'globe',
    uiKit: null,
    apiPrefixes: ['/api/global-ri'],
    anaToolFamilies: ['module1'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Regional marketing-application administrative module (eCTD Module 1) — per-agency required-component checklist for EMA/PMDA/MHRA/TGA/HC/Swissmedic/NMPA over the global-RI regional-module1-requirements engine.',
  },
  {
    id: 'device-workstream',
    label: 'Medical Device & IVD',
    navTier: 'project',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'stethoscope',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx', '/api/510k/estar', '/api/510k/device', '/api/cer', '/api/cerv2', '/api/ivdr', '/api/manufacturing'],
    anaToolFamilies: [],
    sharedContract: '@shared/types/predicate-intelligence',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The MDX workstream — one door. Programs portfolio with classification + 510(k)/PMA/CER/De Novo pathway tabs, predicate intelligence, eSTAR/Annex XIV editors. Built in the MDX kit.',
  },
  /* ── The device kit's own destinations ──
     These twelve were surfaces the kit rendered but the product could not
     route to. `mdx/App.tsx` drew a second rail with fifteen entries; only five
     had v2 ids, so PMA, software lifecycle, UDI, post-market vigilance,
     device engineering, pre-submission and the validation blockers view — some
     1,900 lines against live endpoints — were reachable by nothing a user
     could click, and `pre-sub` only if localStorage happened to hold it. The
     second rail is gone; these are how the shell reaches what it drew. */
  {
    id: 'device-pma',
    label: 'PMA submissions',
    navTier: 'project',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'shieldCheck',
    uiKit: 'mdx',
    apiPrefixes: ['/api/regulatory-programs'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'PMA module status and trial metrics over the program read-model. Had no v2 entry point before the kit shell was retired.',
  },
  {
    id: 'device-clinical-studies',
    label: 'Device clinical studies',
    navTier: 'project',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'stethoscope',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx', '/api/study-design'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Study list, detail, summaries, archetypes and RBM attention. Six endpoints; distinct from clinical-ops, which is the drug-trial operations surface.',
  },
  {
    id: 'device-software',
    label: 'Software lifecycle',
    navTier: 'project',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'code',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'IEC 62304 software lifecycle and completeness summary. The only implementation in the product.',
  },
  {
    id: 'device-engineering',
    label: 'Device engineering',
    navTier: 'project',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'wrench',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Program-scoped engineering rollup. Distinct from design-controls and human-factors, which are org-scoped registers.',
  },
  {
    id: 'device-udi',
    label: 'UDI & device identification',
    navTier: 'specialist',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'barcode',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'UDI/GUDID summary and document catalog. The only UDI surface; labeling itself lives on the labeling surface.',
  },
  {
    id: 'device-postmarket',
    label: 'Post-market vigilance',
    navTier: 'specialist',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'shieldAlert',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx', '/api/capa-mdr'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Device MDR/MAUDE vigilance and CAPA triage. A different regulatory regime from pv-cockpit, which is drug pharmacovigilance.',
  },
  {
    id: 'device-presub',
    label: 'Pre-submission (Q-Sub)',
    navTier: 'project',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'messageSquare',
    uiKit: 'mdx',
    apiPrefixes: ['/api/q-sub'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Q-Sub meeting manager. Previously reachable only through a persisted localStorage value — no rail, tab or palette entry existed.',
  },
  {
    id: 'device-vault',
    label: 'Device artifact vault',
    navTier: 'project',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'vault',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Reads the mdx_vault store with per-artifact version history. Named separately from `vault` because the two read different document stores; converging the stores is a backend decision, and until it is made two names are honest and one is not.',
  },
  {
    id: 'device-tasks',
    label: 'Device submission workload',
    navTier: 'project',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'clipboardList',
    uiKit: 'mdx',
    apiPrefixes: ['/api/submission-ops'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The submission-ops workload slice. Deliberately NOT called "Tasks" — task-board is the task board, and two rail entries with the same name is the defect this convergence removed.',
  },
  {
    id: 'device-validation',
    label: 'Submission blockers',
    navTier: 'project',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'shieldAlert',
    uiKit: 'mdx',
    apiPrefixes: ['/api/submission-ops'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Open blockers across programs. The only blockers view in the product.',
  },
  {
    id: 'device-submission',
    label: 'Device submission packages',
    navTier: 'project',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'rocket',
    uiKit: 'mdx',
    apiPrefixes: ['/api/submission-ops'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Package readiness and milestones from submission-ops. submission-center is the eCTD sequence dispatch surface — a later lifecycle stage over different endpoints.',
  },
  {
    id: 'device-analytics',
    label: 'Device pathway analytics',
    navTier: 'specialist',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'barChart3',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Pathway-scoped device analytics. insights and report-engine answer protocol and report-run questions instead.',
  },
  {
    id: 'protocol-dev',
    label: 'Protocol development',
    navTier: 'project',
    layoutMode: 'protocol-dev',
    group: 'authoring',
    icon: 'clipboardList',
    uiKit: 'authoring',
    apiPrefixes: ['/api/protocol-development', '/api/protocol-soa', '/api/protocol-risks', '/api/protocol-milestones', '/api/protocol-budget', '/api/protocol-amendments', '/api/protocol-deviations', '/api/protocol-reviews', '/api/protocol-consent', '/api/protocol-export'],
    anaToolFamilies: ['create_protocol_document', 'update_protocol_section', 'review_protocol_completeness', 'finalize_protocol_document', 'add_soa_assessment', 'review_soa_matrix'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Protocol authoring hub (C2C-17..22): full eCTD-style section tree, SoA grid, risk register (5×5), milestones, budget/feasibility, amendments, deviations/CAPA, reviews, informed consent — deterministic completeness gate on finalize (ICH M11 / 45 CFR 46 / PHS Policy).',
  },
  {
    id: 'research-admin',
    label: 'Research administration',
    navTier: 'project',
    layoutMode: 'research-admin',
    group: 'collaboration',
    icon: 'network',
    uiKit: 'mdx',
    apiPrefixes: ['/api/committees', '/api/coverage-analysis', '/api/grant-finder', '/api/citi-training', '/api/protocol-portfolio'],
    anaToolFamilies: ['convene_committee_meeting', 'cast_committee_vote', 'finalize_committee_determination', 'review_coverage_analysis', 'find_grant_opportunities', 'review_training_matrix', 'review_protocol_portfolio_analytics'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Research-administration workspace (C2C-14/15/16/01-02): IRB/IACUC/IBC governance with convene→quorum→voting poll + finalize determination, Medicare coverage analysis (NCD 310.1) billing grid, intelligent grant finder (fit scoring), CITI training matrix, continuing-review portfolio analytics.',
  },
  {
    id: 'pyramid',
    label: 'Submission pyramid',
    navTier: 'project',
    layoutMode: 'pyramid',
    group: 'submission',
    icon: 'workflow',
    uiKit: null,
    apiPrefixes: ['/api/v1/pyramids', '/api/v1/global-pyramids', '/api/v1/projects/:id/pyramid'],
    anaToolFamilies: ['plan_submission'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'contract-ready',
    compliance: [A11Y, TONE, 'motion-discipline'],
    notes: 'Deterministic submission work breakdown — submission-type selector, dashboard (progress ring, phase strip, risk gauge, next-available tasks), phase-to-task drill-down with a full-metadata detail sheet (risk, CTD bindings, guidance, dependencies, deliverables), analytics (resources and bottlenecks, document coverage, critical path), and the global pyramid browser. Task status is the only state the browser owns.',
    engineering: 'Contract ref (not yet a @shared file): services/regulatory/SubmissionPyramidEngine.ts, globalPyramids.ts, submission-type-bridge.ts.',
  },
  {
    id: 'registrations',
    label: 'Registrations',
    navTier: 'project',
    layoutMode: 'registrations',
    group: 'lifecycle',
    icon: 'globe',
    uiKit: 'mdx',
    apiPrefixes: ['/api/rim', '/api/global-ri', '/api/global-markets'],
    anaToolFamilies: ['global_ri_market_access'],
    sharedContract: '@shared/types/global-ri-api',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Global registration lifecycle: market authorization status, agency review clocks, renewals/variations, HA commitments, reliance-pathway strategy.',
  },
  {
    id: 'market-access',
    label: 'Market access',
    navTier: 'project',
    layoutMode: 'market-access',
    group: 'lifecycle',
    icon: 'creditCard',
    uiKit: 'mdx',
    apiPrefixes: ['/api/market-access'],
    anaToolFamilies: ['global_ri_market_access', 'compose_value_dossier'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Commercial bridge: payer coverage (CMS NCD/LCD, private, HTA), value-dossier composer (AMCP/NICE/budget-impact), coding strategy (CPT/PLA/HCPCS), access sequencing.',
  },
  {
    id: 'change-assessment',
    label: 'Change assessment',
    navTier: 'project',
    layoutMode: 'change-assessment',
    group: 'lifecycle',
    icon: 'gitBranch',
    uiKit: 'mdx',
    apiPrefixes: ['/api/change-propagation', '/api/rim'],
    anaToolFamilies: ['assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Change impact engine: FDA "When to Submit a 510(k) for a Change" (2017) + EU MDR significant-change (MDCG 2020-3) determinations → new submission vs document-to-file.',
  },
  {
    id: 'quality',
    label: 'Quality & Assurance',
    navTier: 'project',
    layoutMode: 'quality',
    group: 'quality-cmc',
    icon: 'shieldCheck',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx/qms'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Quality & Assurance: the SOP / controlled-document register (periodic review, read-and-understood training) and Change control (the change-control log + lifecycle flowchart, ICH Q10 / EU GMP Annex 15, linking changes to deviations, CAPAs and validation records).',
    engineering: 'Backed by /api/mdx/qms/*.',
  },
  {
    id: 'doc-journey',
    label: 'Document journey',
    navTier: 'project',
    layoutMode: 'doc-journey',
    group: 'authoring',
    icon: 'gitBranch',
    uiKit: 'mdx',
    apiPrefixes: ['/api/authoring', '/api/workflow', '/api/submission', '/api/audit'],
    anaToolFamilies: ['draft_section', 'assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'One document, ideation → submission: ideate → outline → AnA draft → revise → review → QC → approve (§11 e-sign) → assemble (eCTD leaf) → transmit (ESG). Document state visible at every stage.',
  },
  {
    id: 'labeling-pi',
    label: 'Prescribing information',
    navTier: 'project',
    layoutMode: 'labeling-pi',
    group: 'authoring',
    icon: 'fileText',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx', '/api/spl-fhir', '/api/rim'],
    anaToolFamilies: ['draft_label', 'draft_uspi'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'USPI (PLLR / 21 CFR 201.57), EU SmPC (QRD), SPL. End-of-review agency labeling negotiation (sponsor vs FDA redline). The label as the document.',
  },
  {
    id: 'labeling-smpc',
    label: 'EU SmPC (QRD)',
    navTier: 'project',
    layoutMode: 'labeling-smpc',
    group: 'authoring',
    icon: 'fileText',
    uiKit: null,
    apiPrefixes: ['/api/labeling-smpc'],
    anaToolFamilies: ['draft_label'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'EU Summary of Product Characteristics — QRD template section tree (1–10) with per-section authoring status + submission-readiness over the required sections. EU companion to labeling-pi (USPI).',
  },
  {
    id: 'agency-meetings',
    label: 'Agency meetings',
    navTier: 'project',
    layoutMode: 'agency-meetings',
    group: 'lifecycle',
    icon: 'users',
    uiKit: 'mdx',
    apiPrefixes: ['/api/ha-interactions', '/api/rim'],
    anaToolFamilies: ['draft_briefing_book', 'prepare_meeting_request'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Agency interactions: Pre-IND/INTERACT/Type A-D/EOP2/pre-NDA-BLA, device Q-Sub, EMA Scientific Advice. Briefing book document + questions, minutes + commitments back to the dossier.',
  },
  {
    id: 'communication-center',
    label: 'Communication Center',
    navTier: 'project',
    layoutMode: 'communication-center',
    group: 'submission',
    icon: 'mail',
    uiKit: null,
    apiPrefixes: ['/api/ha-interactions', '/api/regulatory-correspondence', '/api/submission-ops'],
    anaToolFamilies: ['draft_agency_response', 'plan_crl_response'],
    sharedContract: '@shared/types/communication-center',
    discoveryCatalog: 'AgencyCommunicationEventRecord',
    readiness: 'contract-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The regulated FDA↔client loop: agency communications (9 source types) auto-generating tasks, submission lifecycle incl. CRL/RTF/denial (rejected_or_remediation) → response → resubmit, HA interactions + PMR/PMC/REMS commitments, authority profiles.',
  },
  {
    id: 'rbm',
    label: 'Risk-based monitoring',
    navTier: 'project',
    layoutMode: 'rbm',
    group: 'clinical',
    icon: 'shieldCheck',
    uiKit: 'risk',
    apiPrefixes: ['/api/mdx/rbm-assessments', '/api/mdx/rbm-kris', '/api/mdx/rbm-qtls', '/api/mdx/rbm-signals', '/api/mdx/rbm-site-risk', '/api/mdx/rbm-monitoring-plans', '/api/mdx/rbm-summary', '/api/mdx/rbm-report', '/api/mdx/rbm-attention'],
    anaToolFamilies: ['run_rbm_assessment', 'assess_site_risk', 'evaluate_kris_qtls', 'generate_rbm_plan', 'prioritize_monitoring_queries', 'run_central_monitoring', 'scan_patient_profiles', 'generate_rbm_report', 'get_rbm_attention'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE, 'motion-discipline'],
    notes: 'ICH E6(R3) RBQM domain shell — overview, risk review report, RACT, KRIs, QTLs, central monitoring, patient profiles, site risk, site oversight and monitoring plan, read through one aggregated board. Every score is produced deterministically; assessment and plan approvals are Part 11 governed (reason-for-change plus e-signature). Every edit is a real write followed by a re-read — nothing is held optimistically in the browser.',
    engineering: 'Routes: /api/mdx/rbm-*, aggregated by GET /api/mdx-rbm/rbm-board/:programId. 5 deterministic engines. Write layer: client/src/concept2cure/v2/surfaces/rbmWrites.tsx.',
  },
  {
    id: 'orchestration',
    label: 'Orchestration & readiness',
    navTier: 'project',
    layoutMode: 'orchestration',
    group: 'review',
    icon: 'workflow',
    uiKit: null,
    apiPrefixes: ['/api/orchestration', '/api/approval-workflows', '/api/submission-readiness'],
    anaToolFamilies: ['assess_filing_readiness'],
    sharedContract: '@shared/schema/orchestration',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Persisted workflow engine: workflowRuns (steps · blockers · diffs · pause/resume/retry), approvalCheckpoints (manual/role/quorum/auto), readiness rules + evaluations → overall score, blocker count, isReady gate before filing.',
  },
  {
    id: 'reg-change',
    label: 'Regulatory change intelligence',
    navTier: 'project',
    layoutMode: 'reg-change',
    group: 'lifecycle',
    icon: 'bell',
    uiKit: null,
    apiPrefixes: ['/api/external-intelligence', '/api/regulatory-intelligence'],
    anaToolFamilies: ['assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Portfolio horizon scan: monitors FDA guidance, ISO/IEC revisions, EU MDCG/MDR-IVDR and statutory changes; assesses impact and resolves each to an action document (gap analysis, transition plan, update task) — never a passive feed.',
  },
  {
    id: 'insights',
    label: 'Reporting & analytics',
    navTier: 'project',
    layoutMode: 'insights',
    group: 'evidence',
    icon: 'barChart',
    uiKit: null,
    apiPrefixes: ['/api/report-os', '/api/insights'],
    anaToolFamilies: ['list_report_types', 'generate_report', 'portfolio_readiness', 'compare_regions', 'get_prediction', 'explain_blockers'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'AnA Reporting Canvas — conversational governed reporting over the Report-OS render model, with a per-segment catalog, entitlement tiers and best-practice packs.',
    engineering: 'Contract ref (not yet a @shared file): server/services/report-os/taxonomy.ts.',
  },
  {
    id: 'pediatric',
    label: 'Pediatric (PIP / PSP)',
    navTier: 'project',
    layoutMode: 'pediatric',
    group: 'lifecycle',
    icon: 'users',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/biopharma/pediatric', '/api/rim'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    // Was 'kit-only', which Coverage renders to customers as "Design prototype
    // exists; backend binding map being assembled". Untrue: BiopharmaSpecialty.tsx binds 12 live reads/writes
    // against audited routes. sharedContract is still null, so this stops at
    // routes-ready rather than contract-ready.
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'FDA §505B PREA / iPSP and EMA PIP: plans, deferrals, waivers, extrapolation rationale and PREA milestones.',
  },
  {
    id: 'orphan',
    label: 'Orphan & rare',
    navTier: 'project',
    layoutMode: 'orphan',
    group: 'lifecycle',
    icon: 'sparkles',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/biopharma/orphan', '/api/rim'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    // Was 'kit-only', which Coverage renders to customers as "Design prototype
    // exists; backend binding map being assembled". Untrue: BiopharmaSpecialty.tsx binds 12 live reads/writes
    // against audited routes. sharedContract is still null, so this stops at
    // routes-ready rather than contract-ready.
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Orphan-drug / rare-disease designations across FDA/EMA/PMDA, RPD priority-review vouchers & grants, and patient-advocacy engagement.',
  },
  {
    id: 'lifecycle-mgmt',
    label: 'Lifecycle management',
    navTier: 'project',
    layoutMode: 'lifecycle-mgmt',
    group: 'lifecycle',
    icon: 'history',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/biopharma/supplements', '/api/change-assessment', '/api/rim'],
    anaToolFamilies: ['assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    // Was 'kit-only', which Coverage renders to customers as "Design prototype
    // exists; backend binding map being assembled". Untrue: BiopharmaSpecialty.tsx binds 12 live reads/writes
    // against audited routes. sharedContract is still null, so this stops at
    // routes-ready rather than contract-ready.
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Post-approval: supplements/variations (sBLA, Type II/IB, CBE-30), CMC change control classified against ICH Q12, and renewal cycles (PADER, 5-year, re-examination).',
  },
  {
    id: 'clinical-ops',
    label: 'Clinical operations',
    navTier: 'project',
    layoutMode: 'clinical-ops',
    group: 'clinical',
    icon: 'users',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/protocol-development', '/api/mdx/rbm-site-risk', '/api/protocol-deviations'],
    anaToolFamilies: ['assess_site_risk'],
    sharedContract: null,
    discoveryCatalog: null,
    // Was 'kit-only', which Coverage renders to customers as "Design prototype
    // exists; backend binding map being assembled". Untrue: ClinicalOps.tsx binds 5 live reads/writes
    // against audited routes. sharedContract is still null, so this stops at
    // routes-ready rather than contract-ready.
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Clinical-development operations: studies & enrollment, study sites with RBM risk linkage, DSMB / interim reviews, and protocol deviations with CAPA. Structured data entry for sites and deviations.',
  },
  {
    id: 'nonclinical',
    label: 'Nonclinical / Module 4',
    navTier: 'project',
    layoutMode: 'nonclinical',
    group: 'clinical',
    icon: 'microscope',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/nonclinical', '/api/preclinical', '/api/documents'],
    anaToolFamilies: ['get_nonclinical_template', 'calculate_ttc'],
    sharedContract: null,
    discoveryCatalog: null,
    // Was 'kit-only', which Coverage renders to customers as "Design prototype
    // exists; backend binding map being assembled". Untrue: Nonclinical.tsx binds 7 live reads/writes
    // against audited routes. sharedContract is still null, so this stops at
    // routes-ready rather than contract-ready.
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'IND-enabling & CTD Module 4: GLP study registry with finding classification and SEND status, SEND 12-domain conformance, the Module 2.6 written/tabulated summary builder, and Module 4 placement. Structured data entry for studies.',
  },

  /* ── PDEV → IND sub-surfaces ───────────────────────────────────────────────
   *
   * `pdev` was registered; its seven destinations were not. All seven ship as
   * SURFACE_VIEWS entries (surfaceViews.ts) rendering PdevSurfaces, and none is
   * a DEEP_LINK_ALIAS — so `surfaceIdFromLocation` handed V2App an id that
   * `getSurface` could not resolve, and the fallback ctxSurface labelled every
   * one of them "Home". Four are reached by a click today (the Overview's
   * workstream cards call `onSelectWorkstream` → `pdev-cmc` /
   * `pdev-nonclinical` / `pdev-clinical` / `pdev-regulatory`, PdevSurfaces.tsx
   * maps the kit's nav vocabulary back to surface ids); the other three had no
   * in-app entry point at all once the kit's own rail was removed, because ⌘K
   * ranks off THIS registry (Shell.tsx CmdK → UI_SURFACES) and they were absent
   * from it. Registering them is what makes them reachable.
   *
   * Family shape mirrors the device-* family: shared `layoutMode` (the kit host
   * they all mount), shared `group`/`uiKit`, distinct label/icon/prefixes.
   *
   * readiness `routes-ready` is claimed, not assumed. /api/pdev is mounted
   * unconditionally and auth-gated (register-regulatory-routes.ts — no feature
   * flag, unlike crl-library's ENABLE_CLINICAL_REGULATORY_GRAPH); every route
   * below was read in server/routes/pdev/pdev-routes.ts; the services behind
   * them carry nine dedicated suites in server/services/pdev/__tests__/ plus a
   * pglite integration test for the view assembler; and the client binds them
   * live in pdev/hooks/usePdevData.ts with no fixture fallback
   * (v2/__tests__/pdevIndNoFixtures.test.tsx). The parent `pdev` entry in
   * ui-surface-registry.ts still reads `kit-only` with a note about a prototype
   * in ui_kits/pdev; that is now stale but is a claim about the Overview
   * surface, so it is left for a separate, evidenced pass rather than flipped
   * here as a side effect.
   *
   * anaToolFamilies are the real tool names from PDEV_COMMAND_METADATA
   * (server/services/ana-ri/pdev-command-handlers.ts), which command-executor.ts
   * spreads into the live ANA tool table — not aspirational names.
   */
  {
    id: 'pdev-cmc',
    label: 'PDEV CMC workstream',
    navTier: 'project',
    layoutMode: 'pdev',
    group: 'submission',
    icon: 'beaker',
    uiKit: 'pdev',
    apiPrefixes: ['/api/pdev/programs', '/api/pdev/registry'],
    anaToolFamilies: ['pdev.program.workstream', 'pdev.activity.set_state', 'pdev.activity.ai_draft'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes:
      'The CMC slice of the closed-enum PDEV → IND activity registry: each activity with its state, evidence links and provenance, drilled from GET /api/pdev/programs/:id/workstreams/cmc. State changes go through the existing auditService hash chain. Distinct from the `cmc` surface (CTD Module 3 authoring) — this is IND-readiness activity tracking, not the dossier section.',
  },
  {
    id: 'pdev-nonclinical',
    label: 'PDEV nonclinical workstream',
    navTier: 'project',
    layoutMode: 'pdev',
    group: 'submission',
    icon: 'microscope',
    uiKit: 'pdev',
    apiPrefixes: ['/api/pdev/programs', '/api/pdev/registry'],
    anaToolFamilies: ['pdev.program.workstream', 'pdev.activity.set_state', 'pdev.activity.ai_draft'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes:
      'The nonclinical slice of the PDEV → IND activity registry, drilled from GET /api/pdev/programs/:id/workstreams/nonclinical. Distinct from the `nonclinical` surface (CTD Module 4 / SEND authoring) — this tracks IND-enabling activity state, evidence and provenance.',
  },
  {
    id: 'pdev-clinical',
    label: 'PDEV clinical workstream',
    navTier: 'project',
    layoutMode: 'pdev',
    group: 'submission',
    icon: 'stethoscope',
    uiKit: 'pdev',
    apiPrefixes: ['/api/pdev/programs', '/api/pdev/registry'],
    anaToolFamilies: ['pdev.program.workstream', 'pdev.activity.set_state', 'pdev.activity.ai_draft'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes:
      'The clinical slice of the PDEV → IND activity registry, drilled from GET /api/pdev/programs/:id/workstreams/clinical. Distinct from `clinical-ops` (studies, sites, DSMB, deviations) — this tracks the IND-readiness activities and their evidence.',
  },
  {
    id: 'pdev-regulatory',
    label: 'PDEV regulatory workstream',
    navTier: 'project',
    layoutMode: 'pdev',
    group: 'submission',
    icon: 'shieldCheck',
    uiKit: 'pdev',
    apiPrefixes: ['/api/pdev/programs', '/api/pdev/registry'],
    anaToolFamilies: ['pdev.program.workstream', 'pdev.activity.set_state', 'pdev.activity.ai_draft'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes:
      'The regulatory slice of the PDEV → IND activity registry, drilled from GET /api/pdev/programs/:id/workstreams/regulatory. Activity state, attached evidence and the provenance trace behind each item.',
  },
  {
    id: 'pdev-ind-assembly',
    label: 'IND assembly readiness',
    navTier: 'project',
    layoutMode: 'pdev',
    group: 'submission',
    icon: 'rocket',
    uiKit: 'pdev',
    apiPrefixes: ['/api/pdev/programs'],
    anaToolFamilies: ['pdev.program.ind_assembly', 'pdev.ind_assembly.compile'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes:
      'Module 1–5 IND assembly readiness from GET /api/pdev/programs/:id/ind-assembly, with a governed compile (POST .../ind-assembly/compile). Named "readiness" deliberately, per the route\'s own doc comment — it reports what is ready to assemble and is NOT eCTD publishing; ectd-compile and ectd-publishing own that.',
  },
  {
    id: 'pdev-contradictions',
    label: 'Contradictions registry',
    navTier: 'project',
    layoutMode: 'pdev',
    group: 'submission',
    icon: 'alertTriangle',
    uiKit: 'pdev',
    apiPrefixes: ['/api/pdev/programs'],
    anaToolFamilies: ['pdev.program.contradictions'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes:
      'Read-side adapter over the existing contradiction engine, scoped to a PDEV program (GET /api/pdev/programs/:id/contradictions). Not a second engine — the same findings the `inconsistency` surface reads, framed against the IND program. Had no in-app entry point before this entry: the kit rail that used to link it was removed in the one-shell convergence.',
  },
  {
    id: 'pdev-fda-interactions',
    label: 'FDA interactions',
    navTier: 'project',
    layoutMode: 'pdev',
    group: 'submission',
    icon: 'messageSquare',
    uiKit: 'pdev',
    apiPrefixes: ['/api/pdev/programs'],
    anaToolFamilies: [
      'pdev.program.fda_interactions',
      'pdev.fda_feedback.proposals',
      'pdev.fda_feedback.apply',
    ],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes:
      'Chronological FDA touchpoint stream for one IND program (q_submissions family + fda_communications) via GET /api/pdev/programs/:id/fda-interactions, with AnA-derived feedback proposals and a governed apply (POST .../fda-feedback/apply). Program-scoped and IND-specific; `agency-meetings` is the cross-program meeting manager.',
  },

  // ─── ui-v2 additions: specialist ─────────────────────────────────────────────
  {
    id: 'intelligence-catalog',
    label: 'Intelligence catalog',
    navTier: 'specialist',
    layoutMode: 'intelligence-catalog',
    group: 'intelligence',
    icon: 'shieldCheck',
    uiKit: 'intelligence',
    apiPrefixes: ['/api/ana'],
    anaToolFamilies: ['calculate_ttc', 'define_estimand', 'assess_pv_causality'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Read-only reference for the deterministic tools AnA can run, grouped by domain, with the determinism-pedigree trust system and the shared result-rendering pattern.',
    engineering: 'Contract ref (not yet a @shared file): server/services/ana/tool-pedigree.ts.',
  },
  {
    id: 'pharmacovigilance',
    label: 'Pharmacovigilance',
    navTier: 'specialist',
    layoutMode: 'pharmacovigilance',
    group: 'safety-pv',
    icon: 'shieldAlert',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/pharmacovigilance', '/api/safety-narratives'],
    anaToolFamilies: ['assess_pv_causality'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Safety surveillance: signal detection (PRR/FAERS/EudraVigilance), PSUR/PBRER aggregate-report cycles, expedited 7/15-day submissions across approved products.',
  },
  {
    id: 'design-controls',
    label: 'Design controls (DHF)',
    navTier: 'specialist',
    layoutMode: 'design-controls',
    group: 'device',
    icon: 'gitBranch',
    uiKit: null,
    apiPrefixes: ['/api/design-risk'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: '21 CFR 820.30 DHF — design inputs/outputs/verification/validation traceability matrix + completeness assessment.',
  },
  {
    id: 'human-factors',
    label: 'Human factors (IEC 62366-1)',
    navTier: 'specialist',
    layoutMode: 'human-factors',
    group: 'device',
    icon: 'users',
    uiKit: null,
    apiPrefixes: ['/api/human-factors'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'IEC 62366-1 HFE/UE — use-related risk analysis (critical tasks + summative gate) + HFE/UE file completeness.',
  },

  // ─── ui-v2 additions: admin ─────────────────────────────────────────────
  {
    id: 'licensing',
    label: 'Plans & licensing',
    navTier: 'admin',
    layoutMode: 'setup',
    group: 'admin',
    icon: 'creditCard',
    uiKit: null,
    apiPrefixes: ['/api/module-subscriptions', '/api/billing'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Plan tiers, seat licensing, module entitlements, upgrade/downgrade.',
  },
  {
    /* Routable but unregistered until now: the account menu's "Licensing"
       entry (Shell.tsx ACCT_ITEMS, org-admin gated) navigated here, and
       `getSurface('master-licensing')` returned undefined — so the platform
       licensing console rendered under a breadcrumb reading "Home" and had no
       ⌘K row. Distinct from `licensing` (Plans & licensing), which is the
       customer-facing plan/upgrade view; this is the platform-admin control
       room that DEFINES the tiers. The surface re-checks platform-admin
       server-side on every read and write; registration only names it. */
    id: 'master-licensing',
    label: 'Master licensing',
    navTier: 'admin',
    layoutMode: 'master-licensing',
    group: 'admin',
    icon: 'checkSquare',
    uiKit: null,
    apiPrefixes: ['/api/admin/master/licensing', '/api/admin/master/feature-flags', '/api/module-access-requests'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes:
      'Platform-admin licensing control room (MasterLicensing.tsx): the module × tier packaging matrix (minTier per module), per-tenant tier + module-by-module effective verdicts with reasons, the platform-scope access-request queue, trials, feature_toggles flags, enforcement observations and the decision history. Every list is a live read of /api/admin/master/* — a failed read renders ErrorState with retry, never an empty table — and every mutation goes through GovernedConfirmDialog with the server’s own reason-for-change floor (min 3 chars), audit-logged verbatim.',
  },
  {
    /* Where a member’s request for a locked module lands. The queue shipped as
       a registered SURFACE_VIEWS component with an account-menu entry
       (Shell.tsx, org-admin gated) but no registry row, so the administrator
       arrived under a breadcrumb reading "Home" with no ⌘K row. Org-scoped
       server-side; scope="all" of the same component is the panel inside
       master-licensing (licensing/AccessRequestsPanel.tsx). */
    id: 'access-requests',
    label: 'Access requests',
    navTier: 'admin',
    layoutMode: 'access-requests',
    group: 'admin',
    icon: 'clipboardList',
    uiKit: null,
    apiPrefixes: ['/api/module-access-requests'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes:
      'The org-admin queue for module access requests (AccessRequests.tsx): who asked for which locked app, in their own words, with approve/decline through GovernedConfirmDialog (reason stored with the decision, written to the Part 11 chain server-side). Nothing optimistic — an approval renders granted only after the server grants. Fail closed: a failed read is ErrorState with retry, never mistaken for "nobody is waiting".',
  },
  {
    id: 'training',
    label: 'Training & enablement',
    navTier: 'admin',
    layoutMode: 'setup',
    group: 'admin',
    icon: 'book',
    uiKit: null,
    apiPrefixes: ['/api/enablement', '/api/ana'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'planned',
    compliance: [A11Y, TONE],
    notes: 'Guided tours, learning paths, certifications, and AnA tutor.',
  },
  {
    id: 'coverage',
    label: 'Codebase coverage',
    navTier: 'admin',
    layoutMode: 'coverage',
    group: 'admin',
    icon: 'grid',
    uiKit: null,
    apiPrefixes: ['/api/module-subscriptions'],
    anaToolFamilies: [],
    sharedContract: '@shared/constants/ui-surface-registry',
    discoveryCatalog: null,
    readiness: 'contract-ready',
    compliance: [A11Y, TONE],
    notes: 'The 33 canonical surfaces + real API prefixes + readiness, cross-referenced with what is built and wired here. Install/coverage tracker.',
  },
  {
    id: 'admin-console',
    label: 'Admin console',
    navTier: 'admin',
    layoutMode: 'admin-console',
    group: 'admin',
    icon: 'users',
    uiKit: null,
    apiPrefixes: ['/api/admin/access', '/api/admin/scim-tenants', '/api/api-keys', '/api/setup'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Designate personnel (platform_role_grants, governed+audited), SSO/SCIM, security, module subscriptions, API keys, audit.',
  },
  {
    id: 'onboarding',
    label: 'Onboarding',
    navTier: 'admin',
    layoutMode: 'onboarding',
    group: 'admin',
    icon: 'rocket',
    uiKit: null,
    apiPrefixes: ['/api/setup', '/api/billing/checkout', '/api/billing/dtc-checkout'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Client onboarding wizard: org archetype → pricing model → tier → seats → personnel → module provisioning → activate.',
  },
  {
    id: 'onboarding-ingest',
    label: 'Set up from a document',
    navTier: 'admin',
    layoutMode: 'onboarding',
    group: 'admin',
    icon: 'upload',
    uiKit: null,
    apiPrefixes: ['/api/onboarding'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes:
      'Upload an onboarding document; AnA proposes values whose provenance it verified against the document text, the human reviews and approves, and approved org-profile fields are applied through the governed, audited commit.',
  },
  {
    id: 'usage',
    label: 'Usage & limits',
    navTier: 'admin',
    layoutMode: 'usage',
    group: 'admin',
    icon: 'barChart',
    uiKit: null,
    apiPrefixes: ['/api/billing/usage/summary', '/api/billing/weekly-usage', '/api/billing/rate-limits'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Plan usage limits, weekly caps, usage credits and rate limits by tier.',
    engineering: 'billing-dashboard.ts router, mounted at /api/billing (verified against register-inline-routes 2026-07-05).',
  },
  {
    /* Wired into the shell (surfaceViews.ts:347, NAV_HIDDEN, and the
       "Review & govern" group of every segment). Registered against what it
       actually mounts.

       NOTE (2026-08-17): the comment here used to say the surface was "never
       registered", so `getSurface` returned undefined. That was wrong — an
       older entry already existed in the v1 half of the registry, and because
       SURFACE_BY_ID is built with Object.fromEntries (LAST wins) this entry was
       already the one getSurface returned. The two together broke the
       uniqueness invariant and listed the surface under two different navTiers
       at once. The v1 duplicate is deleted and its substantive notes merged
       here; this entry's placement is unchanged, so nothing moves on screen. */
    id: 'mission-control',
    label: 'Mission control',
    navTier: 'project',
    layoutMode: 'mission-control',
    group: 'review',
    icon: 'gauge',
    uiKit: null,
    apiPrefixes: ['/api/mission-control'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes:
      'Cross-program standing: what is blocking, what moves next. Router mounted at /api/mission-control behind authenticateToken (register-advanced-platform-routes.ts). ' +
      'The regulatory program engine — programs, server-computed readiness across nine ' +
      'dimensions, and the artifacts, risks, decisions and stale dependencies behind that ' +
      'score. Distinct from `projects` (/api/c2c/projects), which models the workspace a ' +
      'team works inside rather than the regulatory program.',
  },
  {
    /* Same as mission-control: present in the shell and in the segment
       "Intelligence" groups. A v1 duplicate of this id also existed and is
       deleted (see the note above); its notes are merged below. */
    id: 'filing-strategy',
    label: 'Global filing strategy',
    navTier: 'project',
    layoutMode: 'filing-strategy',
    group: 'intelligence',
    icon: 'globe',
    uiKit: null,
    apiPrefixes: ['/api/regulatory-precedent-intelligence'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes:
      'Cross-jurisdictional filing sequence, agency divergence and reliance pathways over the regulatory_intel.* tables. Those tables ship EMPTY — this is storage plus query for a record the tenant builds, not a shipped knowledge base (see migrations/20260814l_catalog_filing_strategy.sql). ' +
      'Reads the cross-jurisdictional and confidence families only — the CRL/RTF/EMA/' +
      'advisory-committee endpoints on the same router are NOT authoritative ' +
      '(see docs/adr/0013).',
  },
];
