/**
 * Global UI Surface Registry — the one map design installs against.
 *
 * Framework-agnostic, single source of truth that ties every installable UI
 * surface to the things a designer/frontend needs to wire it up *without*
 * spelunking the backend:
 *
 *   - the real app-shell key it renders under (`layoutMode`, from
 *     client/src/concept2cure/zen-app-constants.ts),
 *   - the design prototype it grows out of (`uiKit` → ui_kits/<dir>),
 *   - the real mounted REST prefixes it binds to (`apiPrefixes`, grounded in
 *     server/bootstrap/register-*-routes.ts — the authoritative mount table),
 *   - the AnA tool families it can surface (right-rail / slash-command),
 *   - the typed contract it imports for end-to-end typing (`sharedContract`),
 *   - the one-call discovery endpoint that returns nav + dynamic-form schema,
 *     when one exists (`discoveryCatalog`),
 *   - its install readiness and the compliance rails that gate it.
 *
 * This is the app-wide generalization of the two proven "UI-ready" precedents:
 *   - global-RI:  shared/constants/global-ri-ui.ts + shared/types/global-ri-api.ts
 *                 + GET /api/global-ri/catalog
 *   - submission: shared/types/submission-ui.ts (SUBMISSION_WORKSPACES) + submission-api.ts
 *
 * No React, no styling — components stay in the UI layer; this is the contract
 * they read. Import it on the client to drive global navigation and an install
 * tracker; import it on the server for parity checks.
 *
 * NOTE on apiPrefixes: these are the *primary* prefixes a surface binds to, not
 * an exhaustive route list. The authoritative full mount table is
 * server/bootstrap/register-*-routes.ts.
 */

import { GLOBAL_RI_GROUPS } from './global-ri-ui';

// ── Taxonomy ──────────────────────────────────────────────────────────────────

/** Left-rail tier (mirrors FEATURE_INVENTORY.md §7 "left-rail re-structure"). */
export type NavTier = 'global' | 'project' | 'specialist' | 'admin';

export const NAV_TIERS: NavTier[] = ['global', 'project', 'specialist', 'admin'];

/**
 * Install readiness — how much connective tissue already exists for the UI.
 *
 *  - `contract-ready`  typed @shared contract AND/OR a one-call discovery
 *                      catalog exist → nav + forms can be data-driven today.
 *                      (Highest leverage: install is "import the contract,
 *                      render from data".)
 *  - `routes-ready`    REST is mounted and tested; bind components directly to
 *                      the endpoints. A typed contract may be partial/absent.
 *  - `kit-only`        a design prototype exists but the backend binding map is
 *                      still being assembled.
 *  - `planned`         routes exist but the surface is not yet prioritized.
 */
export type ReadinessTier = 'contract-ready' | 'routes-ready' | 'kit-only' | 'planned';

export const READINESS_TIERS: ReadinessTier[] = [
  'contract-ready',
  'routes-ready',
  'kit-only',
  'planned',
];

/** A compliance rail (design skill) that gates a surface's UI. */
export type ComplianceRail =
  | 'regulatory-compliance-ux'
  | 'accessibility-enforcement'
  | 'microcopy-tone'
  | 'motion-discipline';

export interface UiSurface {
  /** Stable id (kebab-case). Unique across the registry. */
  id: string;
  /** Sentence-case display label. */
  label: string;
  /** Left-rail tier. */
  navTier: NavTier;
  /** Real app-shell key (zen-app-constants LayoutMode, or the ui-v2 shell's
      surface map under client/src/concept2cure/v2 for kit-added surfaces). */
  layoutMode: string;
  /** Lucide icon name (kit Icons.jsx vocabulary) used by the ui-v2 rail/⌘K. */
  icon?: string;
  /** Regulatory/domain grouping (free-form, used for nav sectioning + reporting). */
  group: string;
  /** Design prototype this surface grows from: ui_kits/<uiKit>, or null. */
  uiKit: string | null;
  /** Primary mounted REST prefixes (grounded in server/bootstrap/register-*). */
  apiPrefixes: string[];
  /** AnA tool name families this surface can surface (rail / slash / "ask AnA"). */
  anaToolFamilies: string[];
  /** Typed contract the UI imports for end-to-end typing (@shared/...), or null. */
  sharedContract: string | null;
  /** One-call discovery endpoint returning nav + dynamic-form schema, or null. */
  discoveryCatalog: string | null;
  /** Install readiness. */
  readiness: ReadinessTier;
  /** Compliance rails that gate this surface. */
  compliance: ComplianceRail[];
  /** Short note: what's done, what design still owns. */
  notes?: string;
}

// Shorthand for the two near-universal rails.
const A11Y: ComplianceRail = 'accessibility-enforcement';
const TONE: ComplianceRail = 'microcopy-tone';
const PART11: ComplianceRail = 'regulatory-compliance-ux';

// ── The registry ──────────────────────────────────────────────────────────────
// Ordered by nav tier then dependency. Every entry is grounded in a real
// layoutMode + real mounted routes; readiness is reported honestly.

export const UI_SURFACES: UiSurface[] = [
  // ─── Tier: global ────────────────────────────────────────────────────────────
  {
    id: 'projects',
    label: 'Projects',
    navTier: 'global',
    layoutMode: 'projects',
    icon: 'folder',
    group: 'workspace',
    uiKit: 'home',
    apiPrefixes: ['/api/projects', '/api/programs'],
    anaToolFamilies: ['plan_submission'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Entry to everything. Partially built in ui_kits/home and ui_kits/mdx.',
  },
  {
    id: 'apps',
    label: 'Apps catalog',
    navTier: 'global',
    layoutMode: 'apps',
    icon: 'grid',
    group: 'workspace',
    uiKit: null,
    apiPrefixes: ['/api/module-subscriptions'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Module catalog + entitlement-gated launch. Locked modules show upgrade CTA, not a dead button.',
  },
  {
    id: 'artifacts-center',
    label: 'Artifacts Center',
    navTier: 'global',
    layoutMode: 'artifacts-center',
    icon: 'sparkles',
    group: 'evidence',
    uiKit: null,
    apiPrefixes: ['/api/biotech-artifacts', '/api/atoms', '/api/corpus'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE, PART11],
    notes: 'Cross-project artifact library, version chain, provenance, signature status.',
  },

  // ─── Tier: project ───────────────────────────────────────────────────────────
  {
    id: 'project-home',
    label: 'Project home',
    navTier: 'project',
    layoutMode: 'project-home',
    icon: 'home',
    group: 'workspace',
    uiKit: 'mdx',
    apiPrefixes: ['/api/projects', '/api/programs', '/api/rim'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Readiness ring, tasks, milestones, RIM recs, change impact, governance, recent activity.',
  },
  {
    id: 'document-authoring',
    label: 'Document editor & authoring',
    navTier: 'project',
    layoutMode: 'editor',
    icon: 'penLine',
    group: 'authoring',
    uiKit: 'authoring',
    apiPrefixes: [
      '/api/document-authoring',
      '/api/authoring',
      '/api/authoring-actions',
      '/api/coauthor',
      '/api/workflow',
      '/api/esignature',
    ],
    anaToolFamilies: ['get_csr_template', 'get_nonclinical_template', 'draft_clinical_overview_m2_5'],
    sharedContract: '@shared/types/document-contract',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE, 'motion-discipline'],
    notes: 'See HANDOFF_TO_DESIGN_document_authoring.md — editor + Yjs co-author + track-changes + comments + versions + approval + e-sign all have working backends, no UI.',
  },
  {
    id: 'regulatory-workspace',
    label: 'Regulatory workspace',
    navTier: 'project',
    layoutMode: 'regulatory-workspace',
    icon: 'layoutPanels',
    group: 'authoring',
    uiKit: 'mdx',
    apiPrefixes: ['/api/document-authoring', '/api/project-sections', '/api/ind-sections'],
    anaToolFamilies: [],
    sharedContract: '@shared/types/authoring-context',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Generic 3-pane shell (tree · canvas · intelligence). Substrate for documents/editor.',
  },
  {
    id: 'vault',
    label: 'Vault (DMS)',
    navTier: 'project',
    layoutMode: 'vault',
    icon: 'vault',
    group: 'evidence',
    uiKit: 'mdx',
    apiPrefixes: ['/api/corpus', '/api/device-data-center', '/api/evidence'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE, PART11],
    notes: 'Drag-drop upload, chunking/embedding progress, semantic search, version history, evidence linking.',
  },
  {
    id: 'review',
    label: 'Review & approval',
    navTier: 'project',
    layoutMode: 'review',
    icon: 'checkCircle',
    group: 'review',
    uiKit: 'mdx',
    apiPrefixes: ['/api/workflow', '/api/part11'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Review queue, threaded comments (open/resolved/outdated), reject-with-reason, e-sign manifestation (21 CFR §11.50).',
  },
  {
    id: 'submission-center',
    label: 'Submission Center',
    navTier: 'project',
    layoutMode: 'submissions',
    icon: 'rocket',
    group: 'submission',
    uiKit: 'submission',
    apiPrefixes: ['/api/submissions', '/api/submission-center', '/api/region-profiles'],
    anaToolFamilies: ['plan_submission', 'validate_submission'],
    sharedContract: '@shared/types/submission-ui',
    discoveryCatalog: 'SUBMISSION_WORKSPACES (shared/types/submission-ui.ts)',
    readiness: 'contract-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Framework-agnostic workspace map + error catalog already in shared. Package preview, eValidator pass, ESG send vs eSTAR export picker. See SUBMISSION_CENTER_API.md.',
  },
  {
    id: 'ectd-coauthor',
    label: 'eCTD co-author',
    navTier: 'project',
    layoutMode: 'submissions',
    icon: 'gitBranch',
    group: 'submission',
    uiKit: 'ectd_coauthor',
    apiPrefixes: ['/api/ectd', '/api/content-assembly'],
    anaToolFamilies: [],
    sharedContract: '@shared/types/submission-api',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'eCTD tree + section authoring. Back-half pipeline (format→assemble→validate→transmit) is production-grade.',
  },
  {
    id: 'device-510k',
    label: '510(k) workbench',
    navTier: 'project',
    layoutMode: 'section-workspace',
    icon: 'fileCheck',
    group: 'device',
    uiKit: 'mdx',
    apiPrefixes: ['/api/510k-workflow', '/api/cerv2', '/api/cerv2-sections', '/api/fda-forms'],
    anaToolFamilies: [],
    sharedContract: '@shared/types/predicate-intelligence',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'eSTAR section tree · content editor · predicate/SE intelligence panel. In progress.',
  },
  {
    id: 'device-cer',
    label: 'CER generator (EU MDR)',
    navTier: 'project',
    layoutMode: 'section-workspace',
    icon: 'microscope',
    group: 'device',
    uiKit: null,
    apiPrefixes: ['/api/cer', '/api/cerv2'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Annex XIV structure, FAERS, literature, GSPR checklist, export. Dashboard only today.',
  },
  {
    id: 'cmc',
    label: 'CMC / Module 3',
    navTier: 'project',
    layoutMode: 'cmc',
    icon: 'beaker',
    group: 'quality-cmc',
    uiKit: 'cmc',
    apiPrefixes: ['/api/cmc', '/api/cmc/module3-os', '/api/cmc/specifications', '/api/cmc/stability'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Module 3 operating system: blueprint, specifications, stability, batch records, convergence.',
  },
  {
    id: 'ind-checklist',
    label: 'IND lifecycle',
    navTier: 'project',
    layoutMode: 'ind-checklist',
    icon: 'clipboardList',
    group: 'submission',
    uiKit: 'pdev',
    apiPrefixes: ['/api/ind-lifecycle', '/api/ind-forms', '/api/ind-autodraft', '/api/ind-master-data'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'IND checklist, forms (1571/1572/3674), autodraft, master data, amendments, annual reports, safety reports.',
  },
  {
    id: 'pdev',
    label: 'Product development (PDEV → IND)',
    navTier: 'project',
    layoutMode: 'pdev',
    icon: 'workflow',
    group: 'submission',
    uiKit: 'pdev',
    apiPrefixes: ['/api/pdev'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [PART11, A11Y, TONE],
    notes: 'See PDEV_IND_DESIGN_BRIEF.md. Activity → AI draft → evidence → confirm flow prototyped in ui_kits/pdev.',
  },
  {
    id: 'biopharma',
    label: 'Biopharma (BLA / CTD)',
    navTier: 'project',
    layoutMode: 'biopharma',
    icon: 'atom',
    group: 'submission',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/biopharma', '/api/biopharma/bla', '/api/biopharma/ctd', '/api/biopharma/submissions'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [PART11, A11Y, TONE],
    notes: 'BLA workbench + CTD assembly. ui_kits/biopharma prototyped through Phase 10.',
  },
  {
    id: 'template-library',
    label: 'Template library',
    navTier: 'project',
    layoutMode: 'template-library',
    icon: 'template',
    group: 'authoring',
    uiKit: null,
    apiPrefixes: ['/api/templates', '/api/c2c/templates'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Full REST (list/extract-preview/extract+save/create-from-spec/update/render docx|pdf), org-scoped, audited. No UI yet — strongest backend without a surface.',
  },
  {
    id: 'tasks',
    label: 'Tasks & collaboration',
    navTier: 'project',
    layoutMode: 'tasking',
    icon: 'checkSquare',
    group: 'collaboration',
    uiKit: 'tasking',
    apiPrefixes: ['/api/task-management', '/api/regulatory/tasks', '/api/project-sections'],
    anaToolFamilies: [],
    sharedContract: '@shared/schema',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE, 'motion-discipline'],
    notes: 'Org-scoped unifiedTasks board (@shared/schema unifiedTasks · taskDependencies) + critical-path DAG, channels, messages, activity feed, presence, mentions, due dates. See ui_kits/tasking + ui_kits/task-tray.',
  },
  {
    id: 'dossier-map',
    label: 'Dossier map',
    navTier: 'project',
    layoutMode: 'dossier-map',
    icon: 'network',
    group: 'submission',
    uiKit: null,
    apiPrefixes: ['/api/rim', '/api/global-ri'],
    anaToolFamilies: ['global_ri_dossier'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'CTD/eCTD module map with completeness + readiness overlay.',
  },
  {
    id: 'csr-workflow',
    label: 'CSR workflow',
    navTier: 'project',
    layoutMode: 'csr-workflow',
    icon: 'fileText',
    group: 'clinical',
    uiKit: null,
    apiPrefixes: ['/api/csr', '/api/csr-builder'],
    anaToolFamilies: ['get_csr_template'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'ICH E3 CSR builder + intelligence library.',
  },

  // ─── Tier: specialist ────────────────────────────────────────────────────────
  {
    id: 'global-ri',
    label: 'Global regulatory intelligence',
    navTier: 'specialist',
    layoutMode: 'intelligence',
    icon: 'globe',
    group: 'intelligence',
    uiKit: 'intelligence',
    apiPrefixes: ['/api/global-ri'],
    anaToolFamilies: ['global_ri_'],
    sharedContract: '@shared/types/global-ri-api',
    discoveryCatalog: 'GET /api/global-ri/catalog',
    readiness: 'contract-ready',
    compliance: [A11Y, TONE],
    notes: 'Gold-standard pattern: ~41 deterministic capabilities, 9 groups, one-call catalog drives nav + dynamic forms. See HANDOFF_TO_DESIGN_global_ri.md.',
  },
  {
    id: 'precedent-intelligence',
    label: 'Precedent intelligence',
    navTier: 'specialist',
    layoutMode: 'precedent-intelligence',
    icon: 'scale',
    group: 'intelligence',
    uiKit: 'intelligence',
    apiPrefixes: ['/api/precedent-engine', '/api/saved-precedent-queries'],
    anaToolFamilies: [],
    sharedContract: '@shared/types/predicate-intelligence',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Past approvals search + decision rationale. Slots into 510(k) §12 substantial equivalence.',
  },
  {
    id: 'biostatistics',
    label: 'Biostatistics',
    navTier: 'specialist',
    layoutMode: 'biostatistics',
    icon: 'sigma',
    group: 'clinical',
    uiKit: null,
    apiPrefixes: ['/api/biostat', '/api/ana-biostats'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'SAP authoring, power analysis, TLF shells, adaptive trial plans, IDMC.',
  },
  {
    id: 'report-engine',
    label: 'Report engine',
    navTier: 'specialist',
    layoutMode: 'report-engine',
    icon: 'barChart',
    group: 'evidence',
    uiKit: null,
    apiPrefixes: ['/api/haq-manager', '/api/intelligence'],
    anaToolFamilies: [],
    sharedContract: '@shared/types/intelligence',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Immutable report records, cryptographic seal, provenance atoms. See INSIGHTS_REPORTING_IMPLEMENTATION_SPEC.md.',
  },
  {
    id: 'safety-narrative',
    label: 'Safety narrative / PV',
    navTier: 'specialist',
    layoutMode: 'safety-narrative',
    icon: 'shieldAlert',
    group: 'safety-pv',
    uiKit: null,
    apiPrefixes: ['/api/pharmacovigilance'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'SAE narrative generation, ICSR, signal handling.',
  },
  {
    id: 'device-diagnostics',
    label: 'Device & diagnostics workbench',
    navTier: 'specialist',
    layoutMode: 'device-diagnostics-workbench',
    icon: 'stethoscope',
    group: 'device',
    uiKit: 'risk',
    apiPrefixes: ['/api/mdx', '/api/manufacturing', '/api/ivdr'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Classification, performance testing, risk analysis, IVDR, CLIA, CDx, LDT. See ui_kits/risk + ui_kits/labeling.',
  },
  {
    id: 'labeling',
    label: 'Labeling',
    navTier: 'specialist',
    layoutMode: 'labeling',
    icon: 'tag',
    group: 'device',
    uiKit: 'labeling',
    apiPrefixes: ['/api/mdx'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [PART11, A11Y, TONE],
    notes: 'Labeling/IFU authoring + compliance. ui_kits/labeling prototyped.',
  },
  {
    id: 'risk',
    label: 'Risk management',
    navTier: 'specialist',
    layoutMode: 'risk',
    icon: 'alertTriangle',
    group: 'device',
    uiKit: 'risk',
    apiPrefixes: ['/api/mdx', '/api/design-risk'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [PART11, A11Y, TONE],
    notes: 'ISO 14971 risk file, hazard analysis. ui_kits/risk prototyped.',
  },
  {
    id: 'deep-research',
    label: 'Deep research',
    navTier: 'specialist',
    layoutMode: 'deep-research',
    icon: 'telescope',
    group: 'intelligence',
    uiKit: null,
    apiPrefixes: ['/api/deep-research'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Long-running multi-source research (Opus). Shares the AnA rail in deep-research mode.',
  },

  // ─── Tier: admin ─────────────────────────────────────────────────────────────
  {
    id: 'setup',
    label: 'Admin / setup',
    navTier: 'admin',
    layoutMode: 'setup',
    icon: 'settings',
    group: 'admin',
    uiKit: null,
    apiPrefixes: ['/api/setup', '/api/admin', '/api/users', '/api/enterprise/rbac', '/api/api-keys'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Org profile, users/roles, MFA policy, SSO/SCIM, module subscriptions, feature flags, API keys.',
  },
  {
    id: 'audit-trail',
    label: 'Audit trail',
    navTier: 'admin',
    layoutMode: 'audit',
    icon: 'scroll',
    group: 'admin',
    uiKit: null,
    apiPrefixes: ['/api/admin/audit', '/api/part11'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Log entries, filters, signed PDF export. Immutable-history visual per regulatory-compliance-ux.',
  },
  {
    id: 'billing',
    label: 'Billing',
    navTier: 'admin',
    layoutMode: 'billing',
    icon: 'creditCard',
    group: 'admin',
    uiKit: null,
    apiPrefixes: ['/api/billing/invoices', '/api/billing/budgets', '/api/billing/portal'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Usage, invoices, budgets, alerts. See MDX_PAYING_CUSTOMER_VALUE_AND_ENTITLEMENTS.',
  },
  {
    id: 'ana-memory',
    label: 'AnA Memory',
    navTier: 'global',
    layoutMode: 'ana-memory',
    icon: 'database',
    group: 'explore',
    uiKit: null,
    apiPrefixes: ['/api/mdx/ana/memory', '/api/mdx/ana/threads'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Browse/search knowledge atoms, pin/unpin, confidence scores.',
  },

  // ═══ ui-v2 kit reconciliation (2026-07-06) ═════════════════════════════════
  // Surfaces added by the Concept2Cure.RI design kit
  // (design_handoff_c2c_v2_ui_replacement). Ids are the kit registry.jsx ids
  // verbatim — deep links depend on them. Routes were repo-verified against
  // all 15 server/bootstrap mount files in the kit GA_READINESS_AUDIT
  // (2026-07-05). Where the kit named a contract that isn't a real @shared/*.ts
  // file yet, sharedContract is null and the ref is preserved in notes
  // (GAP RULE — surfaced, not faked).

  // ─── ui-v2 additions: global ─────────────────────────────────────────────
  {
    id: 'ana-command',
    label: 'AnA Command',
    navTier: 'global',
    layoutMode: 'ana-command',
    group: 'explore',
    icon: 'sparkles',
    uiKit: null,
    apiPrefixes: ['/api/orchestration/continuity', '/api/orchestration/recommendations', '/api/orchestration/templates', '/api/orchestration/execute', '/api/orchestration/pre-submission-gate', '/api/orchestration/projects/:id/readiness'],
    anaToolFamilies: ['generate_recommendations', 'execute_workflow', 'assess_readiness'],
    sharedContract: '@shared/types/orchestration',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'AnA on top of everything across the portfolio: continuity briefing (what changed / newly ready / needs attention / trajectory), ranked dispatchable recommendations, runnable multi-step workflow templates (submission_readiness_review · draft_validate_route · project_blocker_scan), and the unified pre-submission go/no-go gate (readiness + CMC + CRL + RTF + ICH), audited to Part 11.',
  },
  {
    id: 'cro-portfolio',
    label: 'Sponsor portfolio',
    navTier: 'global',
    layoutMode: 'cro-portfolio',
    group: 'workspace',
    icon: 'network',
    uiKit: 'home',
    apiPrefixes: ['/api/cro/clients', '/api/cro/studies', '/api/cro/submissions'],
    anaToolFamilies: ['plan_submission'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'CRO multi-sponsor rollup. croClients → croStudies → croRegulatorySubmissions, every query org-scoped. Drill into a sponsor; each submission flows through its matching pathway onto the shared Submission Center lifecycle.',
  },
  {
    id: 'etmf',
    label: 'Inspection readiness',
    navTier: 'global',
    layoutMode: 'etmf',
    group: 'workspace',
    icon: 'network',
    uiKit: 'home',
    apiPrefixes: ['/api/etmf'],
    anaToolFamilies: ['generate_inspection_package'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'eTMF inspection-readiness (CRO deliverable). assessTmfCompleteness against the DIA TMF Reference Model (11 zones, ICH E6(R2) §8 essential docs) via GET /api/etmf/trials/:trialId/completeness; file gaps via POST .../artifacts. AnA GENERATES the inspection-readiness package (the hero deliverable), not a dashboard. GAP: the inspection-package ZIP + artifacts/bulk endpoints are on the feature branch claude/doc-mgmt-structure-alignment-4p91eu, not yet on concept2cure-v2 — the Download action wires to them live-first and degrades to an honest in-browser readiness report.',
  },
  {
    id: 'filings-catalog',
    label: 'Filings catalog',
    navTier: 'global',
    layoutMode: 'filings-catalog',
    group: 'workspace',
    icon: 'clipboardList',
    uiKit: 'home',
    apiPrefixes: ['/api/regulatory/registry'],
    anaToolFamilies: ['get_csr_template', 'plan_submission'],
    sharedContract: '@shared/regulatory/global-document-registry',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Canonical taxonomy of 113 filing types across pharma/biotech, device, IVD, cross-cutting. Each routes into its execution workflow (IND/NDA/BLA/MAA/510k/PMA/De Novo/CER).',
  },

  // ─── ui-v2 additions: project ─────────────────────────────────────────────
  {
    id: 'program-journey',
    label: 'Program journey',
    navTier: 'project',
    layoutMode: 'program-journey',
    group: 'workspace',
    icon: 'workflow',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/biopharma/programs', '/api/rim', '/api/regulatory-correspondence', '/api/ectd'],
    anaToolFamilies: ['plan_submission', 'assess_filing_readiness'],
    sharedContract: '@shared/types/submission-api',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The end-to-end biotech/pharma spine — concept to submission to lifecycle. 9 lifecycle stages, each with its agency gate, deliverables and the deep-linked capabilities that serve it, plus program intelligence: CTD readiness, review clock, predicted HAQs, contradictions and blockers.',
  },
  {
    id: 'dispatch-readiness',
    label: 'Dispatch readiness',
    navTier: 'project',
    layoutMode: 'dispatch-readiness',
    group: 'submission',
    icon: 'send',
    uiKit: 'mdx',
    apiPrefixes: ['/api/submissions/sequences'],
    anaToolFamilies: ['assess_dispatch_readiness', 'run_validation'],
    sharedContract: '@shared/types/submission-ui',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The proven, deterministic last gate before transmit (dispatch-gate.ts). Composes structural validation + unacknowledged Shadow Review criticals + external eValidator; a client cannot talk it down (every input server-computed). Flags the cleared-but-never-reviewed blind spot. Bound to GET /api/submissions/sequences/:seqId/dispatch-readiness.',
  },
  {
    id: 'shadow-review',
    label: 'Shadow review',
    navTier: 'project',
    layoutMode: 'shadow-review',
    group: 'submission',
    icon: 'eye',
    uiKit: 'mdx',
    apiPrefixes: ['/api/submissions/sequences'],
    anaToolFamilies: ['run_shadow_review', 'assess_filing_readiness'],
    sharedContract: '@shared/types/submission-ui',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'AnA simulates the reviewer who will read your submission (5 real lenses: FDA filing / EMA D120 / PMDA / MDR NB / IVDR NB) and scores the two gates that kill a filing — RTF (administrative) and CRL (substantive). Findings are model_assisted; the risk aggregation is the verbatim deterministic aggregateRisk (a single critical saturates). Bound to POST /api/submissions/sequences/:seqId/shadow-review.',
  },
  {
    id: 'decision-lineage',
    label: 'Decision lineage',
    navTier: 'project',
    layoutMode: 'decision-lineage',
    group: 'workspace',
    icon: 'gitBranch',
    uiKit: 'mdx',
    apiPrefixes: ['/api/decision-lineage', '/api/provenance'],
    anaToolFamilies: ['get_document', 'run_validation'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The immutable, Part-11 hash-chained decision trail behind every governed artifact (who decided what, when, on what evidence, signed how). Answer-first defensibility read, then the readable chain of governed decisions (5 node types), then chain-integrity verify + compliance frameworks + eCTD-compatible export. Bound to GET /api/decision-lineage/:entityType/:entityId + verify-chain. Contract ref (not yet a @shared file): @shared/types/decision-lineage',
  },
  {
    id: 'ivd-completeness',
    label: 'IVD completeness',
    navTier: 'project',
    layoutMode: 'ivd-completeness',
    group: 'workspace',
    icon: 'microscope',
    uiKit: 'mdx',
    apiPrefixes: ['/api/validate-completeness', '/api/c2c/projects'],
    anaToolFamilies: ['assess_filing_readiness', 'draft_section'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'IVDR technical-file completeness (validate-completeness IVDR branch) — GSPR Annex I, Performance Evaluation Report Annex XIII, analytical + clinical performance, scientific validity, PMPF/PMS. IVD-only; derives from the diagnostics IVDR spine. Answer-first CE-marking readiness, not the borrowed device checklist. Contract ref (not yet a @shared file): @shared/regulatory/ivdr',
  },
  {
    id: 'batch-draft',
    label: 'Parallel drafting',
    navTier: 'project',
    layoutMode: 'batch-draft',
    group: 'authoring',
    icon: 'sparkles',
    uiKit: 'authoring',
    apiPrefixes: ['/api/c2c/documents'],
    anaToolFamilies: ['batch_draft_sections', 'draft_section'],
    sharedContract: '@shared/types/document-contract',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'AnA drafts several dossier sections in parallel (batch_draft_sections) — one Accept card per section, each promoting through the same governed PATCH (saveSection · draftSource=ana). Fans out concurrent streamDraft SSE calls over the live per-section route.',
  },
  {
    id: 'authoring-engine',
    label: 'AnA Authoring Engine',
    navTier: 'project',
    layoutMode: 'authoring-engine',
    group: 'authoring',
    icon: 'sparkles',
    uiKit: 'authoring',
    apiPrefixes: ['/api/document-authoring', '/api/authoring', '/api/coauthor', '/api/templates', '/api/c2c/templates', '/api/task-management'],
    anaToolFamilies: ['draft_section', 'get_csr_template', 'get_nonclinical_template', 'draft_clinical_overview_m2_5'],
    sharedContract: '@shared/types/document-contract',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE, 'motion-discipline'],
    notes: 'End-to-end document suite for the whole CTD pyramid, raw data to final draft. An AI system per document type (no hallucinations, every required element), multi-modal (text/tables/figures/graphs), template-learning, and GxP automations whose non-AI validation logic runs as intended 100% of the time.',
  },
  {
    id: 'inconsistency',
    label: 'Inconsistency Intelligence',
    navTier: 'project',
    layoutMode: 'inconsistency',
    group: 'authoring',
    icon: 'gitCompare',
    uiKit: 'authoring',
    apiPrefixes: ['/api/governed-intelligence', '/api/coauthor', '/api/document-authoring', '/api/task-management'],
    anaToolFamilies: ['assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Change a governed value once and propagate it across every document that cites it. Draft sections update inline; approved/locked sections are flagged for re-approval with a task, on the audit trail. Matches Artos Inconsistency Intelligence / Weave content-update. Contract ref (not yet a @shared file): server/routes/assumption-decision-contradiction.ts',
  },
  {
    id: 'source-tracer',
    label: 'Source Tracer',
    navTier: 'project',
    layoutMode: 'source-tracer',
    group: 'authoring',
    icon: 'search',
    uiKit: 'authoring',
    apiPrefixes: ['/api/documents/:id/sources', '/api/documents/:id/sources/analyze', '/api/citations/verify'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Sentence-level provenance bound to sourceLinks.ts: every sentence carries a typed SourceLink (sourceType ∈ trial_data|literature|regulatory_guidance|internal_data) with a 0–1 confidence. POST /sources/analyze finds untraced claims (claimsFound). Literature citations are verified against PubMed+CrossRef via /api/citations/verify (verified|not_found|unverifiable|error) — an unconfirmed citation is flagged, never assumed. Fixture-backed with a Sample-data pill until live-wired. Contract ref (not yet a @shared file): server/routes/sourceLinks.ts + server/routes/citations.ts',
  },
  {
    id: 'dossier',
    label: 'Dossier',
    navTier: 'project',
    layoutMode: 'dossier',
    group: 'workspace',
    icon: 'folder',
    uiKit: 'mdx',
    apiPrefixes: ['/api/ectd', '/api/documents', '/api/corpus'],
    anaToolFamilies: ['draft_section', 'get_document'],
    sharedContract: '@shared/types/document-contract',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Document-first workspace (Artos/Weave model): eCTD folder tree · submission documents in process with status/version · the live document · Data Room of source files.',
  },
  {
    id: 'conversation-thread',
    label: 'Conversation',
    navTier: 'project',
    layoutMode: 'conversation-thread',
    group: 'workspace',
    icon: 'messageSquare',
    uiKit: 'mdx',
    apiPrefixes: ['/api/conversation-os', '/api/chat', '/api/authoring-actions'],
    anaToolFamilies: [],
    sharedContract: '@shared/schema',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Conversation-os thread: user+AnA messages, artifact proposals (propose→accept→apply), governed mutations, inline document/task/file references that route out. Contract detail: concept2cureConversations/Messages',
  },
  {
    id: 'evidence-search',
    label: 'Evidence search (RAG)',
    navTier: 'project',
    layoutMode: 'vault-workspace',
    group: 'evidence',
    icon: 'search',
    uiKit: null,
    apiPrefixes: ['/api/evidence', '/api/corpus', '/api/biotech-rag'],
    anaToolFamilies: ['get_evidence_chain'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Ask a question across the corpus — 3-layer memory → gateway → cited answer traced back to source chunks.',
  },
  {
    id: 'haq-manager',
    label: 'Health authority questions',
    navTier: 'project',
    layoutMode: 'haq',
    group: 'submission',
    icon: 'messageSquare',
    uiKit: 'mdx',
    apiPrefixes: ['/api/haq-manager', '/api/regulatory-correspondence', '/api/precedent-engine'],
    anaToolFamilies: ['draft_haq_response', 'search_precedent_responses'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Post-submission review phase: agency IR / Day-120 LoQ / CRL decomposed, source-traced responses with precedent intelligence, governed e-sign into the response package. Contract ref (not yet a @shared file): @shared/types/haq',
  },
  {
    id: 'nda-cockpit',
    label: 'NDA / BLA filing',
    navTier: 'project',
    layoutMode: 'nda-cockpit',
    group: 'submission',
    icon: 'beaker',
    uiKit: 'mdx',
    apiPrefixes: ['/api/ectd', '/api/biopharma', '/api/submission', '/api/shadow'],
    anaToolFamilies: ['assess_filing_readiness', 'run_shadow_review'],
    sharedContract: '@shared/types/submission-api',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'NDA/BLA filing cockpit: CTD M1–5 readiness, Module 1 admin set (356h), PDUFA review clock, Refuse-to-File risk (shadow review).',
  },
  {
    id: 'device-workstream',
    label: 'Medical Device & IVD',
    navTier: 'project',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'stethoscope',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx', '/api/510k-workflow', '/api/cer', '/api/cerv2', '/api/ivdr', '/api/manufacturing'],
    anaToolFamilies: [],
    sharedContract: '@shared/types/predicate-intelligence',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The MDX workstream — one door. Programs portfolio with classification + 510(k)/PMA/CER/De Novo pathway tabs, predicate intelligence, eSTAR/Annex XIV editors. Built in the MDX kit.',
  },
  {
    id: 'protocol-dev',
    label: 'Protocol development',
    navTier: 'project',
    layoutMode: 'protocol-dev',
    group: 'authoring',
    icon: 'clipboardList',
    uiKit: 'authoring',
    apiPrefixes: ['/api/protocol-development', '/api/protocol-soa', '/api/protocol-risks', '/api/protocol-milestones', '/api/protocol-budget', '/api/protocol-amendments', '/api/protocol-deviations', '/api/protocol-reviews', '/api/protocol-consent', '/api/protocol-export'],
    anaToolFamilies: ['create_protocol_document', 'update_protocol_section', 'review_protocol_completeness', 'finalize_protocol_document', 'add_soa_assessment', 'review_soa_matrix'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Protocol authoring hub (C2C-17..22): full eCTD-style section tree, SoA grid, risk register (5×5), milestones, budget/feasibility, amendments, deviations/CAPA, reviews, informed consent — deterministic completeness gate on finalize (ICH M11 / 45 CFR 46 / PHS Policy).',
  },
  {
    id: 'research-admin',
    label: 'Research administration',
    navTier: 'project',
    layoutMode: 'research-admin',
    group: 'collaboration',
    icon: 'network',
    uiKit: 'mdx',
    apiPrefixes: ['/api/committees', '/api/coverage-analysis', '/api/grant-finder', '/api/citi-training', '/api/protocol-portfolio'],
    anaToolFamilies: ['convene_committee_meeting', 'cast_committee_vote', 'finalize_committee_determination', 'review_coverage_analysis', 'find_grant_opportunities', 'review_training_matrix', 'review_protocol_portfolio_analytics'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Research-administration workspace (C2C-14/15/16/01-02): IRB/IACUC/IBC governance with convene→quorum→voting poll + finalize determination, Medicare coverage analysis (NCD 310.1) billing grid, intelligent grant finder (fit scoring), CITI training matrix, continuing-review portfolio analytics.',
  },
  {
    id: 'pyramid',
    label: 'Submission pyramid',
    navTier: 'project',
    layoutMode: 'pyramid',
    group: 'submission',
    icon: 'workflow',
    uiKit: null,
    apiPrefixes: ['/api/v1/pyramids', '/api/v1/global-pyramids', '/api/v1/projects/:id/pyramid'],
    anaToolFamilies: ['plan_submission'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'contract-ready',
    compliance: [A11Y, TONE, 'motion-discipline'],
    notes: 'Deterministic submission work breakdown — type selector (8 engine + 12 global types), dashboard (progress ring, phase strip, risk gauge, next-available tasks), phase→task drill-down with full-metadata detail sheet (risk, CTD bindings, guidance, deps, deliverables), analytics (resources/bottlenecks, document coverage, critical path), global pyramid browser. Task status is the only client-owned state. Contract ref (not yet a @shared file): services/regulatory/SubmissionPyramidEngine.ts · globalPyramids.ts · submission-type-bridge.ts',
  },
  {
    id: 'registrations',
    label: 'Registrations',
    navTier: 'project',
    layoutMode: 'registrations',
    group: 'lifecycle',
    icon: 'globe',
    uiKit: 'mdx',
    apiPrefixes: ['/api/rim', '/api/global-ri', '/api/global-markets'],
    anaToolFamilies: ['global_ri_market_access'],
    sharedContract: '@shared/types/global-ri-api',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Global registration lifecycle: market authorization status, agency review clocks, renewals/variations, HA commitments, reliance-pathway strategy.',
  },
  {
    id: 'market-access',
    label: 'Market access',
    navTier: 'project',
    layoutMode: 'market-access',
    group: 'lifecycle',
    icon: 'creditCard',
    uiKit: 'mdx',
    apiPrefixes: ['/api/market-access'],
    anaToolFamilies: ['global_ri_market_access', 'compose_value_dossier'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Commercial bridge: payer coverage (CMS NCD/LCD, private, HTA), value-dossier composer (AMCP/NICE/budget-impact), coding strategy (CPT/PLA/HCPCS), access sequencing.',
  },
  {
    id: 'change-assessment',
    label: 'Change assessment',
    navTier: 'project',
    layoutMode: 'change-assessment',
    group: 'lifecycle',
    icon: 'gitBranch',
    uiKit: 'mdx',
    apiPrefixes: ['/api/change-propagation', '/api/rim'],
    anaToolFamilies: ['assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Change impact engine: FDA "When to Submit a 510(k) for a Change" (2017) + EU MDR significant-change (MDCG 2020-3) determinations → new submission vs document-to-file.',
  },
  {
    id: 'doc-journey',
    label: 'Document journey',
    navTier: 'project',
    layoutMode: 'doc-journey',
    group: 'authoring',
    icon: 'gitBranch',
    uiKit: 'mdx',
    apiPrefixes: ['/api/authoring', '/api/workflow', '/api/submission', '/api/audit'],
    anaToolFamilies: ['draft_section', 'assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'One document, ideation → submission: ideate → outline → AnA draft → revise → review → QC → approve (§11 e-sign) → assemble (eCTD leaf) → transmit (ESG). Document state visible at every stage.',
  },
  {
    id: 'labeling-pi',
    label: 'Prescribing information',
    navTier: 'project',
    layoutMode: 'labeling-pi',
    group: 'authoring',
    icon: 'fileText',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx', '/api/spl-fhir', '/api/rim'],
    anaToolFamilies: ['draft_label', 'draft_uspi'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'USPI (PLLR / 21 CFR 201.57), EU SmPC (QRD), SPL. End-of-review agency labeling negotiation (sponsor vs FDA redline). The label as the document.',
  },
  {
    id: 'agency-meetings',
    label: 'Agency meetings',
    navTier: 'project',
    layoutMode: 'agency-meetings',
    group: 'lifecycle',
    icon: 'users',
    uiKit: 'mdx',
    apiPrefixes: ['/api/ha-interactions', '/api/rim'],
    anaToolFamilies: ['draft_briefing_book', 'prepare_meeting_request'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Agency interactions: Pre-IND/INTERACT/Type A-D/EOP2/pre-NDA-BLA, device Q-Sub, EMA Scientific Advice. Briefing book document + questions, minutes + commitments back to the dossier.',
  },
  {
    id: 'communication-center',
    label: 'Communication Center',
    navTier: 'project',
    layoutMode: 'communication-center',
    group: 'submission',
    icon: 'mail',
    uiKit: null,
    apiPrefixes: ['/api/ha-interactions', '/api/regulatory-correspondence', '/api/submission-ops'],
    anaToolFamilies: ['draft_agency_response', 'plan_crl_response'],
    sharedContract: '@shared/types/communication-center',
    discoveryCatalog: 'AgencyCommunicationEventRecord',
    readiness: 'contract-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The regulated FDA↔client loop: agency communications (9 source types) auto-generating tasks, submission lifecycle incl. CRL/RTF/denial (rejected_or_remediation) → response → resubmit, HA interactions + PMR/PMC/REMS commitments, authority profiles.',
  },
  {
    id: 'rbm',
    label: 'Risk-based monitoring',
    navTier: 'project',
    layoutMode: 'rbm',
    group: 'clinical',
    icon: 'shieldCheck',
    uiKit: 'risk',
    apiPrefixes: ['/api/mdx/rbm-assessments', '/api/mdx/rbm-kris', '/api/mdx/rbm-qtls', '/api/mdx/rbm-signals', '/api/mdx/rbm-site-risk', '/api/mdx/rbm-monitoring-plans', '/api/mdx/rbm-summary', '/api/mdx/rbm-report', '/api/mdx/rbm-attention'],
    anaToolFamilies: ['run_rbm_assessment', 'assess_site_risk', 'evaluate_kris_qtls', 'generate_rbm_plan', 'prioritize_monitoring_queries', 'run_central_monitoring', 'scan_patient_profiles', 'generate_rbm_report', 'get_rbm_attention'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE, 'motion-discipline'],
    notes: 'ICH E6(R3) RBQM domain shell — 10 surfaces (overview, risk review report, RACT, KRIs, QTLs, central monitoring, patient profiles, site risk, site oversight, monitoring plan) over 40 /api/mdx/rbm-* routes. 5 deterministic engines produce every score; assessment + plan approvals are Part 11 governed (reason-for-change + e-sign). Contract ref (not yet a @shared file): client/src/concept2cure/services/rbmService.ts · hooks/useRbm.ts',
  },
  {
    id: 'orchestration',
    label: 'Orchestration & readiness',
    navTier: 'project',
    layoutMode: 'orchestration',
    group: 'review',
    icon: 'workflow',
    uiKit: null,
    apiPrefixes: ['/api/orchestration', '/api/approval-workflows', '/api/submission-readiness'],
    anaToolFamilies: ['assess_filing_readiness'],
    sharedContract: '@shared/schema/orchestration',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Persisted workflow engine: workflowRuns (steps · blockers · diffs · pause/resume/retry), approvalCheckpoints (manual/role/quorum/auto), readiness rules + evaluations → overall score, blocker count, isReady gate before filing.',
  },
  {
    id: 'reg-change',
    label: 'Regulatory change intelligence',
    navTier: 'project',
    layoutMode: 'reg-change',
    group: 'lifecycle',
    icon: 'bell',
    uiKit: null,
    apiPrefixes: ['/api/external-intelligence', '/api/regulatory-intelligence'],
    anaToolFamilies: ['assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Portfolio horizon scan: monitors FDA guidance, ISO/IEC revisions, EU MDCG/MDR-IVDR and statutory changes; assesses impact and resolves each to an action document (gap analysis, transition plan, update task) — never a passive feed.',
  },
  {
    id: 'insights',
    label: 'Reporting & analytics',
    navTier: 'project',
    layoutMode: 'insights',
    group: 'evidence',
    icon: 'barChart',
    uiKit: null,
    apiPrefixes: ['/api/report-os', '/api/insights'],
    anaToolFamilies: ['list_report_types', 'generate_report', 'portfolio_readiness', 'compare_regions', 'get_prediction', 'explain_blockers'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'AnA Reporting Canvas — conversational governed reporting over the Report-OS render model (30 report types), per-segment catalog, entitlement tiers, best-practice packs. Contract ref (not yet a @shared file): server/services/report-os/taxonomy.ts',
  },
  {
    id: 'pediatric',
    label: 'Pediatric (PIP / PSP)',
    navTier: 'project',
    layoutMode: 'pediatric',
    group: 'lifecycle',
    icon: 'users',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/biopharma/pediatric', '/api/rim'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [PART11, A11Y, TONE],
    notes: 'FDA §505B PREA / iPSP and EMA PIP: plans, deferrals, waivers, extrapolation rationale and PREA milestones.',
  },
  {
    id: 'orphan',
    label: 'Orphan & rare',
    navTier: 'project',
    layoutMode: 'orphan',
    group: 'lifecycle',
    icon: 'sparkles',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/biopharma/orphan', '/api/rim'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [A11Y, TONE],
    notes: 'Orphan-drug / rare-disease designations across FDA/EMA/PMDA, RPD priority-review vouchers & grants, and patient-advocacy engagement.',
  },
  {
    id: 'lifecycle-mgmt',
    label: 'Lifecycle management',
    navTier: 'project',
    layoutMode: 'lifecycle-mgmt',
    group: 'lifecycle',
    icon: 'history',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/biopharma/supplements', '/api/change-assessment', '/api/rim'],
    anaToolFamilies: ['assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [PART11, A11Y, TONE],
    notes: 'Post-approval: supplements/variations (sBLA, Type II/IB, CBE-30), CMC change control classified against ICH Q12, and renewal cycles (PADER, 5-year, re-examination).',
  },
  {
    id: 'clinical-ops',
    label: 'Clinical operations',
    navTier: 'project',
    layoutMode: 'clinical-ops',
    group: 'clinical',
    icon: 'users',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/protocol-development', '/api/mdx/rbm-site-risk', '/api/protocol-deviations'],
    anaToolFamilies: ['assess_site_risk'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [PART11, A11Y, TONE],
    notes: 'Clinical-development operations: studies & enrollment, study sites with RBM risk linkage, DSMB / interim reviews, and protocol deviations with CAPA. Structured data entry for sites and deviations.',
  },
  {
    id: 'nonclinical',
    label: 'Nonclinical / Module 4',
    navTier: 'project',
    layoutMode: 'nonclinical',
    group: 'clinical',
    icon: 'microscope',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/nonclinical', '/api/preclinical', '/api/documents'],
    anaToolFamilies: ['get_nonclinical_template', 'calculate_ttc'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [PART11, A11Y, TONE],
    notes: 'IND-enabling & CTD Module 4: GLP study registry with finding classification and SEND status, SEND 12-domain conformance, the Module 2.6 written/tabulated summary builder, and Module 4 placement. Structured data entry for studies.',
  },

  // ─── ui-v2 additions: specialist ─────────────────────────────────────────────
  {
    id: 'intelligence-catalog',
    label: 'Intelligence catalog',
    navTier: 'specialist',
    layoutMode: 'intelligence-catalog',
    group: 'intelligence',
    icon: 'shieldCheck',
    uiKit: 'intelligence',
    apiPrefixes: ['/api/ana'],
    anaToolFamilies: ['calculate_ttc', 'define_estimand', 'assess_pv_causality'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Read-only reference: 142 deterministic_registry tools across 24 domains, with the determinism-pedigree trust system and the shared deterministic-result rendering pattern. Contract ref (not yet a @shared file): server/services/ana/tool-pedigree.ts',
  },
  {
    id: 'pharmacovigilance',
    label: 'Pharmacovigilance',
    navTier: 'specialist',
    layoutMode: 'pharmacovigilance',
    group: 'safety-pv',
    icon: 'shieldAlert',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/pharmacovigilance', '/api/safety-narratives'],
    anaToolFamilies: ['assess_pv_causality'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Safety surveillance: signal detection (PRR/FAERS/EudraVigilance), PSUR/PBRER aggregate-report cycles, expedited 7/15-day submissions across approved products.',
  },
  {
    id: 'design-controls',
    label: 'Design controls (DHF)',
    navTier: 'specialist',
    layoutMode: 'design-controls',
    group: 'device',
    icon: 'gitBranch',
    uiKit: null,
    apiPrefixes: ['/api/design-risk'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: '21 CFR 820.30 DHF — design inputs/outputs/verification/validation traceability matrix + completeness assessment.',
  },
  {
    id: 'human-factors',
    label: 'Human factors (IEC 62366-1)',
    navTier: 'specialist',
    layoutMode: 'human-factors',
    group: 'device',
    icon: 'users',
    uiKit: null,
    apiPrefixes: ['/api/human-factors'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'IEC 62366-1 HFE/UE — use-related risk analysis (critical tasks + summative gate) + HFE/UE file completeness.',
  },

  // ─── ui-v2 additions: admin ─────────────────────────────────────────────
  {
    id: 'licensing',
    label: 'Plans & licensing',
    navTier: 'admin',
    layoutMode: 'setup',
    group: 'admin',
    icon: 'creditCard',
    uiKit: null,
    apiPrefixes: ['/api/module-subscriptions', '/api/billing'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Plan tiers, seat licensing, module entitlements, upgrade/downgrade.',
  },
  {
    id: 'training',
    label: 'Training & enablement',
    navTier: 'admin',
    layoutMode: 'setup',
    group: 'admin',
    icon: 'book',
    uiKit: null,
    apiPrefixes: ['/api/enablement', '/api/ana'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'planned',
    compliance: [A11Y, TONE],
    notes: 'Guided tours, learning paths, certifications, and AnA tutor.',
  },
  {
    id: 'coverage',
    label: 'Codebase coverage',
    navTier: 'admin',
    layoutMode: 'coverage',
    group: 'admin',
    icon: 'grid',
    uiKit: null,
    apiPrefixes: ['/api/module-subscriptions'],
    anaToolFamilies: [],
    sharedContract: '@shared/constants/ui-surface-registry',
    discoveryCatalog: null,
    readiness: 'contract-ready',
    compliance: [A11Y, TONE],
    notes: 'The 33 canonical surfaces + real API prefixes + readiness, cross-referenced with what is built and wired here. Install/coverage tracker.',
  },
  {
    id: 'admin-console',
    label: 'Admin console',
    navTier: 'admin',
    layoutMode: 'admin-console',
    group: 'admin',
    icon: 'users',
    uiKit: null,
    apiPrefixes: ['/api/admin/access', '/api/admin/scim-tenants', '/api/api-keys', '/api/setup'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Designate personnel (platform_role_grants, governed+audited), SSO/SCIM, security, module subscriptions, API keys, audit.',
  },
  {
    id: 'onboarding',
    label: 'Onboarding',
    navTier: 'admin',
    layoutMode: 'onboarding',
    group: 'admin',
    icon: 'rocket',
    uiKit: null,
    apiPrefixes: ['/api/setup', '/api/billing/checkout', '/api/billing/dtc-checkout'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Client onboarding wizard: org archetype → pricing model → tier → seats → personnel → module provisioning → activate.',
  },
  {
    id: 'usage',
    label: 'Usage & limits',
    navTier: 'admin',
    layoutMode: 'usage',
    group: 'admin',
    icon: 'barChart',
    uiKit: null,
    apiPrefixes: ['/api/billing/usage/summary', '/api/billing/weekly-usage', '/api/billing/rate-limits'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Plan usage limits, weekly caps, usage credits, rate limits by tier — billing-dashboard.ts router, MOUNTED AT /api/billing (verified against register-inline-routes 2026-07-05).',
  },
];

// ── Cross-cutting concerns (not surfaces; every surface depends on these) ───────
//
// These are the providers/hooks design needs available app-wide BEFORE installing
// any surface. They are reported here so the install plan accounts for them once,
// not per-surface.

export interface CrossCuttingConcern {
  id: string;
  label: string;
  apiPrefixes: string[];
  sharedContract: string | null;
  notes: string;
}

export const CROSS_CUTTING_CONCERNS: CrossCuttingConcern[] = [
  {
    id: 'auth-session',
    label: 'Auth & session',
    apiPrefixes: ['/api/auth', '/api/users', '/api/auth/sso', '/api/auth/enterprise'],
    sharedContract: null,
    notes: 'JWT (sliding 7-day refresh), MFA (TOTP), SSO/SCIM. Token + org id flow through client/src/utils/authToken.ts and apiRequest headers.',
  },
  {
    id: 'tenant-org',
    label: 'Tenant / organization',
    apiPrefixes: ['/api/setup', '/api/enterprise'],
    sharedContract: null,
    notes: 'Org context via x-organization-id header + client/src/contexts/TenantContext. Multi-org picker.',
  },
  {
    id: 'feature-flags',
    label: 'Feature flags / entitlements',
    apiPrefixes: ['/api/module-subscriptions'],
    sharedContract: null,
    notes: 'Per-tenant module gating. client/src/flags/featureFlags.ts (isFeatureEnabled). Locked modules → upgrade CTA, never a dead button.',
  },
  {
    id: 'ana-rail',
    label: 'AnA assistant rail',
    apiPrefixes: ['/api/ana-ri', '/api/ana', '/api/chat'],
    sharedContract: '@shared/types/ai-actions',
    notes: 'Persistent right rail on EVERY surface. Modes standard/deep-research/quick-ask. SSE via /api/ana-ri/stream. Context card + suggested prompts + "Ask AnA about this" chips. Pedigree badge (registry-grounded vs verify).',
  },
  {
    id: 'esign-modal',
    label: 'E-signature modal',
    apiPrefixes: ['/api/esignature'],
    sharedContract: null,
    notes: 'Cross-cutting governed-action affordance (password re-verify + TOTP). 21 CFR §11.50 manifestation. Reused by review, submission, authoring.',
  },
];

// ── Selectors (pure; safe to import on client or server) ────────────────────────

const SURFACE_BY_ID: Record<string, UiSurface> = Object.fromEntries(
  UI_SURFACES.map((s) => [s.id, s])
);

/** Look up a surface by id, or undefined. */
export function getSurface(id: string): UiSurface | undefined {
  return SURFACE_BY_ID[id];
}

/** All surfaces in a nav tier, in registry order (use to build the left rail). */
export function surfacesByNavTier(tier: NavTier): UiSurface[] {
  return UI_SURFACES.filter((s) => s.navTier === tier);
}

/** Surfaces grouped by nav tier (ready for sectioned navigation). */
export function surfacesGroupedByNavTier(): Record<NavTier, UiSurface[]> {
  return {
    global: surfacesByNavTier('global'),
    project: surfacesByNavTier('project'),
    specialist: surfacesByNavTier('specialist'),
    admin: surfacesByNavTier('admin'),
  };
}

/** Surfaces at a given install readiness (use to drive an install tracker). */
export function surfacesByReadiness(tier: ReadinessTier): UiSurface[] {
  return UI_SURFACES.filter((s) => s.readiness === tier);
}

/** Count of surfaces per readiness tier (one-glance install progress). */
export function readinessSummary(): Record<ReadinessTier, number> {
  return READINESS_TIERS.reduce(
    (acc, tier) => {
      acc[tier] = surfacesByReadiness(tier).length;
      return acc;
    },
    {} as Record<ReadinessTier, number>
  );
}

/** Surfaces that expose a typed contract or a discovery catalog (highest leverage). */
export function contractReadySurfaces(): UiSurface[] {
  return UI_SURFACES.filter((s) => s.sharedContract !== null || s.discoveryCatalog !== null);
}

/**
 * The global-RI nav groups, re-exported so a client builds the global-RI
 * capability browser from the same source the backend uses. Avoids drift.
 */
export { GLOBAL_RI_GROUPS };
