/**
 * ui-v2 surface additions — the 48 surfaces the Concept2Cure.RI design kit
 * (design_handoff_c2c_v2_ui_replacement) adds on top of the 33 canonical
 * surfaces. Split out of ui-surface-registry.ts (kept both files under the
 * repo-health 1,500-line gate); the main file spreads UI_V2_SURFACES into
 * UI_SURFACES so every consumer and selector is unchanged.
 *
 * Ids are the kit registry.jsx ids verbatim — deep links depend on them.
 * Routes were repo-verified against all 15 server/bootstrap mount files in
 * the kit GA_READINESS_AUDIT (2026-07-05). Where the kit named a contract
 * that isn't a real @shared/*.ts file yet, sharedContract is null and the ref
 * is preserved in notes (GAP RULE — surfaced, not faked). See
 * docs/design/UI_V2_REGISTRY_RECONCILIATION_2026-07-06.md.
 */
import type { ComplianceRail, UiSurface } from './ui-surface-registry';

// Shorthand for the two near-universal rails (mirrors the main file).
const A11Y: ComplianceRail = 'accessibility-enforcement';
const TONE: ComplianceRail = 'microcopy-tone';
const PART11: ComplianceRail = 'regulatory-compliance-ux';

export const UI_V2_SURFACES: UiSurface[] = [
  // ─── ui-v2 additions: global ─────────────────────────────────────────────
  {
    id: 'ana-command',
    label: 'AnA Command',
    navTier: 'global',
    layoutMode: 'ana-command',
    group: 'explore',
    icon: 'sparkles',
    uiKit: null,
    apiPrefixes: ['/api/orchestration/continuity', '/api/orchestration/recommendations', '/api/orchestration/templates', '/api/orchestration/execute', '/api/orchestration/pre-submission-gate', '/api/orchestration/projects/:id/readiness'],
    anaToolFamilies: ['generate_recommendations', 'execute_workflow', 'assess_readiness'],
    sharedContract: '@shared/types/orchestration',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'AnA on top of everything across the portfolio: continuity briefing (what changed / newly ready / needs attention / trajectory), ranked dispatchable recommendations, runnable multi-step workflow templates (submission_readiness_review · draft_validate_route · project_blocker_scan), and the unified pre-submission go/no-go gate (readiness + CMC + CRL + RTF + ICH), audited to Part 11.',
  },
  {
    id: 'cro-portfolio',
    label: 'Sponsor portfolio',
    navTier: 'global',
    layoutMode: 'cro-portfolio',
    group: 'workspace',
    icon: 'network',
    uiKit: 'home',
    apiPrefixes: ['/api/cro/clients', '/api/cro/studies', '/api/cro/submissions'],
    anaToolFamilies: ['plan_submission'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'CRO multi-sponsor rollup. croClients → croStudies → croRegulatorySubmissions, every query org-scoped. Drill into a sponsor; each submission flows through its matching pathway onto the shared Submission Center lifecycle.',
  },
  {
    id: 'etmf',
    label: 'Inspection readiness',
    navTier: 'global',
    layoutMode: 'etmf',
    group: 'workspace',
    icon: 'network',
    uiKit: 'home',
    apiPrefixes: ['/api/etmf'],
    anaToolFamilies: ['generate_inspection_package'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'eTMF inspection-readiness (CRO deliverable). assessTmfCompleteness against the DIA TMF Reference Model (11 zones, ICH E6(R2) §8 essential docs) via GET /api/etmf/trials/:trialId/completeness; file gaps via POST .../artifacts. AnA GENERATES the inspection-readiness package (the hero deliverable), not a dashboard. GAP: the inspection-package ZIP + artifacts/bulk endpoints are on the feature branch claude/doc-mgmt-structure-alignment-4p91eu, not yet on concept2cure-v2 — the Download action wires to them live-first and degrades to an honest in-browser readiness report.',
  },
  {
    id: 'filings-catalog',
    label: 'Filings catalog',
    navTier: 'global',
    layoutMode: 'filings-catalog',
    group: 'workspace',
    icon: 'clipboardList',
    uiKit: 'home',
    apiPrefixes: ['/api/regulatory/registry'],
    anaToolFamilies: ['get_csr_template', 'plan_submission'],
    sharedContract: '@shared/regulatory/global-document-registry',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Canonical taxonomy of 113 filing types across pharma/biotech, device, IVD, cross-cutting. Each routes into its execution workflow (IND/NDA/BLA/MAA/510k/PMA/De Novo/CER).',
  },

  // ─── ui-v2 additions: project ─────────────────────────────────────────────
  {
    id: 'program-journey',
    label: 'Program journey',
    navTier: 'project',
    layoutMode: 'program-journey',
    group: 'workspace',
    icon: 'workflow',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/biopharma/programs', '/api/rim', '/api/regulatory-correspondence', '/api/ectd'],
    anaToolFamilies: ['plan_submission', 'assess_filing_readiness'],
    sharedContract: '@shared/types/submission-api',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The end-to-end biotech/pharma spine — concept to submission to lifecycle. 9 lifecycle stages, each with its agency gate, deliverables and the deep-linked capabilities that serve it, plus program intelligence: CTD readiness, review clock, predicted HAQs, contradictions and blockers.',
  },
  {
    id: 'dispatch-readiness',
    label: 'Dispatch readiness',
    navTier: 'project',
    layoutMode: 'dispatch-readiness',
    group: 'submission',
    icon: 'send',
    uiKit: 'mdx',
    apiPrefixes: ['/api/submissions/sequences'],
    anaToolFamilies: ['assess_dispatch_readiness', 'run_validation'],
    sharedContract: '@shared/types/submission-ui',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The proven, deterministic last gate before transmit (dispatch-gate.ts). Composes structural validation + unacknowledged Shadow Review criticals + external eValidator; a client cannot talk it down (every input server-computed). Flags the cleared-but-never-reviewed blind spot. Bound to GET /api/submissions/sequences/:seqId/dispatch-readiness.',
  },
  {
    id: 'shadow-review',
    label: 'Shadow review',
    navTier: 'project',
    layoutMode: 'shadow-review',
    group: 'submission',
    icon: 'eye',
    uiKit: 'mdx',
    apiPrefixes: ['/api/submissions/sequences'],
    anaToolFamilies: ['run_shadow_review', 'assess_filing_readiness'],
    sharedContract: '@shared/types/submission-ui',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'AnA simulates the reviewer who will read your submission (5 real lenses: FDA filing / EMA D120 / PMDA / MDR NB / IVDR NB) and scores the two gates that kill a filing — RTF (administrative) and CRL (substantive). Findings are model_assisted; the risk aggregation is the verbatim deterministic aggregateRisk (a single critical saturates). Bound to POST /api/submissions/sequences/:seqId/shadow-review.',
  },
  {
    id: 'decision-lineage',
    label: 'Decision lineage',
    navTier: 'project',
    layoutMode: 'decision-lineage',
    group: 'workspace',
    icon: 'gitBranch',
    uiKit: 'mdx',
    apiPrefixes: ['/api/decision-lineage', '/api/provenance'],
    anaToolFamilies: ['get_document', 'run_validation'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The immutable, Part-11 hash-chained decision trail behind every governed artifact (who decided what, when, on what evidence, signed how). Answer-first defensibility read, then the readable chain of governed decisions (5 node types), then chain-integrity verify + compliance frameworks + eCTD-compatible export. Bound to GET /api/decision-lineage/:entityType/:entityId + verify-chain. Contract ref (not yet a @shared file): @shared/types/decision-lineage',
  },
  {
    id: 'ivd-completeness',
    label: 'IVD completeness',
    navTier: 'project',
    layoutMode: 'ivd-completeness',
    group: 'workspace',
    icon: 'microscope',
    uiKit: 'mdx',
    apiPrefixes: ['/api/validate-completeness', '/api/c2c/projects'],
    anaToolFamilies: ['assess_filing_readiness', 'draft_section'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'IVDR technical-file completeness (validate-completeness IVDR branch) — GSPR Annex I, Performance Evaluation Report Annex XIII, analytical + clinical performance, scientific validity, PMPF/PMS. IVD-only; derives from the diagnostics IVDR spine. Answer-first CE-marking readiness, not the borrowed device checklist. Contract ref (not yet a @shared file): @shared/regulatory/ivdr',
  },
  {
    id: 'batch-draft',
    label: 'Parallel drafting',
    navTier: 'project',
    layoutMode: 'batch-draft',
    group: 'authoring',
    icon: 'sparkles',
    uiKit: 'authoring',
    apiPrefixes: ['/api/c2c/documents'],
    anaToolFamilies: ['batch_draft_sections', 'draft_section'],
    sharedContract: '@shared/types/document-contract',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'AnA drafts several dossier sections in parallel (batch_draft_sections) — one Accept card per section, each promoting through the same governed PATCH (saveSection · draftSource=ana). Fans out concurrent streamDraft SSE calls over the live per-section route.',
  },
  {
    id: 'authoring-engine',
    label: 'AnA Authoring Engine',
    navTier: 'project',
    layoutMode: 'authoring-engine',
    group: 'authoring',
    icon: 'sparkles',
    uiKit: 'authoring',
    apiPrefixes: ['/api/document-authoring', '/api/authoring', '/api/coauthor', '/api/templates', '/api/c2c/templates', '/api/task-management'],
    anaToolFamilies: ['draft_section', 'get_csr_template', 'get_nonclinical_template', 'draft_clinical_overview_m2_5'],
    sharedContract: '@shared/types/document-contract',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE, 'motion-discipline'],
    notes: 'End-to-end document suite for the whole CTD pyramid, raw data to final draft. An AI system per document type (no hallucinations, every required element), multi-modal (text/tables/figures/graphs), template-learning, and GxP automations whose non-AI validation logic runs as intended 100% of the time.',
  },
  {
    id: 'inconsistency',
    label: 'Inconsistency Intelligence',
    navTier: 'project',
    layoutMode: 'inconsistency',
    group: 'authoring',
    icon: 'gitCompare',
    uiKit: 'authoring',
    apiPrefixes: ['/api/governed-intelligence', '/api/coauthor', '/api/document-authoring', '/api/task-management'],
    anaToolFamilies: ['assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Change a governed value once and propagate it across every document that cites it. Draft sections update inline; approved/locked sections are flagged for re-approval with a task, on the audit trail. Matches Artos Inconsistency Intelligence / Weave content-update. Contract ref (not yet a @shared file): server/routes/assumption-decision-contradiction.ts',
  },
  {
    id: 'source-tracer',
    label: 'Source Tracer',
    navTier: 'project',
    layoutMode: 'source-tracer',
    group: 'authoring',
    icon: 'search',
    uiKit: 'authoring',
    apiPrefixes: ['/api/documents/:id/sources', '/api/documents/:id/sources/analyze', '/api/citations/verify'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Sentence-level provenance bound to sourceLinks.ts: every sentence carries a typed SourceLink (sourceType ∈ trial_data|literature|regulatory_guidance|internal_data) with a 0–1 confidence. POST /sources/analyze finds untraced claims (claimsFound). Literature citations are verified against PubMed+CrossRef via /api/citations/verify (verified|not_found|unverifiable|error) — an unconfirmed citation is flagged, never assumed. Fixture-backed with a Sample-data pill until live-wired. Contract ref (not yet a @shared file): server/routes/sourceLinks.ts + server/routes/citations.ts',
  },
  {
    id: 'dossier',
    label: 'Dossier',
    navTier: 'project',
    layoutMode: 'dossier',
    group: 'workspace',
    icon: 'folder',
    uiKit: 'mdx',
    apiPrefixes: ['/api/ectd', '/api/documents', '/api/corpus'],
    anaToolFamilies: ['draft_section', 'get_document'],
    sharedContract: '@shared/types/document-contract',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Document-first workspace (Artos/Weave model): eCTD folder tree · submission documents in process with status/version · the live document · Data Room of source files.',
  },
  {
    id: 'conversation-thread',
    label: 'Conversation',
    navTier: 'project',
    layoutMode: 'conversation-thread',
    group: 'workspace',
    icon: 'messageSquare',
    uiKit: 'mdx',
    apiPrefixes: ['/api/conversation-os', '/api/chat', '/api/authoring-actions'],
    anaToolFamilies: [],
    sharedContract: '@shared/schema',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Conversation-os thread: user+AnA messages, artifact proposals (propose→accept→apply), governed mutations, inline document/task/file references that route out. Contract detail: concept2cureConversations/Messages',
  },
  {
    id: 'evidence-search',
    label: 'Evidence search (RAG)',
    navTier: 'project',
    layoutMode: 'vault-workspace',
    group: 'evidence',
    icon: 'search',
    uiKit: null,
    apiPrefixes: ['/api/evidence', '/api/corpus', '/api/biotech-rag'],
    anaToolFamilies: ['get_evidence_chain'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Ask a question across the corpus — 3-layer memory → gateway → cited answer traced back to source chunks.',
  },
  {
    id: 'haq-manager',
    label: 'Health authority questions',
    navTier: 'project',
    layoutMode: 'haq',
    group: 'submission',
    icon: 'messageSquare',
    uiKit: 'mdx',
    apiPrefixes: ['/api/haq-manager', '/api/regulatory-correspondence', '/api/precedent-engine'],
    anaToolFamilies: ['draft_haq_response', 'search_precedent_responses'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Post-submission review phase: agency IR / Day-120 LoQ / CRL decomposed, source-traced responses with precedent intelligence, governed e-sign into the response package. Contract ref (not yet a @shared file): @shared/types/haq',
  },
  {
    id: 'nda-cockpit',
    label: 'NDA / BLA filing',
    navTier: 'project',
    layoutMode: 'nda-cockpit',
    group: 'submission',
    icon: 'beaker',
    uiKit: 'mdx',
    apiPrefixes: ['/api/ectd', '/api/biopharma', '/api/submission', '/api/shadow'],
    anaToolFamilies: ['assess_filing_readiness', 'run_shadow_review'],
    sharedContract: '@shared/types/submission-api',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'NDA/BLA filing cockpit: CTD M1–5 readiness, Module 1 admin set (356h), PDUFA review clock, Refuse-to-File risk (shadow review).',
  },
  {
    id: 'maa-cockpit',
    label: 'MAA / non-US Module 1',
    navTier: 'project',
    layoutMode: 'maa-cockpit',
    group: 'submission',
    icon: 'globe',
    uiKit: null,
    apiPrefixes: ['/api/global-ri'],
    anaToolFamilies: ['module1'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Non-US marketing-application administrative module (eCTD Module 1) — region-accurate required-component checklist for EMA/PMDA/MHRA/TGA/HC/NMPA over the global-RI regional-module1-requirements engine.',
  },
  {
    id: 'device-workstream',
    label: 'Medical Device & IVD',
    navTier: 'project',
    layoutMode: 'section-workspace',
    group: 'device',
    icon: 'stethoscope',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx', '/api/510k-workflow', '/api/cer', '/api/cerv2', '/api/ivdr', '/api/manufacturing'],
    anaToolFamilies: [],
    sharedContract: '@shared/types/predicate-intelligence',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The MDX workstream — one door. Programs portfolio with classification + 510(k)/PMA/CER/De Novo pathway tabs, predicate intelligence, eSTAR/Annex XIV editors. Built in the MDX kit.',
  },
  {
    id: 'protocol-dev',
    label: 'Protocol development',
    navTier: 'project',
    layoutMode: 'protocol-dev',
    group: 'authoring',
    icon: 'clipboardList',
    uiKit: 'authoring',
    apiPrefixes: ['/api/protocol-development', '/api/protocol-soa', '/api/protocol-risks', '/api/protocol-milestones', '/api/protocol-budget', '/api/protocol-amendments', '/api/protocol-deviations', '/api/protocol-reviews', '/api/protocol-consent', '/api/protocol-export'],
    anaToolFamilies: ['create_protocol_document', 'update_protocol_section', 'review_protocol_completeness', 'finalize_protocol_document', 'add_soa_assessment', 'review_soa_matrix'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Protocol authoring hub (C2C-17..22): full eCTD-style section tree, SoA grid, risk register (5×5), milestones, budget/feasibility, amendments, deviations/CAPA, reviews, informed consent — deterministic completeness gate on finalize (ICH M11 / 45 CFR 46 / PHS Policy).',
  },
  {
    id: 'research-admin',
    label: 'Research administration',
    navTier: 'project',
    layoutMode: 'research-admin',
    group: 'collaboration',
    icon: 'network',
    uiKit: 'mdx',
    apiPrefixes: ['/api/committees', '/api/coverage-analysis', '/api/grant-finder', '/api/citi-training', '/api/protocol-portfolio'],
    anaToolFamilies: ['convene_committee_meeting', 'cast_committee_vote', 'finalize_committee_determination', 'review_coverage_analysis', 'find_grant_opportunities', 'review_training_matrix', 'review_protocol_portfolio_analytics'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Research-administration workspace (C2C-14/15/16/01-02): IRB/IACUC/IBC governance with convene→quorum→voting poll + finalize determination, Medicare coverage analysis (NCD 310.1) billing grid, intelligent grant finder (fit scoring), CITI training matrix, continuing-review portfolio analytics.',
  },
  {
    id: 'pyramid',
    label: 'Submission pyramid',
    navTier: 'project',
    layoutMode: 'pyramid',
    group: 'submission',
    icon: 'workflow',
    uiKit: null,
    apiPrefixes: ['/api/v1/pyramids', '/api/v1/global-pyramids', '/api/v1/projects/:id/pyramid'],
    anaToolFamilies: ['plan_submission'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'contract-ready',
    compliance: [A11Y, TONE, 'motion-discipline'],
    notes: 'Deterministic submission work breakdown — type selector (8 engine + 12 global types), dashboard (progress ring, phase strip, risk gauge, next-available tasks), phase→task drill-down with full-metadata detail sheet (risk, CTD bindings, guidance, deps, deliverables), analytics (resources/bottlenecks, document coverage, critical path), global pyramid browser. Task status is the only client-owned state. Contract ref (not yet a @shared file): services/regulatory/SubmissionPyramidEngine.ts · globalPyramids.ts · submission-type-bridge.ts',
  },
  {
    id: 'registrations',
    label: 'Registrations',
    navTier: 'project',
    layoutMode: 'registrations',
    group: 'lifecycle',
    icon: 'globe',
    uiKit: 'mdx',
    apiPrefixes: ['/api/rim', '/api/global-ri', '/api/global-markets'],
    anaToolFamilies: ['global_ri_market_access'],
    sharedContract: '@shared/types/global-ri-api',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Global registration lifecycle: market authorization status, agency review clocks, renewals/variations, HA commitments, reliance-pathway strategy.',
  },
  {
    id: 'market-access',
    label: 'Market access',
    navTier: 'project',
    layoutMode: 'market-access',
    group: 'lifecycle',
    icon: 'creditCard',
    uiKit: 'mdx',
    apiPrefixes: ['/api/market-access'],
    anaToolFamilies: ['global_ri_market_access', 'compose_value_dossier'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Commercial bridge: payer coverage (CMS NCD/LCD, private, HTA), value-dossier composer (AMCP/NICE/budget-impact), coding strategy (CPT/PLA/HCPCS), access sequencing.',
  },
  {
    id: 'change-assessment',
    label: 'Change assessment',
    navTier: 'project',
    layoutMode: 'change-assessment',
    group: 'lifecycle',
    icon: 'gitBranch',
    uiKit: 'mdx',
    apiPrefixes: ['/api/change-propagation', '/api/rim'],
    anaToolFamilies: ['assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Change impact engine: FDA "When to Submit a 510(k) for a Change" (2017) + EU MDR significant-change (MDCG 2020-3) determinations → new submission vs document-to-file.',
  },
  {
    id: 'quality',
    label: 'Quality & Assurance',
    navTier: 'project',
    layoutMode: 'quality',
    group: 'quality-cmc',
    icon: 'shieldCheck',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx/qms'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Quality & Assurance: the SOP / controlled-document register (periodic review, read-and-understood training) and Change control (the change-control log + lifecycle flowchart, ICH Q10 / EU GMP Annex 15, linking changes to deviations, CAPAs and validation records). Backed by /api/mdx/qms/*.',
  },
  {
    id: 'doc-journey',
    label: 'Document journey',
    navTier: 'project',
    layoutMode: 'doc-journey',
    group: 'authoring',
    icon: 'gitBranch',
    uiKit: 'mdx',
    apiPrefixes: ['/api/authoring', '/api/workflow', '/api/submission', '/api/audit'],
    anaToolFamilies: ['draft_section', 'assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'One document, ideation → submission: ideate → outline → AnA draft → revise → review → QC → approve (§11 e-sign) → assemble (eCTD leaf) → transmit (ESG). Document state visible at every stage.',
  },
  {
    id: 'labeling-pi',
    label: 'Prescribing information',
    navTier: 'project',
    layoutMode: 'labeling-pi',
    group: 'authoring',
    icon: 'fileText',
    uiKit: 'mdx',
    apiPrefixes: ['/api/mdx', '/api/spl-fhir', '/api/rim'],
    anaToolFamilies: ['draft_label', 'draft_uspi'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'USPI (PLLR / 21 CFR 201.57), EU SmPC (QRD), SPL. End-of-review agency labeling negotiation (sponsor vs FDA redline). The label as the document.',
  },
  {
    id: 'labeling-smpc',
    label: 'EU SmPC (QRD)',
    navTier: 'project',
    layoutMode: 'labeling-smpc',
    group: 'authoring',
    icon: 'fileText',
    uiKit: null,
    apiPrefixes: ['/api/labeling-smpc'],
    anaToolFamilies: ['draft_label'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'EU Summary of Product Characteristics — QRD template section tree (1–10) with per-section authoring status + submission-readiness over the required sections. EU companion to labeling-pi (USPI).',
  },
  {
    id: 'agency-meetings',
    label: 'Agency meetings',
    navTier: 'project',
    layoutMode: 'agency-meetings',
    group: 'lifecycle',
    icon: 'users',
    uiKit: 'mdx',
    apiPrefixes: ['/api/ha-interactions', '/api/rim'],
    anaToolFamilies: ['draft_briefing_book', 'prepare_meeting_request'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Agency interactions: Pre-IND/INTERACT/Type A-D/EOP2/pre-NDA-BLA, device Q-Sub, EMA Scientific Advice. Briefing book document + questions, minutes + commitments back to the dossier.',
  },
  {
    id: 'communication-center',
    label: 'Communication Center',
    navTier: 'project',
    layoutMode: 'communication-center',
    group: 'submission',
    icon: 'mail',
    uiKit: null,
    apiPrefixes: ['/api/ha-interactions', '/api/regulatory-correspondence', '/api/submission-ops'],
    anaToolFamilies: ['draft_agency_response', 'plan_crl_response'],
    sharedContract: '@shared/types/communication-center',
    discoveryCatalog: 'AgencyCommunicationEventRecord',
    readiness: 'contract-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'The regulated FDA↔client loop: agency communications (9 source types) auto-generating tasks, submission lifecycle incl. CRL/RTF/denial (rejected_or_remediation) → response → resubmit, HA interactions + PMR/PMC/REMS commitments, authority profiles.',
  },
  {
    id: 'rbm',
    label: 'Risk-based monitoring',
    navTier: 'project',
    layoutMode: 'rbm',
    group: 'clinical',
    icon: 'shieldCheck',
    uiKit: 'risk',
    apiPrefixes: ['/api/mdx/rbm-assessments', '/api/mdx/rbm-kris', '/api/mdx/rbm-qtls', '/api/mdx/rbm-signals', '/api/mdx/rbm-site-risk', '/api/mdx/rbm-monitoring-plans', '/api/mdx/rbm-summary', '/api/mdx/rbm-report', '/api/mdx/rbm-attention'],
    anaToolFamilies: ['run_rbm_assessment', 'assess_site_risk', 'evaluate_kris_qtls', 'generate_rbm_plan', 'prioritize_monitoring_queries', 'run_central_monitoring', 'scan_patient_profiles', 'generate_rbm_report', 'get_rbm_attention'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE, 'motion-discipline'],
    notes: 'ICH E6(R3) RBQM domain shell — 10 surfaces (overview, risk review report, RACT, KRIs, QTLs, central monitoring, patient profiles, site risk, site oversight, monitoring plan) over 40 /api/mdx/rbm-* routes. 5 deterministic engines produce every score; assessment + plan approvals are Part 11 governed (reason-for-change + e-sign). Contract ref (not yet a @shared file): client/src/concept2cure/services/rbmService.ts · hooks/useRbm.ts',
  },
  {
    id: 'orchestration',
    label: 'Orchestration & readiness',
    navTier: 'project',
    layoutMode: 'orchestration',
    group: 'review',
    icon: 'workflow',
    uiKit: null,
    apiPrefixes: ['/api/orchestration', '/api/approval-workflows', '/api/submission-readiness'],
    anaToolFamilies: ['assess_filing_readiness'],
    sharedContract: '@shared/schema/orchestration',
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Persisted workflow engine: workflowRuns (steps · blockers · diffs · pause/resume/retry), approvalCheckpoints (manual/role/quorum/auto), readiness rules + evaluations → overall score, blocker count, isReady gate before filing.',
  },
  {
    id: 'reg-change',
    label: 'Regulatory change intelligence',
    navTier: 'project',
    layoutMode: 'reg-change',
    group: 'lifecycle',
    icon: 'bell',
    uiKit: null,
    apiPrefixes: ['/api/external-intelligence', '/api/regulatory-intelligence'],
    anaToolFamilies: ['assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Portfolio horizon scan: monitors FDA guidance, ISO/IEC revisions, EU MDCG/MDR-IVDR and statutory changes; assesses impact and resolves each to an action document (gap analysis, transition plan, update task) — never a passive feed.',
  },
  {
    id: 'insights',
    label: 'Reporting & analytics',
    navTier: 'project',
    layoutMode: 'insights',
    group: 'evidence',
    icon: 'barChart',
    uiKit: null,
    apiPrefixes: ['/api/report-os', '/api/insights'],
    anaToolFamilies: ['list_report_types', 'generate_report', 'portfolio_readiness', 'compare_regions', 'get_prediction', 'explain_blockers'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'AnA Reporting Canvas — conversational governed reporting over the Report-OS render model (30 report types), per-segment catalog, entitlement tiers, best-practice packs. Contract ref (not yet a @shared file): server/services/report-os/taxonomy.ts',
  },
  {
    id: 'pediatric',
    label: 'Pediatric (PIP / PSP)',
    navTier: 'project',
    layoutMode: 'pediatric',
    group: 'lifecycle',
    icon: 'users',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/biopharma/pediatric', '/api/rim'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [PART11, A11Y, TONE],
    notes: 'FDA §505B PREA / iPSP and EMA PIP: plans, deferrals, waivers, extrapolation rationale and PREA milestones.',
  },
  {
    id: 'orphan',
    label: 'Orphan & rare',
    navTier: 'project',
    layoutMode: 'orphan',
    group: 'lifecycle',
    icon: 'sparkles',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/biopharma/orphan', '/api/rim'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [A11Y, TONE],
    notes: 'Orphan-drug / rare-disease designations across FDA/EMA/PMDA, RPD priority-review vouchers & grants, and patient-advocacy engagement.',
  },
  {
    id: 'lifecycle-mgmt',
    label: 'Lifecycle management',
    navTier: 'project',
    layoutMode: 'lifecycle-mgmt',
    group: 'lifecycle',
    icon: 'history',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/biopharma/supplements', '/api/change-assessment', '/api/rim'],
    anaToolFamilies: ['assess_change_impact'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [PART11, A11Y, TONE],
    notes: 'Post-approval: supplements/variations (sBLA, Type II/IB, CBE-30), CMC change control classified against ICH Q12, and renewal cycles (PADER, 5-year, re-examination).',
  },
  {
    id: 'clinical-ops',
    label: 'Clinical operations',
    navTier: 'project',
    layoutMode: 'clinical-ops',
    group: 'clinical',
    icon: 'users',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/protocol-development', '/api/mdx/rbm-site-risk', '/api/protocol-deviations'],
    anaToolFamilies: ['assess_site_risk'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [PART11, A11Y, TONE],
    notes: 'Clinical-development operations: studies & enrollment, study sites with RBM risk linkage, DSMB / interim reviews, and protocol deviations with CAPA. Structured data entry for sites and deviations.',
  },
  {
    id: 'nonclinical',
    label: 'Nonclinical / Module 4',
    navTier: 'project',
    layoutMode: 'nonclinical',
    group: 'clinical',
    icon: 'microscope',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/nonclinical', '/api/preclinical', '/api/documents'],
    anaToolFamilies: ['get_nonclinical_template', 'calculate_ttc'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'kit-only',
    compliance: [PART11, A11Y, TONE],
    notes: 'IND-enabling & CTD Module 4: GLP study registry with finding classification and SEND status, SEND 12-domain conformance, the Module 2.6 written/tabulated summary builder, and Module 4 placement. Structured data entry for studies.',
  },

  // ─── ui-v2 additions: specialist ─────────────────────────────────────────────
  {
    id: 'intelligence-catalog',
    label: 'Intelligence catalog',
    navTier: 'specialist',
    layoutMode: 'intelligence-catalog',
    group: 'intelligence',
    icon: 'shieldCheck',
    uiKit: 'intelligence',
    apiPrefixes: ['/api/ana'],
    anaToolFamilies: ['calculate_ttc', 'define_estimand', 'assess_pv_causality'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Read-only reference: 142 deterministic_registry tools across 24 domains, with the determinism-pedigree trust system and the shared deterministic-result rendering pattern. Contract ref (not yet a @shared file): server/services/ana/tool-pedigree.ts',
  },
  {
    id: 'pharmacovigilance',
    label: 'Pharmacovigilance',
    navTier: 'specialist',
    layoutMode: 'pharmacovigilance',
    group: 'safety-pv',
    icon: 'shieldAlert',
    uiKit: 'biopharma',
    apiPrefixes: ['/api/pharmacovigilance', '/api/safety-narratives'],
    anaToolFamilies: ['assess_pv_causality'],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Safety surveillance: signal detection (PRR/FAERS/EudraVigilance), PSUR/PBRER aggregate-report cycles, expedited 7/15-day submissions across approved products.',
  },
  {
    id: 'design-controls',
    label: 'Design controls (DHF)',
    navTier: 'specialist',
    layoutMode: 'design-controls',
    group: 'device',
    icon: 'gitBranch',
    uiKit: null,
    apiPrefixes: ['/api/design-risk'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: '21 CFR 820.30 DHF — design inputs/outputs/verification/validation traceability matrix + completeness assessment.',
  },
  {
    id: 'human-factors',
    label: 'Human factors (IEC 62366-1)',
    navTier: 'specialist',
    layoutMode: 'human-factors',
    group: 'device',
    icon: 'users',
    uiKit: null,
    apiPrefixes: ['/api/human-factors'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'IEC 62366-1 HFE/UE — use-related risk analysis (critical tasks + summative gate) + HFE/UE file completeness.',
  },

  // ─── ui-v2 additions: admin ─────────────────────────────────────────────
  {
    id: 'licensing',
    label: 'Plans & licensing',
    navTier: 'admin',
    layoutMode: 'setup',
    group: 'admin',
    icon: 'creditCard',
    uiKit: null,
    apiPrefixes: ['/api/module-subscriptions', '/api/billing'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Plan tiers, seat licensing, module entitlements, upgrade/downgrade.',
  },
  {
    id: 'training',
    label: 'Training & enablement',
    navTier: 'admin',
    layoutMode: 'setup',
    group: 'admin',
    icon: 'book',
    uiKit: null,
    apiPrefixes: ['/api/enablement', '/api/ana'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'planned',
    compliance: [A11Y, TONE],
    notes: 'Guided tours, learning paths, certifications, and AnA tutor.',
  },
  {
    id: 'coverage',
    label: 'Codebase coverage',
    navTier: 'admin',
    layoutMode: 'coverage',
    group: 'admin',
    icon: 'grid',
    uiKit: null,
    apiPrefixes: ['/api/module-subscriptions'],
    anaToolFamilies: [],
    sharedContract: '@shared/constants/ui-surface-registry',
    discoveryCatalog: null,
    readiness: 'contract-ready',
    compliance: [A11Y, TONE],
    notes: 'The 33 canonical surfaces + real API prefixes + readiness, cross-referenced with what is built and wired here. Install/coverage tracker.',
  },
  {
    id: 'admin-console',
    label: 'Admin console',
    navTier: 'admin',
    layoutMode: 'admin-console',
    group: 'admin',
    icon: 'users',
    uiKit: null,
    apiPrefixes: ['/api/admin/access', '/api/admin/scim-tenants', '/api/api-keys', '/api/setup'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [PART11, A11Y, TONE],
    notes: 'Designate personnel (platform_role_grants, governed+audited), SSO/SCIM, security, module subscriptions, API keys, audit.',
  },
  {
    id: 'onboarding',
    label: 'Onboarding',
    navTier: 'admin',
    layoutMode: 'onboarding',
    group: 'admin',
    icon: 'rocket',
    uiKit: null,
    apiPrefixes: ['/api/setup', '/api/billing/checkout', '/api/billing/dtc-checkout'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Client onboarding wizard: org archetype → pricing model → tier → seats → personnel → module provisioning → activate.',
  },
  {
    id: 'usage',
    label: 'Usage & limits',
    navTier: 'admin',
    layoutMode: 'usage',
    group: 'admin',
    icon: 'barChart',
    uiKit: null,
    apiPrefixes: ['/api/billing/usage/summary', '/api/billing/weekly-usage', '/api/billing/rate-limits'],
    anaToolFamilies: [],
    sharedContract: null,
    discoveryCatalog: null,
    readiness: 'routes-ready',
    compliance: [A11Y, TONE],
    notes: 'Plan usage limits, weekly caps, usage credits, rate limits by tier — billing-dashboard.ts router, MOUNTED AT /api/billing (verified against register-inline-routes 2026-07-05).',
  },
];
