-- Q-Sub (Pre-Submission) — DRAFT migration
--
-- Mirrors shared/schema/q-sub.ts. Generated by hand for review; do not run
-- on a live database without backend lead approval. Once approved, run via
-- `drizzle-kit generate` to produce the canonical migration with index hash.

BEGIN;

-- ─── q_submissions ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS q_submissions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  program_id      text NOT NULL,
  q_number        varchar(32),
  q_sub_type      varchar(16) NOT NULL,
  title           text NOT NULL,
  stage           varchar(16) NOT NULL DEFAULT 'plan',
  days_in         integer NOT NULL DEFAULT 0,
  filed_at        timestamptz,
  target_date     timestamptz,
  fda_team        text,
  tone            varchar(8) DEFAULT '',
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  created_by      text,
  CONSTRAINT q_submissions_qsubtype_chk CHECK (q_sub_type IN ('presub','sir','srd','agree','info')),
  CONSTRAINT q_submissions_stage_chk    CHECK (stage IN ('plan','package','submit','await','feedback','integrate'))
);
CREATE INDEX IF NOT EXISTS q_submissions_program_idx ON q_submissions (program_id);
CREATE INDEX IF NOT EXISTS q_submissions_stage_idx   ON q_submissions (stage);
CREATE UNIQUE INDEX IF NOT EXISTS q_submissions_qnumber_uq ON q_submissions (q_number) WHERE q_number IS NOT NULL;

-- ─── q_sub_meetings ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS q_sub_meetings (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  q_submission_id       uuid NOT NULL REFERENCES q_submissions(id) ON DELETE CASCADE,
  meeting_date          timestamptz NOT NULL,
  kind                  varchar(64) NOT NULL,
  fda_team_display      text,
  confirmed             boolean NOT NULL DEFAULT false,
  minutes_received_at   timestamptz,
  minutes_text          text,
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS q_sub_meetings_submission_idx ON q_sub_meetings (q_submission_id);

-- ─── q_sub_questions ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS q_sub_questions (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  q_submission_id   uuid NOT NULL REFERENCES q_submissions(id) ON DELETE CASCADE,
  n                 integer NOT NULL,
  question          text NOT NULL,
  our_position      text NOT NULL,
  fda_response      text,
  status            varchar(16) NOT NULL DEFAULT 'awaiting',
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT q_sub_questions_status_chk CHECK (status IN ('answered','awaiting'))
);
CREATE INDEX IF NOT EXISTS q_sub_questions_submission_idx ON q_sub_questions (q_submission_id);
CREATE UNIQUE INDEX IF NOT EXISTS q_sub_questions_submission_n_uq ON q_sub_questions (q_submission_id, n);

-- ─── q_sub_commitments ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS q_sub_commitments (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  q_sub_question_id        uuid NOT NULL REFERENCES q_sub_questions(id) ON DELETE CASCADE,
  display_code             varchar(32) NOT NULL,
  text                     text NOT NULL,
  dossier_link_kind        varchar(32) NOT NULL,
  dossier_link_label       varchar(128) NOT NULL,
  dossier_link_section_id  text NOT NULL,
  rolled_in                boolean NOT NULL DEFAULT false,
  rolled_in_at             timestamptz,
  rolled_in_by             text,
  blocker                  boolean NOT NULL DEFAULT false,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT q_sub_commitments_link_chk CHECK (dossier_link_kind IN ('k510-section','pma-section','cer-section'))
);
CREATE INDEX IF NOT EXISTS q_sub_commitments_question_idx ON q_sub_commitments (q_sub_question_id);
CREATE INDEX IF NOT EXISTS q_sub_commitments_blocker_idx ON q_sub_commitments (blocker) WHERE blocker = true;
CREATE INDEX IF NOT EXISTS q_sub_commitments_section_idx ON q_sub_commitments (dossier_link_section_id);
CREATE UNIQUE INDEX IF NOT EXISTS q_sub_commitments_displaycode_uq ON q_sub_commitments (display_code);

-- ─── q_sub_timeline_entries ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS q_sub_timeline_entries (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  q_submission_id   uuid NOT NULL REFERENCES q_submissions(id) ON DELETE CASCADE,
  "when"            varchar(32) NOT NULL,
  who               varchar(64) NOT NULL,
  what              text NOT NULL,
  occurred_at       timestamptz NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS q_sub_timeline_submission_idx ON q_sub_timeline_entries (q_submission_id);
CREATE INDEX IF NOT EXISTS q_sub_timeline_occurred_idx   ON q_sub_timeline_entries (occurred_at DESC);

COMMIT;
