-- ============================================================================
-- 20260930_report_type_registry_seed.sql — GENERATED. DO NOT EDIT BY HAND.
--
-- Source:     REPORT_TYPE_SEED            server/services/report-os/taxonomy.ts
--             GLOBAL_REPORT_TYPE_SEED     server/services/report-os/taxonomy-global.ts
--             PREDICTION_REPORT_TYPES     server/services/report-os/prediction/report-types.ts
-- Generator:  npx tsx scripts/db/generate-report-type-registry-seed.ts
-- Drift test: server/services/report-os/__tests__/report-type-registry-seed.test.ts
-- ============================================================================
--
-- 2026-09-30 (D2, Reporting & analytics joins the launch catalog). Why this
-- file exists: report_runs.report_type_id references
-- report_type_registry(type_id) ON DELETE RESTRICT, and POST /api/report-os/runs
-- answers 404 "Unknown reportTypeId" for a type the registry does not hold. No
-- migration inserted into the registry, and its only writer,
-- POST /api/report-os/taxonomy/seed, was refused in production. On a database
-- provisioned the canonical way (drizzle-kit push + the migration set) the
-- registry held 0 rows, so every Run in the Reporting canvas failed.
--
-- What it does, on every deploy (CLAUDE.md Rule 1: every file in
-- C2C_MIGRATION_FILES re-runs on every deploy):
--   1. Refuses when report_type_registry is missing. drizzle-kit push creates
--      it from shared/schema/report-os.ts at provisioning; a database without
--      it was not provisioned completely, and this file does not create it.
--   2. Upserts the 61 code-defined types, each json column as the text
--      drizzle's json column sends: ON CONFLICT (type_id) DO UPDATE SET every
--      descriptive column and updated_at = now(), so the registry mirrors the
--      code after every deploy. `enabled` is not in the SET list: an
--      operator's disable survives every deploy.
--   3. Raises when fewer than 61 of the seeded type_ids are present.
--
-- Changing a type: edit it in code and regenerate this file; the drift test
-- fails until they match. Regenerating in place registers as `drift` in
-- c2c_migration_journal, which is expected for this file. A type removed from
-- the code keeps its row (report_runs and report_subscriptions reference it
-- ON DELETE RESTRICT); retire it with enabled = false.
--
-- Review round 1 (2026-09-30): POST /taxonomy/seed was deleted. This file is
-- the one writer of the registry.
--
-- No DDL, no DROP.

DO $$
BEGIN
  IF to_regclass('public.report_type_registry') IS NULL THEN
    RAISE EXCEPTION 'report_type_registry does not exist. drizzle-kit push creates it from shared/schema/report-os.ts when the database is provisioned (scripts/db/install-fresh.mjs); this database was not provisioned completely, and this migration does not create the table.';
  END IF;
END $$;

INSERT INTO public.report_type_registry
  (type_id, label, family, allowed_scopes, allowed_personas, allowed_client_segments, data_dependencies, artifact_dependencies, workflow_dependencies, ana_modules, export_template, governance_requirements, truthfulness_rules)
VALUES
  ('readiness.executive_digest', 'Executive Readiness Digest', 'readiness', '["program","project","submission"]'::json, '["executive","ra_lead","pm"]'::json, '["pharma","device","biotech"]'::json, '["submission_readiness","section_status","artifact_lifecycle"]'::json, '["concept2cure_artifacts"]'::json, '["project_sections","submission_ops"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'executive-board-pack', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('provenance.evidence_trace_report', 'Evidence & Provenance Trace Report', 'evidence_provenance', '["project","submission","document"]'::json, '["ra_lead","medical_writer","qa"]'::json, '["pharma","device","biotech"]'::json, '["provenance_map","cross_refs","evidence_links"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["editor_verify_panels"]'::json, '["ana-ri"]'::json, 'evidence-provenance-pack', '{"part11":true,"provenanceCompleteness":true}'::json, '{"allowPartial":true,"requireConfidence":true}'::json),
  ('compliance.audit_assurance_pack', 'Compliance & Audit Assurance Pack', 'compliance_audit', '["project","submission","document"]'::json, '["qa","ra_lead","auditor"]'::json, '["pharma","device","biotech"]'::json, '["audit_events","signature_chain","compliance_scan"]'::json, '["immutable_report_records","report_seal_events"]'::json, '["signature_workflow","governance_boundary"]'::json, '["ana-ri"]'::json, 'qa-audit-pack', '{"part11":true,"signatureChain":true}'::json, '{"allowPartial":true,"requireExplicitGaps":true}'::json),
  ('usa_fda.pma_submission_readiness', 'FDA PMA Submission Readiness Pack', 'usa_fda_pma', '["project","submission"]'::json, '["ra_lead","medical_writer","executive"]'::json, '["device","biotech"]'::json, '["submission_readiness","clinical_evidence","device_safety_summary"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'fda-pma-readiness-pack', '{"part11":true,"auditTrail":true,"region":"USA_FDA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('usa_fda.estar_510k_equivalence_matrix', 'FDA eSTAR / 510(k) Equivalence Matrix', 'usa_fda_510k', '["project","submission","document"]'::json, '["ra_lead","qa"]'::json, '["device"]'::json, '["predicate_mapping","substantial_equivalence","testing_coverage"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","project_sections"]'::json, '["ana-ri"]'::json, 'fda-510k-equivalence-pack', '{"part11":true,"auditTrail":true,"region":"USA_FDA"}'::json, '{"allowPartial":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('usa_fda.deficiency_response_intelligence', 'FDA Deficiency Response Intelligence Report', 'usa_fda_response', '["project","submission","document"]'::json, '["ra_lead","qa","medical_writer"]'::json, '["pharma","device","biotech"]'::json, '["correspondence_issues","response_actions","risk_register"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'fda-deficiency-response-pack', '{"part11":true,"auditTrail":true,"region":"USA_FDA"}'::json, '{"allowPartial":false,"requireBlockers":true,"requireExplicitGaps":true}'::json),
  ('ema.maa_readiness_assessment', 'EMA MAA Readiness Assessment', 'ema_maa', '["program","project","submission"]'::json, '["ra_lead","executive","medical_writer"]'::json, '["pharma","biotech"]'::json, '["submission_readiness","module_completeness","question_risk"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'ema-maa-readiness-pack', '{"part11":true,"auditTrail":true,"region":"EU_EMA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('ema.rmp_psur_signal_alignment', 'EMA RMP / PSUR Signal Alignment Report', 'ema_post_market', '["project","submission","document"]'::json, '["ra_lead","qa"]'::json, '["pharma","biotech"]'::json, '["safety_signals","benefit_risk","risk_management_plan"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'ema-rmp-psur-alignment-pack', '{"part11":true,"auditTrail":true,"region":"EU_EMA"}'::json, '{"allowPartial":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('china_nmpa.ctd_module_gap_analysis', 'NMPA CTD Module Gap Analysis', 'china_nmpa_ctd', '["project","submission","document"]'::json, '["ra_lead","medical_writer","qa"]'::json, '["pharma","biotech","device"]'::json, '["module_completeness","formatting_compliance","evidence_links"]'::json, '["concept2cure_artifacts"]'::json, '["project_sections","submission_ops"]'::json, '["ana-ri"]'::json, 'nmpa-ctd-gap-pack', '{"part11":true,"auditTrail":true,"region":"CN_NMPA"}'::json, '{"allowPartial":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('china_nmpa.registration_dossier_readiness', 'NMPA Registration Dossier Readiness Pack', 'china_nmpa_registration', '["program","project","submission"]'::json, '["ra_lead","executive"]'::json, '["pharma","biotech","device"]'::json, '["submission_readiness","artifact_lifecycle","question_risk"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'nmpa-registration-readiness-pack', '{"part11":true,"auditTrail":true,"region":"CN_NMPA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('china_nmpa.deficiency_letter_root_cause_pack', 'NMPA Deficiency Letter Root-Cause Pack', 'china_nmpa_response', '["project","submission","document"]'::json, '["ra_lead","qa","medical_writer"]'::json, '["pharma","biotech","device"]'::json, '["correspondence_issues","root_cause_analysis","response_actions"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'nmpa-deficiency-root-cause-pack', '{"part11":true,"auditTrail":true,"region":"CN_NMPA"}'::json, '{"allowPartial":false,"requireBlockers":true,"requireExplicitGaps":true}'::json),
  ('fcoi.disclosure_register', 'Financial Disclosure Register (21 CFR 54)', 'fcoi_compliance', '["submission","project"]'::json, '["ra_lead","qa","submission_coordinator"]'::json, '["pharma","biotech","device"]'::json, '["financial_disclosures","disclosure_interests","provenance_links"]'::json, '["concept2cure_artifacts"]'::json, '["signature_workflow","governance_boundary"]'::json, '["ana-ri"]'::json, 'fcoi-disclosure-register', '{"part11":true,"auditTrail":true,"region":"USA_FDA"}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('ha.commitment_register', 'HA Interaction & Commitment Register', 'ha_commitment', '["submission","project","program"]'::json, '["ra_lead","reg_strategy","executive"]'::json, '["pharma","biotech","device"]'::json, '["ha_interactions","regulatory_commitments","commitment_milestones","provenance_links"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'ha-commitment-register', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('iacuc.protocol_register', 'IACUC Protocol & Animal Census Register', 'iacuc_governance', '["project","submission","program"]'::json, '["iacuc_coordinator","ra_lead","qa"]'::json, '["academic","biotech","pharma"]'::json, '["iacuc_protocols","iacuc_animal_cohorts","iacuc_reviews","iacuc_amendments","provenance_links"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'iacuc-protocol-register', '{"part11":true,"auditTrail":true,"region":"USA_OLAW"}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('irb.submission_register', 'IRB Submission & Determination Register', 'irb_ethics', '["study","submission","project"]'::json, '["clinical_ops","ra_lead","qa"]'::json, '["biotech","pharma","academic"]'::json, '["irb_submissions","irb_sites","irb_reviews","irb_amendments","irb_reportable_events","provenance_links"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'irb-submission-register', '{"part11":true,"auditTrail":true,"region":"USA_OHRP"}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('ibc.registration_register', 'IBC Biosafety Registration & Containment Register', 'ibc_biosafety', '["project","submission","program"]'::json, '["biosafety_officer","ra_lead","qa"]'::json, '["biotech","academic","pharma"]'::json, '["ibc_registrations","ibc_biological_agents","ibc_reviews","provenance_links"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'ibc-registration-register', '{"part11":true,"auditTrail":true,"region":"USA_NIH"}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('nonclinical.study_send_register', 'Nonclinical Study & SEND Readiness Register', 'nonclinical_module4', '["submission","program","project"]'::json, '["nonclinical_lead","ra_lead","qa"]'::json, '["pharma","biotech"]'::json, '["nonclinical_studies","send_datasets","provenance_links"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'nonclinical-study-send-register', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('grants.portfolio_register', 'Grant Portfolio & Funder-Milestone Register', 'sponsored_programs', '["program","project","account"]'::json, '["research_admin","pi","finance","executive"]'::json, '["academic","biotech"]'::json, '["grant_opportunities","grant_proposals","grant_awards","grant_milestones","grant_invoices","provenance_links"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'grant-portfolio-register', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('rim.registration_grid', 'Product Registration Grid & Labeling Register', 'rim_registration', '["program","project","account"]'::json, '["ra_ops","labeling_lead","executive"]'::json, '["pharma","biotech"]'::json, '["rim_products","rim_registrations","rim_labels"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'rim-registration-grid', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('inspection.readiness_pack', 'Inspection Readiness & 483 Response Pack', 'inspection_readiness', '["program","project","submission"]'::json, '["qa","ra_lead","executive","clinical_ops"]'::json, '["pharma","biotech","device","ivd","cro"]'::json, '["inspections","inspection_findings","finding_responses","readiness_assessments"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'inspection-readiness-pack', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('controlled_substances.inventory_ledger', 'Controlled Substances Inventory & DEA Ledger', 'controlled_substances', '["program","project","account"]'::json, '["research_ops","qa","ra_lead"]'::json, '["academic","biotech","pharma"]'::json, '["dea_registrations","controlled_substances","cs_transactions"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'controlled-substances-ledger', '{"part11":true,"auditTrail":true,"region":"USA_DEA"}'::json, '{"allowPartial":false,"requireBlockers":true,"requireExplicitGaps":true}'::json),
  ('lifecycle.obligation_calendar', 'Lifecycle Obligation Calendar', 'lifecycle_obligations', '["program","project","submission"]'::json, '["ra_ops","ra_lead","executive"]'::json, '["pharma","biotech"]'::json, '["lifecycle_obligations","lifecycle_obligation_events"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'lifecycle-obligation-calendar', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('etmf.completeness_pack', 'eTMF Completeness & Gap Pack', 'etmf', '["study","submission","project"]'::json, '["clinical_ops","tmf_lead","qa"]'::json, '["pharma","biotech","cro"]'::json, '["tmf_files","tmf_artifacts"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'etmf-completeness-pack', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('research_compliance.training_status', 'Research Personnel Training Status', 'research_compliance', '["program","project","account"]'::json, '["compliance_officer","ra_lead","qa"]'::json, '["academic","biotech","pharma"]'::json, '["research_personnel","personnel_training"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'research-compliance-training-status', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('effort.certification_register', 'Effort Certification Register', 'effort_certification', '["program","project","account"]'::json, '["compliance_officer","ra_lead","finance"]'::json, '["academic","biotech","pharma"]'::json, '["effort_certifications","effort_lines"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'effort-certification-register', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('research_security.coi_register', 'Research Security & COI Disclosure Register', 'research_security', '["program","project","account"]'::json, '["compliance_officer","ra_lead","research_security"]'::json, '["academic","biotech","pharma"]'::json, '["coi_disclosures","research_personnel"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'research-security-coi-register', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('research_admin.scorecard', 'Research Administration Scorecard', 'research_admin', '["program","account"]'::json, '["compliance_officer","ra_lead","executive"]'::json, '["academic","biotech","pharma"]'::json, '["regulatory_commitments","iacuc_protocols","personnel_training","coi_disclosures","grant_awards","grant_closeout_records","effort_certifications"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'research-admin-scorecard', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('prediction.regulatory_forecast', 'Predictive Regulatory Forecast', 'prediction', '["program","project","submission"]'::json, '["executive","ra_lead","pm"]'::json, '["pharma","biotech","device"]'::json, '["submission_readiness","readiness_trend"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'prediction-forecast-pack', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"forbidFinal":true,"requireDisclosure":true}'::json),
  ('prediction.crl_rtf_premortem', 'CRL / RTF Pre-Mortem', 'prediction', '["program","project","submission"]'::json, '["executive","ra_lead","qa"]'::json, '["pharma","biotech"]'::json, '["deficiency_risk","correspondence_issues"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'prediction-premortem-pack', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"forbidFinal":true,"requireDisclosure":true}'::json),
  ('usa_fda.ind_safety_readiness', 'FDA IND Safety & Readiness Pack (21 CFR 312)', 'usa_fda_ind', '["project","submission"]'::json, '["ra_lead","medical_writer","pv_lead","qa"]'::json, '["pharma","biotech"]'::json, '["submission_readiness","nonclinical_studies","safety_signals","module_completeness"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'fda-ind-readiness-pack', '{"part11":true,"auditTrail":true,"region":"USA_FDA"}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true,"requireConfidence":true}'::json),
  ('usa_fda.nda_bla_filing_readiness', 'FDA NDA / BLA Filing Readiness Assessment (eCTD)', 'usa_fda_nda_bla', '["program","project","submission"]'::json, '["ra_lead","medical_writer","executive","qa"]'::json, '["pharma","biotech"]'::json, '["submission_readiness","module_completeness","section_status","question_risk"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'fda-nda-bla-readiness-pack', '{"part11":true,"auditTrail":true,"region":"USA_FDA"}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true,"requireConfidence":true}'::json),
  ('usa_fda.crl_response_intelligence', 'FDA Complete Response Letter (CRL) Response Pack', 'usa_fda_response', '["project","submission","document"]'::json, '["ra_lead","medical_writer","qa","executive"]'::json, '["pharma","biotech"]'::json, '["correspondence_issues","root_cause_analysis","response_actions","risk_register"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'fda-crl-response-pack', '{"part11":true,"auditTrail":true,"region":"USA_FDA"}'::json, '{"allowPartial":false,"requireBlockers":true,"requireExplicitGaps":true,"forbidFinalIfMissingCritical":true}'::json),
  ('usa_fda.type_bcd_meeting_brief', 'FDA Type A/B/C Meeting Briefing Package', 'usa_fda_meetings', '["project","submission"]'::json, '["ra_lead","medical_writer","executive"]'::json, '["pharma","biotech"]'::json, '["ha_interactions","submission_readiness","question_risk","evidence_links"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","project_sections"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'fda-meeting-briefing-package', '{"part11":true,"auditTrail":true,"region":"USA_FDA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('usa_fda.de_novo_classification_pack', 'FDA De Novo Classification Request Pack (21 CFR 860)', 'usa_fda_de_novo', '["project","submission","document"]'::json, '["ra_lead","qa","medical_writer"]'::json, '["device"]'::json, '["submission_readiness","clinical_evidence","device_safety_summary","predicate_mapping"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'fda-de-novo-classification-pack', '{"part11":true,"auditTrail":true,"region":"USA_FDA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('ema.maa_loq_response_pack', 'EMA MAA List of Questions (Day-120 / Day-180) Response Pack', 'ema_response', '["project","submission","document"]'::json, '["ra_lead","medical_writer","qa"]'::json, '["pharma","biotech"]'::json, '["correspondence_issues","response_actions","question_risk","evidence_links"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'ema-loq-response-pack', '{"part11":true,"auditTrail":true,"region":"EU_EMA"}'::json, '{"allowPartial":false,"requireBlockers":true,"requireExplicitGaps":true,"forbidFinalIfMissingCritical":true}'::json),
  ('ema.variation_readiness', 'EMA Variation Readiness Pack (Type IA / IB / II)', 'ema_variation', '["project","submission"]'::json, '["ra_lead","ra_ops","qa"]'::json, '["pharma","biotech"]'::json, '["submission_readiness","module_completeness","lifecycle_obligations"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri"]'::json, 'ema-variation-readiness-pack', '{"part11":true,"auditTrail":true,"region":"EU_EMA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('ema.psur_pbrer_pack', 'EMA PSUR / PBRER Pack (ICH E2C(R2))', 'ema_post_market', '["project","submission","document"]'::json, '["pv_lead","ra_lead","medical_writer"]'::json, '["pharma","biotech"]'::json, '["safety_signals","benefit_risk","risk_management_plan","evidence_links"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'ema-psur-pbrer-pack', '{"part11":true,"auditTrail":true,"region":"EU_EMA"}'::json, '{"allowPartial":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('ema.scientific_advice_brief', 'EMA Scientific Advice / Protocol Assistance Briefing Package', 'ema_meetings', '["project","submission"]'::json, '["ra_lead","medical_writer","executive"]'::json, '["pharma","biotech"]'::json, '["ha_interactions","submission_readiness","question_risk","evidence_links"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","project_sections"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'ema-scientific-advice-brief', '{"part11":true,"auditTrail":true,"region":"EU_EMA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('eu_mdr.technical_documentation_readiness', 'EU MDR Technical Documentation Readiness (Annex II / III)', 'eu_mdr_techdoc', '["project","submission"]'::json, '["ra_lead","qa","medical_writer"]'::json, '["device"]'::json, '["submission_readiness","module_completeness","clinical_evidence","device_safety_summary"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'eu-mdr-techdoc-readiness-pack', '{"part11":true,"auditTrail":true,"region":"EU_MDR"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('eu_mdr.cer_per_completeness', 'EU MDR Clinical Evaluation Report (CER) Completeness Pack (MEDDEV 2.7/1 Rev.4)', 'eu_mdr_clinical', '["project","submission","document"]'::json, '["ra_lead","medical_writer","qa"]'::json, '["device"]'::json, '["clinical_evidence","evidence_links","benefit_risk","section_status"]'::json, '["concept2cure_artifacts"]'::json, '["project_sections","governance_boundary"]'::json, '["ana-ri"]'::json, 'eu-mdr-cer-completeness-pack', '{"part11":true,"auditTrail":true,"region":"EU_MDR"}'::json, '{"allowPartial":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('eu_ivdr.performance_evaluation_readiness', 'EU IVDR Performance Evaluation Report (PER) Readiness (Annex XIII)', 'eu_ivdr_performance', '["project","submission","document"]'::json, '["ra_lead","medical_writer","qa"]'::json, '["ivd","device"]'::json, '["clinical_evidence","evidence_links","device_safety_summary","section_status"]'::json, '["concept2cure_artifacts"]'::json, '["project_sections","governance_boundary"]'::json, '["ana-ri"]'::json, 'eu-ivdr-per-readiness-pack', '{"part11":true,"auditTrail":true,"region":"EU_IVDR"}'::json, '{"allowPartial":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('japan_pmda.jnda_shonin_readiness', 'PMDA J-NDA / Shonin Approval Readiness Pack', 'japan_pmda_jnda', '["program","project","submission"]'::json, '["ra_lead","medical_writer","executive"]'::json, '["pharma","biotech"]'::json, '["submission_readiness","module_completeness","question_risk","section_status"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'pmda-jnda-readiness-pack', '{"part11":true,"auditTrail":true,"region":"JP_PMDA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('japan_pmda.consultation_brief', 'PMDA Consultation (Taimen Advice) Briefing Package', 'japan_pmda_meetings', '["project","submission"]'::json, '["ra_lead","medical_writer","executive"]'::json, '["pharma","biotech"]'::json, '["ha_interactions","submission_readiness","question_risk","evidence_links"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","project_sections"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'pmda-consultation-brief', '{"part11":true,"auditTrail":true,"region":"JP_PMDA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('japan_pmda.reexamination_pack', 'PMDA Re-examination (Saishinsa) Pack', 'japan_pmda_post_market', '["project","submission","document"]'::json, '["ra_lead","pv_lead","qa"]'::json, '["pharma","biotech"]'::json, '["safety_signals","benefit_risk","lifecycle_obligations","evidence_links"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","governance_boundary"]'::json, '["ana-ri"]'::json, 'pmda-reexamination-pack', '{"part11":true,"auditTrail":true,"region":"JP_PMDA"}'::json, '{"allowPartial":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('canada_hc.nds_snds_readiness', 'Health Canada NDS / SNDS Filing Readiness Pack', 'canada_hc_nds', '["program","project","submission"]'::json, '["ra_lead","medical_writer","qa"]'::json, '["pharma","biotech"]'::json, '["submission_readiness","module_completeness","question_risk","section_status"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'hc-nds-snds-readiness-pack', '{"part11":true,"auditTrail":true,"region":"CA_HC"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('canada_hc.device_licence_readiness', 'Health Canada Medical Device Licence (MDL) Readiness Pack', 'canada_hc_device', '["project","submission"]'::json, '["ra_lead","qa","medical_writer"]'::json, '["device"]'::json, '["submission_readiness","clinical_evidence","device_safety_summary","module_completeness"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'hc-device-licence-readiness-pack', '{"part11":true,"auditTrail":true,"region":"CA_HC"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('uk_mhra.maa_readiness', 'MHRA Marketing Authorisation Application Readiness Pack', 'uk_mhra_maa', '["program","project","submission"]'::json, '["ra_lead","medical_writer","executive"]'::json, '["pharma","biotech"]'::json, '["submission_readiness","module_completeness","question_risk","section_status"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'mhra-maa-readiness-pack', '{"part11":true,"auditTrail":true,"region":"UK_MHRA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('uk_mhra.ilap_pathway_brief', 'MHRA ILAP Target Development Profile Briefing Package', 'uk_mhra_pathway', '["project","submission"]'::json, '["ra_lead","medical_writer","executive"]'::json, '["pharma","biotech"]'::json, '["ha_interactions","submission_readiness","question_risk","evidence_links"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","project_sections"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'mhra-ilap-pathway-brief', '{"part11":true,"auditTrail":true,"region":"UK_MHRA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('australia_tga.prescription_medicine_readiness', 'TGA Prescription Medicine Registration Readiness Pack (ARTG)', 'australia_tga_medicine', '["program","project","submission"]'::json, '["ra_lead","medical_writer","qa"]'::json, '["pharma","biotech"]'::json, '["submission_readiness","module_completeness","question_risk","section_status"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'tga-prescription-medicine-readiness-pack', '{"part11":true,"auditTrail":true,"region":"AU_TGA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('australia_tga.artg_device_inclusion_readiness', 'TGA Medical Device ARTG Inclusion Readiness Pack', 'australia_tga_device', '["project","submission"]'::json, '["ra_lead","qa","medical_writer"]'::json, '["device"]'::json, '["submission_readiness","clinical_evidence","device_safety_summary","module_completeness"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'tga-artg-device-inclusion-readiness-pack', '{"part11":true,"auditTrail":true,"region":"AU_TGA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('korea_mfds.drug_registration_readiness', 'MFDS Drug Item Registration Readiness Pack', 'korea_mfds_registration', '["program","project","submission"]'::json, '["ra_lead","medical_writer","qa"]'::json, '["pharma","biotech"]'::json, '["submission_readiness","module_completeness","question_risk","formatting_compliance"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'mfds-drug-registration-readiness-pack', '{"part11":true,"auditTrail":true,"region":"KR_MFDS"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('switzerland_swissmedic.maa_readiness', 'Swissmedic Marketing Authorisation (Zulassung) Readiness Pack', 'switzerland_swissmedic_maa', '["program","project","submission"]'::json, '["ra_lead","medical_writer","qa"]'::json, '["pharma","biotech"]'::json, '["submission_readiness","module_completeness","question_risk","section_status"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'swissmedic-maa-readiness-pack', '{"part11":true,"auditTrail":true,"region":"CH_SWISSMEDIC"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('brazil_anvisa.registration_dossier_readiness', 'ANVISA Registration Dossier (Registro) Readiness Pack', 'brazil_anvisa_registration', '["program","project","submission"]'::json, '["ra_lead","medical_writer","qa"]'::json, '["pharma","biotech","device"]'::json, '["submission_readiness","module_completeness","question_risk","formatting_compliance"]'::json, '["concept2cure_artifacts","immutable_report_records"]'::json, '["submission_ops","project_sections","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'anvisa-registration-dossier-readiness-pack', '{"part11":true,"auditTrail":true,"region":"BR_ANVISA"}'::json, '{"allowPartial":true,"requireBlockers":true,"requireConfidence":true}'::json),
  ('global.cross_region_submission_comparison', 'Cross-Region Submission Comparison Matrix', 'global_portfolio', '["account","program","project"]'::json, '["ra_lead","reg_strategy","executive"]'::json, '["pharma","device","biotech"]'::json, '["submission_readiness","module_completeness","rim_registrations","question_risk"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'global-cross-region-comparison-matrix', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('global.harmonization_gap_matrix', 'ICH Harmonization Gap Matrix (Cross-Market Alignment)', 'global_portfolio', '["account","program","project"]'::json, '["ra_lead","reg_strategy","qa","executive"]'::json, '["pharma","device","biotech"]'::json, '["module_completeness","formatting_compliance","rim_registrations","evidence_links"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'global-harmonization-gap-matrix', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('global.label_currency_matrix', 'Label Currency Matrix (USPI / SmPC / PIL / J-Label per Market)', 'global_labeling', '["account","program","project"]'::json, '["labeling_lead","ra_ops","ra_lead","executive"]'::json, '["pharma","biotech"]'::json, '["rim_labels","rim_registrations","rim_products","lifecycle_obligations"]'::json, '["concept2cure_artifacts"]'::json, '["governance_boundary"]'::json, '["ana-ri"]'::json, 'global-label-currency-matrix', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"forbidFinalIfMissingCritical":true}'::json),
  ('pv.dsur_readiness', 'DSUR Readiness Pack (ICH E2F)', 'pv_periodic', '["program","project","submission"]'::json, '["pv_lead","ra_lead","medical_writer"]'::json, '["pharma","biotech"]'::json, '["safety_signals","benefit_risk","nonclinical_studies","evidence_links"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'pv-dsur-readiness-pack', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireBlockers":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('pv.signal_management_report', 'Signal Management Report (GVP Module IX)', 'pv_signal', '["project","submission","document"]'::json, '["pv_lead","ra_lead","qa"]'::json, '["pharma","biotech"]'::json, '["safety_signals","benefit_risk","risk_management_plan","evidence_links"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","governance_boundary"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'pv-signal-management-report', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireExplicitGaps":true,"requireConfidence":true}'::json),
  ('prediction.deficiency_risk', 'Deficiency Risk Prediction (RTF / CRL / First-Cycle Approval)', 'prediction', '["project","submission"]'::json, '["ra_lead","executive","biostatistician"]'::json, '["pharma","device","biotech"]'::json, '["submission_readiness","risk_model","network_prior"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'prediction-advisory-pack', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireConfidence":true}'::json),
  ('prediction.readiness_trajectory', 'Readiness Trajectory Prediction', 'prediction', '["project","submission"]'::json, '["ra_lead","executive","biostatistician"]'::json, '["pharma","device","biotech"]'::json, '["submission_readiness","section_status","gap_score"]'::json, '["concept2cure_artifacts"]'::json, '["submission_ops","project_sections"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'prediction-advisory-pack', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireConfidence":true}'::json),
  ('prediction.trial_pos', 'Trial Probability of Success Prediction', 'prediction', '["project","submission","study"]'::json, '["ra_lead","executive","biostatistician"]'::json, '["pharma","device","biotech"]'::json, '["trial_design","evidence_prior","monte_carlo_simulation"]'::json, '["concept2cure_artifacts"]'::json, '["study_design"]'::json, '["ana-ri","foresight_risk_synthesis"]'::json, 'prediction-advisory-pack', '{"part11":true,"auditTrail":true}'::json, '{"allowPartial":true,"requireConfidence":true}'::json)
ON CONFLICT (type_id) DO UPDATE SET
  label = EXCLUDED.label,
  family = EXCLUDED.family,
  allowed_scopes = EXCLUDED.allowed_scopes,
  allowed_personas = EXCLUDED.allowed_personas,
  allowed_client_segments = EXCLUDED.allowed_client_segments,
  data_dependencies = EXCLUDED.data_dependencies,
  artifact_dependencies = EXCLUDED.artifact_dependencies,
  workflow_dependencies = EXCLUDED.workflow_dependencies,
  ana_modules = EXCLUDED.ana_modules,
  export_template = EXCLUDED.export_template,
  governance_requirements = EXCLUDED.governance_requirements,
  truthfulness_rules = EXCLUDED.truthfulness_rules,
  updated_at = now();

DO $$
DECLARE
  expected CONSTANT integer := 61;
  present integer;
BEGIN
  SELECT count(*) INTO present
    FROM public.report_type_registry
   WHERE type_id = ANY (ARRAY[
     'readiness.executive_digest',
     'provenance.evidence_trace_report',
     'compliance.audit_assurance_pack',
     'usa_fda.pma_submission_readiness',
     'usa_fda.estar_510k_equivalence_matrix',
     'usa_fda.deficiency_response_intelligence',
     'ema.maa_readiness_assessment',
     'ema.rmp_psur_signal_alignment',
     'china_nmpa.ctd_module_gap_analysis',
     'china_nmpa.registration_dossier_readiness',
     'china_nmpa.deficiency_letter_root_cause_pack',
     'fcoi.disclosure_register',
     'ha.commitment_register',
     'iacuc.protocol_register',
     'irb.submission_register',
     'ibc.registration_register',
     'nonclinical.study_send_register',
     'grants.portfolio_register',
     'rim.registration_grid',
     'inspection.readiness_pack',
     'controlled_substances.inventory_ledger',
     'lifecycle.obligation_calendar',
     'etmf.completeness_pack',
     'research_compliance.training_status',
     'effort.certification_register',
     'research_security.coi_register',
     'research_admin.scorecard',
     'prediction.regulatory_forecast',
     'prediction.crl_rtf_premortem',
     'usa_fda.ind_safety_readiness',
     'usa_fda.nda_bla_filing_readiness',
     'usa_fda.crl_response_intelligence',
     'usa_fda.type_bcd_meeting_brief',
     'usa_fda.de_novo_classification_pack',
     'ema.maa_loq_response_pack',
     'ema.variation_readiness',
     'ema.psur_pbrer_pack',
     'ema.scientific_advice_brief',
     'eu_mdr.technical_documentation_readiness',
     'eu_mdr.cer_per_completeness',
     'eu_ivdr.performance_evaluation_readiness',
     'japan_pmda.jnda_shonin_readiness',
     'japan_pmda.consultation_brief',
     'japan_pmda.reexamination_pack',
     'canada_hc.nds_snds_readiness',
     'canada_hc.device_licence_readiness',
     'uk_mhra.maa_readiness',
     'uk_mhra.ilap_pathway_brief',
     'australia_tga.prescription_medicine_readiness',
     'australia_tga.artg_device_inclusion_readiness',
     'korea_mfds.drug_registration_readiness',
     'switzerland_swissmedic.maa_readiness',
     'brazil_anvisa.registration_dossier_readiness',
     'global.cross_region_submission_comparison',
     'global.harmonization_gap_matrix',
     'global.label_currency_matrix',
     'pv.dsur_readiness',
     'pv.signal_management_report',
     'prediction.deficiency_risk',
     'prediction.readiness_trajectory',
     'prediction.trial_pos'
   ]);
  IF present < expected THEN
    RAISE EXCEPTION 'report_type_registry holds % of the % seeded report types after the seed; the file is incomplete or a row was refused.', present, expected;
  END IF;
END $$;
