/**
 * Acknowledgement documents — and the difference between an agency's bytes and
 * this platform's own record of what it sent.
 *
 * WHY THIS MODULE EXISTS
 * Twelve of the thirteen gateways answered `downloadAcknowledgment` by composing
 * a text file out of their own `submission_transmittals` row:
 *
 *     Buffer.from(`ANVISA Acknowledgement\nProtocol: ${r.transmission_id}\n` +
 *                 `Status: ${r.status}\nReceived: ${...}\n`)
 *
 * The agency's real response body was read at transmit time (to extract a
 * protocol or receipt id) and then discarded. The download route served the
 * result as `ack-<transmissionId>.txt` with no marker, and the surface reported
 * "Gateway acknowledgment downloaded — the agency's actual bytes."
 *
 * A sponsor could therefore place a document this platform wrote into a
 * regulatory archive as proof that an agency received a submission. In a filing
 * date dispute or an inspection, that document would be shown to have been
 * generated by Concept2Cure from its own database — the sponsor would have no
 * agency receipt at all, and would have represented a self-authored file as
 * agency correspondence.
 *
 * The values inside were not invented — the receipt id really did come from the
 * gateway's 2xx response. The document's *identity* was. That is the defect
 * this module fixes: the same information, titled as what it is.
 */

import type { GatewayAcknowledgment } from './types';

export interface PlatformRecordInput {
  transmittalId: number;
  transmissionId: string;
  /** Human-readable agency + gateway, e.g. "ANVISA (anvisa_gateway)". */
  gatewayLabel: string;
  /** Current status on the transmittal row. */
  status: string;
  /** When the gateway accepted the transmission, if it did. */
  ackReceivedAt: Date | null;
  /** Bundle digest, so the record identifies WHAT was sent. */
  bundleSha256?: string | null;
  /** Anything else worth stating, rendered as `Key: value` lines. */
  extra?: Record<string, string | null | undefined>;
}

/**
 * Compose this platform's own record of a transmission.
 *
 * The heading, the disclaimer and the filename all say the same thing, because
 * any one of them alone can be lost — a heading survives a rename, a filename
 * survives someone reading only the directory listing.
 */
export function platformTransmittalRecord(input: PlatformRecordInput): GatewayAcknowledgment {
  const {
    transmittalId,
    transmissionId,
    gatewayLabel,
    status,
    ackReceivedAt,
    bundleSha256,
    extra,
  } = input;

  const lines = [
    'CONCEPT2CURE TRANSMITTAL RECORD',
    '',
    'THIS IS NOT AN AGENCY ACKNOWLEDGEMENT.',
    `It was generated by Concept2Cure from its own transmittal record, not received from ${gatewayLabel}.`,
    'It is not evidence that the agency received or accepted this submission.',
    'Obtain the agency-issued receipt from the agency portal for that purpose.',
    '',
    `Gateway: ${gatewayLabel}`,
    `Transmittal: #${transmittalId}`,
    `Transmission id (as reported by the gateway): ${transmissionId || 'none'}`,
    `Status recorded by this platform: ${status}`,
    `Gateway accepted at: ${ackReceivedAt ? ackReceivedAt.toISOString() : 'not recorded'}`,
  ];

  if (bundleSha256) lines.push(`Bundle SHA-256: ${bundleSha256}`);
  for (const [key, value] of Object.entries(extra ?? {})) {
    if (value !== null && value !== undefined && value !== '') lines.push(`${key}: ${value}`);
  }

  lines.push('');

  return {
    transmittalId,
    transmissionId,
    contentType: 'text/plain',
    buffer: Buffer.from(`${lines.join('\n')}\n`, 'utf8'),
    receivedAt: ackReceivedAt ?? new Date(),
    provenance: 'platform-record',
  };
}

/**
 * Filename for a downloaded acknowledgement, distinct per provenance so the two
 * cannot be confused once they are sitting in a downloads folder.
 */
export function acknowledgementFilename(ack: GatewayAcknowledgment): string {
  const id = ack.transmissionId || String(ack.transmittalId);
  return ack.provenance === 'agency'
    ? `agency-acknowledgement-${id}.txt`
    : `concept2cure-transmittal-record-${id}-NOT-AN-AGENCY-ACK.txt`;
}
