import { Router, Request, Response } from 'express';
import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { eq } from 'drizzle-orm';
import { draftingTasks } from '@shared/schema';
import { fallbackTemplates } from '../services/templates/ectd-fallback-templates';
import { getSecureOrgId } from '../utils/tenantContext';

// Document generation helper — used by POST /v1/drafting/start_task
async function generateDocumentContent(
  ectdSection: string,
  documentTitle: string,
  template: string
) {
  const matchingTemplate = fallbackTemplates.find(
    t =>
      t.granule_id.includes(ectdSection.toLowerCase().replace('.', '-')) ||
      t.module_number === ectdSection.split('.')[0]
  );

  if (matchingTemplate) {
    let content = matchingTemplate.content;

    content = content.replace(
      /\[DRUG_NAME\]/g,
      documentTitle.split(' - ')[0] || 'Investigational Drug'
    );
    content = content.replace(
      /\[INDICATION\]/g,
      documentTitle.split(' - ')[1] || 'Primary Indication'
    );
    content = content.replace(/\[DOCUMENT_TITLE\]/g, documentTitle);
    content = content.replace(/\[ECTD_SECTION\]/g, ectdSection);
    content = content.replace(/\[TEMPLATE\]/g, template);
    content = content.replace(/\[DATE\]/g, new Date().toLocaleDateString());

    return content;
  }

  // Default content if no template matches
  return `${documentTitle}

Module: ${ectdSection}
Template: ${template}
Generated: ${new Date().toLocaleDateString()}

1. INTRODUCTION
This document has been generated for Module ${ectdSection} according to eCTD specifications.

2. DOCUMENT STRUCTURE
The document follows FDA eCTD v4.0 guidelines and includes all required sections for regulatory submission.

3. CONTENT PLACEHOLDER
[This section should be completed with study-specific information]

4. REGULATORY COMPLIANCE
This document template ensures compliance with:
- FDA eCTD v4.0 requirements
- ICH guidelines
- Regional regulatory standards

5. NEXT STEPS
1. Complete all placeholder sections
2. Review for regulatory compliance
3. Prepare for submission

---
Generated by Concept2Cure AI Document Generator
Date: ${new Date().toISOString()}
`;
}

export function createMiscInlineRoutes(pool: Pool, authMiddleware: any): Router {
  const router = Router();
  const db = drizzle(pool);

  // GET /api/templates — returns fallbackTemplates
  router.get('/templates', async (req: Request, res: Response) => {
    try {
      res.json({
        success: true,
        templates: fallbackTemplates,
      });
    } catch (error) {
      console.error('Error fetching templates:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to fetch templates',
      });
    }
  });

  // GET /api/vault/statistics — real DB query on documents table
  router.get('/vault/statistics', async (req: Request, res: Response) => {
    try {
      const statsResult = await pool.query(`
        SELECT
          COUNT(*)::int AS total_documents,
          0::bigint AS total_size,
          COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '7 days')::int AS recent_uploads
        FROM documents
      `);
      const stats = statsResult.rows[0] || {};
      res.json({
        totalDocuments: stats.total_documents || 0,
        totalSize: parseInt(stats.total_size) || 0,
        recentUploads: stats.recent_uploads || 0,
        // Removed `complianceScore: 95` — a fabricated constant with no
        // computation. Vault document counts do not yield a compliance
        // score; a real one would come from the compliance subsystem.
        storageUsed: parseInt(stats.total_size) || 0,
        storageLimit: 1000000000,
      });
    } catch (error) {
      console.error('Error fetching vault statistics:', error);
      res.status(500).json({ error: 'Failed to fetch vault statistics' });
    }
  });

  // GET /api/vault/list — paginated documents query
  router.get('/vault/list', async (req: Request, res: Response) => {
    try {
      const page = Math.max(1, parseInt(String(req.query.page || '1'), 10));
      const pageSize = Math.max(1, Math.min(100, parseInt(String(req.query.pageSize || '50'), 10)));
      const offset = (page - 1) * pageSize;

      const countResult = await pool.query('SELECT COUNT(*)::int AS total FROM documents');
      const total = countResult.rows[0]?.total || 0;

      const docsResult = await pool.query(
        `SELECT id, title, document_type, category, status, document_code, description, created_at, updated_at
         FROM documents ORDER BY created_at DESC LIMIT $1 OFFSET $2`,
        [pageSize, offset]
      );

      res.json({
        success: true,
        documents: docsResult.rows,
        metadata: {
          totalCount: total,
          currentPage: page,
          totalPages: Math.max(1, Math.ceil(total / pageSize)),
          pageSize,
        },
      });
    } catch (error) {
      console.error('Error fetching vault documents:', error);
      res.status(500).json({ error: 'Failed to fetch vault documents' });
    }
  });

  // GET /api/ana/regulatory-intelligence (authMiddleware)
  router.get(
    '/ana/regulatory-intelligence',
    authMiddleware as any,
    async (req: Request, res: Response) => {
      try {
        // No regulatory-intelligence data source is wired for this feed.
        // The prior handler fabricated a complianceScore (95), a documents
        // successRate (94), and a full per-agency "Compliant" matrix with
        // invented scores (FDA 94, EMA 87, …) — none backed by any data.
        // Emit honest nulls / empty rather than fake regulatory compliance
        // statuses. Real values land when the source is connected.
        res.json({
          success: true,
          advisorySummary: {
            totalAdvisories: 0,
            criticalAlerts: 0,
            recentUpdates: 0,
            complianceScore: null,
          },
          documents: {
            totalAnalyzed: 0,
            successRate: null,
            averageProcessingTime: null,
            templatesAvailable: null,
          },
          compliance: {
            globalStatus: 'unknown',
            regions: [],
          },
          updates: [],
        });
      } catch (error) {
        console.error('Error fetching regulatory intelligence:', error);
        res.status(500).json({ error: 'Failed to fetch regulatory intelligence' });
      }
    }
  );

  // NOTE: /api/ana/regulatory-analysis and /api/ana/ich-e6r3-guidance were
  // removed from this grab-bag router. They were unconsumed duplicates of the
  // canonical handlers in server/routes/ana-cortex.ts (mounted at
  // /api/ana-cortex/*, which is what the client actually calls). Single source
  // now lives there.

  // GET /api/advisor/check-readiness
  router.get('/advisor/check-readiness', async (req: Request, res: Response) => {
    console.log('🔥 Advisor check readiness endpoint hit!');
    try {
      const { playbook = 'Fast IND Playbook' } = req.query;

      res.set({
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        Pragma: 'no-cache',
        Expires: '0',
      });

      res.json({
        success: true,
        playbook: playbook,
        readinessScore: 78,
        overallScore: 78,
        riskLevel: 'Medium',
        readinessLevel: 'Medium',
        estimatedDelayDays: 45,
        estimatedSubmissionDate: 'September 15, 2025',
        playbookUsed: playbook,
        gaps: [
          {
            section: 'CMC Stability Study',
            status: 'missing',
            priority: 'high',
            estimatedDays: 30,
            financialImpact: 750000,
          },
          {
            section: 'Clinical Study Reports (CSR)',
            status: 'incomplete',
            priority: 'high',
            estimatedDays: 45,
            financialImpact: 1000000,
          },
          {
            section: 'Toxicology Reports',
            status: 'missing',
            priority: 'medium',
            estimatedDays: 14,
            financialImpact: 300000,
          },
          {
            section: 'Drug Substance Specs',
            status: 'incomplete',
            priority: 'medium',
            estimatedDays: 21,
            financialImpact: 400000,
          },
          {
            section: 'Quality Overall Summary',
            status: 'missing',
            priority: 'medium',
            estimatedDays: 10,
            financialImpact: 200000,
          },
        ],
        missingSections: [
          'CMC Stability Study',
          'Clinical Study Reports (CSR)',
          'Toxicology Reports',
          'Drug Substance Specs',
          'Quality Overall Summary',
        ],
        recommendations: [
          'Prioritize CMC Stability Study completion',
          'Accelerate CSR finalization',
          'Review toxicology data requirements',
        ],
        timeline: {
          estimatedCompletionDays: 45,
          criticalPathItems: ['CMC Stability Study', 'Clinical Study Reports (CSR)'],
        },
      });
    } catch (error) {
      console.error('Error in advisor check readiness:', error);
      res.status(500).json({ error: 'Failed to check readiness' });
    }
  });

  // GET /api/ectd/templates — DB query with fallback
  router.get('/ectd/templates', async (req: Request, res: Response) => {
    try {
      const organizationId = getSecureOrgId(req);
      if (!organizationId) {
        return res.status(401).json({ error: 'Organization context required' });
      }

      try {
        const result = await pool.query(
          `SELECT id, template_name as name, template_name as title, 'FDA' as region, version,
                  template_name as description, content as template_data
           FROM ectd_templates
           WHERE organization_id = $1
           ORDER BY id`,
          [organizationId]
        );

        const templates = result.rows.map(row => {
          const templateData = row.template_data || {};
          return {
            id: row.id,
            name: row.name,
            title: row.title,
            template_name: row.title,
            region: row.region,
            version: row.version,
            description: row.description,
            module_number: templateData.module,
            granule_id: templateData.granule_id,
            content: templateData.content,
            placeholders: templateData.placeholders,
            category: row.name.includes('Module_1')
              ? 'administrative'
              : row.name.includes('Module_2')
              ? 'clinical'
              : 'regulatory',
            template_data: templateData,
          };
        });

        res.json(templates);
      } catch (dbError: any) {
        console.error('[WARNING] Database unavailable, using fallback templates:', dbError.message);
        res.json(fallbackTemplates);
      }
    } catch (error) {
      console.error('[ERROR] Failed to fetch templates:', error);
      res.status(500).json({ error: 'Internal server error' });
    }
  });

  // GET /api/ectd/templates/:id — single template with fallback
  router.get('/ectd/templates/:id', async (req: Request, res: Response) => {
    try {
      const templateId = req.params.id;
      const organizationId = getSecureOrgId(req);
      if (!organizationId) {
        return res.status(401).json({ error: 'Organization context required' });
      }

      try {
        const result = await pool.query(
          `SELECT id, template_name as name, template_name as title, 'FDA' as region, version,
                  template_name as description, content as template_data
           FROM ectd_templates
           WHERE id = $1 AND organization_id = $2`,
          [templateId, organizationId]
        );

        if (result.rows.length === 0) {
          return res.status(404).json({ error: 'Template not found' });
        }

        const row = result.rows[0];
        const templateData = row.template_data || {};

        const template = {
          id: row.id,
          name: row.name,
          title: row.title,
          template_name: row.title,
          region: row.region,
          version: row.version,
          description: row.description,
          module_number: templateData.module,
          granule_id: templateData.granule_id,
          content: templateData.content,
          placeholders: templateData.placeholders,
          category: row.name.includes('Module_1')
            ? 'administrative'
            : row.name.includes('Module_2')
            ? 'clinical'
            : 'regulatory',
          template_data: templateData,
        };

        res.json(template);
      } catch (dbError: any) {
        console.error('[WARNING] Database unavailable for template fetch:', dbError.message);

        const fallbackTemplate = fallbackTemplates.find(t => t.id.toString() === templateId);
        if (fallbackTemplate) {
          res.json(fallbackTemplate);
        } else {
          res.status(404).json({ error: 'Template not found' });
        }
      }
    } catch (error) {
      console.error('[ERROR] Failed to fetch template:', error);
      res.status(500).json({ error: 'Internal server error' });
    }
  });

  // POST /api/v1/drafting/start_task — creates drafting task (DB-persisted)
  router.post('/v1/drafting/start_task', async (req: Request, res: Response) => {
    try {
      const { project_id, ectd_section, document_title, template } = req.body;

      if (!project_id || !ectd_section || !document_title) {
        return res.status(400).json({
          error: 'project_id, ectd_section, and document_title are required',
        });
      }

      const taskId = `task_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

      const generatedContent = await generateDocumentContent(ectd_section, document_title, template);

      try {
        await db.insert(draftingTasks).values({
          taskId,
          projectId: project_id,
          ectdSection: ectd_section,
          documentTitle: document_title,
          template: template || null,
          status: 'COMPLETED',
          draftContent: generatedContent,
          createdById: (req as any).user?.id || null,
        });
      } catch (dbError) {
        // Fallback: if table doesn't exist yet (pre-migration), use in-memory
        console.warn(
          '[drafting] DB insert failed, using in-memory fallback:',
          (dbError as Error).message
        );
        (global as any).draftingTasks = (global as any).draftingTasks || {};
        (global as any).draftingTasks[taskId] = {
          id: taskId,
          project_id,
          ectd_section,
          document_title,
          template,
          status: 'COMPLETED',
          draft_content: generatedContent,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        };
      }

      res.status(202).json({ task_id: taskId });
    } catch (error) {
      console.error('Document creation error:', error);
      res.status(500).json({ error: 'Failed to create document' });
    }
  });

  // GET /api/v1/drafting/task_status/:task_id — DB-backed with in-memory fallback
  router.get('/v1/drafting/task_status/:task_id', async (req: Request, res: Response) => {
    try {
      const { task_id } = req.params;

      try {
        const [task] = await db.select().from(draftingTasks).where(eq(draftingTasks.taskId, task_id));
        if (task) {
          return res.json({
            id: task.taskId,
            project_id: task.projectId,
            ectd_section: task.ectdSection,
            document_title: task.documentTitle,
            template: task.template,
            status: task.status,
            draft_content: task.draftContent,
            created_at: task.createdAt?.toISOString(),
            updated_at: task.updatedAt?.toISOString(),
          });
        }
      } catch {
        // DB query failed — fall through to in-memory
      }

      const memTask = (global as any).draftingTasks?.[task_id];
      if (!memTask) {
        return res.status(404).json({ error: 'Task not found' });
      }
      res.json(memTask);
    } catch (error) {
      console.error('Get task status error:', error);
      res.status(500).json({ error: 'Failed to get task status' });
    }
  });

  // POST /api/workflow/progression/create
  router.post('/workflow/progression/create', async (req: Request, res: Response) => {
    try {
      const {
        sourceSubmissionId,
        sourceType,
        targetType,
        therapeuticArea,
        indication,
        analysisMode,
        templateId,
        includeRiskAssessment,
        includeCostAnalysis,
        includeTimeline,
      } = req.body;

      if (!sourceSubmissionId || !sourceType || !targetType || !therapeuticArea || !indication) {
        return res.status(400).json({
          success: false,
          error: 'All required fields must be provided',
        });
      }

      const workflowPlan = {
        id: `workflow_${Date.now()}`,
        sourceSubmissionId,
        sourceType,
        targetType,
        therapeuticArea,
        indication,
        analysisMode,
        created: new Date().toISOString(),
        phases: [
          {
            id: 'phase-1',
            title: 'IND Data Review and Analysis',
            duration: '2-3 months',
            tasks: [
              'Review existing IND safety data',
              'Analyze clinical trial results',
              'Assess manufacturing changes',
              'Evaluate regulatory feedback',
            ],
          },
          {
            id: 'phase-2',
            title: `${targetType} Preparation`,
            duration: '4-6 months',
            tasks: [
              'Prepare comprehensive clinical package',
              'Complete manufacturing documentation',
              'Conduct risk assessment',
              'Prepare regulatory submissions',
            ],
          },
          {
            id: 'phase-3',
            title: 'Submission and Review',
            duration: '6-12 months',
            tasks: [
              `Submit ${targetType} application`,
              'Respond to regulatory queries',
              'Conduct advisory meetings',
              'Complete regulatory review process',
            ],
          },
        ],
      };

      const contentMapping = {
        mappedModules: [
          {
            sourceModule: 'IND Module 1',
            targetModule: `${targetType} Module 1`,
            contentGap: 'Expand administrative information',
            reusePercentage: 85,
          },
          {
            sourceModule: 'IND Module 2',
            targetModule: `${targetType} Module 2`,
            contentGap: 'Add comprehensive clinical overview',
            reusePercentage: 65,
          },
          {
            sourceModule: 'IND Module 3',
            targetModule: `${targetType} Module 3`,
            contentGap: 'Complete quality documentation',
            reusePercentage: 70,
          },
        ],
        overallReuseRate: 73,
      };

      const gapAnalysis = {
        criticalGaps: [
          'Comprehensive efficacy data required',
          'Complete safety database needed',
          'Manufacturing scale-up documentation',
        ],
        mediumGaps: [
          'Additional pharmacokinetic studies',
          'Risk evaluation and mitigation strategies',
        ],
        minorGaps: ['Updated labeling information', 'Additional regulatory correspondence'],
      };

      const timeline = {
        totalDuration: '12-21 months',
        milestones: [
          {
            id: 'milestone-1',
            title: 'IND Review Complete',
            targetDate: '3 months',
            status: 'pending',
          },
          {
            id: 'milestone-2',
            title: `${targetType} Submission Ready`,
            targetDate: '9 months',
            status: 'pending',
          },
          {
            id: 'milestone-3',
            title: 'Regulatory Approval',
            targetDate: '21 months',
            status: 'pending',
          },
        ],
      };

      const costAnalysis = {
        totalEstimatedCost: '$2.5M - $4.2M',
        breakdown: [
          { category: 'Clinical Studies', cost: '$1.5M - $2.5M' },
          { category: 'Regulatory Support', cost: '$500K - $800K' },
          { category: 'Manufacturing', cost: '$300K - $600K' },
          { category: 'Quality Assurance', cost: '$200K - $300K' },
        ],
      };

      const riskAssessment = {
        overallRisk: 'Medium',
        riskFactors: [
          {
            factor: 'Clinical Data Adequacy',
            level: 'Medium',
            mitigation: 'Conduct additional studies if needed',
          },
          {
            factor: 'Manufacturing Complexity',
            level: 'Low',
            mitigation: 'Established manufacturing process',
          },
          {
            factor: 'Regulatory Timeline',
            level: 'Medium',
            mitigation: 'Early FDA engagement recommended',
          },
        ],
      };

      res.json({
        success: true,
        workflow: workflowPlan,
        contentMapping,
        gapAnalysis,
        timeline,
        costAnalysis,
        riskAssessment,
      });
    } catch (error) {
      console.error('Workflow progression creation error:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to create workflow progression',
      });
    }
  });

  return router;
}
