/**
 * ReviewPulseDashboard — PM orchestration and visibility layer.
 *
 * Documents are the source of truth; this dashboard reflects and manages
 * the work generated by governed documents. It does NOT replace the
 * governed document workflow — it surfaces review activity as
 * project-management signals: who owes what, what's blocked,
 * which sections are at risk, and which artifacts await review.
 *
 * Data: GET /api/concept2cure/projects/:projectId/review-pulse
 */

import React, { useEffect, useState, useCallback } from 'react';
import { cn } from '@/lib/utils';
import { apiRequest } from '@/lib/queryClient';
import { useToast } from '@/hooks/use-toast';
import { LoadingState, ErrorState } from '@/components/ui/statesV2';
import { PageTitleHeader, WorkspaceStatusBadge } from '@/components/ui/workspace-primitives';
import type { StatusBadgeConfig } from '@/components/ui/workspace-primitives';
import {
  AlertTriangle,
  CheckCircle2,
  Clock,
  FileText,
  Loader2,
  MessageSquare,
  ShieldAlert,
  Target,
  UserCheck,
  Users,
  XCircle,
  RefreshCw,
} from 'lucide-react';

// ── Types ────────────────────────────────────────────────────────────────────

interface PulseSummary {
  totalThreads: number;
  openThreads: number;
  resolvedThreads: number;
  highPriorityOpen: number;
  unassignedThreads: number;
  staleThreads: number;
  totalTasks: number;
  activeTasks: number;
  overdueTasks: number;
  changeRequests: number;
  unassignedTasks: number;
  reviewCompletionRate: number;
}

interface ArtifactReadiness {
  artifactId: string;
  title: string;
  ctdSection: string | null;
  documentStatus: string;
  openThreads: number;
  activeTasks: number;
  overdueTasks: number;
  highPriorityThreads: number;
  reviewStatus: 'blocked' | 'in_review' | 'clear';
}

interface RiskSignal {
  severity: string;
  signal: string;
  entityId: string;
  entityType: string;
}

interface AssigneeWorkload {
  userId: number;
  name: string;
  threads: number;
  tasks: number;
  overdue: number;
}

interface ActivityEntry {
  activityType: string;
  entityType: string;
  entityId: string;
  description: string;
  createdAt: string;
}

interface PulseData {
  projectId: string;
  generatedAt: string;
  summary: PulseSummary;
  artifactReadiness: ArtifactReadiness[];
  riskSignals: RiskSignal[];
  assigneeWorkload: AssigneeWorkload[];
  recentActivity: ActivityEntry[];
}

interface Props {
  projectId: string;
  onNavigateToArtifact?: (artifactId: string) => void;
  className?: string;
}

// ── Stat pill ────────────────────────────────────────────────────────────────
const StatCard: React.FC<{
  icon: React.ElementType;
  label: string;
  value: number | string;
  color: string;
  subtext?: string;
}> = ({ icon: Icon, label, value, color, subtext }) => (
  <div className="flex items-center gap-2 px-3 py-1.5 border border-stone-200 rounded bg-stone-50/50 min-w-0">
    <Icon className={cn('w-3.5 h-3.5 shrink-0', color)} />
    <span className="text-sm font-semibold tabular-nums text-stone-900">{value}</span>
    <span className="text-xs text-stone-500 truncate">{label}</span>
    {subtext && <span className="text-xs text-stone-400 ml-auto">{subtext}</span>}
  </div>
);

// ── Readiness badge (maps review statuses to WorkspaceStatusBadge) ───────────
const REVIEW_STATUS_CONFIG: Record<string, StatusBadgeConfig> = {
  blocked: { key: 'blocked', label: 'Blocked', color: 'bg-stone-100 text-stone-800' },
  in_review: { key: 'in_review', label: 'In Review', color: 'bg-stone-100 text-stone-700' },
  clear: { key: 'clear', label: 'Clear', color: 'bg-stone-100 text-stone-800' },
};

const ReviewStatusBadge: React.FC<{ status: string }> = ({ status }) => (
  <WorkspaceStatusBadge
    status={status}
    config={REVIEW_STATUS_CONFIG[status] || REVIEW_STATUS_CONFIG.clear}
  />
);

// ── Component ────────────────────────────────────────────────────────────────

export const ReviewPulseDashboard: React.FC<Props> = ({
  projectId,
  onNavigateToArtifact,
  className,
}) => {
  const { toast } = useToast();
  const [data, setData] = useState<PulseData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchPulse = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await apiRequest('GET', `/api/concept2cure/projects/${projectId}/review-pulse`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const json = await res.json();
      if (json.success) {
        setData(json.data);
      } else {
        throw new Error(json.message || 'Failed to load review pulse');
      }
    } catch (err: any) {
      setError(err.message);
      toast({ title: 'Failed to load review pulse', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, [projectId, toast]);

  useEffect(() => {
    fetchPulse();
  }, [fetchPulse]);

  if (loading) {
    return (
      <div className={className}>
        <LoadingState message="Loading review pulse…" size="md" />
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className={className}>
        <ErrorState
          title="Review pulse unavailable"
          message={error || 'No data available'}
          retry={fetchPulse}
        />
      </div>
    );
  }

  const { summary: s, artifactReadiness, riskSignals, assigneeWorkload, recentActivity } = data;
  const blockedArtifacts = artifactReadiness.filter(a => a.reviewStatus === 'blocked');

  return (
    <div className={cn('space-y-6 pb-8', className)}>
      {/* ── Header ─────────────────────────────────────────────────────── */}
      <PageTitleHeader
        title="Review Pulse"
        description="Project review orchestration — signals from document workspace"
        actions={
          <button
            onClick={fetchPulse}
            className="p-1.5 rounded hover:bg-stone-100 text-stone-400 hover:text-stone-600 transition"
            title="Refresh"
          >
            <RefreshCw className="w-4 h-4" />
          </button>
        }
      />

      {/* ── Summary strip ──────────────────────────────────────────────── */}
      <div className="flex flex-wrap gap-3">
        <StatCard
          icon={MessageSquare}
          label="Open Threads"
          value={s.openThreads}
          color="text-stone-1000"
        />
        <StatCard
          icon={CheckCircle2}
          label="Resolved"
          value={s.resolvedThreads}
          color="text-stone-1000"
        />
        <StatCard
          icon={ShieldAlert}
          label="High Priority"
          value={s.highPriorityOpen}
          color="text-stone-1000"
        />
        <StatCard
          icon={Clock}
          label="Overdue Tasks"
          value={s.overdueTasks}
          color={s.overdueTasks > 0 ? 'text-stone-1000' : 'text-stone-400'}
        />
        <StatCard
          icon={Target}
          label="Change Requests"
          value={s.changeRequests}
          color="text-stone-1000"
        />
        <StatCard
          icon={Users}
          label="Unassigned"
          value={s.unassignedThreads + s.unassignedTasks}
          color={s.unassignedThreads + s.unassignedTasks > 0 ? 'text-stone-1000' : 'text-stone-400'}
        />
        <StatCard
          icon={UserCheck}
          label="Completion"
          value={`${s.reviewCompletionRate}%`}
          color={s.reviewCompletionRate >= 80 ? 'text-stone-1000' : 'text-stone-1000'}
        />
      </div>

      {/* ── Risk signals ───────────────────────────────────────────────── */}
      {riskSignals.length > 0 && (
        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-stone-700 flex items-center gap-1.5">
            <AlertTriangle className="w-3.5 h-3.5 text-stone-1000" />
            Risk Signals
          </h3>
          <div className="space-y-1.5">
            {riskSignals.map((rs, i) => (
              <div
                key={i}
                className={cn(
                  'flex items-start gap-2 px-3 py-2 rounded-md border text-sm',
                  rs.severity === 'high'
                    ? 'bg-stone-100 border-stone-200 text-stone-800'
                    : 'bg-stone-100 border-stone-200 text-stone-700'
                )}
              >
                <AlertTriangle className="w-3.5 h-3.5 mt-0.5 flex-shrink-0" />
                <span>{rs.signal}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Artifact readiness table ───────────────────────────────────── */}
      <div className="space-y-2">
        <h3 className="text-sm font-semibold text-stone-700 flex items-center gap-1.5">
          <FileText className="w-3.5 h-3.5 text-stone-1000" />
          Artifact Review Readiness
          {blockedArtifacts.length > 0 && (
            <span className="text-xs font-normal text-stone-700 ml-1">
              ({blockedArtifacts.length} blocked)
            </span>
          )}
        </h3>
        {artifactReadiness.length === 0 ? (
          <p className="text-xs text-stone-400 italic">No artifacts in project</p>
        ) : (
          <div className="border rounded-lg overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-stone-50 border-b text-left">
                  <th className="px-3 py-2 font-medium text-stone-600 text-xs">Document</th>
                  <th className="px-3 py-2 font-medium text-stone-600 text-xs">Section</th>
                  <th className="px-3 py-2 font-medium text-stone-600 text-xs text-center">
                    Threads
                  </th>
                  <th className="px-3 py-2 font-medium text-stone-600 text-xs text-center">Tasks</th>
                  <th className="px-3 py-2 font-medium text-stone-600 text-xs text-center">
                    Overdue
                  </th>
                  <th className="px-3 py-2 font-medium text-stone-600 text-xs text-center">
                    Status
                  </th>
                </tr>
              </thead>
              <tbody>
                {artifactReadiness.map(a => (
                  <tr
                    key={a.artifactId}
                    className={cn(
                      'border-b last:border-0 hover:bg-stone-50/50 transition-colors duration-150',
                      a.reviewStatus === 'blocked' && 'bg-stone-100/30',
                      onNavigateToArtifact && 'cursor-pointer'
                    )}
                    onClick={() => onNavigateToArtifact?.(a.artifactId)}
                  >
                    <td className="px-3 py-2 text-stone-900 font-medium truncate max-w-[200px]">
                      {a.title}
                    </td>
                    <td className="px-3 py-2 text-stone-500 text-xs font-mono">
                      {a.ctdSection || '—'}
                    </td>
                    <td className="px-3 py-2 text-center tabular-nums">
                      {a.openThreads > 0 ? (
                        <span className="text-stone-600 font-medium">{a.openThreads}</span>
                      ) : (
                        <span className="text-stone-400">0</span>
                      )}
                    </td>
                    <td className="px-3 py-2 text-center tabular-nums">
                      {a.activeTasks > 0 ? (
                        <span className="text-stone-600 font-medium">{a.activeTasks}</span>
                      ) : (
                        <span className="text-stone-400">0</span>
                      )}
                    </td>
                    <td className="px-3 py-2 text-center tabular-nums">
                      {a.overdueTasks > 0 ? (
                        <span className="text-stone-700 font-semibold">{a.overdueTasks}</span>
                      ) : (
                        <span className="text-stone-400">0</span>
                      )}
                    </td>
                    <td className="px-3 py-2 text-center">
                      <ReviewStatusBadge status={a.reviewStatus} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* ── Assignee workload ──────────────────────────────────────────── */}
      {assigneeWorkload.length > 0 && (
        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-stone-700 flex items-center gap-1.5">
            <Users className="w-3.5 h-3.5 text-stone-1000" />
            Team Workload
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
            {assigneeWorkload.map(aw => (
              <div
                key={aw.userId}
                className={cn(
                  'px-3 py-2 rounded-lg border bg-white space-y-1',
                  aw.overdue > 0 && 'border-stone-200'
                )}
              >
                <p className="text-sm font-medium text-stone-900 truncate">{aw.name}</p>
                <div className="flex items-center gap-3 text-xs text-stone-500">
                  <span>{aw.threads} threads</span>
                  <span>{aw.tasks} tasks</span>
                  {aw.overdue > 0 && (
                    <span className="text-stone-700 font-medium">{aw.overdue} overdue</span>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Recent activity ────────────────────────────────────────────── */}
      {recentActivity.length > 0 && (
        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-stone-700">Recent Review Activity</h3>
          <div className="space-y-1">
            {recentActivity.slice(0, 10).map((a, i) => (
              <div key={i} className="flex items-start gap-2 px-3 py-1.5 text-xs text-stone-600">
                <span className="text-stone-400 tabular-nums whitespace-nowrap">
                  {new Date(a.createdAt).toLocaleDateString()}
                </span>
                <span className="truncate">{a.description}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default ReviewPulseDashboard;
