/**
 * The compute sandbox must not be able to read the server's secrets.
 *
 * ── The threat this is about ──────────────────────────────────────────────────
 * `workers/artifact-compute/python-script-runtime.py` calls `exec()` on
 * AnA-authored Python. That is the feature: it is a scripting sandbox, and the
 * runtime documents it plainly. The problem was never the `exec` — it was that
 * both spawn sites passed `{ ...process.env }`, so the script's environment
 * contained `DATABASE_URL`, `AUDIT_HMAC_SECRET`, `AUDIT_ATTESTATION_KEY`, the
 * Stripe key and every AI provider key.
 *
 * The code being executed is not written by the operator. It is generated by a
 * model that reads customer-supplied documents, so the distance from a sentence
 * hidden in an uploaded PDF to `print(os.environ['DATABASE_URL'])` was one hop,
 * and the only thing between them was a monkeypatched `socket` module that
 * `subprocess` ignores.
 *
 * ── Why the end-to-end case matters more than the unit one ────────────────────
 * `sandboxEnv()` returning a filtered object proves the function is right. It
 * does not prove the spawn sites USE it, and it does not prove Python sees what
 * we think it sees. So the case that matters actually runs `python3` through the
 * real runtime with a planted secret in `process.env`, and asserts the script
 * cannot find it. That is the property; everything else is a detail of how it is
 * achieved.
 *
 * ── What this does NOT claim ──────────────────────────────────────────────────
 * The script can still execute arbitrary code, spawn processes and touch the
 * filesystem, because that is what the runtime is for. Containment of THAT is
 * the container's job — which `runner.ts` describes as something the process
 * "should" run inside, with no code in this repository making it so. Removing
 * the credentials shrinks the blast radius; it does not close the boundary, and
 * this file should not be read as saying it does.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { sandboxEnv, SANDBOX_PASSTHROUGH } from '../sandboxEnv';

const PLANTED = {
  DATABASE_URL: 'postgres://planted-user:planted-password@db.internal:5432/prod',
  AUDIT_HMAC_SECRET: 'planted-audit-hmac-secret',
  AUDIT_ATTESTATION_KEY: 'planted-attestation-key',
  STRIPE_SECRET_KEY: 'sk_live_planted',
  ANTHROPIC_API_KEY: 'sk-ant-planted',
  OPENAI_API_KEY: 'sk-planted',
};

describe('sandboxEnv', () => {
  beforeEach(() => {
    for (const [k, v] of Object.entries(PLANTED)) process.env[k] = v;
  });
  afterEach(() => {
    for (const k of Object.keys(PLANTED)) delete process.env[k];
  });

  it('passes through none of the planted secrets', () => {
    const env = sandboxEnv();
    for (const key of Object.keys(PLANTED)) {
      expect(env[key], `${key} reached the sandbox environment`).toBeUndefined();
    }
  });

  it('passes through PATH, without which python3 cannot start', () => {
    expect(sandboxEnv().PATH).toBe(process.env.PATH);
  });

  it('applies caller values last, so the runtime contract wins', () => {
    const env = sandboxEnv({ ARTIFACT_COMPUTE_NO_NETWORK: '1', ARTIFACT_COMPUTE_WORKDIR: '/w' });
    expect(env.ARTIFACT_COMPUTE_NO_NETWORK).toBe('1');
    expect(env.ARTIFACT_COMPUTE_WORKDIR).toBe('/w');
  });

  it('is an allowlist — a newly-added secret is excluded without anyone editing this file', () => {
    // The point of allowlisting. A denylist would have to be updated for this
    // variable to be safe; an allowlist is safe by default and fails toward a
    // worker that will not start rather than a credential that leaks.
    process.env.SOME_FUTURE_TOKEN = 'invented-after-this-file-was-written';
    try {
      expect(sandboxEnv().SOME_FUTURE_TOKEN).toBeUndefined();
      expect(SANDBOX_PASSTHROUGH).not.toContain('SOME_FUTURE_TOKEN');
    } finally {
      delete process.env.SOME_FUTURE_TOKEN;
    }
  });
});

describe('the spawn sites use it', () => {
  /*
   * The unit tests above prove `sandboxEnv()` filters. They cannot prove the
   * callers use it — and a correct helper that nobody calls is the shape of a
   * fix that reads as done and changes nothing.
   *
   * Asserting on source text is blunt, and it is the right bluntness here: the
   * failure being prevented is one token long, `...process.env`, and it will be
   * reintroduced by someone adding a variable the worker needs, in a hurry,
   * without reading sandboxEnv.ts.
   */
  it.each([
    'server/services/compute/scriptWorker.ts',
    'server/services/compute/workerClient.ts',
  ])('%s does not spread process.env into a worker', (rel) => {
    const src = fs.readFileSync(path.resolve(process.cwd(), rel), 'utf8');
    expect(
      src.includes('...process.env'),
      `${rel} spreads process.env into a spawned worker again — the sandbox can read every secret. ` +
        `If the worker needs a new variable, add it to PASSTHROUGH in sandboxEnv.ts.`,
    ).toBe(false);
    expect(src, `${rel} no longer routes through sandboxEnv`).toContain('sandboxEnv(');
  });
});

/*
 * The end-to-end case. Skipped rather than failed where python3 is absent —
 * a missing interpreter is a fact about the machine, not about the product, and
 * failing on it would train people to ignore this file.
 */
const python3 = spawnSync('python3', ['--version'], { encoding: 'utf8' });
const havePython = python3.status === 0;

describe.skipIf(!havePython)('the real runtime cannot read the secrets', () => {
  let workdir: string;

  beforeEach(() => {
    for (const [k, v] of Object.entries(PLANTED)) process.env[k] = v;
    workdir = fs.mkdtempSync(path.join(os.tmpdir(), 'sandbox-env-test-'));
  });
  afterEach(() => {
    for (const k of Object.keys(PLANTED)) delete process.env[k];
    fs.rmSync(workdir, { recursive: true, force: true });
  });

  it('a script that dumps os.environ finds no secret', () => {
    const runtime = path.resolve(
      process.cwd(),
      'workers/artifact-compute/python-script-runtime.py',
    );
    expect(fs.existsSync(runtime), 'the runtime under test is missing').toBe(true);

    const outputPath = path.join(workdir, 'output.json');
    const inputPath = path.join(workdir, 'input.json');
    // Exactly what a prompt-injected script would do first.
    fs.writeFileSync(
      inputPath,
      JSON.stringify({
        code: 'import os, json\nprint(json.dumps(dict(os.environ)))\n',
        output_path: outputPath,
        cpu_seconds: 10,
      }),
    );

    const res = spawnSync('python3', [runtime, inputPath], {
      cwd: workdir,
      env: sandboxEnv({ ARTIFACT_COMPUTE_NO_NETWORK: '1', ARTIFACT_COMPUTE_WORKDIR: workdir }),
      encoding: 'utf8',
      timeout: 30_000,
    });
    expect(res.error, `python3 failed to run: ${res.error?.message}`).toBeUndefined();

    const out = JSON.parse(fs.readFileSync(outputPath, 'utf8'));
    expect(out.ok, `the runtime errored: ${out.error}`).toBe(true);

    const seen = JSON.parse(out.stdout.trim()) as Record<string, string>;
    for (const [key, value] of Object.entries(PLANTED)) {
      expect(seen[key], `${key} was visible to the sandboxed script`).toBeUndefined();
      expect(
        JSON.stringify(seen),
        `the VALUE of ${key} appeared in the sandbox environment under another name`,
      ).not.toContain(value);
    }

    // And the control: the sandbox got the environment it legitimately needs,
    // so this test cannot pass merely because the script saw nothing at all.
    expect(seen.ARTIFACT_COMPUTE_NO_NETWORK, 'the runtime contract did not reach the script').toBe(
      '1',
    );
    expect(seen.PATH, 'PATH was not passed; python3 would not have started').toBeTruthy();
  });
});
