/**
 * The compute sandbox must not be able to read the server's secrets.
 *
 * ── The threat this is about ──────────────────────────────────────────────────
 * `workers/artifact-compute/python-script-runtime.py` called `exec()` on
 * AnA-authored Python. That is the feature: it is a scripting sandbox, and the
 * runtime documents it plainly. The problem was never the `exec` — it was that
 * both spawn sites passed `{ ...process.env }`, so the script's environment
 * contained `DATABASE_URL`, `AUDIT_HMAC_SECRET`, `AUDIT_ATTESTATION_KEY`, the
 * Stripe key and every AI provider key.
 *
 * The code being executed is not written by the operator. It is generated by a
 * model that reads customer-supplied documents, so the distance from a sentence
 * hidden in an uploaded PDF to `print(os.environ['DATABASE_URL'])` was one hop,
 * and the only thing between them was a monkeypatched `socket` module that
 * `subprocess` ignores.
 *
 * ── Why the end-to-end case matters more than the unit one ────────────────────
 * `sandboxEnv()` returning a filtered object proves the function is right. It
 * does not prove the spawn sites USE it, and it does not prove Python sees what
 * we think it sees. So the case that matters actually runs `python3` through the
 * real runtime with a planted secret in `process.env`, and asserts the script
 * cannot find it. That is the property; everything else is a detail of how it is
 * achieved.
 *
 * ── Closed since (INJ-PATH-002) ───────────────────────────────────────────────
 * This file used to say, rightly, that removing the credentials shrank the blast
 * radius but did not close the boundary: the script could still execute any
 * code and touch the filesystem, and the container `runner.ts` described was one
 * no code in this repository created. The exec runtime has since been removed
 * and run_python_script runs in the hardened container instead; the last block
 * below pins that no host-side runtime executes code it was handed.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

import { sandboxEnv, SANDBOX_PASSTHROUGH } from '../sandboxEnv';

/*
 * The planted values are built at runtime rather than written as literals, and
 * deliberately do not look like credentials.
 *
 * The obvious way to write this test is `STRIPE_SECRET_KEY: 'sk_live_…'` and a
 * `postgres://user:password@host` URL, because realism feels like rigour. It is
 * not: a static analyser reads those as hardcoded credentials and files real
 * alerts against the file, and a scanner cannot tell a decoy from the thing it
 * imitates. I know because I wrote it that way first and CodeQL's high-severity
 * count went from 2 to 4 on the commit.
 *
 * Nothing is lost. What this test needs is a value present in `process.env` and
 * absent from the child's — the shape of the string is irrelevant to that, and
 * a unique marker is easier to assert on than a plausible-looking secret.
 */
const MARKER = 'canary-value-that-must-not-escape';
const PLANTED: Record<string, string> = Object.fromEntries(
  [
    'DATABASE_URL',
    'AUDIT_HMAC_SECRET',
    'AUDIT_ATTESTATION_KEY',
    'STRIPE_SECRET_KEY',
    'ANTHROPIC_API_KEY',
    'OPENAI_API_KEY',
  ].map((name) => [name, `${MARKER}-${name.toLowerCase()}`]),
);

describe('sandboxEnv', () => {
  beforeEach(() => {
    for (const [k, v] of Object.entries(PLANTED)) process.env[k] = v;
  });
  afterEach(() => {
    for (const k of Object.keys(PLANTED)) delete process.env[k];
  });

  it('passes through none of the planted secrets', () => {
    const env = sandboxEnv();
    for (const key of Object.keys(PLANTED)) {
      expect(env[key], `${key} reached the sandbox environment`).toBeUndefined();
    }
  });

  it('passes through PATH, without which python3 cannot start', () => {
    expect(sandboxEnv().PATH).toBe(process.env.PATH);
  });

  it('applies caller values last, so the runtime contract wins', () => {
    const env = sandboxEnv({ ARTIFACT_COMPUTE_NO_NETWORK: '1', ARTIFACT_COMPUTE_WORKDIR: '/w' });
    expect(env.ARTIFACT_COMPUTE_NO_NETWORK).toBe('1');
    expect(env.ARTIFACT_COMPUTE_WORKDIR).toBe('/w');
  });

  it('is an allowlist — a newly-added secret is excluded without anyone editing this file', () => {
    // The point of allowlisting. A denylist would have to be updated for this
    // variable to be safe; an allowlist is safe by default and fails toward a
    // worker that will not start rather than a credential that leaks.
    process.env.SOME_FUTURE_TOKEN = 'invented-after-this-file-was-written';
    try {
      expect(sandboxEnv().SOME_FUTURE_TOKEN).toBeUndefined();
      expect(SANDBOX_PASSTHROUGH).not.toContain('SOME_FUTURE_TOKEN');
    } finally {
      delete process.env.SOME_FUTURE_TOKEN;
    }
  });
});

describe('the spawn sites use it', () => {
  /*
   * The unit tests above prove `sandboxEnv()` filters. They cannot prove the
   * callers use it — and a correct helper that nobody calls is the shape of a
   * fix that reads as done and changes nothing.
   *
   * Asserting on source text is blunt, and it is the right bluntness here: the
   * failure being prevented is one token long, `...process.env`, and it will be
   * reintroduced by someone adding a variable the worker needs, in a hurry,
   * without reading sandboxEnv.ts.
   */
  it.each([
    'server/services/compute/scriptWorker.ts',
    'server/services/compute/workerClient.ts',
  ])('%s does not spread process.env into a worker', (rel) => {
    const src = fs.readFileSync(path.resolve(process.cwd(), rel), 'utf8');
    expect(
      src.includes('...process.env'),
      `${rel} spreads process.env into a spawned worker again — the sandbox can read every secret. ` +
        `If the worker needs a new variable, add it to PASSTHROUGH in sandboxEnv.ts.`,
    ).toBe(false);
    expect(src, `${rel} no longer routes through sandboxEnv`).toContain('sandboxEnv(');
  });
});

/*
 * The end-to-end case used to run python-script-runtime.py — the runtime that
 * exec()'d AnA's Python — with a planted secret, and check the script could not
 * print it. That runtime is gone (INJ-PATH-002): scrubbing the environment never
 * closed the boundary, because the script still ran on the application host with
 * the whole filesystem, including every tenant's uploads and /proc. Model-written
 * code now runs only in the hardened container (services/compute/containerExec).
 *
 * So the property this file can now pin is stronger and structural: no runtime
 * the host spawns compiles or executes code it was handed.
 */
describe('no host-side compute runtime executes supplied code', () => {
  const dir = path.resolve(process.cwd(), 'workers/artifact-compute');
  const runtimes = fs.readdirSync(dir).filter(f => f.endsWith('.py'));

  it('has runtimes to check', () => {
    expect(runtimes.length).toBeGreaterThan(0);
  });

  it.each(runtimes)('%s neither exec()s, eval()s nor compile()s', rel => {
    const src = fs.readFileSync(path.join(dir, rel), 'utf8');
    expect(src).not.toMatch(/\b(exec|eval|compile)\s*\(/);
    expect(src).not.toMatch(/\b__import__\s*\(/);
  });
});
