#!/usr/bin/env python3
"""
services/ectd_generator.py
Generate a Module 2.7.3-style clinical summary document in DOCX format,
with strict page margins, typography, heading hierarchy, a shaded table
with borders, centered numeric columns, and a footer.

Outputs: Concept2Cure_Clinical_Summary.docx
"""

from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.enum.style import WD_STYLE_TYPE
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
import logging
import os
from typing import List, Tuple

OUTPUT_FILENAME = "Concept2Cure_Clinical_Summary.docx"
LOG = logging.getLogger("ectd_generator")
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")


def set_page_margins(doc: Document, inches: float = 1.0) -> None:
    """Set identical 1.0 inch margins on all sections (FDA compliance)."""
    for section in doc.sections:
        section.top_margin = Inches(inches)
        section.bottom_margin = Inches(inches)
        section.left_margin = Inches(inches)
        section.right_margin = Inches(inches)


def create_base_styles(doc: Document) -> None:
    """Create/adjust styles so body is Times New Roman (12pt) and headings are bold/hierarchical."""
    styles = doc.styles

    # Body (create or override 'C2CBody' style)
    try:
        body_style = styles.add_style("C2CBody", WD_STYLE_TYPE.PARAGRAPH)
    except Exception:
        body_style = styles["Normal"]
    body_style.font.name = "Times New Roman"
    body_style.font.size = Pt(12)

    # Heading 1
    h1 = styles["Heading 1"]
    h1.font.name = "Times New Roman"
    h1.font.size = Pt(14)
    h1.font.bold = True

    # Heading 2
    h2 = styles["Heading 2"]
    h2.font.name = "Times New Roman"
    h2.font.size = Pt(13)
    h2.font.bold = True

    # Heading 3
    h3 = styles["Heading 3"]
    h3.font.name = "Times New Roman"
    h3.font.size = Pt(12)
    h3.font.bold = True


def _shade_cell(cell, fill_hex: str = "D9D9D9"):
    """Apply background shading to a single cell."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:fill"), fill_hex)
    shd.set(qn("w:val"), "clear")
    tcPr.append(shd)


def add_header(document: Document) -> None:
    """Add document title and introductory paragraphs using defined styles."""
    title = document.add_heading("Module 2.7.3 Clinical Summary", level=1)
    # Ensure style for the heading is applied
    if title.runs:
        title.runs[0].font.name = "Times New Roman"
        title.runs[0].font.size = Pt(14)
        title.runs[0].font.bold = True

    intro = document.add_paragraph(style="C2CBody")
    intro.add_run(
        "This document provides the clinical summary and primary efficacy endpoints "
        "for the submission. The document is generated programmatically to ensure "
        "regulatory-compliant formatting."
    )


def add_table_primary_endpoints(document: Document, rows: List[Tuple[str, str, str]]) -> None:
    """Insert a properly styled table (Table 1: Primary Efficacy Endpoints)."""
    document.add_heading("Table 1: Primary Efficacy Endpoints", level=2)

    # Use built-in Table Grid style to ensure borders present. Start with header row.
    table = document.add_table(rows=1, cols=3, style="Table Grid")
    table.autofit = True

    hdr_cells = table.rows[0].cells
    headers = ["Endpoint", "Treatment A", "Treatment B"]
    for idx, text in enumerate(headers):
        p = hdr_cells[idx].paragraphs[0]
        run = p.add_run(text)
        run.font.name = "Times New Roman"
        run.font.size = Pt(12)
        run.font.bold = True
        _shade_cell(hdr_cells[idx])

        # Left align header text
        p.alignment = WD_PARAGRAPH_ALIGNMENT.LEFT

    # Add rows and center numeric columns (columns 2 and 3)
    for (endpoint, tA, tB) in rows:
        r_cells = table.add_row().cells
        r_cells[0].text = endpoint
        r_cells[0].paragraphs[0].runs[0].font.name = "Times New Roman"
        r_cells[0].paragraphs[0].runs[0].font.size = Pt(12)

        r_cells[1].text = tA
        r_cells[2].text = tB
        for idx in (1, 2):
            p = r_cells[idx].paragraphs[0]
            p.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
            if p.runs:
                p.runs[0].font.name = "Times New Roman"
                p.runs[0].font.size = Pt(12)


def add_footer(document: Document) -> None:
    """Add the required footer: italicized confidentiality notice centered."""
    section = document.sections[0]
    footer = section.footer
    # Use existing paragraph if present, otherwise add one.
    if footer.paragraphs:
        p = footer.paragraphs[0]
        p.clear()
    else:
        p = footer.add_paragraph()
    run = p.add_run("Generated by Concept2Cure eCTD Co-Author | Confidential")
    run.italic = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(9)
    p.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER


import json
from typing import Any, Dict


def _normalize_row(row, headers):
    """Normalize a row that might be a list or dict into a list of values matching headers."""
    values = []
    if isinstance(row, dict):
        for h in headers:
            v = row.get(h, "N/A")
            values.append(str(v) if v is not None else "N/A")
    elif isinstance(row, (list, tuple)):
        for idx in range(len(headers)):
            try:
                v = row[idx]
            except IndexError:
                v = "N/A"
            values.append(str(v) if v is not None else "N/A")
    else:
        # Fallback: single value -> place into first column
        values = [str(row)] + ["N/A"] * (len(headers) - 1)
    return values


def add_table_from_spec(document: Document, table_spec: Dict[str, Any]) -> None:
    """Add a table to the document from a spec:
    {
        "title": "Table 1",
        "headers": ["A", "B", "C"],
        "rows": [ [..], {..}, ... ]
    }
    """
    title = table_spec.get("title") or table_spec.get("name") or "Table"
    headers = table_spec.get("headers") or []
    rows = table_spec.get("rows") or []

    document.add_heading(title, level=2)

    # If no headers provided, attempt to infer from first row if it's a dict
    if not headers and rows:
        first = rows[0]
        if isinstance(first, dict):
            headers = list(first.keys())

    cols = max(1, len(headers))
    table = document.add_table(rows=1, cols=cols, style="Table Grid")
    hdr_cells = table.rows[0].cells

    for idx in range(cols):
        text = headers[idx] if idx < len(headers) else f"Column {idx+1}"
        p = hdr_cells[idx].paragraphs[0]
        run = p.add_run(str(text))
        run.font.name = "Times New Roman"
        run.font.size = Pt(12)
        run.font.bold = True
        _shade_cell(hdr_cells[idx])
        p.alignment = WD_PARAGRAPH_ALIGNMENT.LEFT

    # Add rows
    for row in rows:
        values = _normalize_row(row, headers)
        cells = table.add_row().cells
        for idx, val in enumerate(values):
            cells[idx].text = val
            p = cells[idx].paragraphs[0]
            p.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER if idx >= 1 else WD_PARAGRAPH_ALIGNMENT.LEFT
            if p.runs:
                p.runs[0].font.name = "Times New Roman"
                p.runs[0].font.size = Pt(12)


def generate_clinical_summary(output_path: str = OUTPUT_FILENAME, data: Dict[str, Any] = None) -> str:
    """Main generator function; accepts optional parsed JSON `data` containing `tables` list."""
    LOG.info("Generating clinical summary DOCX: %s", output_path)

    doc = Document()
    set_page_margins(doc, 1.0)
    create_base_styles(doc)
    add_header(doc)

    if data and isinstance(data, dict):
        tables = data.get("tables") or []
        if tables:
            for t in tables:
                add_table_from_spec(doc, t)
        else:
            LOG.info("No tables found in input data; rendering default example table")
            # fallback example
            rows = [
                ("Primary endpoint: Mean systolic BP change (mmHg)", "−5.2 ± 1.1", "−3.8 ± 1.2"),
                ("Secondary endpoint: Proportion achieving target BP (%)", "62%", "49%"),
            ]
            add_table_primary_endpoints(doc, rows)
    else:
        # No data provided: keep the example content
        rows = [
            ("Primary endpoint: Mean systolic BP change (mmHg)", "−5.2 ± 1.1", "−3.8 ± 1.2"),
            ("Secondary endpoint: Proportion achieving target BP (%)", "62%", "49%"),
        ]
        add_table_primary_endpoints(doc, rows)

    # Add short methods section
    doc.add_heading("Methods", level=2)
    methods = doc.add_paragraph(style="C2CBody")
    methods.add_run(
        "Study design: Randomized, double-blind. Statistical tests: ANCOVA on change from baseline."
    )

    add_footer(doc)

    # Ensure output directory exists
    out_dir = os.path.dirname(os.path.abspath(output_path)) or "."
    os.makedirs(out_dir, exist_ok=True)

    doc.save(output_path)
    LOG.info("Saved document to %s", output_path)
    return os.path.abspath(output_path)


def _replace_placeholders_in_paragraph(para, mapping: Dict[str, Any]):
    """Replace placeholders in a paragraph's runs where possible, otherwise replace whole paragraph text."""
    if not mapping:
        return
    for key, val in mapping.items():
        ph = f"{{{{{key}}}}}"
        if ph in para.text:
            replaced = False
            for run in para.runs:
                if ph in run.text:
                    run.text = run.text.replace(ph, str(val))
                    replaced = True
            if not replaced:
                # clear runs and add a single run preserving paragraph style
                for run in para.runs:
                    run.text = ""
                new_run = para.add_run(str(val))
                # best-effort font preservation
                new_run.font.name = "Times New Roman"
                new_run.font.size = Pt(12)


def replace_placeholders_in_doc(doc: Document, mapping: Dict[str, Any]):
    """Replace placeholders in body paragraphs, table cells, headers, and footers."""
    # Body paragraphs
    for para in doc.paragraphs:
        _replace_placeholders_in_paragraph(para, mapping)

    # Table cells
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                for para in cell.paragraphs:
                    _replace_placeholders_in_paragraph(para, mapping)

    # Headers and footers
    for section in doc.sections:
        header = section.header
        for para in header.paragraphs:
            _replace_placeholders_in_paragraph(para, mapping)
        footer = section.footer
        for para in footer.paragraphs:
            _replace_placeholders_in_paragraph(para, mapping)


def _insert_table_after_paragraph(doc: Document, para, headers, rows):
    """Create a table and move it to immediately follow `para` in the document body."""
    cols = max(1, len(headers))
    tbl = doc.add_table(rows=1, cols=cols, style="Table Grid")
    hdr_cells = tbl.rows[0].cells
    for idx in range(cols):
        text = headers[idx] if idx < len(headers) else f"Column {idx+1}"
        p = hdr_cells[idx].paragraphs[0]
        run = p.add_run(str(text))
        run.font.name = "Times New Roman"
        run.font.size = Pt(12)
        run.font.bold = True
        _shade_cell(hdr_cells[idx])
        p.alignment = WD_PARAGRAPH_ALIGNMENT.LEFT

    for row in rows:
        values = _normalize_row(row, headers)
        cells = tbl.add_row().cells
        for idx, val in enumerate(values):
            cells[idx].text = val
            p = cells[idx].paragraphs[0]
            p.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER if idx >= 1 else WD_PARAGRAPH_ALIGNMENT.LEFT
            if p.runs:
                p.runs[0].font.name = "Times New Roman"
                p.runs[0].font.size = Pt(12)

    # Move table to after the paragraph
    body = doc.element.body
    # Find paragraph element index
    p_elm = para._p
    idx = list(body).index(p_elm)
    # move table (its element is tbl._tbl) to correct position
    body.remove(tbl._tbl)
    body.insert(idx + 1, tbl._tbl)


def replace_table_placeholders(doc: Document, tables: list):
    """Replace placeholders like {{efficacy_table}} with actual tables from `tables` specs."""
    # Build quick lookup by name or placeholder
    table_map = {}
    for t in tables:
        name = t.get("name") or t.get("placeholder") or t.get("title")
        if name:
            table_map[name] = t

    # Iterate top-level paragraphs
    paras = list(doc.paragraphs)
    for para in paras:
        text = para.text.strip()
        if text.startswith("{{") and text.endswith("}}"):
            key = text[2:-2].strip()
            if key in table_map:
                spec = table_map[key]
                headers = spec.get("headers") or []
                rows = spec.get("rows") or []
                _insert_table_after_paragraph(doc, para, headers, rows)
                # remove the placeholder paragraph
                p_elm = para._p
                p_elm.getparent().remove(p_elm)


def generate_clinical_summary(output_path: str = OUTPUT_FILENAME, data: Dict[str, Any] = None, template_path: str = None) -> str:
    """Main generator function; accepts optional parsed JSON `data` containing `tables` list and optional `template_path` to load a master template."""
    LOG.info("Generating clinical summary DOCX: %s", output_path)

    doc = Document(template_path) if template_path else Document()
    set_page_margins(doc, 1.0)
    create_base_styles(doc)
    # Only add header if template not provided
    if not template_path:
        add_header(doc)

    if data and isinstance(data, dict):
        # Replace simple placeholders from metadata
        metadata = data.get("metadata") or {}
        replace_placeholders_in_doc(doc, metadata)

        tables = data.get("tables") or []
        if tables:
            # First, replace any table placeholders by name
            replace_table_placeholders(doc, tables)
            # Then, for any tables not injected, append them
            for t in tables:
                name = t.get("name") or t.get("placeholder") or t.get("title")
                # if placeholder present and already replaced, skip
                if name and any(name == (p.text.strip()[2:-2].strip()) for p in doc.paragraphs if p.text.strip().startswith("{{") and p.text.strip().endswith("}}")):
                    continue
                add_table_from_spec(doc, t)
        else:
            LOG.info("No tables found in input data; rendering default example table")
            rows = [
                ("Primary endpoint: Mean systolic BP change (mmHg)", "−5.2 ± 1.1", "−3.8 ± 1.2"),
                ("Secondary endpoint: Proportion achieving target BP (%)", "62%", "49%"),
            ]
            add_table_primary_endpoints(doc, rows)
    else:
        # No data provided: keep the example content
        rows = [
            ("Primary endpoint: Mean systolic BP change (mmHg)", "−5.2 ± 1.1", "−3.8 ± 1.2"),
            ("Secondary endpoint: Proportion achieving target BP (%)", "62%", "49%"),
        ]
        add_table_primary_endpoints(doc, rows)

    # Add short methods section if not present in template
    if not template_path:
        doc.add_heading("Methods", level=2)
        methods = doc.add_paragraph(style="C2CBody")
        methods.add_run(
            "Study design: Randomized, double-blind. Statistical tests: ANCOVA on change from baseline."
        )

    # Only add default footer if no template provided - preserve template footer otherwise
    if not template_path:
        add_footer(doc)

    # Ensure output directory exists
    out_dir = os.path.dirname(os.path.abspath(output_path)) or "."
    os.makedirs(out_dir, exist_ok=True)

    doc.save(output_path)
    LOG.info("Saved document to %s", output_path)
    return os.path.abspath(output_path)


def generate_docx_from_json(input_path: str, output_path: str = OUTPUT_FILENAME, template_path: str = None) -> str:
    """Load JSON from `input_path` and generate a DOCX to `output_path` optionally using `template_path`."""
    with open(input_path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    return generate_clinical_summary(output_path=output_path, data=data, template_path=template_path)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Generate Concept2Cure clinical summary DOCX from JSON input.")
    parser.add_argument("-i", "--input", help="Input JSON file containing tables (see docs)")
    parser.add_argument(
        "-t", "--template", help="Optional DOCX template to use (preserves headers/footers/styles)")
    parser.add_argument(
        "-o", "--output", default=OUTPUT_FILENAME, help="Output DOCX filename (default: %(default)s)"
    )
    args = parser.parse_args()
    if args.input:
        path = generate_docx_from_json(args.input, args.output, template_path=args.template)
    else:
        path = generate_clinical_summary(args.output, template_path=args.template)
    print(f"Generated: {path}")
