/**
 * eTMF Inspection Readiness -- kit app/etmf.jsx ported (registry id `etmf`).
 *
 * AnA produces the inspection-readiness package (the CRO deliverable). NOT
 * a dashboard: the hero is the generated package document; the readiness
 * verdict + missing-essentials punch-list are what AnA computed and drives
 * to closed. Three lenses: completeness, timeliness, quality.
 *
 * Grounded verbatim in concept2cure-v2:
 *   assessTmfCompleteness / TMF_REFERENCE_MODEL (etmf fixture)
 *   GET  /api/etmf/trials/:trialId/completeness?scope=
 *   POST /api/etmf/trials/:trialId/artifacts {artifactCode,documentRef?}
 *   POST /api/etmf/trials/:trialId/artifacts/bulk
 *   GET  /api/etmf/trials/:trialId/inspection-package?scope= (streams ZIP)
 */
import React, { useState, useMemo, useEffect } from 'react';
import { I } from '../icons';
import { SampleTag } from '../dataConnect';
import { AnswerLead } from '../AnswerLead';
import type { SurfaceViewProps } from '../surfaceViews';
import {
  assessTmfCompleteness,
  assessTmfTimeliness,
  assessTmfQc,
  tmfArtifactName,
  ETMF_SAMPLE_TRIAL,
  ETMF_FILINGS,
} from '../fixtures/etmf';
import type { TmfCompletenessResult } from '../fixtures/etmf';
import '../styles/project-home-v2.css';

/* ---- Helper: file download ---- */
function downloadBlob(name: string, blob: Blob) {
  try {
    const u = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = u;
    a.download = name;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(u), 1500);
  } catch (_e) { /* noop */ }
}

/* ---- Helper: offline readiness report as markdown ---- */
function readinessReportMd(
  trial: typeof ETMF_SAMPLE_TRIAL,
  R: TmfCompletenessResult,
  missing: { zone: number; zoneName: string; code: string; name: string }[],
): string {
  let s = '# Trial Master File -- Inspection-Readiness Package\n\n';
  s += '**Trial:** ' + trial.title + ' (' + trial.trialId + ')\n\n';
  s += '**Sponsor:** ' + trial.sponsor + '  --  **Model:** ' + trial.model + '  --  **Scope:** ' + (R.scope === 'all' ? 'All artifacts' : 'Essential (ICH E6(R2) §8)') + '\n\n';
  s += '**Verdict:** ' + (R.ready ? 'INSPECTION-READY' : 'NOT INSPECTION-READY') + '  --  Zones complete ' + R.summary.zonesComplete + '/' + R.summary.zoneCount + '  --  Open gaps ' + R.summary.totalMissing + '\n\n';
  s += '## Zone index\n\n| Zone | Name | Filed | Status |\n|---|---|---|---|\n';
  (R.zones || []).forEach((z) => { s += '| ' + z.number + ' | ' + z.name + ' | ' + z.present.length + '/' + z.required.length + ' | ' + (z.complete ? 'complete' : (z.required.length - z.present.length) + ' open') + ' |\n'; });
  s += '\n## Open essential documents\n\n';
  if (!missing.length) s += '_None -- every required document is filed._\n';
  else { s += '| Zone | Document | Code |\n|---|---|---|\n'; missing.forEach((m) => { s += '| ' + m.zone + ' | ' + m.name + ' | ' + m.code + ' |\n'; }); }
  s += '\n---\n_This package is the inspection index and readiness picture -- not the document bytes, which live in the systems of record referenced per artifact. Generated by AnA from the DIA TMF Reference Model completeness assessment (ICH E6(R2) §8)._\n';
  return s;
}

/* ---- Component ---- */

export function Etmf({ onAsk, onNav }: SurfaceViewProps) {
  const ask = onAsk;
  const trial = ETMF_SAMPLE_TRIAL;
  const [scope, setScope] = useState<'essential' | 'all'>('essential');
  const [filed, setFiled] = useState<string[]>([]);
  const [live, setLive] = useState<TmfCompletenessResult | null>(null);
  const [busy, setBusy] = useState(false);
  const [toast, setToast] = useState('');
  const [dl, setDl] = useState<string | null>(null);

  /* live ?? fixture: try the real per-trial completeness endpoint once. */
  useEffect(() => {
    let cancel = false;
    if ((window as any).C2C_API && (window as any).C2C_API.connected()) {
      (window as any).C2C_API.live('/api/etmf/trials/' + encodeURIComponent(trial.trialId) + '/completeness?scope=' + scope, null)
        .then((r: any) => { if (!cancel && r && !r.sample && r.data) setLive(r.data); });
    }
    return () => { cancel = true; };
  }, [scope]);

  const provided = useMemo(() => (trial.providedArtifacts || []).concat(filed), [filed]);
  const R = useMemo(() => {
    return live || assessTmfCompleteness({ providedArtifacts: provided, scope });
  }, [live, provided, scope]);

  const sample = !live;
  const missing = useMemo(() => {
    const out: { zone: number; zoneName: string; code: string; name: string }[] = [];
    (R.zones || []).forEach((z) => { (z.missing || []).forEach((code) => { out.push({ zone: z.number, zoneName: z.name, code, name: tmfArtifactName(code) }); }); });
    return out;
  }, [R]);
  const incompleteZones = (R.zones || []).filter((z) => !z.complete).length;
  const timeliness = useMemo(() => assessTmfTimeliness(provided), [provided]);
  const qc = useMemo(() => assessTmfQc(provided), [provided]);
  const inspectionReady = R.ready && timeliness.timely && qc.qcClean;
  const openIssues = R.summary.totalMissing + timeliness.late + qc.inQc;

  /* File a missing essential -- real POST when connected; local otherwise. */
  const fileArtifact = (code: string) => {
    if ((window as any).C2C_API && (window as any).C2C_API.connected()) {
      setBusy(true);
      (window as any).C2C_API.post('/api/etmf/trials/' + encodeURIComponent(trial.trialId) + '/artifacts', { artifactCode: code, documentRef: 'vault://' + trial.trialId + '/' + code })
        .then(() => { setFiled((f) => f.concat([code])); setLive(null); setToast(tmfArtifactName(code) + ' filed to the TMF'); })
        .catch(() => { setFiled((f) => f.concat([code])); setToast(tmfArtifactName(code) + ' filed (recorded locally -- reconnect to persist)'); })
        .then(() => { setBusy(false); setTimeout(() => setToast(''), 2600); });
    } else {
      setFiled((f) => f.concat([code]));
      setToast(tmfArtifactName(code) + ' filed to the TMF');
      setTimeout(() => setToast(''), 2600);
    }
  };

  /* Bulk file all open essentials in one call. */
  const fileBulk = (codes: string[]) => {
    if (!codes || !codes.length) return;
    if ((window as any).C2C_API && (window as any).C2C_API.connected()) {
      setBusy(true);
      (window as any).C2C_API.post('/api/etmf/trials/' + encodeURIComponent(trial.trialId) + '/artifacts/bulk',
        { artifacts: codes.map((c) => ({ artifactCode: c, documentRef: 'vault://' + trial.trialId + '/' + c })) })
        .then((r: any) => { setFiled((f) => f.concat(codes)); setLive(null);
          const n = (r && r.filed != null) ? r.filed : codes.length;
          const t = (r && r.total != null) ? r.total : codes.length;
          setToast(n + ' of ' + t + ' essentials filed to the TMF'); })
        .catch(() => { setFiled((f) => f.concat(codes)); setToast(codes.length + ' essentials filed (recorded locally -- reconnect to persist)'); })
        .then(() => { setBusy(false); setTimeout(() => setToast(''), 3000); });
    } else {
      setFiled((f) => f.concat(codes));
      setToast(codes.length + ' essentials filed to the TMF');
      setTimeout(() => setToast(''), 3000);
    }
  };

  /* Generate / download the inspection package. */
  const generatePackage = () => {
    setBusy(true);
    setDl(null);
    const finish = (kind: string) => { setBusy(false); setDl(kind); setTimeout(() => setDl(null), 3200); };
    const downloadReport = () => {
      const md = readinessReportMd(trial, R, missing);
      downloadBlob(trial.trialId + '_inspection-readiness.md', new Blob([md], { type: 'text/markdown' }));
    };
    if ((window as any).C2C_API && (window as any).C2C_API.connected()) {
      const url = ((window as any).C2C_API.base() || '') + '/api/etmf/trials/' + encodeURIComponent(trial.trialId) + '/inspection-package?scope=' + scope;
      let hdrs: Headers | null = null;
      fetch(url, { headers: (window as any).C2C_API.getAuthHeaders() })
        .then((res: Response) => { if (!res.ok) throw new Error('HTTP ' + res.status); hdrs = res.headers; return res.blob(); })
        .then((blob: Blob) => {
          downloadBlob(trial.trialId + '_inspection-package.zip', blob);
          const sha = hdrs && hdrs.get && hdrs.get('X-TMF-SHA256');
          const rdy = hdrs && hdrs.get && hdrs.get('X-TMF-Ready');
          setToast('Inspection index generated' + (rdy != null ? ' -- ' + ((rdy === 'true' || rdy === '1') ? 'ready' : 'gaps remain') : '') + (sha ? ' -- SHA-256 ' + String(sha).slice(0, 10) + '...' : '') + ' -- index + readiness, not the document bytes');
          setTimeout(() => setToast(''), 4400);
          finish('zip');
        })
        .catch(() => { downloadReport(); finish('report'); });
    } else {
      downloadReport();
      finish('report');
    }
  };

  return (
    <div className="page-inner etmf">
      <div className="surface-head">
        <div>
          <div className="surface-kicker">{I.vault || I.folder} Vault -- CRO / service view -- Trial Master File (DIA Reference Model v3)</div>
          <h1>Inspection readiness <SampleTag sample={sample} /></h1>
          <p className="surface-sub">{trial.title} -- {trial.trialId} -- {trial.sites} sites -- completeness -- timeliness -- quality</p>
        </div>
        <div className="surface-head-actions">
          <div className="etmf-scope" role="tablist" aria-label="Completeness scope">
            <button role="tab" className={scope === 'essential' ? 'on' : ''} onClick={() => { setScope('essential'); setLive(null); }}>Essential (ICH E6 §8)</button>
            <button role="tab" className={scope === 'all' ? 'on' : ''} onClick={() => { setScope('all'); setLive(null); }}>All artifacts</button>
          </div>
          <button className="btn ghost" onClick={() => onNav && onNav('project-home')} title="Open the study in Project management">{I.folder} Open in Project management</button>
          <button className="btn ghost" onClick={() => ask('What TMF gaps would an inspector flag on ' + trial.trialId + ' and how do I close them?')}>{I.sparkles} Ask AnA</button>
        </div>
      </div>

      <AnswerLead
        tone={inspectionReady ? 'good' : 'urgent'}
        eyebrow={'Whether ' + trial.trialId + "'s TMF would survive an inspection today"}
        headline={inspectionReady
          ? <>{trial.trialId}'s TMF is <b>inspection-ready</b> -- complete, contemporaneously filed, and QC-clean across all {R.summary.zoneCount} zones.</>
          : <>{trial.trialId}'s TMF isn't inspection-ready yet -- <b>{openIssues} thing{openIssues === 1 ? '' : 's'}</b> across completeness, timeliness and QC {openIssues === 1 ? 'needs' : 'need'} your attention.</>}
        body={inspectionReady
          ? <>Every {scope === 'all' ? 'artifact' : 'essential document'} is filed, filed on time, and reviewed to final. I keep it that way as the trial runs -- say the word and I'll generate the package.</>
          : <>I keep this file inspection-ready as the trial runs. Right now: {R.summary.totalMissing > 0 ? <><b>{R.summary.totalMissing}</b> essential{R.summary.totalMissing === 1 ? '' : 's'} not yet filed; </> : null}{timeliness.late > 0 ? <><b>{timeliness.late}</b> filed late (worst {timeliness.worstLag}d after the document date -- inspectors see upload dates); </> : null}{qc.inQc > 0 ? <><b>{qc.inQc}</b> received but not yet QC-final.</> : null}</>}
        reassure={R.ready ? 'Nothing here is a finding -- this is the clean picture an inspector would see.' : 'None of these are findings yet -- they are gaps you can close before an inspector ever opens the file.'}
        action={{ label: R.ready ? 'Generate the inspection package' : 'Generate the readiness package', onClick: generatePackage }}
        secondary={sample ? 'Sample trial -- the live route computes this from the trial\'s filed artifacts.' : 'Live from the trial\'s filed TMF artifacts.'}
      />

      {/* AnA's read across the three inspection lenses */}
      <div className="etmf-lenses">
        <div className={'etmf-lens' + (R.ready ? ' ok' : ' warn')}>
          <div className="etmf-lens-k">{I.checkSquare} Completeness</div>
          <div className="etmf-lens-v">{R.summary.zonesComplete}/{R.summary.zoneCount} zones</div>
          <div className="etmf-lens-s">{R.ready ? 'All essentials filed' : R.summary.totalMissing + ' essential' + (R.summary.totalMissing === 1 ? '' : 's') + ' open'}</div>
        </div>
        <div className={'etmf-lens' + (timeliness.timely ? ' ok' : ' warn')}>
          <div className="etmf-lens-k">{I.clock} Timeliness</div>
          <div className="etmf-lens-v">{timeliness.timely ? 'Contemporaneous' : timeliness.late + ' filed late'}</div>
          <div className="etmf-lens-s">{timeliness.timely ? 'No backfilled uploads' : 'Worst ' + timeliness.worstLag + 'd after document date'}</div>
        </div>
        <div className={'etmf-lens' + (qc.qcClean ? ' ok' : ' warn')}>
          <div className="etmf-lens-k">{I.shieldCheck} Quality (QC)</div>
          <div className="etmf-lens-v">{qc.qcClean ? 'All QC-final' : qc.inQc + ' in QC'}</div>
          <div className="etmf-lens-s">{qc.qcClean ? 'Every doc reviewed to final' : qc.inQc + ' received, not yet final'}</div>
        </div>
      </div>

      <div className="etmf-body">
        {/* Left -- AnA's punch list: the essentials still to file */}
        <div className="etmf-left">
          <div className="etmf-panel">
            <div className="etmf-panel-h">{I.checkSquare} AnA punch-list <span className="x">-- {missing.length} to file before inspection</span>
              {missing.length > 1 && <button className="btn ghost sm" style={{ marginLeft: 'auto' }} disabled={busy} onClick={() => fileBulk(missing.map((m) => m.code))}>{I.filePlus || I.plus} File all {missing.length}</button>}
            </div>
            {missing.length === 0 ? (
              <div className="etmf-clean">{I.check} Every {scope === 'all' ? '' : 'essential '}document is filed. The package is inspection-clean.</div>
            ) : (
              <div className="etmf-missing">
                {missing.map((m) => (
                  <div key={m.code} className="etmf-miss">
                    <div className="etmf-miss-main">
                      <div className="etmf-miss-name">{m.name}</div>
                      <div className="etmf-miss-zone">Zone {m.zone} -- {m.zoneName} -- <span className="mono">{m.code}</span></div>
                    </div>
                    <button className="btn ghost sm" disabled={busy} onClick={() => fileArtifact(m.code)}>{I.filePlus || I.plus} File</button>
                  </div>
                ))}
              </div>
            )}
          </div>
          <div className="etmf-panel">
            <div className="etmf-panel-h">{I.grid} Zone completeness <span className="x">-- {R.summary.zonesComplete}/{R.summary.zoneCount} complete</span></div>
            <div className="etmf-zones">
              {(R.zones || []).map((z) => (
                <div key={z.number} className={'etmf-zone' + (z.complete ? ' ok' : '')}>
                  <span className="etmf-zone-n">{z.number}</span>
                  <span className="etmf-zone-name">{z.name}</span>
                  <span className="etmf-zone-cnt">{z.present.length}/{z.required.length}</span>
                  <span className="etmf-zone-dot">{z.complete ? I.check : I.alertTriangle}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right -- THE DELIVERABLE: the generated inspection-readiness package */}
        <div className="etmf-right">
          <div className="etmf-sec">Inspection-readiness package <span className="etmf-sec-x">-- generated by AnA from the DIA Reference Model assessment -- the index + readiness picture, not the document bytes (those stay in the systems of record)</span></div>
          <div className="cm-doc etmf-doc">
            <div className="cm-doc-bar">
              <span className="cm-doc-name">{trial.trialId}_inspection-package{scope === 'all' ? '_all' : ''}</span>
              <div className="cm-doc-bar-r">
                {dl === 'zip' && <span className="etmf-dl ok">{I.check} governed ZIP downloaded</span>}
                {dl === 'report' && <span className="etmf-dl">{I.download} readiness report downloaded</span>}
                <button className="btn primary sm" disabled={busy} onClick={generatePackage}>{busy ? 'Generating...' : <>{I.download} Generate package</>}</button>
              </div>
            </div>
            <div className="cm-doc-body etmf-doc-body">
              <div className="etmf-cover">
                <div className="etmf-cover-badge" data-ready={R.ready || undefined}>{R.ready ? 'INSPECTION-READY' : 'NOT INSPECTION-READY'}</div>
                <h2>Trial Master File -- Inspection-Readiness Package</h2>
                <div className="etmf-cover-meta">
                  <span>{trial.title}</span><span>Trial {trial.trialId}</span><span>{trial.sponsor}</span>
                  <span>{trial.model}</span><span>Scope: {scope === 'all' ? 'All artifacts' : 'Essential (ICH E6(R2) §8)'}</span>
                  <span>Generated {new Date().toLocaleDateString([], { year: 'numeric', month: 'short', day: 'numeric' })}</span>
                </div>
              </div>

              <div className="etmf-doc-kpis">
                <div className="etmf-kpi"><div className="v">{R.summary.zonesComplete}/{R.summary.zoneCount}</div><div className="k">Zones complete</div></div>
                <div className="etmf-kpi"><div className="v">{R.summary.totalRequired - R.summary.totalMissing}/{R.summary.totalRequired}</div><div className="k">{scope === 'all' ? 'Artifacts' : 'Essential docs'} filed</div></div>
                <div className={'etmf-kpi' + (R.summary.totalMissing ? ' warn' : '')}><div className="v">{R.summary.totalMissing}</div><div className="k">Open gaps</div></div>
              </div>

              <h3>1 -- Readiness verdict</h3>
              <p>{R.ready
                ? <>This trial's TMF holds every required {scope === 'all' ? 'artifact' : 'essential document'} across all {R.summary.zoneCount} DIA Reference-Model zones. On a completeness basis it is <b>inspection-ready</b>.</>
                : <>This trial's TMF is missing <b>{R.summary.totalMissing} required {scope === 'all' ? 'artifact' : 'essential'} document{R.summary.totalMissing === 1 ? '' : 's'}</b> across {incompleteZones} zone{incompleteZones === 1 ? '' : 's'}. It is <b>not yet inspection-ready</b>; the open items are listed in §3.</>}</p>

              <h3>2 -- Zone index (DIA TMF Reference Model)</h3>
              <table className="etmf-tbl">
                <thead><tr><th>Zone</th><th>Name</th><th>Filed</th><th>Status</th></tr></thead>
                <tbody>
                  {(R.zones || []).map((z) => (
                    <tr key={z.number}><td className="mono">{z.number}</td><td>{z.name}</td><td className="mono">{z.present.length}/{z.required.length}</td>
                      <td><span className={'etmf-tag' + (z.complete ? ' ok' : ' warn')}>{z.complete ? 'complete' : (z.required.length - z.present.length) + ' open'}</span></td></tr>
                  ))}
                </tbody>
              </table>

              <h3>3 -- Open essential documents</h3>
              {missing.length === 0
                ? <p className="etmf-none">None -- every required {scope === 'all' ? 'artifact' : 'essential document'} is filed.</p>
                : (<table className="etmf-tbl">
                    <thead><tr><th>Zone</th><th>Document</th><th>Artifact code</th></tr></thead>
                    <tbody>{missing.map((m) => <tr key={m.code}><td className="mono">{m.zone}</td><td>{m.name}</td><td className="mono">{m.code}</td></tr>)}</tbody>
                  </table>)}

              <h3>4 -- What this package is</h3>
              <p className="etmf-readme">This package is the inspection <b>index and readiness picture</b> -- the manifest of filed artifacts, the completeness assessment, and the zone-by-zone gap list. The document bytes themselves live in the systems of record referenced per artifact; this package does not contain them. Present it to an inspector as the map to the file, not the file itself.</p>
              {sample && <p className="etmf-readme sample">Sample trial. The live route streams the governed ZIP (manifest.json -- completeness.json -- inspection-index.csv -- README.txt) with an X-TMF-SHA256 seal; offline, AnA renders this readiness report from the same deterministic assessment.</p>}
            </div>
          </div>
        </div>
      </div>

      {toast && <div className="etmf-toast">{I.check} {toast}</div>}
    </div>
  );
}
