/**
 * Signed-package snapshot + resume hydration (Part-11 §11.70).
 *
 * The release-signature drift check used to RE-DERIVE the package from source on
 * resume and compare digests. That is non-reproducible under useAI (AI-refined
 * narratives cannot be regenerated byte-for-byte) and fragile to input key-order,
 * so a legitimately-signed run would fail on resume with a false
 * signature_payload_drift. The fix persists the exact signed package on the sign
 * step and HYDRATES it on resume, binding the signature to a frozen record.
 *
 * These tests prove:
 *   1. the digest refactor is byte-identical (no existing signature invalidated);
 *   2. the digest is a pure function of (leaves, validatorOutcome, identity), so
 *      hydration reproduces the signed digest and tampering is detectable;
 *   3. resume HYDRATES the snapshot — a run whose source no longer reproduces the
 *      package still signs (the useAI fix);
 *   4. a corrupted snapshot fails closed;
 *   5. legacy runs without a snapshot fall back to re-derive + drift-check.
 */
import { describe, it, expect, beforeEach, vi } from 'vitest';

// SQL-aware DB mock. getRun's SELECT returns H.runRow; findActiveReleaseSignature
// returns H.signatureRows; every write/other query returns no rows.
const H = vi.hoisted(() => ({
  runRow: null as Record<string, unknown> | null,
  signatureRows: [] as Array<{ id: number }>,
}));

vi.mock('../../db', () => ({
  pool: {
    query: vi.fn(async (sql: string) => {
      const s = String(sql);
      if (/FROM submission_orchestrator_runs/i.test(s) && /SELECT/i.test(s) && /WHERE run_id/i.test(s)) {
        return { rows: H.runRow ? [H.runRow] : [] };
      }
      if (/FROM electronic_signatures/i.test(s)) {
        return { rows: H.signatureRows };
      }
      return { rows: [] };
    }),
  },
  db: { execute: vi.fn(async () => ({ rows: [] })) },
}));

vi.mock('../../lib/unified-ai-client.js', () => ({ ai: { complete: vi.fn(async () => '') } }));

import {
  runOrchestrator,
  computeBoundPayloadDigest,
  computeBoundPayloadDigestFromComponents,
  type OrchestratorInputs,
  type StepRecord,
  type BoundDigestValidatorOutcome,
} from '../submission-package-orchestrator';
import type { ECTDLeaf } from '../ectd/ectd4-validator';
import type { CanonicalSource } from '../module3Composer';

// ── Fixtures ──────────────────────────────────────────────────────────────────

function makeLeaf(sectionCode: string, checksum: string): ECTDLeaf {
  return {
    sectionCode,
    title: sectionCode,
    checksum,
    checksumType: 'md5',
    operation: 'new',
    filePath: `m3/${sectionCode}.pdf`,
    mimeType: 'application/pdf',
    fileSize: 1024,
  };
}

function makeSummary() {
  return { errors: 0, warnings: 0, infos: 0, sectionsPresent: 2, sectionsRequired: 2, sectionsMissing: [] as string[] };
}

const VO: BoundDigestValidatorOutcome = { gatewayReady: true, hardenedScore: 100, summary: makeSummary() };

const IDENTITY = {
  submissionId: 'sub-001',
  applicationNumber: 'IND123456',
  region: 'US' as const,
  submissionType: 'IND',
  organizationId: 1,
};

/** OrchestratorInputs with EMPTY sources: a re-derive on resume would produce a
 *  ZERO-leaf package (a totally different digest), so if resume does NOT drift,
 *  hydration is proven — it cannot have re-derived. */
const RESUME_INPUTS: OrchestratorInputs = {
  organizationId: 1,
  submissionId: 'sub-001',
  applicationNumber: 'IND123456',
  region: 'US',
  submissionType: 'IND',
  cmcSources: [],
  nonclinicalStudies: [],
  clinicalStudyData: [],
  csrInputs: [],
  skipValidation: true,
};

function makeRunRow(signPayload: unknown): Record<string, unknown> {
  const steps: StepRecord[] = [
    { key: 'package.assemble', status: 'complete', inputHash: 'a', dependsOn: [] },
    {
      key: 'package.sign',
      status: 'awaiting-signature',
      inputHash: 'h',
      dependsOn: ['package.assemble'],
      outputRef: JSON.stringify(signPayload),
    },
  ];
  return {
    run_id: 'run-1',
    organization_id: 1,
    submission_id: 'sub-001',
    submission_id_fk: 42,
    application_number: 'IND123456',
    region: 'US',
    submission_type: 'IND',
    started_at: new Date(0).toISOString(),
    completed_at: null,
    status: 'awaiting-signature',
    steps: JSON.stringify(steps),
    workflow_version: null,
    dependency_graph_digest: null,
  };
}

function snapshotFor(leaves: ECTDLeaf[]) {
  return {
    leaves,
    backboneXml: '<index.xml/>',
    validatorOutcome: VO,
    applicationNumber: IDENTITY.applicationNumber,
    sequenceNumber: '0000',
    region: 'US',
    submissionType: 'IND',
    totalSizeBytes: 2048,
  };
}

beforeEach(() => {
  H.runRow = null;
  H.signatureRows = [];
});

// ── 1–2. Digest is a pure function of its components ────────────────────────────

describe('computeBoundPayloadDigest refactor', () => {
  it('the component helper produces a byte-identical digest to the wrapper (no signature invalidated)', () => {
    const leaves = [makeLeaf('m3.2.S.1', 'a'.repeat(32)), makeLeaf('m3.2.P.1', 'b'.repeat(32))];
    const assembly = {
      leaves,
      totalSizeBytes: 2048,
      applicationNumber: IDENTITY.applicationNumber,
      sequenceNumber: '0000',
      region: 'US' as const,
      submissionType: 'IND',
      backboneXml: '<index/>',
    };
    const validation = { gatewayReady: VO.gatewayReady, hardenedScore: VO.hardenedScore, summary: VO.summary } as never;

    const viaWrapper = computeBoundPayloadDigest({ assembly, validation, ...IDENTITY });
    const viaComponents = computeBoundPayloadDigestFromComponents({ leaves, validatorOutcome: VO, ...IDENTITY });
    expect(viaComponents).toBe(viaWrapper);
  });

  it('full sign-prep → persist(JSON) → resume cycle reproduces the digest (the integrity-guard invariant)', () => {
    // Mirror sign-prep EXACTLY: digest via the wrapper with backboneXml:undefined.
    const leaves = [makeLeaf('m3.2.S.1', 'a'.repeat(32)), makeLeaf('m3.2.P.1', 'b'.repeat(32))];
    const assembly = {
      leaves,
      totalSizeBytes: 4096,
      applicationNumber: IDENTITY.applicationNumber,
      sequenceNumber: '0000',
      region: 'US' as const,
      submissionType: 'IND',
      backboneXml: '<index>real backbone</index>',
    };
    const validation = { gatewayReady: VO.gatewayReady, hardenedScore: VO.hardenedScore, summary: VO.summary } as never;
    const prepDigest = computeBoundPayloadDigest({ assembly, validation, ...IDENTITY, backboneXml: undefined });

    // Persist the snapshot the way the sign step does, then JSON round-trip it
    // through the steps column (getRun does JSON.parse), then recompute the way
    // resume does — must equal the prep digest or every new run fails on resume.
    const persisted = JSON.parse(
      JSON.stringify({
        payloadDigest: prepDigest,
        awaitingSince: new Date(0).toISOString(),
        signedSnapshot: snapshotFor(leaves),
      }),
    );
    const resumeDigest = computeBoundPayloadDigestFromComponents({
      leaves: persisted.signedSnapshot.leaves,
      validatorOutcome: persisted.signedSnapshot.validatorOutcome,
      ...IDENTITY,
      // resume also passes NO backboneXml — matching sign-prep's undefined.
    });
    expect(resumeDigest).toBe(prepDigest);
  });

  it('depends only on (leaves, validatorOutcome, identity) — deep-cloned components hash the same; a tampered leaf does not', () => {
    const leaves = [makeLeaf('m3.2.S.1', 'a'.repeat(32))];
    const d1 = computeBoundPayloadDigestFromComponents({ leaves, validatorOutcome: VO, ...IDENTITY });

    const cloned = JSON.parse(JSON.stringify(leaves)) as ECTDLeaf[];
    const clonedVo = JSON.parse(JSON.stringify(VO)) as BoundDigestValidatorOutcome;
    expect(computeBoundPayloadDigestFromComponents({ leaves: cloned, validatorOutcome: clonedVo, ...IDENTITY })).toBe(d1);

    const tampered = JSON.parse(JSON.stringify(leaves)) as ECTDLeaf[];
    tampered[0].checksum = 'deadbeef'.repeat(4);
    expect(computeBoundPayloadDigestFromComponents({ leaves: tampered, validatorOutcome: VO, ...IDENTITY })).not.toBe(d1);
  });
});

// ── 3–5. Resume hydration behavior ──────────────────────────────────────────────

describe('resumeAwaitingSignature — snapshot hydration', () => {
  it('HYDRATES the signed snapshot (no re-derive) — a run whose source cannot reproduce the package still signs', async () => {
    const leaves = [makeLeaf('m3.2.S.1', 'a'.repeat(32)), makeLeaf('m3.2.P.1', 'b'.repeat(32))];
    const payloadDigest = computeBoundPayloadDigestFromComponents({ leaves, validatorOutcome: VO, ...IDENTITY });
    const payload = { payloadDigest, awaitingSince: new Date(0).toISOString(), signedSnapshot: snapshotFor(leaves) };

    H.runRow = makeRunRow(payload);
    H.signatureRows = [{ id: 777 }]; // a matching signature exists

    const { run } = await runOrchestrator(RESUME_INPUTS, { resumeRunId: 'run-1' });
    const sign = run.steps.find((s) => s.key === 'package.sign')!;

    // No false drift, no re-derive: the frozen snapshot was hydrated and the
    // signature bound. RESUME_INPUTS has empty sources — a re-derive would have
    // produced 0 leaves and drifted.
    expect(sign.status).toBe('complete');
    expect(sign.error).toBeUndefined();
    const out = JSON.parse(sign.outputRef!);
    expect(out.signatureId).toBe(777);
    expect(out.signedSnapshot).toBeDefined(); // carried forward for later resumes
  });

  it('stays awaiting-signature (no drift) when the snapshot is intact but no signature exists yet', async () => {
    const leaves = [makeLeaf('m3.2.S.1', 'c'.repeat(32))];
    const payloadDigest = computeBoundPayloadDigestFromComponents({ leaves, validatorOutcome: VO, ...IDENTITY });
    const payload = { payloadDigest, awaitingSince: new Date(0).toISOString(), signedSnapshot: snapshotFor(leaves) };

    H.runRow = makeRunRow(payload);
    H.signatureRows = []; // no signature yet

    const { run } = await runOrchestrator(RESUME_INPUTS, { resumeRunId: 'run-1' });
    const sign = run.steps.find((s) => s.key === 'package.sign')!;
    expect(sign.status).toBe('awaiting-signature');
    expect(sign.error).toBeUndefined();
  });

  it('fails closed when the persisted snapshot no longer matches its signed digest', async () => {
    const signedLeaves = [makeLeaf('m3.2.S.1', 'a'.repeat(32))];
    const payloadDigest = computeBoundPayloadDigestFromComponents({ leaves: signedLeaves, validatorOutcome: VO, ...IDENTITY });
    // Persist a snapshot whose leaves were tampered AFTER the digest was bound.
    const tamperedLeaves = [makeLeaf('m3.2.S.1', 'f'.repeat(32))];
    const payload = { payloadDigest, awaitingSince: new Date(0).toISOString(), signedSnapshot: snapshotFor(tamperedLeaves) };

    H.runRow = makeRunRow(payload);
    H.signatureRows = [{ id: 777 }];

    const { run } = await runOrchestrator(RESUME_INPUTS, { resumeRunId: 'run-1' });
    const sign = run.steps.find((s) => s.key === 'package.sign')!;
    expect(sign.status).toBe('failed');
    expect(sign.error).toBe('signature_snapshot_integrity_failure');
  });

  it('legacy runs without a snapshot fall back to re-derive + drift-check', async () => {
    // No signedSnapshot → legacy branch. With real sources the re-derived digest
    // is well-defined but will not match this arbitrary persisted digest → drift.
    const drugSubstance: CanonicalSource = {
      id: 'src-ds-1',
      sourceType: 'drug_substance',
      sourcePayload: { name: 'Compound X', manufacturer: 'BioCo' },
    };
    const payload = { payloadDigest: 'legacy-digest-will-not-match', awaitingSince: new Date(0).toISOString() };

    H.runRow = makeRunRow(payload);
    H.signatureRows = [];

    const { run } = await runOrchestrator(
      { ...RESUME_INPUTS, cmcSources: [drugSubstance], skipValidation: false },
      { resumeRunId: 'run-1' },
    );
    const sign = run.steps.find((s) => s.key === 'package.sign')!;
    expect(sign.status).toBe('failed');
    expect(sign.error).toBe('signature_payload_drift');
  });
});
