"""Phase 7.0F — eCTD Assembly v1 Renderer.

Generates an eCTD-style sequence ZIP from a proof pack record.
This is a "v1 scaffolding" assembly: real folder skeleton with
rendered PDFs placed in the correct eCTD module locations,
plus checksums.sha256 and submission_readme.md.

Output structure inside ZIP:
  sequence-NNNN/
    m1/
      us/
        submission_readme.md
    m2/
      (reserved — summaries will go here in v2)
    m3/
      (reserved — quality will go here in v2)
    m4/
      study-reports/
        se-matrix-report.pdf      (if rendered)
    m5/
      clinical-reports/
        defense-packet-report.pdf (if rendered)
        audit-trail-report.pdf    (if rendered)
    proof-pack/
      proof-pack-summary.pdf      (if rendered)
      manifest.json
    checksums.sha256
"""

from __future__ import annotations

import hashlib
import io
import json
import logging
from datetime import datetime, timezone
from typing import Any
from zipfile import ZipFile, ZIP_DEFLATED

from ..render_runner import register_renderer

logger = logging.getLogger(__name__)


_SEQUENCE_NUMBER = "0000"  # v1 always uses 0000

# ═══════════════════════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════════════════════


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _safe_str(val: Any) -> str:
    if val is None:
        return ""
    if isinstance(val, (dict, list)):
        return json.dumps(val, ensure_ascii=False, default=str)[:500]
    return str(val)[:500]


def _generate_readme(pp_row: dict[str, Any]) -> str:
    """Generate the submission_readme.md for Module 1."""
    lines = [
        "# eCTD Submission README",
        "",
        "## Submission Identity",
        "",
        f"- **Proof Pack ID**: {_safe_str(pp_row.get('id'))}",
        f"- **Program ID**: {_safe_str(pp_row.get('program_id'))}",
        f"- **Sequence**: {_SEQUENCE_NUMBER}",
        f"- **Generator**: ClinicalSageAI v{_safe_str(pp_row.get('generator_version', 'unknown'))}",
        f"- **Generated**: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        "",
        "## Contract Hashes",
        "",
        f"- Manifest Hash: `{_safe_str(pp_row.get('manifest_hash'))}`",
        f"- Risk Vocab Hash: `{_safe_str(pp_row.get('risk_vocab_hash'))}`",
        f"- Risk Code Lock Hash: `{_safe_str(pp_row.get('risk_code_lock_hash'))}`",
        f"- Schema Hash: `{_safe_str(pp_row.get('schema_hash'))}`",
        "",
        "## Module Layout",
        "",
        "| Module | Content |",
        "|--------|---------|",
        "| m1/    | Submission readme, regional admin |",
        "| m2/    | (Reserved for summaries) |",
        "| m3/    | (Reserved for quality data) |",
        "| m4/    | SE Matrix Report |",
        "| m5/    | Defense Packet, Audit Trail |",
        "| proof-pack/ | Summary, manifest |",
        "",
        "## Notes",
        "",
        "This eCTD assembly was generated by ClinicalSageAI's automated",
        "regulatory document pipeline. All rendered PDFs are deterministic",
        "and can be reproduced from the same proof pack data.",
        "",
        "For verification, compare file checksums against `checksums.sha256`.",
    ]
    return "\n".join(lines)


def _generate_manifest_json(pp_row: dict[str, Any]) -> str:
    """Generate simplified manifest.json for the proof-pack module."""
    manifest = {
        "proof_pack_id": _safe_str(pp_row.get("id")),
        "program_id": _safe_str(pp_row.get("program_id")),
        "generator_version": _safe_str(pp_row.get("generator_version", "unknown")),
        "manifest_hash": _safe_str(pp_row.get("manifest_hash")),
        "risk_vocab_hash": _safe_str(pp_row.get("risk_vocab_hash")),
        "risk_code_lock_hash": _safe_str(pp_row.get("risk_code_lock_hash")),
        "schema_hash": _safe_str(pp_row.get("schema_hash")),
        "subject_hash": _safe_str(pp_row.get("subject_hash")),
        "assembled_at": datetime.now(timezone.utc).isoformat(),
    }
    return json.dumps(manifest, indent=2, ensure_ascii=False)


def _try_render_inline(artifact_type: str, pp_row: dict[str, Any]) -> bytes | None:
    """Try to render a PDF inline for embedding in the ZIP.

    This calls back into the registry to render sub-documents.
    If a renderer is not registered or it fails, returns None.
    """
    from ..render_runner import _RENDERERS

    fn = _RENDERERS.get(artifact_type)
    if fn is None:
        logger.debug("No renderer registered for %s — skipping embed", artifact_type)
        return None

    try:
        result = fn(pp_row, request_id="ectd-assembly-inline")
        if isinstance(result, bytes) and len(result) > 0:
            return result
    except Exception as exc:
        logger.warning("Inline render of %s failed: %s", artifact_type, exc)
    return None


# ═══════════════════════════════════════════════════════════════════════════════
# Main renderer
# ═══════════════════════════════════════════════════════════════════════════════


@register_renderer("ectd_sequence_zip")
def render_ectd_assembly(pp_row: dict[str, Any] | Any, request_id: str = "") -> bytes:
    """Render an eCTD v1 sequence ZIP with real folder skeleton.

    Embeds rendered PDFs from registry where available.
    """
    if hasattr(pp_row, "keys"):
        row = dict(pp_row)
    else:
        row = pp_row

    logger.info("Assembling eCTD sequence ZIP for proof_pack=%s", str(row.get("id", "?"))[:24])

    prefix = f"sequence-{_SEQUENCE_NUMBER}"
    checksums: dict[str, str] = {}

    buf = io.BytesIO()
    with ZipFile(buf, "w", compression=ZIP_DEFLATED) as zf:
        # ── m1/ — submission readme ───────────────────────────────────
        readme = _generate_readme(row).encode("utf-8")
        readme_path = f"{prefix}/m1/us/submission_readme.md"
        zf.writestr(readme_path, readme)
        checksums[readme_path] = _sha256(readme)

        # ── m2/ — placeholder ─────────────────────────────────────────
        m2_placeholder = b"# Module 2 - Summaries (Reserved for v2)\n"
        m2_path = f"{prefix}/m2/.gitkeep"
        zf.writestr(m2_path, m2_placeholder)
        checksums[m2_path] = _sha256(m2_placeholder)

        # ── m3/ — placeholder ─────────────────────────────────────────
        m3_placeholder = b"# Module 3 - Quality (Reserved for v2)\n"
        m3_path = f"{prefix}/m3/.gitkeep"
        zf.writestr(m3_path, m3_placeholder)
        checksums[m3_path] = _sha256(m3_placeholder)

        # ── m4/ — SE Matrix Report ────────────────────────────────────
        se_pdf = _try_render_inline("se_matrix_pdf", row)
        if se_pdf:
            se_path = f"{prefix}/m4/study-reports/se-matrix-report.pdf"
            zf.writestr(se_path, se_pdf)
            checksums[se_path] = _sha256(se_pdf)
            logger.info("Embedded se-matrix-report.pdf (%d bytes)", len(se_pdf))

        # ── m5/ — Defense Packet + Audit Trail ────────────────────────
        defense_pdf = _try_render_inline("defense_packet_pdf", row)
        if defense_pdf:
            dp_path = f"{prefix}/m5/clinical-reports/defense-packet-report.pdf"
            zf.writestr(dp_path, defense_pdf)
            checksums[dp_path] = _sha256(defense_pdf)
            logger.info("Embedded defense-packet-report.pdf (%d bytes)", len(defense_pdf))

        audit_pdf = _try_render_inline("audit_trail_pdf", row)
        if audit_pdf:
            at_path = f"{prefix}/m5/clinical-reports/audit-trail-report.pdf"
            zf.writestr(at_path, audit_pdf)
            checksums[at_path] = _sha256(audit_pdf)
            logger.info("Embedded audit-trail-report.pdf (%d bytes)", len(audit_pdf))

        # ── proof-pack/ — summary + manifest ──────────────────────────
        summary_pdf = _try_render_inline("proof_pack_summary_pdf", row)
        if summary_pdf:
            sp_path = f"{prefix}/proof-pack/proof-pack-summary.pdf"
            zf.writestr(sp_path, summary_pdf)
            checksums[sp_path] = _sha256(summary_pdf)
            logger.info("Embedded proof-pack-summary.pdf (%d bytes)", len(summary_pdf))

        manifest_json = _generate_manifest_json(row).encode("utf-8")
        mj_path = f"{prefix}/proof-pack/manifest.json"
        zf.writestr(mj_path, manifest_json)
        checksums[mj_path] = _sha256(manifest_json)

        # ── checksums.sha256 ──────────────────────────────────────────
        checksum_lines = [f"{digest}  {path}" for path, digest in sorted(checksums.items())]
        checksum_content = "\n".join(checksum_lines) + "\n"
        zf.writestr(f"{prefix}/checksums.sha256", checksum_content.encode("utf-8"))

    result = buf.getvalue()
    buf.close()

    file_count = len(checksums) + 1  # +1 for checksums.sha256 itself
    logger.info("eCTD ZIP assembled: %d bytes, %d files", len(result), file_count)
    return result
