/**
 * useElectronicSignature — applies a real 21 CFR Part 11 signature.
 *
 * ## What this replaces
 *
 * The MDX approval card used to "sign" like this:
 *
 *     <input type="password" value={pwd} onChange={…} />
 *     <button onClick={() => setSigned(true)}>Apply signature</button>
 *
 * The password was collected and discarded — never sent anywhere. The
 * card then rendered "Signed just now", a padlock, and a record number
 * generated by `Math.random()`, under footer text promising that "time,
 * IP, and a SHA-256 of this record will be appended to the audit trail".
 * None of that happened. Nothing left the browser, and a page refresh
 * erased the signature entirely.
 *
 * That is not a cosmetic gap. A user could reasonably believe they had
 * executed a binding electronic signature on a submission document.
 *
 * ## What happens now
 *
 * Everything goes through `POST /api/esignature/sign`, which:
 *   - rejects signers whose role lacks signing authority (§11.10(g))
 *   - re-verifies the password server-side at the moment of signing,
 *     and the MFA token when the signer has MFA enabled (§11.200(a)(1))
 *   - computes the hash, IP and timestamp server-side
 *   - writes the audit row, and fails the signature if that write fails
 *
 * The hook never reports success without a server-issued signature id.
 * Every failure surfaces the server's own reason — wrong password,
 * missing authority, MFA required — rather than a generic message.
 */

import { useCallback, useState } from 'react';
import { getAuthToken, getOrgId } from '@/utils/authToken';

/** Server-issued evidence that a signature was actually recorded. */
export interface SignatureReceipt {
  /** Primary key in electronic_signatures. Real, not generated here. */
  signatureId: number;
  /** Server-computed hash over the signed record. */
  signatureHash: string;
  /** Server timestamp — never the browser's clock. */
  signedAt: string;
}

export interface SignArgs {
  documentId: number;
  /** Pins the signature to a revision, per §11.50(a). */
  versionId: number;
  /** Human-readable declaration, e.g. "Reviewed and approved". */
  signatureMeaning: string;
  /** "approval" | "review" | "verification" | … */
  signaturePurpose?: string;
  action?: string;
  password: string;
  /** Required when the signer has MFA enabled; the server decides. */
  mfaToken?: string;
}

export interface UseElectronicSignatureResult {
  sign: (args: SignArgs) => Promise<SignatureReceipt | null>;
  /** Populated only after the server confirms the signature. */
  receipt: SignatureReceipt | null;
  submitting: boolean;
  /** The server's own rejection reason, verbatim. */
  error: string | null;
  reset: () => void;
}

export function useElectronicSignature(): UseElectronicSignatureResult {
  const [receipt, setReceipt] = useState<SignatureReceipt | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const reset = useCallback(() => {
    setReceipt(null);
    setError(null);
    setSubmitting(false);
  }, []);

  const sign = useCallback(async (args: SignArgs): Promise<SignatureReceipt | null> => {
    setSubmitting(true);
    setError(null);

    const headers: Record<string, string> = { 'Content-Type': 'application/json' };
    const token = getAuthToken();
    const orgId = getOrgId();
    if (token) headers.Authorization = `Bearer ${token}`;
    if (orgId) headers['x-organization-id'] = orgId;

    try {
      const res = await fetch('/api/esignature/sign', {
        method: 'POST',
        credentials: 'include',
        headers,
        body: JSON.stringify({
          documentId: args.documentId,
          versionId: args.versionId,
          signaturePurpose: args.signaturePurpose ?? 'approval',
          signatureMeaning: args.signatureMeaning,
          action: args.action ?? 'approved',
          password: args.password,
          ...(args.mfaToken ? { mfaToken: args.mfaToken } : {}),
        }),
      });

      const body: unknown = await res.json().catch(() => null);

      if (!res.ok) {
        /* Surface the server's reason verbatim. "Signature rejected:
           password verification failed" and "your role does not permit
           applying an electronic signature" are different problems and
           the signer needs to know which one they have. */
        const message =
          (body && typeof body === 'object' && 'error' in body
            ? String((body as { error: unknown }).error)
            : null) ?? `Signature failed (HTTP ${res.status})`;
        setError(message);
        return null;
      }

      const b = body as Partial<SignatureReceipt> | null;
      if (!b || typeof b.signatureId !== 'number' || typeof b.signatureHash !== 'string') {
        /* A 200 without a signature id is not a signature. Refusing it
           here is the difference between this hook and the local
           setSigned(true) it replaces. */
        setError('Server did not return a signature record. Nothing was signed.');
        return null;
      }

      const confirmed: SignatureReceipt = {
        signatureId: b.signatureId,
        signatureHash: b.signatureHash,
        signedAt: b.signedAt ?? '',
      };
      setReceipt(confirmed);
      return confirmed;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Signature request failed');
      return null;
    } finally {
      setSubmitting(false);
    }
  }, []);

  return { sign, receipt, submitting, error, reset };
}
