/**
 * Kit icon vocabulary → lucide-react.
 *
 * The design kit ships Icons.jsx as `window.I` — a map of lucide-style glyphs
 * rendered at 1em / strokeWidth 1.75. On port every `window.I` lookup becomes
 * this map (lucide is the repo's only sanctioned icon library — see
 * design-system CI gate). Elements, not components, so the kit JSX pattern
 * `{I[name]}` transfers unchanged.
 */
import React from 'react';
import {
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Atom,
  BarChart3,
  Beaker,
  Bell,
  BellOff,
  Book,
  Building,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Clock,
  Copy,
  CreditCard,
  Database,
  Dot,
  Download,
  Eraser,
  ExternalLink,
  Eye,
  FileCheck,
  FileDown,
  FileText,
  Filter,
  Folder,
  GitBranch,
  GitCompare,
  Globe,
  HelpCircle,
  History,
  Home,
  Image,
  Indent,
  Info,
  Key,
  Layers,
  LayoutGrid,
  LayoutPanelLeft,
  LayoutTemplate,
  Link,
  List,
  ListOrdered,
  Lock,
  LogOut,
  Maximize,
  MessageSquare,
  Mic,
  Microscope,
  Minus,
  MoreVertical,
  Network,
  Outdent,
  Paperclip,
  Pause,
  PenLine,
  PanelLeft,
  PanelRight,
  Play,
  Plug,
  Plus,
  Quote,
  Redo2,
  RotateCw,
  Rocket,
  Scale,
  Scroll,
  Search,
  Send,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Sigma,
  SlidersVertical,
  Sparkles,
  Star,
  Stethoscope,
  Table,
  Tag,
  Telescope,
  Terminal,
  Type,
  Undo2,
  User,
  Vault,
  Wand2,
  Workflow,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Kit rendering contract: 1em glyphs, 1.75 stroke, decorative by default. */
function el(Icon: LucideIcon): React.ReactElement {
  return <Icon size="1em" strokeWidth={1.75} aria-hidden="true" focusable="false" />;
}

export const I: Record<string, React.ReactElement> = {
  folder: el(Folder),
  grid: el(LayoutGrid),
  sparkles: el(Sparkles),
  home: el(Home),
  building: el(Building),
  penLine: el(PenLine),
  layoutPanels: el(LayoutPanelLeft),
  vault: el(Vault),
  checkCircle: el(CheckCircle),
  rocket: el(Rocket),
  gitBranch: el(GitBranch),
  fileCheck: el(FileCheck),
  microscope: el(Microscope),
  beaker: el(Beaker),
  clipboardList: el(ClipboardList),
  workflow: el(Workflow),
  atom: el(Atom),
  template: el(LayoutTemplate),
  checkSquare: el(CheckSquare),
  network: el(Network),
  fileText: el(FileText),
  globe: el(Globe),
  scale: el(Scale),
  sigma: el(Sigma),
  barChart: el(BarChart3),
  shieldAlert: el(ShieldAlert),
  stethoscope: el(Stethoscope),
  tag: el(Tag),
  alertTriangle: el(AlertTriangle),
  info: el(Info),
  terminal: el(Terminal),
  telescope: el(Telescope),
  settings: el(Settings),
  scroll: el(Scroll),
  creditCard: el(CreditCard),
  database: el(Database),
  panelLeft: el(PanelLeft),
  panelRight: el(PanelRight),
  search: el(Search),
  mic: el(Mic),
  bell: el(Bell),
  help: el(HelpCircle),
  filter: el(Filter),
  down: el(ChevronDown),
  up: el(ChevronUp),
  copy: el(Copy),
  right: el(ChevronRight),
  arrowUp: el(ArrowUp),
  arrowRight: el(ArrowRight),
  send: el(Send),
  plus: el(Plus),
  plug: el(Plug),
  key: el(Key),
  download: el(Download),
  close: el(X),
  check: el(Check),
  clock: el(Clock),
  bellOff: el(BellOff),
  sliders: el(SlidersVertical),
  lock: el(Lock),
  logOut: el(LogOut),
  externalLink: el(ExternalLink),
  shieldCheck: el(ShieldCheck),
  zap: el(Zap),
  play: el(Play),
  pause: el(Pause),
  rotateCw: el(RotateCw),
  layers: el(Layers),
  book: el(Book),
  paperclip: el(Paperclip),
  image: el(Image),
  wand: el(Wand2),
  alignLeft: el(AlignLeft),
  alignCenter: el(AlignCenter),
  alignRight: el(AlignRight),
  alignJustify: el(AlignJustify),
  indent: el(Indent),
  outdent: el(Outdent),
  eraser: el(Eraser),
  minus: el(Minus),
  star: el(Star),
  more: el(MoreVertical),
  left: el(ArrowLeft),
  undo: el(Undo2),
  redo: el(Redo2),
  listBullet: el(List),
  listOrdered: el(ListOrdered),
  table: el(Table),
  link: el(Link),
  type: el(Type),
  quote: el(Quote),
  history: el(History),
  messageSquare: el(MessageSquare),
  gitCompare: el(GitCompare),
  maximize: el(Maximize),
  fileDown: el(FileDown),
  eye: el(Eye),
  chevDown: el(ChevronDown),
  chevRight: el(ChevronRight),
  dot: el(Dot),
  user: el(User),
};

export default I;
