
#!/usr/bin/env python3
import os
import re
from pathlib import Path

def find_requirements_files():
    """Find all requirements.txt files in the project"""
    requirements_files = []
    for root, dirs, files in os.walk('.'):
        for file in files:
            if file == 'requirements.txt':
                requirements_files.append(os.path.join(root, file))
    return requirements_files

def parse_requirements(file_path):
    """Parse requirements from a file"""
    requirements = set()
    try:
        with open(file_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    # Extract package name (before ==, >=, etc.)
                    package = re.split(r'[<>=!]', line)[0].strip()
                    requirements.add(line)
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
    return requirements

def create_unified_requirements():
    """Create a unified requirements.txt file"""
    all_requirements = set()
    requirements_files = find_requirements_files()
    
    print(f"Found {len(requirements_files)} requirements files:")
    for file in requirements_files:
        print(f"  - {file}")
        requirements = parse_requirements(file)
        all_requirements.update(requirements)
    
    # Sort requirements alphabetically
    sorted_requirements = sorted(list(all_requirements))
    
    # Write unified requirements
    with open('requirements.txt', 'w') as f:
        f.write("# Unified Python dependencies for TrialSage\n")
        f.write("# Generated by reorganization script\n\n")
        for req in sorted_requirements:
            f.write(f"{req}\n")
    
    print(f"\n✅ Created unified requirements.txt with {len(sorted_requirements)} packages")
    return len(sorted_requirements)

if __name__ == "__main__":
    create_unified_requirements()
