#!/usr/bin/env ts-node
/**
 * Phase 6.6.G Gate 1 — generate-risk-codes.ts
 *
 * Reads risk_codes.lock.json → generates shared/types/generated/risk-codes.generated.ts
 *
 * This is the "3-gate contract" entry point:
 *   Gate 1: npm run generate:risk-codes → writes TypeScript union types + label map
 *   Gate 2: CI validates the generated file matches the lock file (no stale types)
 *   Gate 3: Runtime contract_hashes.compute_risk_vocab_hash() uses the same lock file
 *
 * Usage:
 *   npx ts-node scripts/generate-risk-codes.ts
 *
 * Exit codes:
 *   0 — generated successfully
 *   1 — lock file missing or invalid
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, join, dirname } from 'path';
import { createHash } from 'crypto';
import { fileURLToPath } from 'url';

// ESM-compatible __dirname
const __ESM_filename =
  typeof __filename !== 'undefined' ? __filename : fileURLToPath(import.meta.url);
const __ESM_dirname = typeof __dirname !== 'undefined' ? __dirname : dirname(__ESM_filename);

const ROOT = resolve(__ESM_dirname, '..');
const LOCK_FILE = join(ROOT, 'shadow_service', 'risk_codes.lock.json');
const OUTPUT_DIR = join(ROOT, 'shared', 'types', 'generated');
const OUTPUT_FILE = join(OUTPUT_DIR, 'risk-codes.generated.ts');

function log(msg: string) {
  console.log(`[generate-risk-codes] ${msg}`);
}

// ── Load lock file ──

if (!existsSync(LOCK_FILE)) {
  console.error(`[generate-risk-codes] ❌ Lock file not found: ${LOCK_FILE}`);
  console.error(
    '[generate-risk-codes] Run from project root. Lock file should be at shadow_service/risk_codes.lock.json'
  );
  process.exit(1);
}

let lockData: Record<string, unknown>;
try {
  const raw = readFileSync(LOCK_FILE, 'utf-8');
  lockData = JSON.parse(raw);
} catch (err: any) {
  console.error(`[generate-risk-codes] ❌ Invalid JSON in lock file: ${err.message}`);
  process.exit(1);
}

// ── Compute lock hash ──

const lockRaw = readFileSync(LOCK_FILE, 'utf-8');
const lockHash = createHash('sha256').update(lockRaw).digest('hex');

// ── Extract risk codes ──

const riskCodes: Array<{ code: string; label: string; severity: string }> = [];

const codesMap = (lockData as any).risk_codes || lockData;

if (typeof codesMap === 'object' && !Array.isArray(codesMap)) {
  for (const [code, value] of Object.entries(codesMap)) {
    if (typeof value === 'object' && value !== null) {
      riskCodes.push({
        code,
        label: (value as any).label || (value as any).description || code,
        severity: (value as any).severity || 'MEDIUM',
      });
    } else if (typeof value === 'string') {
      riskCodes.push({ code, label: value, severity: 'MEDIUM' });
    }
  }
}

riskCodes.sort((a, b) => a.code.localeCompare(b.code));

log(`Found ${riskCodes.length} risk codes`);
log(`Lock hash: ${lockHash.slice(0, 24)}…`);

// ── Generate TypeScript ──

const lines: string[] = [
  '/**',
  ' * AUTO-GENERATED by scripts/generate-risk-codes.ts',
  ' * DO NOT EDIT MANUALLY',
  ' *',
  ` * Source: shadow_service/risk_codes.lock.json`,
  ` * Lock hash: ${lockHash}`,
  ' */',
  '',
  `/** SHA-256 of risk_codes.lock.json at generation time */`,
  `export const RISK_CODES_LOCK_HASH = '${lockHash}' as const;`,
  '',
  `/** All known risk codes */`,
  `export const RISK_CODES = [`,
];

for (const rc of riskCodes) {
  lines.push(`  '${rc.code}',`);
}

lines.push('] as const;');
lines.push('');
lines.push('/** TypeScript union type of all risk codes */');
lines.push('export type RiskCode = (typeof RISK_CODES)[number];');
lines.push('');
lines.push('/** Human-readable labels for each risk code */');
lines.push('export const RISK_CODE_LABELS: Record<RiskCode, string> = {');

for (const rc of riskCodes) {
  const escapedLabel = rc.label.replace(/'/g, "\\'");
  lines.push(`  '${rc.code}': '${escapedLabel}',`);
}

lines.push('};');
lines.push('');
lines.push('/** Severity mapping for each risk code */');
lines.push('export const RISK_CODE_SEVERITY: Record<RiskCode, string> = {');

for (const rc of riskCodes) {
  lines.push(`  '${rc.code}': '${rc.severity}',`);
}

lines.push('};');
lines.push('');

const output = lines.join('\n');

// ── Write output ──

if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

writeFileSync(OUTPUT_FILE, output, 'utf-8');

log(`✅ Generated ${OUTPUT_FILE}`);
log(`   ${riskCodes.length} risk codes, lock hash ${lockHash.slice(0, 16)}…`);
