#!/usr/bin/env bash
#
# startup.sh - Enterprise Database Startup Script
# 
# PURPOSE: Single source of truth for database configuration.
# This script MUST be run before any dev server startup.
# It ensures Docker is running, DATABASE_URL is correct, and schema is synced.
#
# USAGE:
#   source scripts/startup.sh      # Sets env vars in current shell
#   ./scripts/startup.sh           # Run standalone checks
#
# This file is the ONLY place where DATABASE_URL should be set for local development.
# All other configuration files should read from process.env.DATABASE_URL.
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# ============================================================================
# CONFIGURATION - SINGLE SOURCE OF TRUTH
# ============================================================================
export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/clinicalsage?sslmode=disable"
export DOCKER_DB_CONTAINER="clinicalsageai-2-replit-db-1"
export DB_NAME="clinicalsage"
export DB_USER="postgres"
export DB_PASSWORD="postgres"
export DB_HOST="localhost"
export DB_PORT="5432"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ============================================================================
# STEP 1: Ensure Docker container is running
# ============================================================================
check_docker() {
    log_info "Checking Docker container..."
    
    if ! docker ps --format '{{.Names}}' | grep -q "^${DOCKER_DB_CONTAINER}$"; then
        log_warn "Database container not running. Starting Docker Compose..."
        cd "$PROJECT_ROOT"
        docker compose up -d db 2>/dev/null || docker-compose up -d db 2>/dev/null || {
            log_error "Failed to start database container"
            return 1
        }
        log_info "Waiting for database to be ready..."
        sleep 5
    fi
    
    # Verify container is healthy
    if docker exec "$DOCKER_DB_CONTAINER" pg_isready -U "$DB_USER" -d "$DB_NAME" > /dev/null 2>&1; then
        log_success "Docker PostgreSQL container is running and healthy"
        return 0
    else
        log_error "Database container is not responding"
        return 1
    fi
}

# ============================================================================
# STEP 2: Verify database connection
# ============================================================================
verify_connection() {
    log_info "Verifying database connection..."
    
    if docker exec "$DOCKER_DB_CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -c "SELECT 1" > /dev/null 2>&1; then
        log_success "Database connection verified: $DATABASE_URL"
        return 0
    else
        log_error "Cannot connect to database"
        return 1
    fi
}

# ============================================================================
# STEP 3: Create database if it doesn't exist
# ============================================================================
ensure_database() {
    log_info "Ensuring database '$DB_NAME' exists..."
    
    # Check if database exists
    if docker exec "$DOCKER_DB_CONTAINER" psql -U "$DB_USER" -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
        log_success "Database '$DB_NAME' exists"
    else
        log_warn "Database '$DB_NAME' not found. Creating..."
        docker exec "$DOCKER_DB_CONTAINER" psql -U "$DB_USER" -c "CREATE DATABASE $DB_NAME;" || {
            log_error "Failed to create database"
            return 1
        }
        log_success "Database '$DB_NAME' created"
    fi
    
    # Ensure pgvector extension
    log_info "Ensuring pgvector extension..."
    docker exec "$DOCKER_DB_CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -c "CREATE EXTENSION IF NOT EXISTS vector;" > /dev/null 2>&1
    log_success "pgvector extension ready"
}

# ============================================================================
# STEP 4: Write .env file (overwrites any existing)
# ============================================================================
write_env_file() {
    log_info "Writing .env file..."
    
    cat > "$PROJECT_ROOT/.env" << EOF
# =============================================================================
# ClinicalSageAI Environment Configuration
# Generated by scripts/startup.sh - DO NOT EDIT MANUALLY
# Run: source scripts/startup.sh to regenerate
# =============================================================================

# Database - LOCAL DOCKER DEVELOPMENT
DATABASE_URL="${DATABASE_URL}"

# Auth
JWT_SECRET="dev-enterprise-secret-key-256"

# OpenAI (add your key here)
# OPENAI_API_KEY="sk-..."

# Feature Flags
ENABLE_LITERATURE_FEATURES=true
NODE_ENV=development
EOF
    
    log_success ".env file written with local Docker configuration"
}

# ============================================================================
# STEP 5: Display summary
# ============================================================================
show_summary() {
    echo ""
    echo "============================================================================"
    echo -e "${GREEN}DATABASE CONFIGURATION SUMMARY${NC}"
    echo "============================================================================"
    echo -e "DATABASE_URL: ${BLUE}${DATABASE_URL}${NC}"
    echo -e "Container:    ${BLUE}${DOCKER_DB_CONTAINER}${NC}"
    echo ""
    echo "To verify in a new terminal, run:"
    echo "  source scripts/startup.sh && echo \$DATABASE_URL"
    echo ""
    echo "To start the dev server:"
    echo "  source scripts/startup.sh && npm run dev"
    echo "============================================================================"
}

# ============================================================================
# MAIN
# ============================================================================
main() {
    echo ""
    echo "============================================================================"
    echo "ClinicalSageAI Database Startup Script"
    echo "============================================================================"
    echo ""
    
    # Override any existing DATABASE_URL in shell
    unset DATABASE_URL 2>/dev/null || true
    export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/clinicalsage?sslmode=disable"
    
    check_docker || exit 1
    ensure_database || exit 1
    verify_connection || exit 1
    write_env_file
    show_summary
    
    echo ""
    log_success "Startup complete. DATABASE_URL is set correctly."
}

# Run main if executed (not sourced)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main
fi

# Always export DATABASE_URL when sourced
export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/clinicalsage?sslmode=disable"
