/**
 * Lifecycle Obligation metrics (Capability C2C-11) — in-memory counters surfaced
 * via the central /api/metrics endpoint.
 *
 * @module server/services/lifecycle-metrics
 */

interface LifecycleMetricsState {
  obligationsCreated: Record<string, number>; // by type
  occurrencesGenerated: number;
  submissions: number;
}

const state: LifecycleMetricsState = { obligationsCreated: {}, occurrencesGenerated: 0, submissions: 0 };

export function recordLifecycleObligation(type: string, occurrences: number): void {
  state.obligationsCreated[type] = (state.obligationsCreated[type] ?? 0) + 1;
  state.occurrencesGenerated += occurrences;
}
export function recordLifecycleSubmission(): void {
  state.submissions += 1;
}

export function renderLifecycleMetrics(): string[] {
  const lines: string[] = [];
  lines.push('# HELP lifecycle_obligations_created_total Lifecycle obligations created, by type');
  lines.push('# TYPE lifecycle_obligations_created_total counter');
  for (const [t, n] of Object.entries(state.obligationsCreated)) lines.push(`lifecycle_obligations_created_total{type="${t}"} ${n}`);
  lines.push('# HELP lifecycle_occurrences_generated_total Periodic occurrences generated by the cadence engine');
  lines.push('# TYPE lifecycle_occurrences_generated_total counter');
  lines.push(`lifecycle_occurrences_generated_total ${state.occurrencesGenerated}`);
  lines.push('# HELP lifecycle_submissions_total Lifecycle obligations marked submitted');
  lines.push('# TYPE lifecycle_submissions_total counter');
  lines.push(`lifecycle_submissions_total ${state.submissions}`);
  return lines;
}

export function snapshotLifecycleMetrics(): LifecycleMetricsState {
  return JSON.parse(JSON.stringify(state));
}
export function resetLifecycleMetrics(): void {
  state.obligationsCreated = {};
  state.occurrencesGenerated = 0;
  state.submissions = 0;
}
