/**
 * PPTX Generator Service
 *
 * Generates PowerPoint presentations from markdown-like content.
 * Supports slide-based layout with title slides, content slides,
 * bullet lists, and section headers.
 *
 * Used by AnA to generate regulatory presentations, training decks,
 * board decks, and advisory committee briefings.
 */

import PptxGenJS from 'pptxgenjs';

// Brand colors
const BRAND = {
  dark: '1a1a2e',
  accent: '4361ee',
  light: 'f8f9fa',
  text: '2d2d2d',
  muted: '6c757d',
  white: 'ffffff',
};

interface SlideData {
  title: string;
  subtitle?: string;
  bullets?: string[];
  body?: string;
  layout?: 'title' | 'section' | 'content' | 'two-column' | 'blank';
}

/**
 * Parse markdown content into slide data.
 * Convention:
 * - # Heading → title slide
 * - ## Heading → section slide
 * - ### Heading → content slide title
 * - - bullet → bullets
 * - Regular text → body text
 * - --- → slide break
 */
function parseContentToSlides(title: string, content: string): SlideData[] {
  const slides: SlideData[] = [];
  const rawSlides = content.split(/\n---\n|\n___\n/);

  for (const raw of rawSlides) {
    const lines = raw.trim().split('\n').filter(l => l.trim());
    if (lines.length === 0) continue;

    const slide: SlideData = { title: '', bullets: [], body: '' };
    const bodyParts: string[] = [];

    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed.startsWith('# ')) {
        slide.title = trimmed.replace(/^# /, '');
        slide.layout = 'title';
      } else if (trimmed.startsWith('## ')) {
        slide.title = trimmed.replace(/^## /, '');
        slide.layout = slide.layout || 'section';
      } else if (trimmed.startsWith('### ')) {
        slide.title = trimmed.replace(/^### /, '');
        slide.layout = slide.layout || 'content';
      } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ') || trimmed.match(/^\d+\. /)) {
        const bullet = trimmed.replace(/^[-*]\s+/, '').replace(/^\d+\.\s+/, '');
        slide.bullets!.push(bullet);
      } else if (trimmed.startsWith('> ')) {
        slide.subtitle = trimmed.replace(/^> /, '');
      } else if (trimmed.startsWith('**') && trimmed.endsWith('**')) {
        // Bold line treated as subtitle
        slide.subtitle = trimmed.replace(/^\*\*|\*\*$/g, '');
      } else {
        bodyParts.push(trimmed.replace(/\*\*/g, '').replace(/\*/g, ''));
      }
    }

    if (bodyParts.length > 0) {
      slide.body = bodyParts.join('\n');
    }
    if (!slide.layout) {
      slide.layout = slide.bullets && slide.bullets.length > 0 ? 'content' : 'content';
    }
    if (!slide.title && bodyParts.length > 0) {
      slide.title = bodyParts.shift() || 'Slide';
      slide.body = bodyParts.join('\n');
    }

    slides.push(slide);
  }

  // If parsing produced nothing meaningful, create a simple presentation
  if (slides.length === 0) {
    slides.push({
      title: title,
      subtitle: 'Generated by AnA',
      layout: 'title',
    });
    // Split content into paragraph-based slides
    const paragraphs = content.split('\n\n').filter(p => p.trim());
    for (const para of paragraphs) {
      const lines = para.split('\n');
      slides.push({
        title: lines[0]?.replace(/^#+\s*/, '') || 'Content',
        body: lines.slice(1).join('\n'),
        layout: 'content',
      });
    }
  }

  return slides;
}

/**
 * Generate a PPTX buffer from title + markdown content.
 */
export async function generatePptxBuffer(title: string, content: string): Promise<Buffer> {
  const pptx = new PptxGenJS();

  pptx.author = 'ClinicalSageAI — AnA';
  pptx.company = 'Concept2Cure';
  pptx.title = title;
  pptx.subject = 'Regulatory Document';
  pptx.layout = 'LAYOUT_WIDE'; // 13.33 x 7.5

  const slides = parseContentToSlides(title, content);

  for (const slideData of slides) {
    const slide = pptx.addSlide();

    if (slideData.layout === 'title') {
      // Title slide — dark background
      slide.background = { color: BRAND.dark };
      slide.addText(slideData.title, {
        x: 0.8,
        y: 2.0,
        w: 11.5,
        h: 1.5,
        fontSize: 36,
        fontFace: 'Arial',
        color: BRAND.white,
        bold: true,
        align: 'left',
      });
      if (slideData.subtitle) {
        slide.addText(slideData.subtitle, {
          x: 0.8,
          y: 3.6,
          w: 11.5,
          h: 0.8,
          fontSize: 18,
          fontFace: 'Arial',
          color: BRAND.muted,
          align: 'left',
        });
      }
      // Branding footer
      slide.addText('Concept2Cure · ClinicalSageAI', {
        x: 0.8,
        y: 6.5,
        w: 5,
        h: 0.4,
        fontSize: 10,
        fontFace: 'Arial',
        color: BRAND.muted,
      });
    } else if (slideData.layout === 'section') {
      // Section divider
      slide.background = { color: BRAND.accent };
      slide.addText(slideData.title, {
        x: 0.8,
        y: 2.5,
        w: 11.5,
        h: 1.5,
        fontSize: 32,
        fontFace: 'Arial',
        color: BRAND.white,
        bold: true,
        align: 'left',
      });
      if (slideData.subtitle) {
        slide.addText(slideData.subtitle, {
          x: 0.8,
          y: 4.2,
          w: 11.5,
          h: 0.6,
          fontSize: 16,
          fontFace: 'Arial',
          color: BRAND.light,
        });
      }
    } else {
      // Content slide
      slide.background = { color: BRAND.white };

      // Title bar
      slide.addText(slideData.title, {
        x: 0.8,
        y: 0.3,
        w: 11.5,
        h: 0.7,
        fontSize: 22,
        fontFace: 'Arial',
        color: BRAND.dark,
        bold: true,
      });

      // Accent line
      slide.addShape(pptx.ShapeType.rect, {
        x: 0.8,
        y: 1.05,
        w: 2,
        h: 0.04,
        fill: { color: BRAND.accent },
      });

      let yPos = 1.4;

      // Bullets
      if (slideData.bullets && slideData.bullets.length > 0) {
        const bulletText = slideData.bullets.map(b => ({
          text: b,
          options: {
            fontSize: 14,
            fontFace: 'Arial',
            color: BRAND.text,
            bullet: { type: 'bullet' as const },
            paraSpaceAfter: 6,
          },
        }));
        slide.addText(bulletText, {
          x: 0.8,
          y: yPos,
          w: 11.5,
          h: 5.5,
          valign: 'top',
        });
        yPos += slideData.bullets.length * 0.4;
      }

      // Body text
      if (slideData.body) {
        slide.addText(slideData.body, {
          x: 0.8,
          y: yPos,
          w: 11.5,
          h: 7.5 - yPos - 0.8,
          fontSize: 13,
          fontFace: 'Arial',
          color: BRAND.text,
          valign: 'top',
          paraSpaceAfter: 8,
        });
      }

      // Footer
      slide.addText('Confidential — Concept2Cure', {
        x: 0.8,
        y: 7.0,
        w: 5,
        h: 0.3,
        fontSize: 8,
        fontFace: 'Arial',
        color: BRAND.muted,
      });
    }
  }

  // Generate buffer
  const output = await pptx.write({ outputType: 'nodebuffer' });
  return output as Buffer;
}
