import { useState, useEffect } from 'react';
import { useQuery, useMutation } from '@tanstack/react-query';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useToast } from '@/hooks/use-toast';
import { useQueryClient } from '@tanstack/react-query';
import {
  FileText,
  Download,
  CheckCircle,
  AlertCircle,
  Clock,
  RefreshCw,
  FileDown,
  Loader2
} from 'lucide-react';

interface FDAForm {
  id: string;
  name: string;
  description: string;
  required: boolean;
  status: 'pending' | 'generated' | 'error';
  completeness?: number;
  version?: number;
  updatedAt?: string;
}

interface FDAFormGeneratorProps {
  projectId: string;
}

export default function FDAFormGenerator({ projectId }: FDAFormGeneratorProps) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [selectedForm, setSelectedForm] = useState<string | null>(null);
  const [generatedFormContent, setGeneratedFormContent] = useState<string | null>(null);
  const [isGeneratingAll, setIsGeneratingAll] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // Fetch available forms for the project
  const { data: formsData, isLoading: isLoadingForms, refetch } = useQuery<{ forms: FDAForm[] }>({
    queryKey: [`/api/fda-forms/project/${projectId}/forms`],
    enabled: !!projectId
  });

  // Generate a single form
  const generateFormMutation = useMutation({
    mutationFn: async (formType: string) => {
      const response = await fetch(`/api/fda-forms/project/${projectId}/generate/${formType}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-organization-id': '1'
        }
      });
      
      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Failed to generate form');
      }
      
      return response.json();
    },
    onSuccess: (data) => {
      toast({
        title: 'Form Generated',
        description: `${data.form.name} has been successfully generated.`
      });
      
      // Set the generated content for preview
      if (data.form.htmlContent) {
        setGeneratedFormContent(data.form.htmlContent);
        setSelectedForm(data.form.type);
      }
      
      // Refetch forms to update status
      refetch();
    },
    onError: (error: Error) => {
      toast({
        title: 'Generation Failed',
        description: error.message,
        variant: 'destructive'
      });
    }
  });

  // Generate all forms
  const generateAllFormsMutation = useMutation({
    mutationFn: async () => {
      setIsGeneratingAll(true);
      const response = await fetch(`/api/fda-forms/project/${projectId}/generate-all`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-organization-id': '1'
        }
      });
      
      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Failed to generate forms');
      }
      
      return response.json();
    },
    onSuccess: (data) => {
      toast({
        title: 'All Forms Generated',
        description: 'All FDA forms have been successfully generated.'
      });
      refetch();
      setIsGeneratingAll(false);
    },
    onError: (error: Error) => {
      toast({
        title: 'Generation Failed',
        description: error.message,
        variant: 'destructive'
      });
      setIsGeneratingAll(false);
    }
  });

  // Auto-generate forms on initial load if no forms exist
  useEffect(() => {
    if (!isLoadingForms && formsData && !hasAutoGenerated) {
      const forms = formsData.forms || [];
      const hasNoGeneratedForms = forms.every((form: FDAForm) => form.status !== 'generated');
      
      if (hasNoGeneratedForms && forms.length > 0) {
        // Auto-generate forms if none exist
        setHasAutoGenerated(true);
        autoGenerateFormsMutation.mutate();
      }
    }
  }, [formsData, isLoadingForms, hasAutoGenerated]);

  // Auto-generate forms based on workflow data
  const autoGenerateFormsMutation = useMutation({
    mutationFn: async () => {
      const response = await fetch(`/api/fda-forms/project/${projectId}/auto-generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-organization-id': '1'
        }
      });
      
      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Failed to auto-generate forms');
      }
      
      return response.json();
    },
    onSuccess: (data) => {
      toast({
        title: 'Forms Auto-Generated',
        description: 'FDA forms have been automatically generated from your workflow data.'
      });
      refetch();
    },
    onError: (error: Error) => {
      toast({
        title: 'Auto-Generation Failed',
        description: error.message,
        variant: 'destructive'
      });
    }
  });

  // Fetch a specific form content for preview
  const fetchFormContent = async (formType: string) => {
    try {
      const response = await fetch(`/api/fda-forms/project/${projectId}/form/${formType}`, {
        headers: {
          'x-organization-id': '1'
        }
      });
      
      if (response.ok) {
        const data = await response.json();
        if (data.form && data.form.content) {
          setGeneratedFormContent(data.form.content);
          setSelectedForm(formType);
        }
      }
    } catch (error) {
      console.error('Error fetching form content:', error);
    }
  };

  // Download form as HTML
  const downloadForm = (formType: string, content: string) => {
    const blob = new Blob([content], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `FDA_${formType}_${projectId}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: 'Form Downloaded',
      description: `FDA ${formType} has been downloaded.`
    });
  };

  // Calculate overall progress
  const calculateOverallProgress = () => {
    if (!formsData?.forms) return 0;
    const generatedCount = formsData.forms.filter((f: FDAForm) => f.status === 'generated').length;
    return Math.round((generatedCount / formsData.forms.length) * 100);
  };

  if (isLoadingForms) {
    return (
      <div className="flex items-center justify-center p-8">
        <Loader2 className="h-8 w-8 animate-spin" />
      </div>
    );
  }

  const forms = formsData?.forms || [];
  const overallProgress = calculateOverallProgress();

  return (
    <div className="space-y-6" data-testid="fda-form-generator">
      {/* Header Card */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>FDA Form Generation</CardTitle>
              <CardDescription>
                Generate required FDA forms for your 510(k) submission
              </CardDescription>
            </div>
            <div className="flex items-center gap-4">
              <div className="text-right">
                <p className="text-sm text-muted-foreground">Overall Progress</p>
                <p className="text-2xl font-bold">{overallProgress}%</p>
              </div>
              <Progress value={overallProgress} className="w-32" />
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="flex gap-2">
            <Button
              onClick={() => autoGenerateFormsMutation.mutate()}
              disabled={autoGenerateFormsMutation.isPending}
              variant="default"
              data-testid="button-auto-generate-forms"
            >
              {autoGenerateFormsMutation.isPending ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Auto-Generating...
                </>
              ) : (
                <>
                  <RefreshCw className="mr-2 h-4 w-4" />
                  Auto-Generate from Workflow
                </>
              )}
            </Button>
            <Button
              onClick={() => generateAllFormsMutation.mutate()}
              disabled={isGeneratingAll || generateAllFormsMutation.isPending}
              variant="secondary"
              data-testid="button-generate-all-forms"
            >
              {isGeneratingAll ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating All...
                </>
              ) : (
                <>
                  <FileText className="mr-2 h-4 w-4" />
                  Generate All Blank
                </>
              )}
            </Button>
            <Button 
              variant="outline" 
              onClick={() => refetch()}
              data-testid="button-refresh-status"
            >
              <RefreshCw className="mr-2 h-4 w-4" />
              Refresh
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Forms List and Preview */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Forms List */}
        <Card>
          <CardHeader>
            <CardTitle>Available Forms</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {forms.map((form: FDAForm) => (
              <Card key={form.id} className="cursor-pointer hover:bg-accent/50 transition-colors">
                <CardContent className="p-4">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <FileText className="h-4 w-4 text-muted-foreground" />
                        <span className="font-medium text-sm">{form.id}</span>
                        {form.required && (
                          <Badge variant="secondary" className="text-xs">Required</Badge>
                        )}
                      </div>
                      <p className="text-sm font-medium mb-1">{form.name}</p>
                      <p className="text-xs text-muted-foreground">{form.description}</p>
                      
                      {form.status === 'generated' && form.completeness !== undefined && (
                        <div className="mt-2 flex items-center gap-2">
                          <Progress value={form.completeness} className="flex-1 h-2" />
                          <span className="text-xs text-muted-foreground">{form.completeness}%</span>
                        </div>
                      )}
                    </div>
                    
                    <div className="flex flex-col items-end gap-2">
                      {form.status === 'generated' ? (
                        <>
                          <Badge variant="outline" className="text-xs">
                            <CheckCircle className="mr-1 h-3 w-3" />
                            Generated
                          </Badge>
                          <div className="flex gap-1">
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => fetchFormContent(form.id)}
                              data-testid={`button-view-${form.id}`}
                            >
                              View
                            </Button>
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => generateFormMutation.mutate(form.id)}
                              data-testid={`button-regenerate-${form.id}`}
                            >
                              Regenerate
                            </Button>
                          </div>
                        </>
                      ) : form.status === 'error' ? (
                        <>
                          <Badge variant="destructive" className="text-xs">
                            <AlertCircle className="mr-1 h-3 w-3" />
                            Error
                          </Badge>
                          <Button
                            size="sm"
                            onClick={() => generateFormMutation.mutate(form.id)}
                            disabled={generateFormMutation.isPending}
                            data-testid={`button-generate-${form.id}`}
                          >
                            Retry
                          </Button>
                        </>
                      ) : (
                        <>
                          <Badge variant="outline" className="text-xs">
                            <Clock className="mr-1 h-3 w-3" />
                            Pending
                          </Badge>
                          <Button
                            size="sm"
                            onClick={() => generateFormMutation.mutate(form.id)}
                            disabled={generateFormMutation.isPending}
                            data-testid={`button-generate-${form.id}`}
                          >
                            {generateFormMutation.isPending ? (
                              <Loader2 className="h-4 w-4 animate-spin" />
                            ) : (
                              'Generate'
                            )}
                          </Button>
                        </>
                      )}
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </CardContent>
        </Card>

        {/* Form Preview */}
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Form Preview</CardTitle>
              {selectedForm && generatedFormContent && (
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => downloadForm(selectedForm, generatedFormContent)}
                  data-testid="button-download-form"
                >
                  <Download className="mr-2 h-4 w-4" />
                  Download HTML
                </Button>
              )}
            </div>
          </CardHeader>
          <CardContent>
            {generatedFormContent ? (
              <div className="border rounded-lg p-4 bg-white min-h-[600px] overflow-auto">
                <iframe
                  srcDoc={generatedFormContent}
                  className="w-full min-h-[600px] border-0"
                  title="FDA Form Preview"
                />
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center min-h-[600px] text-muted-foreground">
                <FileText className="h-12 w-12 mb-4" />
                <p className="text-center">
                  Select a form to preview or generate one to see it here
                </p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}