import { Router } from 'express';
import multer from 'multer';
import generateCER2V from './generate.post';
import intelligenceHandler from './intelligence.post';
import exportHandler from './export.post';
import manifestHandler from './manifest.post';
import workbenchHandler from './workbench.get';
import classifyEvidenceHandler from './evidence-classify.post';
import linkClaimHandler from './link-claim.post';
import linkStandardHandler from './link-standard.post';
import linkOutcomeHandler from './link-outcome.post';
import readinessHandler from './readiness.get';
import preflightHandler from './preflight.post';
import verifyHandler from './verify.post';
import createClaimHandler from './claims.post';
import updateClaimHandler from './claims.patch';
import createStandardHandler from './standards.post';
import updateStandardHandler from './standards.patch';
import createOutcomeHandler from './outcomes.post';
import updateOutcomeHandler from './outcomes.patch';
import submissionsHandler from './submissions.get';
import sectionLinkHandler from './sections-link.post';
import sectionLinksHandler from './sections-links.get';
import citationsResolveHandler from './citations-resolve.post';
import auditHandler from './audit.get';
import createEvidenceHandler from './evidence.post';
import listEvidenceHandler from './evidence.get';
import listEvidenceInboxHandler from './evidence-inbox.get';
import updateEvidenceHandler from './evidence.patch';
import evidenceUploadHandler from './evidence-upload.post';
import evidenceDownloadHandler from './evidence-download.get';
import bulkEvidenceHandler from './evidence-bulk.patch';
import dedupeEvidenceHandler from './evidence-dedupe.post';

const router = Router();
const upload = multer({ storage: multer.memoryStorage() });

router.post('/generate', generateCER2V);
router.post('/intelligence', intelligenceHandler);
router.post('/export', exportHandler);
router.post('/manifest', manifestHandler);
router.get('/workbench', workbenchHandler);
router.get('/readiness', readinessHandler);
router.post('/preflight', preflightHandler);
router.post('/verify', verifyHandler);
router.post('/claims', createClaimHandler);
router.patch('/claims/:id', updateClaimHandler);
router.post('/standards', createStandardHandler);
router.patch('/standards/:id', updateStandardHandler);
router.post('/outcomes', createOutcomeHandler);
router.patch('/outcomes/:id', updateOutcomeHandler);
router.get('/submissions', submissionsHandler);
router.post('/sections/link', sectionLinkHandler);
router.get('/sections/:id/links', sectionLinksHandler);
router.post('/citations/resolve', citationsResolveHandler);
router.get('/audit', auditHandler);
router.get('/evidence', listEvidenceHandler);
router.get('/evidence/inbox', listEvidenceInboxHandler);
router.get('/evidence/:id/download', evidenceDownloadHandler);
router.post('/evidence', createEvidenceHandler);
router.post('/evidence/upload', upload.array('files'), evidenceUploadHandler);
router.patch('/evidence/:id', updateEvidenceHandler);
router.patch('/evidence/bulk', bulkEvidenceHandler);
router.post('/evidence/dedupe', dedupeEvidenceHandler);
router.post('/evidence/classify', classifyEvidenceHandler);
router.post('/claims/:id/link', linkClaimHandler);
router.post('/standards/:id/link', linkStandardHandler);
router.post('/outcomes/:id/link', linkOutcomeHandler);

export default router;
