/**
 * AnA RI — Artifact Generator
 *
 * Turns document actions into real governed artifacts using the AI gateway
 * and the artifact-tagger persistence layer.
 *
 * This is the bridge that makes AnA a governed work producer, not just an advisor.
 *
 * @module server/services/ana-ri/artifact-generator
 */

import { getGateway } from '../ai-gateway/index.js';
import type { GatewayMessage } from '../ai-gateway/types.js';
import { tagArtifact, type TagArtifactParams, type TagArtifactResult } from '../artifact-tagger.js';
import { buildAnaRISystemPrompt } from './persona.js';
import type { DocumentActionType } from './document-actions.js';
import type { IntentLens, UserRole } from './persona.js';
import {
  validateArtifactQuality,
  checkEvidenceDiscipline,
  validateResponseStructure,
  logGeneration,
  buildArtifactContract,
} from './enforcement.js';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export interface ArtifactGenerationRequest {
  /** The document action to produce */
  actionType: DocumentActionType;
  /** Conversation context — the messages that led to this action */
  conversationContext: Array<{ role: 'user' | 'assistant'; content: string }>;
  /** Project binding */
  projectId: number;
  organizationId: number;
  userId?: number;
  /** User role for tone adaptation */
  userRole?: UserRole;
  /** Active intent lens */
  intentLens?: IntentLens;
  /** Optional title override */
  title?: string;
  /** Optional CTD section code for dossier placement */
  sectionCode?: string;
}

export interface ArtifactGenerationResult {
  success: boolean;
  /** The generated artifact content */
  content: string;
  /** Title of the generated artifact */
  title: string;
  /** Artifact ID if persisted */
  artifactId?: number;
  /** Whether this is a new artifact or update */
  isNew?: boolean;
  /** Whether the artifact was persisted to DB */
  persisted?: boolean;
  /** Persistence error if content was generated but DB write failed */
  persistenceError?: string;
  /** Quality gate grade */
  qualityGrade?: string;
  /** Error message if generation itself failed */
  error?: string;
  /** AI provider/model used */
  provider?: string;
  model?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Generation Prompts
// ─────────────────────────────────────────────────────────────────────────────

const ARTIFACT_PROMPTS: Record<DocumentActionType, string> = {
  deficiency_preemption_memo: `Generate a **Deficiency Preemption Memo** based on the conversation above.

CRITICAL INSTRUCTIONS:
- Identify 3-7 specific deficiencies that reviewers would raise for THIS submission
- Do NOT generate generic risks. Every deficiency must reference specific weakness in the materials discussed
- Each reviewer signal must sound like a real FDA/EMA reviewer — skeptical, specific, demanding evidence
- Each prepared response must be a DRAFT of the actual response text, not a summary of what to say
- Every claim must carry [KNOWN], [INFERRED], or [MISSING] labels with specific reasoning

Structure it EXACTLY as follows:

# Deficiency Preemption Memo

## Submission Context
[Product name, regulatory pathway, submission stage, target agency, therapeutic area]

## Anticipated Deficiencies

For each (rank by likelihood, most likely first):
### [Deficiency Title] — Severity: [Critical/Major/Minor] | Likelihood: [Very Likely/Likely/Possible]

**What the reviewer will say:**
> "[Write the actual reviewer language — skeptical, specific, demanding. Not polite summaries.]"

**Why this deficiency is likely:**
[Cite the specific weakness in THIS application that triggers this deficiency. Reference specific data, sections, or gaps discussed in conversation. Tag each claim as [KNOWN/INFERRED/MISSING].]

**Prepared response (draft):**
[Write the ACTUAL response text that could be sent to the agency. Include specific data references, regulatory citations, and evidence. This should be copy-pasteable, not a plan.]

**Evidence basis:**
- Available: [List what supports the response — [KNOWN] items]
- Needs strengthening: [What is [INFERRED] and needs data]
- Missing: [What is [MISSING] and must be generated]

## Evidence Gap Summary
| Gap | Impact on Submission | Action Required | Priority |
|-----|---------------------|-----------------|----------|
[Populated from above]

## Pre-Submission Action Plan
[Ordered by priority. Each action must be specific and assignable.]

---
*Generated by AnA RI — Regulatory Intelligence Copilot*
*Classification: Governed Document | Status: Draft*`,

  strategy_note: `Generate a **Regulatory Strategy Note** based on the conversation above.

Structure it EXACTLY as follows:

# Regulatory Strategy Note

## Strategic Assessment
[One-paragraph strategic position summary]

## Recommended Pathway
[Optimal regulatory route with justification]
- **Primary pathway**: [pathway with rationale]
- **Alternative pathways**: [if applicable]
- **Key precedents**: [similar approved products and their pathways]

## Argument Hierarchy
[Priority-ordered regulatory arguments, strongest first]
1. [Strongest argument] — Evidence status: [KNOWN/INFERRED]
2. [Second argument] — Evidence status: [KNOWN/INFERRED]
3. [Additional arguments...]

## Agency-Specific Considerations
- **FDA**: [specific considerations]
- **EMA**: [specific considerations, if applicable]

## Risk-Benefit Positioning
[How to frame the benefit-risk argument for reviewers]

## Timeline and Key Milestones
[Critical dates, dependencies, and decision points]

## Strategic Risks
[Ranked risks that could derail the strategy]

---
*Generated by AnA RI — Regulatory Intelligence Copilot*
*Classification: Governed Document | Status: Draft*`,

  reviewer_question_brief: `Generate a **Reviewer Question Anticipation Brief** based on the conversation above.

Structure it EXACTLY as follows:

# Reviewer Question Anticipation Brief

## Context
[Submission type, stage, product, and key regulatory considerations]

## High-Priority Questions (Likely to Be Asked)

For each question:
### Q[N]: [The anticipated reviewer question]
- **Why they'll ask**: [Reviewer motivation]
- **Prepared Answer**: [Specific, evidence-backed response]
- **Evidence Status**: [KNOWN] / [INFERRED] / [MISSING]
- **Supporting References**: [Specific data, studies, or regulatory precedent]

## Medium-Priority Questions (May Be Asked)

[Same format as above]

## Response Strategy
- **Tone**: [How to approach reviewer interactions]
- **Key themes**: [Recurring themes to emphasize]
- **Red lines**: [Topics to handle carefully]

## Evidence Inventory
[Summary table: Question → Available Evidence → Gap Status]

---
*Generated by AnA RI — Regulatory Intelligence Copilot*
*Classification: Governed Document | Status: Draft*`,

  risk_memo: `Generate a **Regulatory Risk Assessment Memo** based on the conversation above.

CRITICAL INSTRUCTIONS:
- Identify REAL risks specific to THIS submission — not generic regulatory checklist items
- Each risk must cite the specific weakness or gap in the materials discussed
- Rank by combination of severity AND likelihood — not just severity alone
- Mitigations must be specific actions (not "consider addressing this")
- Include a clear go/conditional-go/no-go recommendation with conditions
- Tag every claim with [KNOWN], [INFERRED], or [MISSING] with reasoning

Structure it EXACTLY as follows:

# Regulatory Risk Assessment Memo

## Executive Summary
[One-paragraph verdict: What is the overall risk posture? Is this submission defensible?
Include: go/conditional-go/no-go signal with the top 1-2 reasons.]

## Critical Risks (Severity: Critical — Must resolve before submission)
For each:
### [Risk Title] | Likelihood: [Very Likely/Likely/Possible]
- **The problem**: [What specifically is wrong — cite data, sections, or gaps from conversation] **[KNOWN/INFERRED/MISSING]**
- **Regulatory consequence**: [What happens: RTF, CR letter, clinical hold, information request?] **[INFERRED — based on precedent/regulation]**
- **Mitigation**: [Specific, assignable action — not "consider" or "evaluate"]
- **Residual risk after mitigation**: [High/Medium/Low]
- **Timeline impact**: [How many months does this add if unresolved?]

## Major Risks (Severity: Major — Should resolve, may trigger deficiency)
[Same format as Critical]

## Evidence Gaps
| Gap | Creates Exposure | Regulatory Reference | Action | Priority |
|-----|-----------------|---------------------|--------|----------|
[Each gap tagged [MISSING] with specific regulatory citation]

## Mitigation Priority Matrix
| # | Risk | Severity | Mitigation | Timeline | Dependencies |
|---|------|----------|------------|----------|--------------|
[Ranked by impact. Include dependencies between mitigations.]

## Recommendation
**[GO / CONDITIONAL GO / NO-GO]**
Conditions: [Specific, measurable conditions that must be met]
Key decision: [The single most important question leadership must answer]

---
*Generated by AnA RI — Regulatory Intelligence Copilot*
*Classification: Governed Document | Status: Draft*`,

  rewritten_section: `Generate a **Submission-Defensible Section Rewrite** based on the conversation above.

Structure it EXACTLY as follows:

# Section Rewrite

## Original Assessment
[What is wrong with the current version — specific issues, not vague critique]
- **Weak claims identified**: [list with evidence status]
- **Structural issues**: [flow, organization, argument hierarchy]
- **Reviewer risk**: [what a reviewer would challenge]

## Rewritten Section
[The complete rewritten text, ready for submission]

## Change Rationale
For each significant change:
- **Change**: [what was changed]
- **Why**: [regulatory or quality justification]
- **Evidence basis**: [KNOWN/INFERRED]

## Remaining Issues
[What still needs attention beyond this rewrite]

---
*Generated by AnA RI — Regulatory Intelligence Copilot*
*Classification: Governed Document | Status: Draft*`,

  revised_artifact: `Generate a **Revised Document** based on the conversation above.

Produce the complete revised version with tracked changes noted.

# Revised Document

## Revision Summary
[What was changed and why — high-level overview]

## Revised Content
[The complete revised document or section text]

## Key Changes
[Bullet list of significant changes with rationale]

---
*Generated by AnA RI — Regulatory Intelligence Copilot*
*Classification: Governed Document | Status: Draft*`,

  evidence_memo: `Generate an **Evidence Assessment Memo** based on the conversation above.

Structure it EXACTLY as follows:

# Evidence Assessment Memo

## Evidence Overview
[Summary of the evidence landscape for this submission/section]

## Strong Evidence — [KNOWN]
[Well-supported claims with robust data]
- Each item: Claim → Source → Strength assessment

## Weak Evidence — [INFERRED]
[Claims with insufficient or marginal support]
- Each item: Claim → Available data → What's missing

## Missing Evidence — [MISSING]
[Gaps where no supporting data exists]
- Each item: What's needed → Why it matters → How to obtain

## Evidence Quality Matrix
| Claim | Status | Source | Strength | Action Needed |
|-------|--------|--------|----------|---------------|
[Populated from above]

## Strengthening Recommendations
[Prioritized actions to improve the evidence package]

---
*Generated by AnA RI — Regulatory Intelligence Copilot*
*Classification: Governed Document | Status: Draft*`,

  attach_to_dossier: `Prepare the content from the conversation above for dossier attachment.

# Dossier Attachment

## Document Classification
- **Type**: [Determine from conversation context]
- **Purpose**: [Why this document exists]
- **Regulatory Relevance**: [How it supports the submission]

## Content
[The complete content to attach, organized and formatted for inclusion in the regulatory dossier]

## Metadata
- **Source**: AnA RI analysis
- **Status**: Draft — requires review
- **Date**: [Current date]

---
*Generated by AnA RI — Regulatory Intelligence Copilot*
*Classification: Governed Document | Status: Draft*`,
};

// ─────────────────────────────────────────────────────────────────────────────
// Title Generation
// ─────────────────────────────────────────────────────────────────────────────

const DEFAULT_TITLES: Record<DocumentActionType, string> = {
  deficiency_preemption_memo: 'Deficiency Preemption Memo',
  strategy_note: 'Regulatory Strategy Note',
  reviewer_question_brief: 'Reviewer Question Anticipation Brief',
  risk_memo: 'Regulatory Risk Assessment Memo',
  rewritten_section: 'Section Rewrite — Submission Defensible',
  revised_artifact: 'Revised Document',
  evidence_memo: 'Evidence Assessment Memo',
  attach_to_dossier: 'Dossier Attachment',
};

const ARTIFACT_TYPE_MAP: Record<DocumentActionType, string> = {
  deficiency_preemption_memo: 'memo',
  strategy_note: 'memo',
  reviewer_question_brief: 'briefing-book',
  risk_memo: 'risk-file',
  rewritten_section: 'section',
  revised_artifact: 'section',
  evidence_memo: 'memo',
  attach_to_dossier: 'report',
};

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate a governed artifact from a document action.
 *
 * This is the core function that turns AnA from an advisor into a work producer.
 * It: (1) builds a generation prompt, (2) calls the AI gateway, (3) persists
 * the result as a governed artifact in concept2cure_artifacts.
 */
export async function generateArtifact(
  request: ArtifactGenerationRequest
): Promise<ArtifactGenerationResult> {
  const {
    actionType,
    conversationContext,
    projectId,
    organizationId,
    userId,
    userRole,
    intentLens,
    title: titleOverride,
    sectionCode,
  } = request;

  // 1. Build the generation prompt
  const generationInstruction = ARTIFACT_PROMPTS[actionType];
  if (!generationInstruction) {
    return { success: false, content: '', title: '', error: `Unknown action type: ${actionType}` };
  }

  // 2. Build system prompt with AnA RI persona
  const systemPrompt = buildAnaRISystemPrompt({
    userRole: userRole || 'general',
    intentLens: intentLens || 'auto',
  });

  // 3. Assemble messages: system + conversation history + generation instruction
  const messages: GatewayMessage[] = [
    { role: 'system', content: systemPrompt },
  ];

  // Include conversation context (last 20 messages — matches /chat endpoint)
  const usedContext = conversationContext.slice(-20);
  for (const msg of usedContext) {
    messages.push({ role: msg.role, content: msg.content });
  }

  // Add the generation instruction as a user message
  messages.push({
    role: 'user',
    content: generationInstruction,
  });

  // 4. Call AI gateway
  let gateway;
  try {
    gateway = getGateway();
  } catch {
    return { success: false, content: '', title: '', error: 'AI gateway unavailable' };
  }

  let response;
  try {
    // Per-action token budgets — revised_artifact and risk_memo need more room
    const TOKEN_BUDGETS: Partial<Record<DocumentActionType, number>> = {
      revised_artifact: 12000,
      risk_memo: 10000,
    };
    const maxTokens = TOKEN_BUDGETS[actionType] || 8192;

    response = await gateway.chat({
      taskType: 'document_drafting',
      messages,
      maxTokens,
      temperature: 0.2,
      routingStrategy: 'quality_optimized',
    });
  } catch (err: any) {
    return {
      success: false,
      content: '',
      title: '',
      error: `AI generation failed: ${err?.message || 'Unknown error'}`,
    };
  }

  if (!response.content) {
    return { success: false, content: '', title: '', error: 'Empty response from AI provider' };
  }

  const generatedContent = response.content;
  const artifactTitle = titleOverride || DEFAULT_TITLES[actionType] || 'AnA RI Generated Document';

  // 5. Quality gate — reject garbage before persisting
  const qualityResult = validateArtifactQuality(generatedContent, actionType);
  const evidenceResult = checkEvidenceDiscipline(generatedContent);
  const structureResult = validateResponseStructure(generatedContent);

  if (!qualityResult.pass) {
    console.error(`[AnA RI] Quality gate REJECTED artifact: ${qualityResult.issues.join('; ')}`);
    logGeneration({
      timestamp: new Date().toISOString(),
      route: '/api/ana-ri/generate',
      action: actionType,
      projectId,
      organizationId,
      userId,
      artifactCreated: false,
      anaRiOrchestrated: true,
      qualityGrade: qualityResult.grade,
      evidenceCompliant: evidenceResult.compliant,
      structureScore: structureResult.score,
    });
    return {
      success: false,
      content: generatedContent,
      title: artifactTitle,
      error: `Quality gate rejected: ${qualityResult.issues.join('; ')}`,
    };
  }

  // 6. Persist as governed artifact
  let artifactResult: TagArtifactResult | undefined;
  let persistenceError: string | undefined;
  try {
    const tagParams: TagArtifactParams = {
      projectId,
      organizationId,
      userId,
      sectionCode: sectionCode || `ana-ri.${actionType}`,
      title: artifactTitle,
      content: generatedContent,
      status: 'draft',
      source: 'ana_ri',
      metadata: {
        anaRiActionType: actionType,
        anaRiIntentLens: intentLens || 'auto',
        anaRiUserRole: userRole || 'general',
        generatedAt: new Date().toISOString(),
        aiProvider: response.provider || 'unknown',
        aiModel: response.model || 'unknown',
        conversationMessagesUsed: usedContext.length,
        conversationMessagesTotal: conversationContext.length,
        qualityGrade: qualityResult.grade,
        qualityScore: qualityResult.score,
        evidenceLabels: evidenceResult.totalLabels,
        evidenceCompliant: evidenceResult.compliant,
        structureScore: structureResult.score,
        structureSections: structureResult.present,
      },
    };

    artifactResult = await tagArtifact(tagParams);
  } catch (err: any) {
    console.error('[AnA RI] Artifact persistence failed:', err?.message);
    persistenceError = err?.message || 'Unknown persistence error';
  }

  // 7. Log generation event for observability
  logGeneration({
    timestamp: new Date().toISOString(),
    route: '/api/ana-ri/generate',
    action: actionType,
    projectId,
    organizationId,
    userId,
    artifactCreated: !!artifactResult,
    artifactId: artifactResult?.artifactId,
    provider: response.provider || 'unknown',
    model: response.model || 'unknown',
    anaRiOrchestrated: true,
    qualityGrade: qualityResult.grade,
    evidenceCompliant: evidenceResult.compliant,
    structureScore: structureResult.score,
  });

  return {
    success: true,
    content: generatedContent,
    title: artifactTitle,
    artifactId: artifactResult?.artifactId,
    isNew: artifactResult?.isNew,
    persisted: !!artifactResult,
    persistenceError,
    qualityGrade: qualityResult.grade,
    provider: response.provider || 'unknown',
    model: response.model || 'unknown',
  };
}

/**
 * Get available artifact types and their default titles.
 */
export function getArtifactTypes(): Array<{ type: DocumentActionType; title: string; artifactType: string }> {
  return Object.entries(DEFAULT_TITLES).map(([type, title]) => ({
    type: type as DocumentActionType,
    title,
    artifactType: ARTIFACT_TYPE_MAP[type as DocumentActionType],
  }));
}
