// Mock service for development purposes
// In a real implementation, these would be API calls

const coauthorService = {
  // Save a draft of a section
  saveDraft: async ({ sectionId, content }) => {
    console.log(`Auto-saving section ${sectionId}...`);
    // In a real implementation, this would be an API call
    localStorage.setItem(`draft_${sectionId}`, content);
    return Promise.resolve(true);
  },

  // Get draft history for a section
  getDraftHistory: async sectionId => {
    // Mock history data
    const mockHistory = [
      {
        id: 'version-3',
        timestamp: new Date(Date.now() - 60000).toISOString(),
        author: 'Current User',
        content: localStorage.getItem(`draft_${sectionId}`) || 'Current version of the document.',
        changes: '+125 words, -42 words',
      },
      {
        id: 'version-2',
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        author: 'Current User',
        content:
          'Previous version with some differences in the content to demonstrate the history feature.',
        changes: '+78 words, -15 words',
      },
      {
        id: 'version-1',
        timestamp: new Date(Date.now() - 86400000).toISOString(),
        author: 'AI Assistant',
        content: 'Initial draft generated by AI with basic structure and content outline.',
        changes: '+230 words',
      },
    ];

    return Promise.resolve(mockHistory);
  },

  // Generate a draft using AI
  generateDraft: async sectionId => {
    // In a real implementation, this would be an API call to trigger
    // the AI generation process
    console.log(`Generating draft for section ${sectionId}...`);
    return Promise.resolve(true);
  },

  // Toggle markdown view
  toggleMarkdownView: () => {
    console.log('Toggling markdown view...');
    // In a real implementation, this would update state in the editor component
    return true;
  },

  // Insert a placeholder
  insertPlaceholder: () => {
    console.log('Inserting placeholder...');
    // In a real implementation, this would insert a placeholder at cursor position
    return true;
  },

  // Export content in different formats
  exportContent: async (content, format) => {
    console.log(`Exporting content in ${format} format...`);
    // In a real implementation, this would convert the content to
    // the specified format and return it

    if (format === 'pdf') {
      return Promise.resolve({
        url: 'https://example.com/exports/document.pdf',
        filename: 'document.pdf',
      });
    } else if (format === 'docx') {
      return Promise.resolve({
        url: 'https://example.com/exports/document.docx',
        filename: 'document.docx',
      });
    } else if (format === 'html') {
      return Promise.resolve({
        url: 'https://example.com/exports/document.html',
        filename: 'document.html',
      });
    } else {
      return Promise.resolve({
        url: 'https://example.com/exports/document.txt',
        filename: 'document.txt',
      });
    }
  },
};

export default coauthorService;
