/**
 * The report catalog GET /api/insights-canvas/overview answers with
 * (server/routes/insights-canvas-routes.ts, CanvasReportType), for the canvas
 * suites that mock that read. The canvas no longer carries its own copy of the
 * catalog (QA 2026-10-08, j8): it reads this from the server, with `runnable`
 * saying whether an engine computes the type over a program
 * (server/services/report-os/report-engine.ts — the readiness digest and the
 * research-compliance registers). Unfiltered by segment: the server filters
 * by the lead program's product type, and the suites that test that build
 * their own list.
 */
export const CANVAS_REPORT_TYPES = [
  { typeId: 'readiness.executive_digest', label: 'Executive Readiness Digest', family: 'readiness', allowedScopes: ['program', 'project', 'submission'], allowedClientSegments: ['pharma', 'device', 'biotech'], truthfulnessRules: { allowPartial: true, requireBlockers: true }, runnable: true },
  { typeId: 'provenance.evidence_trace_report', label: 'Evidence & Provenance Trace Report', family: 'evidence_provenance', allowedScopes: ['project', 'submission', 'document'], allowedClientSegments: ['pharma', 'device', 'biotech'], truthfulnessRules: { allowPartial: true, requireConfidence: true }, runnable: false },
  { typeId: 'compliance.audit_assurance_pack', label: 'Compliance & Audit Assurance Pack', family: 'compliance_audit', allowedScopes: ['project', 'submission', 'document'], allowedClientSegments: ['pharma', 'device', 'biotech'], truthfulnessRules: { allowPartial: true, requireExplicitGaps: true }, runnable: false },
  { typeId: 'usa_fda.pma_submission_readiness', label: 'FDA PMA Submission Readiness Pack', family: 'usa_fda_pma', allowedScopes: ['project', 'submission'], allowedClientSegments: ['device', 'biotech'], truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true }, runnable: false },
  { typeId: 'usa_fda.estar_510k_equivalence_matrix', label: 'FDA eSTAR / 510(k) Equivalence Matrix', family: 'usa_fda_510k', allowedScopes: ['project', 'submission', 'document'], allowedClientSegments: ['device'], truthfulnessRules: { allowPartial: true, requireExplicitGaps: true, requireConfidence: true }, runnable: false },
  { typeId: 'usa_fda.deficiency_response_intelligence', label: 'FDA Deficiency Response Intelligence Report', family: 'usa_fda_response', allowedScopes: ['project', 'submission', 'document'], allowedClientSegments: ['pharma', 'device', 'biotech'], truthfulnessRules: { allowPartial: false, requireBlockers: true, requireExplicitGaps: true }, runnable: false },
  { typeId: 'ema.maa_readiness_assessment', label: 'EMA MAA Readiness Assessment', family: 'ema_maa', allowedScopes: ['program', 'project', 'submission'], allowedClientSegments: ['pharma', 'biotech'], truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true }, runnable: false },
  { typeId: 'ema.rmp_psur_signal_alignment', label: 'EMA RMP / PSUR Signal Alignment Report', family: 'ema_post_market', allowedScopes: ['project', 'submission', 'document'], allowedClientSegments: ['pharma', 'biotech'], truthfulnessRules: { allowPartial: true, requireExplicitGaps: true, requireConfidence: true }, runnable: false },
  { typeId: 'china_nmpa.ctd_module_gap_analysis', label: 'NMPA CTD Module Gap Analysis', family: 'china_nmpa_ctd', allowedScopes: ['project', 'submission', 'document'], allowedClientSegments: ['pharma', 'biotech', 'device'], truthfulnessRules: { allowPartial: true, requireExplicitGaps: true, requireConfidence: true }, runnable: false },
  { typeId: 'china_nmpa.registration_dossier_readiness', label: 'NMPA Registration Dossier Readiness Pack', family: 'china_nmpa_registration', allowedScopes: ['program', 'project', 'submission'], allowedClientSegments: ['pharma', 'biotech', 'device'], truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true }, runnable: false },
  { typeId: 'china_nmpa.deficiency_letter_root_cause_pack', label: 'NMPA Deficiency Letter Root-Cause Pack', family: 'china_nmpa_response', allowedScopes: ['project', 'submission', 'document'], allowedClientSegments: ['pharma', 'biotech', 'device'], truthfulnessRules: { allowPartial: false, requireBlockers: true, requireExplicitGaps: true }, runnable: false },
  { typeId: 'fcoi.disclosure_register', label: 'Financial Disclosure Register (21 CFR 54)', family: 'fcoi_compliance', allowedScopes: ['submission', 'project'], allowedClientSegments: ['pharma', 'biotech', 'device'], truthfulnessRules: { allowPartial: true, requireBlockers: true }, runnable: true },
  { typeId: 'ha.commitment_register', label: 'HA Interaction & Commitment Register', family: 'ha_commitment', allowedScopes: ['submission', 'project', 'program'], allowedClientSegments: ['pharma', 'biotech', 'device'], truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true }, runnable: true },
  { typeId: 'iacuc.protocol_register', label: 'IACUC Protocol & Animal Census Register', family: 'iacuc_governance', allowedScopes: ['project', 'submission', 'program'], allowedClientSegments: ['academic', 'biotech', 'pharma'], truthfulnessRules: { allowPartial: true, requireBlockers: true }, runnable: true },
  { typeId: 'irb.submission_register', label: 'IRB Submission & Determination Register', family: 'irb_ethics', allowedScopes: ['study', 'submission', 'project'], allowedClientSegments: ['biotech', 'pharma', 'academic'], truthfulnessRules: { allowPartial: true, requireBlockers: true }, runnable: true },
  { typeId: 'ibc.registration_register', label: 'IBC Biosafety Registration & Containment Register', family: 'ibc_biosafety', allowedScopes: ['project', 'submission', 'program'], allowedClientSegments: ['biotech', 'academic', 'pharma'], truthfulnessRules: { allowPartial: true, requireBlockers: true }, runnable: true },
  { typeId: 'nonclinical.study_send_register', label: 'Nonclinical Study & SEND Readiness Register', family: 'nonclinical_module4', allowedScopes: ['submission', 'program', 'project'], allowedClientSegments: ['pharma', 'biotech'], truthfulnessRules: { allowPartial: true, requireBlockers: true }, runnable: true },
  { typeId: 'grants.portfolio_register', label: 'Grant Portfolio & Funder-Milestone Register', family: 'sponsored_programs', allowedScopes: ['program', 'project', 'account'], allowedClientSegments: ['academic', 'biotech'], truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true }, runnable: true },
  { typeId: 'rim.registration_grid', label: 'Product Registration Grid & Labeling Register', family: 'rim_registration', allowedScopes: ['program', 'project', 'account'], allowedClientSegments: ['pharma', 'biotech'], truthfulnessRules: { allowPartial: true, requireBlockers: true }, runnable: true },
  { typeId: 'inspection.readiness_pack', label: 'Inspection Readiness & 483 Response Pack', family: 'inspection_readiness', allowedScopes: ['program', 'project', 'submission'], allowedClientSegments: ['pharma', 'biotech', 'device', 'ivd', 'cro'], truthfulnessRules: { allowPartial: true, requireBlockers: true }, runnable: true },
  { typeId: 'controlled_substances.inventory_ledger', label: 'Controlled Substances Inventory & DEA Ledger', family: 'controlled_substances', allowedScopes: ['program', 'project', 'account'], allowedClientSegments: ['academic', 'biotech', 'pharma'], truthfulnessRules: { allowPartial: false, requireBlockers: true, requireExplicitGaps: true }, runnable: true },
  { typeId: 'lifecycle.obligation_calendar', label: 'Lifecycle Obligation Calendar', family: 'lifecycle_obligations', allowedScopes: ['program', 'project', 'submission'], allowedClientSegments: ['pharma', 'biotech'], truthfulnessRules: { allowPartial: true, requireBlockers: true, requireConfidence: true }, runnable: true },
  { typeId: 'etmf.completeness_pack', label: 'eTMF Completeness & Gap Pack', family: 'etmf', allowedScopes: ['study', 'submission', 'project'], allowedClientSegments: ['pharma', 'biotech', 'cro'], truthfulnessRules: { allowPartial: true, requireBlockers: true }, runnable: true },
  { typeId: 'research_compliance.training_status', label: 'Research Personnel Training Status', family: 'research_compliance', allowedScopes: ['program', 'project', 'account'], allowedClientSegments: ['academic', 'biotech', 'pharma'], truthfulnessRules: { allowPartial: true, requireBlockers: true }, runnable: true },
  { typeId: 'effort.certification_register', label: 'Effort Certification Register', family: 'effort_certification', allowedScopes: ['program', 'project', 'account'], allowedClientSegments: ['academic', 'biotech', 'pharma'], truthfulnessRules: { allowPartial: true, requireBlockers: true }, runnable: true },
  { typeId: 'research_security.coi_register', label: 'Research Security & COI Disclosure Register', family: 'research_security', allowedScopes: ['program', 'project', 'account'], allowedClientSegments: ['academic', 'biotech', 'pharma'], truthfulnessRules: { allowPartial: true, requireBlockers: true }, runnable: true },
  { typeId: 'research_admin.scorecard', label: 'Research Administration Scorecard', family: 'research_admin', allowedScopes: ['program', 'account'], allowedClientSegments: ['academic', 'biotech', 'pharma'], truthfulnessRules: { allowPartial: true, requireBlockers: true }, runnable: true },
];

/** The catalog the server answers for a program of `segment` (its recorded product type). */
export function catalogForSegment(segment: string) {
  return CANVAS_REPORT_TYPES.filter((t) => t.allowedClientSegments.length === 0 || t.allowedClientSegments.includes(segment));
}
